<?php
/**
 * Modèle des "block-affectations" pour la fiche élève
 *
 * Variables de la vue :
 * - identite (nom et prénom de l'élève concerné)
 * - structure (description de son affectation pour un domicile)
 * - trajet (numéro du trajet)
 * 
 * @project sbm
 * @package SbmAjax/view/sbm-ajax/eleve
 * @filesource blockaffectations.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 mai 2015
 * @version 2015-1
 */
?>
<h3>
	Affectations&nbsp;&nbsp;&nbsp;&nbsp;<i class="fam-car-add"
		title="Ajouter une affectation pour <?php echo $this->identite;?>"
		data-button="btnaffectation" data-trajet="<?php echo $this->trajet?>" data-href="/op:add"></i>
</h3>
<?php 
if (isset($this->structure)) {
    echo $this->affectations($this->trajet, $this->structure);
}
?> 