<?php
/**
 * Modèle des "block-affectations" pour la fiche élève
 *
 * Variables de la vue :
 * - identite (nom et prénom de l'élève concerné)
 * - structure (description de son affectation pour un domicile)
 * - trajet (numéro du trajet)
 *
 * @project sbm
 * @package SbmAjax/view/sbm-ajax/eleve
 * @filesource blockaffectations.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 juil. 2020
 * @version 2020-2.6.0
 */

// on cache le chexkbox accordRi si une affectation est présente dans la structure
$disableAccord = isset($this->structure['annee_courante']);
$this->inlineScript()->captureStart();
?>
<?php if ($this->trajet == 1) :?>
js_edit.setDisableAccordR1(<?php echo $disableAccord; ?>);
<?php else :?>
js_edit.setDisableAccordR2(<?php echo $disableAccord; ?>);
<?php endif;?>
<?php $this->inlineScript()->captureEnd(); ?>
<h3>
	Affectations<i class="fam-car-key"
		title="Recherche automatique des circuits pour <?= $this->identite;?>"
		data-button="btnchercheraffectations"
		data-trajet="<?= $this->trajet; ?>" data-href="/op:auto"></i><i
		class="fam-car-add"
		title="Ajouter un circuit pour <?= $this->identite;?>"
		data-button="btnaffectation" data-trajet="<?= $this->trajet; ?>"
		data-href="/op:add"></i><i class="fam-car-delete"
		title="Supprimer tous les circuits pour <?= $this->identite;?>"
		data-button="btnsuppraffectations" data-trajet="<?= $this->trajet; ?>"
		data-href="/op:remove"></i>
</h3>
<?php
if (isset($this->structure)) {
    echo $this->affectations($this->trajet, $this->structure);
}
?>