<?php
/**
 * Formulaire de prise en charge du paiement
 *
 * Ce formulaire s'ouvre en popup par le jQuery dialog dans la fiche d'un élève
 * 
 * @project sbm
 * @package SbmAjax/view/sbm-ajax/eleve
 * @filesource formpaiement.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.5.0
 */
// style css utilisés dans le formulaire
$this->headStyle()->captureStart();
?>
#formpaiement<?= $this->trajet;?> label.sbm-form-auto {
    display: inline-block;
    width: 150px;
    margin-right: 5px;
}
#formpaiement<?= $this->trajet;?> label.sbm-form-auto:before {
	content: "\A";
	white-space: pre;
	line-height: 1.5em;
}
#formpaiement<?= $this->trajet;?> input.button {
    position: relative;
    top: 1.5rem;
}
#formpaiement<?= $this->trajet;?> input.button.cancel {
    margin-left: 100px;
}
#formpaiement<?= $this->trajet;?> input.button.submit {
	margin-left: 15px;
}
<?php $this->headStyle()->captureEnd(); ?>
<?= $this->headStyle();?>
<?php $this->inlineScript()->captureStart();?>
is_xmlhttprequest = <?= $this->is_xmlhttprequest; ?>;
urlform = '<?= $this->form->getAttribute('action'); ?>';
priseenchargepaiement().init(is_xmlhttprequest, urlform);
<?php $this->inlineScript()->captureEnd();?>
<?= $this->inlineScript();?>
<div id="formpaiement">
<?= $this->form()->openTag($this->form);?>
<?= $this->formHidden($this->form->get('eleveId'));?>
<?= $this->formHidden($this->form->get('csrf'));?>
<div id="formpaiement-gratuit" class="row-inner"><?= $this->formRow($this->form->get('gratuit'));?></div>
	<div id="formpaiement-organismeId" class="row-inner"
		style="display: none;"><?= $this->formRow($this->form->get('organismeId'));?></div>
	<div id="formpaiement-buttons" class="row-inner edit left-95px">
<?= $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'));?>
</div>
<?= $this->form()->closeTag();?>
</div>
<div id="errors"></div>