<?php
/**
 * Formulaire d'affectation d'un élève
 *
 * Ce formulaire s'ouvre en popup par le jQuery dialog dans la fiche d'un élève
 * 
 * @project sbm
 * @package SbmAjax/view/sbm-ajax/eleve
 * @filesource formaffectation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 avr. 2018
 * @version 2018-2.4.0
 */

/*
 * Pour DEBUG
 * décommenter les lignes suivantes
 *
 * $msg_alert = '"eleveId: "+$("#formaffectation' . $this->trajet . ' input[name=eleveId]").val()';
 * $msg_alert .= '+"\nmillesime: "+$("#formaffectation' . $this->trajet . ' input[name=millesime]").val()';
 * $msg_alert .= '+"\ntrajet: "+$("#formaffectation' . $this->trajet . ' input[name=trajet]").val()';
 * $msg_alert .= '+"\njours: "+$("#formaffectation' . $this->trajet . ' input[name=jours]").val()';
 * $msg_alert .= '+"\nsens: "+$("#formaffectation' . $this->trajet . ' input[name=sens]").val()';
 * $msg_alert .= '+"\ncorrespondance: "+$("#formaffectation' . $this->trajet . ' input[name=correspondance]").val()';
 * $msg_alert .= '+"\nresponsableId: "+$("#formaffectation' . $this->trajet . ' input[name=responsableId]").val()';
 * $msg_alert .= '+"\ndemandeR1: "+$("#formaffectation' . $this->trajet . ' input[name=demandeR1]").val()';
 * $msg_alert .= '+"\nop: "+$("#formaffectation' . $this->trajet . ' input[name=op]").val()';
 * $msg_alert .= '+"\nservice1: "+$("#affectation-service1Id option:selected").val()';
 *
 * /* et ajouter la ligne qui suit dans inlineScript()->captureStart()
 * alert(<?php echo $msg_alert;?>);
 */
?>
<?php $this->headStyle()->captureStart(); ?>
#formaffectation<?php echo $this->trajet;?> label.sbm-form-auto {
    display: inline-block;
    width: 150px;
    margin-right: 5px;
}
#formaffectation<?php echo $this->trajet;?> label.sbm-form-auto:before {
	content: "\A";
	white-space: pre;
	line-height: 1.5em;
}
#formaffectation<?php echo $this->trajet;?> input.button {
    position: relative;
    top: 1.5rem;
}
#formaffectation<?php echo $this->trajet;?> input.button.cancel {
    margin-left: 100px;
}
#formaffectation<?php echo $this->trajet;?> input.button.submit {
	margin-left: 15px;
}
<?php $this->headStyle()->captureEnd(); ?>
<?php echo $this->headStyle();?>
<?php $this->headScript()->appendFile($this->basePath('js/ajax/formaffectation.js'));?>
<?php echo $this->headScript();?>
<?php $this->inlineScript()->captureStart();?>
is_xmlhttprequest = <?= $this->is_xmlhttprequest; ?>;
formaffectation = "#formaffectation<?= $this->trajet;?>";
var urlform = '<?= $this->form->getAttribute('action'); ?>';
var station1Id = <?php echo $this->station1Id ?:'null';?>;
var station2Id = <?php echo $this->station2Id?:'null';?>;
affectation.init(station1Id, station2Id);
<?php $this->inlineScript()->captureEnd();?>
<div id="formaffectation<?php echo $this->trajet;?>">
<?php echo $this->form($this->form);?>
</div>
<div id="errors"></div>
<?php echo $this->inlineScript();?>
