<?php
/**
 * Contenu de l'onglet 1 d'une fiche invité
 *
 * @project sbm
 * @package SbmAjax\view\sbm-ajax\eleve
 * @filesource inviteformonglet1.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 juin 2021
 * @version 2021-2.6.2
 */
$element = $this->form->get('eleveId');
$element->setLabel('Identité du bénéficiaire');
$hiddens = [
    'nom' => null,
    'prenom' => null,
    'sexe' => null,
    'nationalite' => null,
    'responsableId' => null,
    'organismeId' => null
];
foreach ($hiddens as $elementName => $value) {
    $element = $this->form->get($elementName);
    $element->setValue($value);
    echo $this->formHidden($element);
}
?>
<div id="wrapper-onglet1">
	<div id="wrapper-beneficiaire" class="beneficiaire">
		<div id="wrapper-nom" class="row-inner"><?=$this->formRow($this->form->get('eleveId'));?></div>
	</div>
	<div id="wrapper-domicile" class="domicile">
		<div class="clearfix">
			<div id="wrapper-chez" class="row-inner float-left"><?=$this->formRow($this->form->get('chez'));?></div>
			<div id="wrapper-adresseL1" class="row-inner float-left"><?=$this->formRow($this->form->get('adresseL1'));?></div>
			<div id="wrapper-adresseL2" class="row-inner float-left"><?=$this->formRow($this->form->get('adresseL2'));?></div>
			<div id="wrapper-adresseL3" class="row-inner float-left"><?=$this->formRow($this->form->get('adresseL3'));?></div>
		</div>
		<div class="clearfix">
			<div id="wrapper-codePostal" class="row-inner float-left"><?=$this->formRow($this->form->get('codePostal'));?></div>
			<div id="wrapper-communeId" class="row-inner float-left"><?=$this->formRow($this->form->get('communeId'));?></div>
			<div id="wrapper-stationId" class="row-inner float-left"><?=$this->formRow($this->form->get('stationId'));?></div>
		</div>
	</div>
	<div id="wrapper-destination" class="destination">
		<div id="wrapper-etablissementId" class="row-inner"><?=$this->formRow($this->form->get('etablissementId'));?></div>
	</div>
	<div id="wrapper-transport" class="transport clearfix">
		<div id="wrapper-servicesMatin" class="row-inner float-left"><?=$this->formRow($this->form->get('servicesMatin'));?></div>
		<div id="wrapper-servicesMidi" class="row-inner float-left"><?=$this->formRow($this->form->get('servicesMidi'));?></div>
		<div id="wrapper-servicesSoir" class="row-inner float-left"><?=$this->formRow($this->form->get('servicesSoir'));?></div>
		<div id="wrapper-servicesMerSoir" class="row-inner float-left"><?=$this->formRow($this->form->get('servicesMerSoir'));?></div>
	</div>
</div>