<?php
/**
 * Exportation de données géolocalisées
 * 
 * Vue des critères d'exportation des élèves
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource export-eleve.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
?>
<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="flashMessenger float-right">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
        </div>
		<h1>Exportation des élèves</h1>
	</div>
	<div id="fiche-inner">
	<?php echo $this->form()->openTag($this->form);?>
	    <fieldset class="sbm-page1">
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('id_ccda'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('numero'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('nom_eleve'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('prenom_eleve'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('etablissementId'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('classeId'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('responsable1'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('communeId_responsable1'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('responsable2'));?></div>
			<div class="row-inner label-120"><?php echo $this->formRow($this->form->get('communeId_responsable2'));?></div>
			<div class="row-inner"><?php echo $this->formRow($this->form->get('ga'));?></div>
			<div class="row-inner"><?php echo $this->formRow($this->form->get('chez'));?></div>
			<div class="row-inner"><?php echo $this->formRow($this->form->get('lot'));?></div>
			<div class="row-inner"><?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
	<?php echo $this->form()->closeTag();?>
	</div>
	<div id="fiche-footer"></div>
</div>