<?php
/**
 * Vue présentant le choix des données à exporter
 *
 * Données avec coordonnées géographiques
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource export.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 juin 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_exportEleves = $this->url('sbmadmin', array(
    'action' => 'export-eleve'
));;
$url_exportEtablissements = $this->url('sbmadmin', array(
    'action' => 'export-etablissement'
));;
$url_exportResponsables = $this->url('sbmadmin', array(
    'action' => 'export-responsable'
));;
$url_exportStations = $this->url('sbmadmin', array(
    'action' => 'export-station'
));;
$url_retour = $this->url('sbmadmin');
?>
<div id="menugeneral">
	<div class="flashMessenger float-right">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
    </div>
    <h1>Exportation de données avec coordonnées géographiques</h1>
	<div  id="menugeneral-inner">
		<ul>
			<li><a href="<?php echo $url_exportEleves; ?>"><i class="fam-bullet-go"></i>Exporter des élèves</a></li>
			<li><a href="<?php echo $url_exportEtablissements; ?>"><i class="fam-bullet-go"></i>Exporter des établissements</a></li>
			<li><a href="<?php echo $url_exportResponsables; ?>"><i class="fam-bullet-go"></i>Exporter des responsables</a></li>
			<li><a href="<?php echo $url_exportStations; ?>"><i class="fam-bullet-go"></i>Exporter des stations</a></li>
			<li><a href="<?php echo $url_retour; ?>"><i class="fam-door-out"></i>Espace d'administration</a></li>
		</ul>
	</div>
</div>