<?php
/**
 * Exportation de données géolocalisées
 * 
 * Vue des critères d'exportation des responsables
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource export-responsable.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
?>

<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="flashMessenger float-right">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
        </div>
		<h1>Exportation des responsables</h1>
	</div>
	<div id="fiche-inner">
	<?= $this->form()->openTag($this->form);?>
	    <fieldset class="sbm-page1">
			<div class="row-inner label-120"><?= $this->formRow($this->form->get('nomSA'));?></div>
			<div class="row-inner label-120"><?= $this->formRow($this->form->get('communeId'));?></div>
			<div class="row-inner label-120"><?= $this->formRow($this->form->get('selection'));?></div>
			<div class="row-inner label-120"><?= $this->formRow($this->form->get('demenagement'));?></div>
			<div class="row-inner label-120"><?= $this->formRow($this->form->get('nbEleves'));?></div>
			<div class="row-inner">
				<?= $this->formSubmit($this->form->get('submit'));?>
				<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
	<?= $this->form()->closeTag();?>
	</div>
	<div id="fiche-footer"></div>
</div>