<?php
/**
 *  Vue de l'action index du controller IndexController du module SbmAdmin
 *
 *
 * @project sbm
 * @package SbmAdmin/view/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 juin 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_pdf_liste = $this->url('sbmpdf', [
    'action' => 'pdf-liste'
]);
$url_libelle_liste = $this->url('sbmadmin', [
    'action' => 'libelle-liste'
]);
$url_gestion = $this->url('sbmgestion');
$url_export = $this->url('sbmadmin', [
    'action' => 'export'
]);
$url_images = $this->url('sbminstall', [
    'action' => 'gestion-images'
]);
$url_edit_css = $this->url('sbminstall', [
    'action' => 'edit-css'
]);
if ($this->layout()->hassbmservicesms) {
    $url_edit_servicesms = $this->url('sbminstall',
        [
            'action' => 'edit-' . $this->layout()->servicesms_name
        ]);
}
$url_edit_client = $this->url('sbminstall', [
    'action' => 'edit-client'
]);
$url_edit_page = $this->url('sbminstall', [
    'action' => 'edit-page'
]);
$url_edit_sites = $this->url('sbminstall', [
    'action' => 'edit-sites'
]);
?>
<h1>Espace d'administration</h1>
<div id="menugeneral">
	<div class="flashMessenger">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
    </div>
	<div id="menugeneral-inner" class="clearfix">
		<div class="col1 float-left">
			<fieldset class="sbm-page1">
				<ul>
			<?php
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
], [
    'value' => 'Gestion des documents pdf',
    'formaction' => $url_pdf_liste
]);
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
], [
    'value' => 'Gestion des images de l\'application',
    'formaction' => $url_images
]);
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
], [
    'value' => 'Gestion de la feuille de style',
    'formaction' => $url_edit_css
]);
echo $this->ligneMenuAction('fam-bullet-go', [],
    [
        'value' => 'Gestion des liens',
        'formaction' => $url_edit_sites
    ]);
echo $this->ligneMenuAction('fam-bullet-go', [],
    [
        'value' => 'Gestion des informations de l\'organisateur',
        'formaction' => $url_edit_client
    ]);
if ($this->layout()->hassbmservicesms) {
    echo $this->ligneMenuAction('fam-bullet-go', [],
        [
            'value' => 'Configuration de l\'API du service de SMS',
            'formaction' => $url_edit_servicesms
        ]);
}
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
],
    [
        'value' => 'Gestion des libellés de l\'application',
        'formaction' => $url_libelle_liste
    ]);
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
], [
    'value' => 'Exportation des données géolocalisées',
    'formaction' => $url_export
]);
echo $this->ligneMenuAction('fam-bullet-go', [
    'filename' => 'sbm.css'
], [
    'value' => 'Espace des gestionnaires',
    'formaction' => $url_gestion
]);
?>
		</ul>
			</fieldset>
		</div>
		<div class="col2 float-left">
			<fieldset class="sbm-page1">
				<legend>Modification du contenu de la page d'accueil</legend>
				<ul>
			<?php
include $this->theme->getIncludeView('sbm-installation/index/gestion-config');
?>
			</ul>
			</fieldset>
		</div>
	</div>
</div>