<?php
/**
 *  Vue de l'action index du controller IndexController du module SbmAdmin
 *
 *
 * @project sbm
 * @package SbmAdmin/view/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_pdf_liste = $this->url('sbmadmin', array(
    'action' => 'pdf-liste'
));
$url_libelle_liste = $this->url('sbmadmin', array(
    'action' => 'libelle-liste'
));
$url_droits = $this->url('sbmadmin', array('action' => 'user-liste'));
?>
<h1>Menu du module d'administration</h1>
<div id="menugeneral">
	<div class="flashMessenger">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
    </div>
	<div  id="menugeneral-inner">
		<ul>
			<li><a href="<?php echo $url_droits; ?>"><i class="fam-bullet-go"></i>Gestion des utilisateurs</a></li>
			<li><a href="<?php echo $url_libelle_liste; ?>"><i class="fam-bullet-go"></i>Gestion des libellés
					de l'application</a></li>
			<li><a href="<?php echo $url_pdf_liste; ?>"><i class="fam-bullet-go"></i>Gestion des documents pdf</a></li>
		</ul>
	</div>
</div>