<?php
/**
 *  Vue de l'action index du controller IndexController du module SbmAdmin
 *
 *
 * @project sbm
 * @package SbmAdmin/view/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_pdf_liste = $this->url('sbmpdf', [
    'action' => 'pdf-liste'
]);
$url_libelle_liste = $this->url('sbmadmin', [
    'action' => 'libelle-liste'
]);
$url_droits = $this->url('sbmadmin', [
    'action' => 'user-liste'
]);
$url_secteurs_scolaires_liste = $this->url('sbmadmin',
    [
        'action' => 'secteur-scolaire-liste'
    ]);
$url_simulation_etablissement_liste = $this->url('sbmadmin',
    [
        'action' => 'simulation-etablissement-liste'
    ]);
$url_rpi_liste = $this->url('sbmadmin', [
    'action' => 'rpi-liste'
]);
$url_gestion = $this->url('sbmgestion');
$url_export = $this->url('sbmadmin', [
    'action' => 'export'
]);
$url_images = $this->url('sbminstall', [
    'action' => 'gestion-images'
]);
?>
<h1>Espace d'administration</h1>
<div id="menugeneral">
	<div class="flashMessenger">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
    </div>
	<div id="menugeneral-inner">
		<ul>
			<li><a href="<?= $url_droits; ?>"><i class="fam-bullet-go"></i>Gestion
					des utilisateurs</a></li>
			<li><a href="<?= $url_export; ?>"><i class="fam-bullet-go"></i>Exportation
					des données géolocalisées</a></li>
			<li><a href="<?= $url_rpi_liste; ?>"><i class="fam-bullet-go"></i>Gestion
					des RPI</a></li>
			<li><a href="<?= $url_secteurs_scolaires_liste; ?>"><i
					class="fam-bullet-go"></i>Gestion des secteurs scolaires des
					collèges publics</a></li>
			<li><a href="<?= $url_simulation_etablissement_liste; ?>"><i
					class="fam-bullet-go"></i>Règles de correspondance pour le passage
					dans un établissement de niveau supérieur</a></li>
			<li><a href="<?= $url_libelle_liste; ?>"><i class="fam-bullet-go"></i>Gestion
					des libellés de l'application</a></li>
			<li><a href="<?= $url_pdf_liste; ?>"><i class="fam-bullet-go"></i>Gestion
					des documents pdf</a></li>
			<li><a href="<?= $url_images;?>"><i class="fam-bullet-go"></i>Gestion
					des images de l'application</a></li>
			<li><a href="<?= $url_gestion; ?>"><i class="fam-bullet-go"></i>Espace
					des gestionnaires</a></li>
		</ul>
	</div>
</div>