<?php
/**
 * Page de création d'un libellé
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 janv. 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$retour = $this->url('sbmadmin', array('action'=> 'libelle-liste', 'page' => $this->page));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    )
);
?>
<h1>Création d'un nouveau libellé</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
        <div id="libelle-ajout-nature" class="row-inner ajout"><?php echo $this->formRow($this->form->get('nature')); ?></div>
        <div id="libelle-ajout-code" class="row-inner ajout"><?php echo $this->formRow($this->form->get('code')); ?></div>
        <div id="libelle-ajout-libelle" class="row-inner ajout"><?php echo $this->formRow($this->form->get('libelle')); ?></div>
        <div id="libelle-ajout-ouvert" class="row-inner ajout"><?php echo $this->formRow($this->form->get('ouvert')); ?></div>
        <div id="libelle-ajout-buttons" class="row-inner ajout">  
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
    </fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>