<?php
/**
 * Vue du module SbmAdmin, controller IndexController, affichant la liste des libelles de l'application
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 janv. 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$libelles = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmadmin', array(
    'action' => 'libelle-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmadmin', array(
    'action' => 'libelle-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmadmin');
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouveau libellé'
    )
);
?>
<h1>Liste des libellés de l'application</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
	    <div class="float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	    <div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
	</div>
	<div id="liste-inner">
	    <table class="libelles">
		    <tbody>
		        <tr><th>Nature</th><th>Code</th><th>Libellé</th><th>Ouvert</th></tr>
          <?php foreach($libelles as $test => $libelle): ?>
                <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				    <td class="nature"><?php echo $this->escapeHtml($libelle->nature); ?></td>
				    <td class="code centre"><?php echo $this->escapeHtml($libelle->code); ?></td>
				    <td class="libelle"><?php echo $this->escapeHtml($libelle->libelle); ?></td>
				    <td class="ouvert centre"><?php echo $this->escapeHtml($libelle->ouvert); ?></td>
				    <td class="boutons">
            <?php
            $url_edit = $this->url('sbmadmin', array(
                'action' => 'libelle-edit',
                'page' => $this->page,
            ));
            $url_delete = $this->url('sbmadmin', array(
                'action' => 'libelle-suppr',
                'page' => $this->page,
            ));
            $url_group = $this->url('sbmadmin', array(
                'action' => 'libelle-group',
                'page' => $this->page,
            ));
            $hiddens = array(
                'id' => $libelle->nature . '|' . $libelle->code
            );
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'libellés de même nature'
                )
            );
            echo $this->listeLigneActions($hiddens['id'], $hiddens, $buttons);
            ?>
				    </td>
			    </tr>         
        <?php endforeach;?>
            </tbody>
	    </table>
	</div>
	<div id="liste-footer">
	    <div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	    <div class="criteres-wrapper">
        <?php echo $this->form()->openTag($this->criteres_form);?>
        <?php echo $this->formCollection($this->criteres_form, true);?>
        <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>