<?php
/**
 * Page de suppression d'un libellé
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Suppression d'un libellé</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du libellé :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->nature); ?></li>
			<li><?= $this->data->code; ?></li>
			<li><?= $this->escapeHtml($this->data->libelle); ?></li>
		</ul>
		<p>Dans le paramétrage actuel, c'est un libellé 
			<?= $this->data->ouvert ? 'employé' : 'inemployé'; ?> dans l'application.</p>
	</div>
	<p>Confirmez-vous ?</p>
		<?= $this->form()->openTag($this->form);?> 
		<?= $this->formCollection($this->form);?> 
		<?= $this->form()->closeTag();?> 
</div>