<?php
/**
 * Vue du module SbmAdmin, controller IndexController, affichant la liste des libelles de l'application
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$retour = $this->url('sbmadmin', [
    'action' => 'libelle-liste',
    'page' => $this->page
]);
$url_rapports = $this->url('sbmadmin',
    [
        'action' => 'libelle-group-pdf'
    ]);
$hiddens = [
    'nature' => $this->nature,
    //'code' => $this->code
];
$menuImpression = $this->menuRapports(
    $this->url('sbmadmin', [
        'action' => 'libelle-group'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens']; // mise à jour si nécessaire par l'ajout de 'documentId'
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
];
?>
<h1>Libellés de même nature</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li><?= $this->escapeHtml($this->nature); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?= $this->data->count(); ?> libellés.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="libelles">
			<tbody>
				<tr>
					<th>Nature</th>
					<th>Code</th>
					<th>Libellé</th>
					<th>Ouvert</th>
				</tr>
                    <?php foreach($this->data as $row): ?>
                    <tr
					class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="nature"><?= $this->escapeHtml($row['nature']); ?></td>
					<td class="code centre"><?= $this->escapeHtml($row['code']); ?></td>
					<td class="libelle"><?= $this->escapeHtml($row['libelle']); ?></td>
					<td class="ouvert centre"><?= $this->escapeHtml($row['ouvert']); ?></td>
				</tr>
                    <?php endforeach;?>
                </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?= $this->data->count(); ?> libellés.</em>
		</p>
	</div>
</div>