<?php
/**
 * Page de modification d'un libellé
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin',
    [
        'action' => 'libelle-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un libellé</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('id'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
		<fieldset class="sbm-page1">
			<div id="wrapper-nature" class="row-inner edit">
				<?= $this->formRow($this->form->get('nature')); ?></div>
			<div id="wrapper-code" class="row-inner edit">
				<?= $this->formRow($this->form->get('code')); ?></div>
			<div id="wrapper-libelle" class="row-inner edit">
				<?= $this->formRow($this->form->get('libelle')); ?></div>
			<div id="wrapper-ouvert" class="row-inner edit">
				<?= $this->formRow($this->form->get('ouvert')); ?></div>
			<div id="wrapper-buttons" class="row-inner edit">
        		<?= $this->formSubmit($this->form->get('submit'))?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>