<?php
/**
 * Page de modification d'un libellé
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'libelle-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un libellé</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
			<div id="libelle-edit-nature" class="row-inner edit"><?php echo $this->formRow($this->form->get('nature')); ?></div>
			<div id="libelle-edit-code" class="row-inner edit"><?php echo $this->formRow($this->form->get('code')); ?></div>
			<div id="libelle-edit-libelle" class="row-inner edit"><?php echo $this->formRow($this->form->get('libelle')); ?></div>
			<div id="libelle-edit-ouvert" class="row-inner edit"><?php echo $this->formRow($this->form->get('ouvert')); ?></div>
			<div id="libelle-edit-buttons" class="row-inner edit">  
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>