<?php
/**
 * Vue du module SbmAdmin, controller IndexController, affichant la liste des libelles de l'application
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource libelle-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$libelles = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmadmin',
    [
        'action' => 'libelle-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmadmin',
    [
        'action' => 'libelle-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmadmin');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmadmin', [
        'action' => 'libelle-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens']; // mise à jour si nécessaire par l'ajout de 'documentId'
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau libellé'
    ]
];
?>
<h1>Liste des libellés de l'application</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="libelles">
			<tbody>
				<tr>
					<th>Nature</th>
					<th>Code</th>
					<th>Libellé</th>
					<th>Ouvert</th>
				</tr>
          		<?php foreach($libelles as $libelle): ?>
          		<?php
                $url_edit = $this->url('sbmadmin',
                    [
                        'action' => 'libelle-edit',
                        'page' => $this->page
                    ]);
                $url_delete = $this->url('sbmadmin',
                    [
                        'action' => 'libelle-suppr',
                        'page' => $this->page
                    ]);
                $url_group = $this->url('sbmadmin',
                    [
                        'action' => 'libelle-group',
                        'page' => $this->page
                    ]);
                $hiddens = [
                    'id' => $libelle->nature . '|' . $libelle->code
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'libellés de même nature'
                    ]
                ];
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="nature"><?= $this->escapeHtml($libelle->nature); ?></td>
					<td class="code centre"><?= $this->escapeHtml($libelle->code); ?></td>
					<td class="libelle"><?= $this->escapeHtml($libelle->libelle); ?></td>
					<td class="ouvert centre"><?= $this->escapeHtml($libelle->ouvert); ?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($hiddens['id'], $hiddens, $buttons);?></td>
				</tr>         
        		<?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        <?= $this->form()->openTag($this->criteres_form);?>
        <?= $this->formCollection($this->criteres_form, true);?>
        <?= $this->form()->closeTag();?>
        </div>
	</div>
</div>