<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource pdf-dupliquer.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 janv. 2015
 * @version 2015-1
 */

?>
<h1>Dupliquer un document pdf</h1> 
<p><i>à voir ultérieurement ...</i></p> 