<?php
/**
 * Vue du module SbmAdmin, controller IndexController, affichant la liste des documents pdf
 *
 *
 * @project sbm
 * @package SbmAdmin/view/pdf
 * @filesource pdf-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$documents = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmadmin', array(
    'action' => 'pdf-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmadmin', array(
    'action' => 'pdf-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmadmin');
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouveau document'
    )
);
?>
<h1>Liste des documents pdf</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
	    <div class="float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	    <div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
	</div>
	<div id="liste-inner">
	    <table class="pdf">
		    <tbody>
		    <tr><th>Id</th><th>Nom</th><th>Source</th><th>Filtre</th><th>Ordre</th><th>Format</th><th>Orientation</th><th>Entête de document</th><th>Titre</th><th>Pied de document</th><th>Entête de page</th><th>Contenu</th><th>Pied de page</th></tr>
            <?php foreach($documents as $test => $doc): ?>
                <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				    <td class="documentId"><?php echo $doc->documentId; ?></td>
				    <td class="name"><?php echo $this->escapeHtml($doc->name); ?></td>
				    <td class="recordSource"><?php echo $this->escapeHtml($doc->recordSource); ?></td>
				    <td class="filter"><?php echo $this->escapeHtml($doc->filter); ?></td>
				    <td class="orderBy"><?php echo $this->escapeHtml($doc->orderBy); ?></td>
				    <td class="pdf_page_format"><?php echo $doc->page_format; ?></td>
				    <td class="pdf_page_orientation"><?php echo $doc->page_orientation; ?></td>
				    <td class="docheader"><?php echo $doc->docheader; ?></td>
				    <td class="title"><?php echo $this->escapeHtml($doc->title); ?></td>
				    <td class="docfooter"><?php echo $doc->docfooter; ?></td>
				    <td class="pageheader"><?php echo $doc->pageheader; ?></td>
				    <td class="pageheader_title"><?php echo $this->escapeHtml($doc->pageheader_title); ?></td>
				    <td class="pagefooter"><?php echo $doc->pagefooter; ?></td>
				    <td class="boutons">
            <?php
            $url_edit = $this->url('sbmadmin', array(
                'action' => 'pdf-edit',
                'page' => $this->page,
            ));
            $url_delete = $this->url('sbmadmin', array(
                'action' => 'pdf-suppr',
                'page' => $this->page,
            ));
            $url_dupliquer = $this->url('sbmadmin', array(
                'action' => 'pdf-dupliquer',
                'page' => $this->page,
            ));
            $url_group = $this->url('sbmadmin', array(
                'action' => 'pdf-group',
                'page' => $this->page,
            ));
            $hiddens = array(
                'documentId' => $doc->documentId
            );
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'dupliquer' => array(
                    'class' => 'fam-user-add',
                    'formaction' => $url_dupliquer,
                    'title' => 'dupliquer'
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'documents ayant la même source de données'
                )
            );
            echo $this->listeLigneActions($doc->documentId, $hiddens, $buttons);
            ?>
				    </td>
			    </tr>         
        <?php endforeach;?>
            </tbody>
	    </table>
	</div>
	<div id="liste-footer">
	    <div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	    <div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
	    </div>
	</div>    
</div>
