<?php
/**
 * Page de suppression d'un rpi
 *
 * Réservé à l'administrateur
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource rpi-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 mai 2018
 * @version 2018-2.4.1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmadmin',
    [
        'action' => 'rpi-liste'
    ]);
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Suppression d'un RPI</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du RPI :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->nom); ?></li>
			<li><?= $this->escapeHtml($this->data->libelle); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
<?= $this->form()->openTag($form);?>
<?= $this->formCollection($form);?>
<?= $this->form()->closeTag();?>
</div> 