<?php
/**
 * Page de modification d'un rpi
 *
 * Proposé au gestionnaire
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource rpi-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 10 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery('jquery-ui');
$this->themeJS('sbm-admin','rpi-edit.js');
$this->themeJS('commun','checkallbox.js');
$this->headScript()->captureStart();
?>
multicheckbox_actions.init("classe-edit-niveau");
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'rpi-liste'
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<div id="winpopup"></div>
<h1>Composition d'un RPI</h1>
<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="menu float-left">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
	    </div>
	</div>
	<div id="fiche-inner">
	    <?= $this->form()->openTag($this->form);?>
	    <?= $this->formHidden($this->form->get('rpiId'));?>
	    <?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset class="page1">
			<div id="wrapper-nom" class="row-inner">
				<?= $this->formRow($this->form->get('nom'));?></div>
			<div id="wrapper-libelle" class="row-inner">
				<?= $this->formRow($this->form->get('libelle'));?></div>
			<div id="wrapper-niveau" class="row-inner edit">
				<?= $this->formRow($this->form->get('niveau')); ?></div>
			<div id="wrapper-grille" class="row-inner edit">
				<?= $this->formRow($this->form->get('grille')); ?></div>
			<div class="row-inner">
				<table>
					<tr>
						<td style='vertical-align: top; width: 25em'>
							<fieldset>
								<legend>Communes du RPI</legend>
								<table id="rpi-communes">
								<?= $this->rpiCommunes($this->structure['communes']);?>
								</table>
								<p class="sbm-description"
									style="border-top: 1px solid #fdddcc;">
									<b>Note:</b><br> <i class="fam-add"></i> pour ajouter une
									commune.<br> <i class="fam-delete"></i> pour supprimer une
									commune.
								</p>
							</fieldset>
						</td>
						<td>
							<fieldset>
								<legend>Écoles et classes concernées</legend>
								<table id="rpi-etablissements">
<?php
$viewHelperRpiClasses = $this->getHelperPluginManager()->get('rpiClasses');
echo $this->rpiEtablissements($this->structure['etablissements'],
    function ($etablissement) use ($viewHelperRpiClasses) {
        $etablissementId = $etablissement['etablissementId'];
        $lignesClasses = $viewHelperRpiClasses($etablissement);
        return <<<EOT
<table id="rpi-classes-$etablissementId">
    $lignesClasses
</table>
EOT;
    });
?>

								</table>
								<p class="sbm-description"
									style="border-top: 1px solid #fdddcc;">
									<b>Note:</b><br> <i class="fam-add"></i> pour ajouter une école
									ou une classe.<br> <i class="fam-delete"></i> pour supprimer un
									établissement ou une classe.<br> La suppression d'un
									établissement supprime aussi les classes.
								</p>
							</fieldset>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
			<div id="wrapper-buttons" class="row-inner">
            	<?= $this->formSubmit($this->form->get('submit'));?>
            	<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>