<?php
/**
 * Page de création d'une nouvelle entrée d'un secteur scolaire
 *
 * Destiné à l'administrateur
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource secteur-scolaire-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'secteur-scolaire-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Ajout dans un secteur scolaire de collège public</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
	<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset class="page1">
			<div><?php echo $this->formRow($this->form->get('etablissementId'));?></div>
			<div><?php echo $this->formRow($this->form->get('communeId'));?></div>
			<div id="secteur-scolaire-buttons">  
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>