<?php
/**
 * Liste des secteurs scolaires des collèges publics
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource secteur-scolaire-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();

$url_ajouter = $this->url('sbmadmin',
    [
        'action' => 'secteur-scolaire-ajout',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmadmin',
    [
        'action' => 'secteur-scolaire-suppr',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmadmin',
    [
        'action' => 'secteur-scolaire-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmadmin');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmadmin', [
        'action' => 'secteur-scolaire-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle entrée'
    ]
];
?>
<h1>Liste des secteurs scolaires des collèges publics</h1>
<div id="liste-wrapper">
<?php if ($this->etablissementId):?>
	<div id="liste-title">
		<ul>
			<li><?= $this->escapeHtml($this->etablissement->commune); ?></li>
			<li><?= $this->escapeHtml($this->etablissement->nom); ?></li>
		</ul>
	</div>
<?php endif;?>
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
	    </div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner secteurs-scolaires">
			<tbody>
				<tr>
					<th>Commune de l'établissement</th>
					<th>Etablissement</th>
					<th>Communes du secteur scolaire</th>
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
				<?php
                $hiddens = [
                    'etablissementId' => $row->etablissementId,
                    'communeId' => $row->communeId,
                    'origine' => 'secteur-scolaire-liste'
                ];
                $buttons = [
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'Supprimer'
                    ]
                ];
                ?>
                <tr class="<?=$this->cycle(["even", "odd"])->next();?>">
					<td class="communeetab"><?= $this->escapeHtml($row->communeetab); ?></td>
					<td class="etablissement"><?= $this->escapeHtml($row->etablissement); ?></td>
					<td class="commune"><?= $this->escapeHtml($row->commune); ?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($this->serviceId, $hiddens, $buttons);?></td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        <?= $this->form()->openTag($this->criteres_form);?>
        <?= $this->formCollection($this->criteres_form, true);?>
        <?= $this->form()->closeTag();?>
        </div>
	</div>
</div>
