<?php
/**
 * Fiche du commune associé à un user
 *
 * S'il n'y a pas d'association, on présente un formulaire de création d'une relation
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-commune.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 avr. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$url_suppr = $this->url('sbmadmin',
    [
        'action' => 'user-commune-suppr',
        'page' => $this->page
    ]);
$hiddens = [
    'userId' => $this->user->userId,
    'communeId' => $this->commune ? $this->commune->communeId : null
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ],
    'suppr' => [
        'class' => 'fam-group-delete',
        'formaction' => $url_suppr,
        'title' => 'Supprimer la relation entre cet utilisateur et cette commune'
    ]
];
?>
<h1>Commune associée à un compte d'utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="menu">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<div class="float-left">
			<fieldset style="margin-top: 0;" class="sbm-page1 gras">
				<legend>Utilisateur</legend>
				<div><?= $this->user->titre . ' ' . $this->user->nom . ' ' . $this->user->prenom;?><br>&nbsp;
				</div>
				<div>Identifiant: <?= $this->user->email;?><br>&nbsp;
				</div>
				<div>Créé le: <?= $this->user->dateCreation;?></div>
				<div>Modifié le: <?= $this->user->dateModification;?></div>
			</fieldset>
		</div>
		<div class="float-left">
<?php if ($this->commune === false) :?>
        <p class="left-10px">Il n'y a pas de commune associée à ce
				compte d'utilisateur.</p>
		<?= $this->form()->openTag($this->form);?>
        <fieldset class="sbm-page1">
    		<?= $this->formHidden($this->form->get('csrf'));?>
    		<?= $this->formHidden($this->form->get('userId'));?>
            <div id="user-commune-ajout-communeId"
					class="row-inner ajout">
            <?= $this->formRow($this->form->get('communeId'));?>
            </div>
			<div id="classe-ajout-buttons" class="row-inner ajout">
			    <?= $this->formSubmit($this->form->get('submit'));?>
			    <?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
    	<?= $this->form()->closeTag();?>
<?php else :?>
        <fieldset id="user" class="sbm-page1">
			<legend>Commune</legend>
			<div>
				<div class="label">Nom</div>
				<?= $this->commune->alias; ?></div>
			<div>
				<div class="label">Code postal</div>
				<?= $this->commune->codePostal;?></div>
			<div>
				<div class="label">Code INSEE</div>
				<?= $this->commune->communeId; ?></div>
			<div>
				<div class="label">Arlysère</div>
				<?= $this->commune->membre ? 'Oui' : 'Non'; ?></div>
			<div>
				<div class="label">Desservie</div>
				<?= $this->commune->desservie ? 'Oui' : 'Non'; ?></div>
		</fieldset>
<?php endif;?>
        </div>
	</div>
	<div id="fiche-footer"></div>
</div>