<?php
/**
 * Page de création d'un user
 *
 * Destiné à l'administrateur
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'un compte d'utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
    	<?= $this->form()->openTag($this->form);?>
    	<?= $this->formHidden($this->form->get('userId'));?>
    	<?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset id="user" class="page1">
			<div class="clearfix">
				<div class="float-left col1"><?= $this->formRow($this->form->get('titre'));?></div>
				<div class="float-left colsuiv"><?= $this->formRow($this->form->get('nom'));?></div>
				<div class="float-left colsuiv"><?= $this->formRow($this->form->get('prenom'));?></div>
			</div>
			<div class="col1">
				<?= $this->formRow($this->form->get('email'));?></div>
			<div class="col1">
				<?= $this->formRow($this->form->get('categorieId'));?></div>
			<div class="col1">
				<?= $this->formRow($this->form->get('tokenalive'));?></div>
			<div class="col1">
				<?= $this->formRow($this->form->get('confirme'));?></div>
			<div class="col1">
				<?= $this->formRow($this->form->get('active'));?></div>
			<div class="col1">
				<?= $this->formRow($this->form->get('selection'));?></div>
			<div id="wrapper-commentaire"><?= $this->formRow($this->form->get('note'));?></div>
			<div id="user-buttons">  
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
