<?php
/**
 * Page de supprssion d'un user
 *
 * On ne peut supprimer un user que s'il n'est pas associé à un responsable.
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$acategories = [
    255 => 'Administrateur',
    254 => 'Administrateur',
    253 => 'Gestionnaire',
    1 => 'Parent',
    2 => 'Transporteur',
    3 => 'Etablissement'
];
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Suppression d'un compte d'utilisateur</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du compte :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->titre . ' ' . $this->data->nom . ' ' . $this->data->prenom);?></li>
			<li><?= $this->data->email;?></li>
			<li><?= $this->escapeHtml($acategories[$this->data->categorieId]);?></li>
		</ul>
		<p>.</p>
	</div>
<?php if ($this->autorise) : ?>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($this->form);?>
    <?= $this->formCollection($this->form);?>
    <?= $this->form()->closeTag();?>    
<?php else :?>
    <p>Ce compte est celui d'un responsable. Pour supprimer ce compte,
		vous devez d'abord supprimer le responsable associé.</p>
	<div class="menu clearfix"><?= $this->listeZoneActions([], $actions);?></div>
<?php endif;?>
</div>
