<?php

/**
 * Liste des utilisateurs
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-liste.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.4.7
 */
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$acategories = [
    255 => 'Administrateur',
    254 => 'Administrateur',
    253 => 'Gestionnaire',
    200 => 'Secrétariat',
    1 => 'Parent',
    2 => 'Transporteur',
    3 => 'Etablissement'
];

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsTrigger = '';
$jsCallback = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxadmin/'+action+'selectionuser/userId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$users = $this->paginator->getCurrentItems();
$url_edit = $this->url('sbmadmin', [
    'action' => 'user-edit',
    'page' => $this->page
]);
$url_delete = $this->url('sbmadmin', [
    'action' => 'user-suppr',
    'page' => $this->page
]);
$url_group = $this->url('sbmadmin', [
    'action' => 'user-link',
    'page' => $this->page
]);
$url_ajouter = $this->url('sbmadmin', [
    'action' => 'user-ajout',
    'page' => $this->page
]);
$url_rapports = $this->url('sbmadmin', [
    'action' => 'user-pdf',
    'page' => $this->page
]);
$url_creer_comptes_parent = $this->url('sbmadmin',
    [
        'action' => 'user-prepare-nouveaux-comptes',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmadmin');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmadmin', [
        'action' => 'user-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    '' => [
        'class' => 'fam-cog-add',
        'formaction' => $url_creer_comptes_parent,
        'title' => 'Créer tous les comptes de parents ayant un email'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel utilisateur'
    ]
];
?>
<h1>Liste des utilisateurs</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
    	<?= $this->flashMessenger()->render('success');?>
    	<?= $this->flashMessenger()->render('warning');?>
    	<?= $this->flashMessenger()->render('error');?>
    	<?= $this->flashMessenger()->render('info');?>
    	<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="users">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Email</th>
					<th>Catégorie</th>
					<th>Sans mdp</th>
					<th>Confirmé</th>
					<th>Actif</th>
					<th>Sélection</th>
				</tr>
          <?php foreach($users as $user): ?>
          <?php
            // construction du JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $user->userId);
            $jsCallback .= sprintf("$modele\n", $user->userId, $user->userId);
            // préparation des boutons de la ligne
            $hiddens = [
                'userId' => $user->userId,
                'email' => $user->email
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ],
                'relation' => [
                    'class' => 'fam-group-link',
                    'formaction' => $url_group,
                    'title' => 'fiche du compte associé (responsable, transporteur ou établissement)'
                ]
            ];
            ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="nom">
						<?= $this->escapeHtml($user->nom); ?></td>
					<td class="prenom">
						<?= $this->escapeHtml($user->prenom); ?></td>
					<td class="email">
						<?= $this->escapeHtml($user->email); ?></td>
					<td class="categorieId">
						<?= $this->escapeHtml($acategories[$user->categorieId]); ?></td>
					<td class="tokenalive centre">
						<?= $user->categorieId == 255 ? '' : ($user->tokenalive ? 'Oui' : ''); ?></td>
					<td class="confirme centre">
						<?= $user->categorieId == 255 ? '' : ($user->confirme ? '' : 'Non'); ?></td>
					<td class="active centre">
						<?= $user->categorieId == 255 ? '' : ($user->active ? '' : 'Non'); ?></td>
					<td class="selection centre">
						<?= $user->categorieId == 255 ? '' : renderCheckbox($this, 'selection', 'chk' . $user->userId, $user->selection)?></td>
					<td class="boutons">
            			<?= $user->categorieId == 255 ? '' : $this->listeLigneActions($hiddens['userId'], $hiddens, $buttons);?>
				    </td>
				</tr>         
        <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        <?= $this->form()->openTag($this->criteres_form);?>
        <?= $this->formCollection($this->criteres_form, true);?>
        <?= $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
// Mise en place du JS pour selection
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?= $jsTrigger;?>}
<?= $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();