<?php
/**
 * Fiche du responsable associé à un user
 *
 * Pas de modification ni d'action sur cette page
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-link.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 fév. 2019
 * @version 2019-2.4.7
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Fiche du responsable associé à un compte d'utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="menu float-left">
        	<?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="float-left">
			<ul style="margin-top: 0;" class="gras">
				<li><?= $this->user->titre . ' ' . $this->user->nom . ' ' . $this->user->prenom;?></li>
				<li>Identifiant: <?= $this->user->email;?></li>
				<li>Créé le: <?= $this->user->dateCreation;?> 
					- Modifié le: <?= $this->user->dateModification;?></li>
			</ul>
		</div>
	</div>
	<div id="fiche-inner">
<?php if ($this->responsable === false) :?>
        <p class="left-10px">Il n'y a pas de responsable associé à ce
			compte d'utilisateur.</p>
<?php else :?>
        <fieldset id="user" class="page1">
			<div>
				<div class="label">Titre</div>
				<?= $this->responsable->titre; ?></div>
			<div>
				<div class="label">Nom</div>
				<?= $this->responsable->nom; ?></div>
			<div>
				<div class="label">Prénom</div>
				<?= $this->responsable->prenom; ?></div>
			<div>
				<div class="label">Adresse</div>
				<?= $this->responsable->adresseL1; ?></div>
			<div>
				<div class="label">Adresse</div>
				<?= $this->responsable->adresseL2; ?></div>
			<div>
				<div class="label">Localité</div>
				<?= $this->responsable->codePostal . ' ' . $this->responsable->commune; ?></div>
			<div>
				<div class="label">Téléphone</div>
				<?= $this->telephone($this->responsable->telephoneF); ?></div>
			<div>
				<div class="label">Téléphone</div>
				<?= $this->telephone($this->responsable->telephoneP); ?></div>
			<div>
				<div class="label">Téléphone</div>
				<?= $this->telephone($this->responsable->telephoneT); ?></div>
			<div>
				<div class="label">Email</div>
				<?= $this->responsable->email; ?></div>
			<div>
				<div class="label">Créé le</div>
				<?= $this->responsable->dateCreation; ?></div>
			<div>
				<div class="label">Modifié le</div>
				<?= $this->responsable->dateModification; ?></div>
			<div class="clearfix">
				<div class="label float-left">Commentaires</div>
				<div class="float-left" style="width: 750px;"><?= $this->responsable->note; ?></div>
			</div>
		</fieldset>
<?php endif;?>
    </div>
	<div id="fiche-footer"></div>
</div>