<?php
/**
 * Page de supprssion d'un user
 *
 * On ne peut supprimer un user que s'il n'est pas associé à un responsable.
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 mai 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$acategories = array(
    255 => 'Administrateur',
    254 => 'Administrateur',
    253 => 'Gestionnaire',
    1 => 'Parent',
    2 => 'Transporteur',
    3 => 'Etablissement'
);
$url_retour = $this->url('sbmadmin', array(
    'action' => 'user-liste',
    'page' => $this->page
));
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);
?>
<h1>Suppression d'un compte d'utilisateur</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du compte :</p>
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapeHtml($this->data->titre . ' ' . $this->data->nom . ' ' . $this->data->prenom); ?></li>
			<li><?php echo $this->data->email; ?></li>
			<li><?php echo $this->escapeHtml($acategories[$this->data->categorieId]); ?></li>
		</ul>
		<p>.</p>
	</div>
	<?php if ($this->autorise) : ?>
	<p>Confirmez-vous ?</p>
<?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?> 
    <?php else :?>
    <p>Ce compte est celui d'un responsable. Pour supprimer ce compte,
		vous devez d'abord supprimer le responsable associé.</p>
	<div><?php echo $this->listeZoneActions(array(), $actions);?></div>
    <?php endif;?>
</div>
