<?php
/**
 * Page de modification d'un user
 *
 * Réservé à l'administrateur
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 mars 2019
 * @version 2019-2.4.8
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$cssToken = $this->user->tokenalive ? 'label left-10px ' : 'hidden';
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
// force_canonical est utilisée pour obtenir l'adresse absolue
$url_confirm = $this->url('login', [
    'action' => 'confirm',
    'id' => $this->user->token
], [
    'force_canonical' => true
]);
?>
<h1>Compte d'un utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
    	<?= $this->formHidden($this->form->get('userId'));?>
    	<?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset id="user" class="page1">
			<div class="clearfix">
				<div class="float-left col1"><?= $this->formRow($this->form->get('titre'));?></div>
				<div class="float-left colsuiv"><?= $this->formRow($this->form->get('nom'));?></div>
				<div class="float-left colsuiv"><?= $this->formRow($this->form->get('prenom'));?></div>

			</div>
			<div class="col1"><?= $this->formRow($this->form->get('email'));?></div>
			<div class="col1"><?= $this->formRow($this->form->get('categorieId'));?></div>
			<div class="clearfix">
				<div class="float-left">
					<div class="col1 top-12px"><?= $this->formRow($this->form->get('tokenalive'));?></div>
					<div class="col1"><?= $this->formRow($this->form->get('confirme'));?></div>
					<div class="col1"><?= $this->formRow($this->form->get('active'));?></div>
					<div class="col1"><?= $this->formRow($this->form->get('selection'));?></div>
				</div>
				<div class="float-left left-95px">
					<div>
						<div class="label">Créé le</div>
							<?= $this->user->dateCreation; ?></div>
					<div>
						<div class="label">Modifié le</div>
							<?= $this->user->dateModification; ?></div>
					<div>
						<div class="label">Date du dernier login</div>
							<?= $this->user->dateLastLogin; ?></div>
					<div>
						<div class="label">Date du login précédent</div>
							<?= $this->user->datePreviousLogin; ?></div>
					<div>
						<div class="label">IP du dernier login</div>
							<?= $this->user->adresseIp; ?></div>
					<div>
						<div class="label">IP du login précédent</div>
							<?= $this->user->previousIp; ?></div>
				</div>
			</div>
			<?php if ($this->user->token):?>
			<p>Lien à communiquer pour entrer après demande de mot de passe : <?=$url_confirm;?></p>
			<?php endif;?>
			<div id="wrapper-commentaire"><?= $this->formRow($this->form->get('note'));?></div>
			<div id="user-buttons">  
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
