<?php
/**
 * Page de confirmation du lancement de la procédure
 *
 * La procédure va supprimer les comptes non confirmés et créer les comptes des responsables
 * sans compte associé et dont l'adresse email est connue.
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-prepare-nouveaux-comptes.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 sept. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Préparation des nouveaux comptes d'utilisateurs pour les parents</h1>
<div id="suppr-wrapper">
	<p>Cette procédure va</p>
	<div class="header-wrapper">
		<ul>
			<li>supprimer les comptes de parents non confirmés (sans responsable
				associé) ;</li>
			<li>créer des comptes non confirmés pour les responsables qui n'en
				ont pas et dont l'adresse email est connue.</li>
		</ul>
		<p>Cette procédure peut être lancée sans risque à tout moment de
			l'année.</p>
	</div>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($form);?>
    <?= $this->formCollection($form);?>
    <?= $this->form()->closeTag();?> 
</div>
