<?php
/**
 * Page de modification d'un user
 *
 * Réservé à l'administrateur
 *
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$cssToken = $this->user->tokenalive ? 'label left-10px ' : 'hidden';
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$url_ici = $this->url('sbmadmin', [
    'action' => 'user-edit'
]);
$url_mail = $this->url('sbmadmin', [
    'action' => 'user-mail'
]);
// force_canonical est utilisée pour obtenir l'adresse absolue
$url_confirm = $this->url('login', [
    'action' => 'confirm',
    'id' => $this->user->token
], [
    'force_canonical' => true
]);
if ($this->layout()->hassbmservicesms) {
    $url_sms = $this->url('sbmservicesms', [
        'action' => 'envoi-sms'
    ]);
}
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
if ($this->user->token) {
    $hiddens = [
        'userId' => $this->user->userId,
        'utilisateur' => implode(' ',
            [
                $this->user->titre,
                $this->user->nom,
                $this->user->prenom
            ]),
        'email' => $this->user->email,
        'origine' => $url_ici,
        'sujet' => 'Lien pour accéder à votre compte',
        'contenu' => "Pour accéder à votre compte : $url_confirm"
    ];
    $actions['ecrire'] = [
        'class' => 'fam-email',
        'formaction' => $url_mail,
        'title' => 'Envoyer le lien par email'
    ];
    if ($this->telephones) {
        $hiddens['telephones[]'] = $this->telephones;
        $hiddens['url1_retour'] = $url_ici;
        $hiddens['responsable'] = $hiddens['utilisateur'];
        $actions['sms'] = [
            'class' => 'fam-phone',
            'formaction' => $url_sms,
            'title' => 'Envoyer le lien par SMS'
        ];
    }
}
?>
<h1>Compte d'un utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
    	<?= $this->formHidden($this->form->get('userId'));?>
    	<?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset id="user" class="page1">
			<div class="clearfix">
				<div id="wrapper-titre" class="float-left col1">
					<?= $this->formRow($this->form->get('titre'));?></div>
				<div id="wrapper-nom" class="float-left colsuiv">
					<?= $this->formRow($this->form->get('nom'));?></div>
				<div id="wrapper-prenom" class="float-left colsuiv">
					<?= $this->formRow($this->form->get('prenom'));?></div>
			</div>
			<div id="wrapper-email" class="col1">
				<?= $this->formRow($this->form->get('email'));?></div>
			<div id="wrapper-categorieId" class="col1">
				<?= $this->formRow($this->form->get('categorieId'));?></div>
			<div class="clearfix">
				<div class="float-left">
					<div id="wrapper-tokenalive" class="col1 top-12px">
						<?= $this->formRow($this->form->get('tokenalive'));?></div>
					<div id="wrapper-confirme" class="col1">
						<?= $this->formRow($this->form->get('confirme'));?></div>
					<div id="active" class="col1">
						<?= $this->formRow($this->form->get('active'));?></div>
					<div id="selection" class="col1">
						<?= $this->formRow($this->form->get('selection'));?></div>
				</div>
				<div id="wrapper-infos" class="float-left left-95px">
					<div>
						<div class="label">Créé le</div>
							<?= $this->user->dateCreation; ?></div>
					<div>
						<div class="label">Modifié le</div>
							<?= $this->user->dateModification; ?></div>
					<div>
						<div class="label">Date du dernier login</div>
							<?= $this->user->dateLastLogin; ?></div>
					<div>
						<div class="label">Date du login précédent</div>
							<?= $this->user->datePreviousLogin; ?></div>
					<div>
						<div class="label">IP du dernier login</div>
							<?= $this->user->adresseIp; ?></div>
					<div>
						<div class="label">IP du login précédent</div>
							<?= $this->user->previousIp; ?></div>
				</div>
			</div>
			<?php if ($this->user->token):?>
			<p>Lien à communiquer pour entrer après demande de mot de passe : <?=$url_confirm;?></p>
			<?php endif;?>
			<div id="wrapper-commentaire">
				<?= $this->formRow($this->form->get('note'));?></div>
			<div id="wrapper-buttons">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
