<?php
/**
 * Page de modification d'un user
 *
 * Réservé à l'administrateur
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 avr. 2016
 * @version 2016-2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'javascript:window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Compte d'un utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
	<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('userId'));
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset id="user" class="page1">
			<div class="clearfix">
				<div class="float-left col1"><?php echo $this->formRow($this->form->get('titre'));?></div>
				<div class="float-left colsuiv"><?php echo $this->formRow($this->form->get('nom'));?></div>
				<div class="float-left colsuiv"><?php echo $this->formRow($this->form->get('prenom'));?></div>

			</div>
			<div class="col1"><?php echo $this->formRow($this->form->get('email'));?></div>
			<div class="col1"><?php echo $this->formRow($this->form->get('categorieId'));?></div>
			<div class="clearfix">
				<div class="float-left">
					<div>
						<div class="label">Créé le</div><?php echo $this->user->dateCreation; ?></div>
					<div>
						<div class="label">Modifié le</div><?php echo $this->user->dateModification; ?></div>
					<div>
						<div class="label">Date du dernier login</div><?php echo $this->user->dateLastLogin; ?></div>
					<div>
						<div class="label">Date du login précédent</div><?php echo $this->user->datePreviousLogin; ?></div>
					<div>
						<div class="label">IP du dernier login</div><?php echo $this->user->adresseIp; ?></div>
					<div>
						<div class="label">IP du login précédent</div><?php echo $this->user->previousIp; ?></div>
				</div>
				<div class="float-left left-95px">
					<div class="col1"><?php echo $this->formRow($this->form->get('tokenalive'));?></div>
					<?php $css = $user->tokenalive ? 'label left-10px ' : 'hidden';?>
					<div>
						<div class="<?php echo  $css;?>">Token d'entrée</div><?php echo $this->user->token; ?></div>
					<div class="col1"><?php echo $this->formRow($this->form->get('confirme'));?></div>
					<div class="col1"><?php echo $this->formRow($this->form->get('active'));?></div>
					<div class="col1"><?php echo $this->formRow($this->form->get('selection'));?></div>
				</div>
			</div>
			<div id="wrapper-commentaire"><?php echo $this->formRow($this->form->get('note'));?></div>
			<div id="user-buttons">  
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
