<?php
/**
 * Fiche du etablissement associé à un user
 *
 * S'il n'y a pas d'association, on présente un formulaire de création d'une relation
 * 
 * @project sbm
 * @package SbmAdmin/view/sbm-admin/index
 * @filesource user-etablissement.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 fév. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmadmin', [
    'action' => 'user-liste',
    'page' => $this->page
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Fiche du etablissement associé à un compte d'utilisateur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header" class="clearfix">
		<div class="menu float-left">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
		<div class="float-left">
			<ul style="margin-top: 0;" class="gras">
				<li><?= $this->user->titre . ' ' . $this->user->nom . ' ' . $this->user->prenom;?></li>
				<li>Identifiant: <?= $this->user->email;?></li>
				<li>Créé le: 
					<?= $this->user->dateCreation;?> - Modifié le: <?= $this->user->dateModification;?></li>
			</ul>
		</div>
	</div>
	<div id="fiche-inner">
<?php if ($this->etablissement === false) :?>
        <p class="left-10px">Il n'y a pas de etablissement associé à ce
			compte d'utilisateur.</p>
		<?= $this->form()->openTag($this->form);?>
        <fieldset class="sbm-page1">
            <?= $this->formHidden($this->form->get('csrf'));?>
            <?= $this->formHidden($this->form->get('userId'));?>
            <div id="user-etablissement-ajout-etablissementId"
				class="row-inner ajout"><?= $this->formRow($this->form->get('etablissementId'));?></div>
			<div id="classe-ajout-buttons" class="row-inner ajout">
			    <?= $this->formSubmit($this->form->get('submit'));?>
			    <?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
    <?= $this->form()->closeTag();?>
<?php else :?>
        <fieldset id="user" class="page1">
			<div>
				<div class="label">Nom</div>
				<?= $this->etablissement->nom; ?></div>
			<div>
				<div class="label">Adresse</div>
				<?= $this->etablissement->adresse1; ?></div>
			<div>
				<div class="label">Adresse</div>
				<?= $this->etablissement->adresse2; ?></div>
			<div>
				<div class="label">Localité</div>
				<?= $this->etablissement->codePostal?>
				<?= $this->etablissement->commune; ?></div>
			<div>
				<div class="label">Téléphone</div>
				<?= $this->telephone($this->etablissement->telephone); ?></div>
			<div>
				<div class="label">Fax</div>
				<?= $this->telephone($this->etablissement->fax); ?></div>
			<div>
				<div class="label">Email</div>
				<?= $this->etablissement->email; ?></div>
			<div>
				<div class="label">Directeur</div>
				<?= $this->etablissement->directeur; ?></div>
			<div>
				<div class="label">Horaires du matin</div>
				de <?= $this->etablissement->hMatin; ?> 
				à <?= $this->etablissement->hMidi; ?></div>
			<div>
				<div class="label">de l'après-midi</div>
				de <?= $this->etablissement->hAMidi; ?> 
				à <?= $this->etablissement->hSoir; ?></div>

		</fieldset>
<?php endif;?>
    </div>
	<div id="fiche-footer"></div>
</div>