<?php
/**
 * Page de création d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 fév. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->headScript()->appendFile($this->basePath('/js/gestion-eleve/ajout.js'));
$this->inlineScript()->captureStart();
?>
js_ajout.montreGa();
<?php
$this->inlineScript()->captureEnd();
// ================= Fin JS =======================================================
// le retour se fait dans l'action eleveAjoutAction() pour décharger le redirectorToOrigin()
$url_ici = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-ajout',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_ici, // traitement de cancel pour un redirectToOrigin()->back()
                                   // proprement
        'title' => 'Retour'
    ]
];
if (! $this->form instanceof \Zend\Form\FormInterface) {
    try {
        $responsable2Id = $this->data->responsable2Id;
    } catch (\SbmCommun\Model\Db\ObjectData\Exception\ExceptionInterface $e) {
        $responsable2Id = null;
    }
    $hiddens = [
        'eleveId' => $this->data->eleveId,
        'nom' => $this->data->nom,
        'prenom' => $this->data->prenom,
        'dateN' => $this->data->dateN,
        'responsable1Id' => $this->data->responsable1Id,
        'responsable2Id' => $responsable2Id
    ];
    $url_nouveau = $this->url('sbmgestion/eleve',
        [
            'action' => 'eleve-ajout22',
            'page' => $this->page
        ]);
    $url_reprise = $this->url('sbmgestion/eleve',
        [
            'action' => 'eleve-ajout21',
            'page' => $this->page
        ]);
    $actions['nouveau'] = [
        'class' => 'fam-basket-add',
        'formaction' => $url_nouveau,
        'title' => 'Nouvel élève'
    ];
}
?>
<h1>Création d'un nouvel élève</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<?php if ($this->form instanceof \Zend\Form\FormInterface) :?>
	<div id="fiche-inner">	
    <?= $this->form()->openTag($this->form);?>
    <?= $this->formHidden($this->form->get('eleveId'));?>
    <?= $this->formHidden($this->form->get('csrf'));?>    
        <fieldset id="commun" class="sbm-page1">
			<div id="commun-col1">
				<div id="wrapper-nom" class="row-inner edit">
				<?= $this->formRow($this->form->get('nom'));?></div>
				<div id="wrapper-prenom" class="row-inner edit">
				<?= $this->formRow($this->form->get('prenom'));?></div>
				<div id="wrapper-dateN" class="row-inner edit">
				<?= $this->formRow($this->form->get('dateN'));?></div>
				<div id="wrapper-responsable1Id" class="row-inner edit">
				<?= $this->formRow($this->form->get('responsable1Id'));?></div>
				<div id="wrapper-ga" class="row-inner edit">
				<?= $this->formRow($this->form->get('ga'));?></div>
				<div id="wrapper-responsable2Id" class="row-inner edit">
				<?= $this->formRow($this->form->get('responsable2Id'));?></div>
				<div id="eleve-edit-buttons" class="row-inner edit">
                    <?= $this->formSubmit($this->form->get('submit'))?>
                    <?= $this->formSubmit($this->form->get('cancel'));?>
                </div>
			</div>
		</fieldset>
<?= $this->form()->closeTag();?>
    </div>
    <?php else :?>
    <div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Numéro</th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Né(e) le</th>
					<th>Responsable 1</th>
					<th>Commune</th>
					<th>Responsable 2</th>
					<th>Commune</th>
					<th></th>
				</tr>
			<?php foreach($this->eleves as $eleve): ?>
			<?php
        $info = $eleve['nom'] . ' ' . $eleve['prenom'];
        $hiddensLigne = [
            'eleveId' => $eleve['eleveId'],
            'info' => $info
        ];
        $actionsLigne = [
            'reprendre' => [
                'class' => 'fam-basket-put',
                'formaction' => $url_reprise,
                'title' => 'Choisir ' . $info
            ]
        ];
        ?>
				<tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="numero">
						<?= $eleve['numero']; ?></td>
					<td class="nom">
						<?= $this->escapeHtml($eleve['nom']); ?></td>
					<td class="prenom">
						<?= $this->escapeHtml($eleve['prenom']); ?></td>
					<td class="dateN">
						<?= $this->escapeHtml($eleve['dateN']); ?></td>
					<td class="responsable1">
						<?= $this->escapehtml($eleve['responsable1NomPrenom']); ?></td>
					<td class="commune1">
						<?= $this->escapehtml($eleve['communeR1']); ?></td>
					<td class="responsable2">
						<?= $this->escapehtml($eleve['responsable2NomPrenom']); ?></td>
					<td class="commune2">
						<?= $this->escapeHtml($eleve['communeR2']);?></td>
					<td>
						<?= $this->listeLigneActions($eleve['eleveId'], $hiddensLigne, $actionsLigne);?></td>
				</tr>
			<?php endforeach;?>
            </tbody>
		</table>
	</div>
    <?php endif;?>
</div>