<?php
/**
 * Page de création d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 juillet 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/eleve', array('action'=> 'eleve-liste', 'page' => $this->page));
?>
<h1>Création d'un nouvel élève</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la liste des élèves"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('eleveId'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div id="eleve-edit-nom" class="row-inner edit">' . $this->formRow($this->form->get('nom')) . '</div>';
echo '<div id="eleve-edit-prenom" class="row-inner edit">' . $this->formRow($this->form->get('prenom')) . '</div>';
echo '<div id="eleve-edit-dateN" class="row-inner edit">' . $this->formRow($this->form->get('dateN')) . '</div>';
echo '<div id="eleve-edit-regimeId" class="row-inner edit">' . $this->formRow($this->form->get('regimeId')) . '</div>';
echo '<div id="eleve-edit-etablissementId" class="row-inner edit">' . $this->formRow($this->form->get('etablissementId')) . '</div>';
echo '<div id="eleve-edit-classeId" class="row-inner edit">' . $this->formRow($this->form->get('classeId')) . '</div>';
//echo '<div id="eleve-edit-horaire1" class="row-inner edit">' . $this->formRow($this->form->get('titreR1')) . '</div>';
//echo '<div id="eleve-edit-horaire2" class="row-inner edit">' . $this->formRow($this->form->get('horaire2')) . '</div>';
//echo '<div id="eleve-edit-horaire3" class="row-inner edit">' . $this->formRow($this->form->get('horaire3')) . '</div>';
echo '<div id="eleve-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</fieldset>';
echo $this->form()->closeTag();
?>
</div>