<?php
/**
 * Page de confirmation de remise à zéro des sélections
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-selection.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 31 août 2015
 * @version 2015-1
 */
?>
<h1>Démarquer les fiches sélectionnées</h1>
<div id="suppr-wrapper">
<?php  
if ($this->nbSelection) :
    if ($this->nbSelection > 1) {
        $description = sprintf('%d fiches sélectionnées', $this->nbSelection);
    } else {
        $description = '1 fiche sélectionnée';
    }
    ?>
	<p>Il y a <?php echo $description; ?>.</p>
	<p>Vous souhaitez que toutes les fiches élèves soient désélectionnées.</p>
	<p>Confirmez ou abandonnez.</p>
<?php else :?>
    <p>Il n'y a pas de fiche sélectionnée.</p>
    <?php 
        $this->form->remove('csrf')->remove('confirmer');
    ?>
<?php endif;?>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>