<?php
/**
 * Liste des élèves
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 juil. 2014
 * @version 2014-1
 */
$this->paginator->setDefaultItemCountPerPage($this->nb_eleve_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$eleves = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/eleve');
?>
<h1>Liste des élèves</h1>
<div class="liste-wrapper">
	<div class="zone-actions">
		<a href="<?php echo $retour; ?>" class="bouton"
			title="retour au menu de gestion des élèves"><i
			class="fam-door-out"></i> Retour</a> <a href="<?php echo $pdf; ?>"
			class="bouton" title="exporter en pdf" target="_blank"><i
			class="fam-application-view-list"></i> Exporter en pdf</a> <a
			href="<?php echo $ajouter; ?>" class="bouton"
			title="créer un nouvel élève"><i class="fam-add"></i> Ajouter
			un élève</a>
	</div>
	<table class="liste-inner eleves">
		<tbody>
        <?php foreach($eleves as $test => $eleve): ?>
         <tr
				class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				<td class="eleveId"><?php echo $eleve->eleveId; ?></td>
				<td class="numero"><?php echo $eleve->numero; ?></td>
				<td class="nom"><?php echo $this->escapeHtml($eleve->nom); ?></td>
				<td class="prenom"><?php echo $this->escapeHtml($eleve->prenom); ?></td>
				<td class="dateN"><?php echo $this->escapehtml($eleve->dateN); ?></td>
				<td class="responsable1"><?php echo $this->escapehtml($eleve->responsable1NomPrenom); ?></td>
				<td class="responsable2"><?php echo $this->escapeHtml($eleve->responsable2NomPrenom); ?></td>
				<td class="responsableF"><?php echo $this->escapeHtml($eleve->responsableFNomPrenom); ?></td>
				<td class="selection"><?php echo $eleve->selection ? 'X' : ''; ?></td>
				<td class="boutons">
             <?php
            $url_edit = $this->url('sbmgestion/eleve', array(
                'action' => 'eleve-edit',
                'page' => $this->page,
                'id' => $eleve->eleveId
            ));
            $url_delete = $this->url('sbmgestion/eleve', array(
                'action' => 'eleve-suppr',
                'page' => $this->page,
                'id' => $eleve->eleveId
            ));
            $url_group = $this->url('sbmgestion/eleve', array(
                'action' => 'eleve-group',
                'page' => $this->page,
                'id' => $eleve->responsable1Id
            ));
            ?>
                 <a href="<?php echo $url_edit; ?>" class="bouton"
					title="modifier"><i class="fam-pencil"></i></a> <a
					href="<?php echo $url_delete; ?>" class="bouton" title="supprimer"><i
						class="fam-delete"></i></a> <a href="<?php echo $url_group; ?>"
					class="bouton" title="groupe des élèves ayant le même responsable 1"><i
						class="fam-group"></i></a>
				</td>
			</tr>         
        <?php endforeach;?>
    </tbody>
	</table>
	<div class="zone-pagination"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
<?php echo $this->form()->openTag($this->criteres_form);?>
<?php echo $this->formCollection($this->criteres_form, true);?>
<?php echo $this->form()->closeTag();?>	
</div>