<?php
/**
 * Page de localisation d'un élève dont les coordonnées sont données
 *
 * (La carte est centrée avec les mêmes paramètres que pour les cartes des parents)
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 juin 2015
 * @version 2015-1
 */
$nomEleve =  implode(' ', array($this->eleve['nom'], $this->eleve['prenom']));
// calcul du contenu de l'infobulle
$description = array();
$description[] = '<b>' . $nomEleve . '</b>';
//$description[] = $this->responsable->adresseL1;
//$tmp = $this->responsable->adresseL2;
//if (!empty($tmp)) {
//    $description[] = $this->responsable->adresseL2;
//}
//$description[] = implode(' ', array($this->responsable->codePostal, $this->responsable->commune));
//$telephone = array();
//$tmp = $this->responsable->telephoneF;
//if (!empty($tmp)) {
//    $telephone[] = $this->responsable->telephoneF;
//}
//$tmp = $this->responsable->telephoneP;
//if (!empty($tmp)) {
//    $telephone[] = $this->responsable->telephoneP;
//}
//$tmp = $this->responsable->telephoneT;
//if (!empty($tmp)) {
//    $telephone[] = $this->responsable->telephoneT;
//}
//$tel = implode(' ', $telephone);
//if (!empty($tel)) {
//    $description[] = 'Tél.' . $tel;
//}
//$description[] = $this->responsable->email;

// mise en place des JS de googleMaps
$this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->captureStart();?>
var marker;
function initialiser() {
    var latlng = new google.maps.LatLng(<?php echo $this->config['centre']['lat'];?>, <?php echo $this->config['centre']['lng'];?>);
    // initialisation des paramètres de la carte
    var options = {
        center: latlng,
        zoom: <?php echo $this->config['zoom'];?>,
        //mapTypeId: google.maps.MapTypeId.ROADMAP
        mapTypeId: "OSM",
        mapTypeControl: true,
        mapTypeControlOptions: {
            mapTypeIds: [
                "OSM",
                //google.maps.MapTypeId.ROADMAP, 
                //google.maps.MapTypeId.SATELLITE, 
                google.maps.MapTypeId.HYBRID, 
                google.maps.MapTypeId.TERRAIN
            ],
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        streetViewControl: true
    };
    var carte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // define OSM map type pointing at the OpenStreetMap tile server
    carte.mapTypes.set("OSM", new google.maps.ImageMapType({
        getTileUrl: function(coord, zoom) {
            return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
        },
        tileSize: new google.maps.Size(256,256),
        name: "OpenStreetMap",
        maxZoom: 18,
        opacity: 1,
        alt: "Carte OpenStreetMap"
    }));
    // initialisation du marker
    var optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(document.getElementById('eleve-lat').value, document.getElementById('eleve-lng').value),
        title: 'mon domicile'
    }
    marker = new google.maps.Marker(optionsMarqueur);
    
    var contentMarker = "<?php echo implode('<br/>', $description);?>";
 
var infoWindow = new google.maps.InfoWindow({
    content  : contentMarker,
    position : latlng
});
google.maps.event.addListener(marker, 'click', function() {
    infoWindow.open(carte,marker);
});
    
    google.maps.event.addListener(carte, 'click', function(event) {
        var latlng = event.latLng;
    	document.getElementById('eleve-lat').value = latlng.lat();
    	document.getElementById('eleve-lng').value = latlng.lng();
    	if (marker) {
    	   marker.setPosition(latlng);
    	} else {
    	   var optionsMarker = {
    	       map: carte,
    	       position: new google.maps.LatLng(latlng.lat(), latlng.lng()),
    	       title: 'mon domicile'
    	   }
    	   marker = Marker(optionsMarker);
        }
    });
}

<?php 
$this->headScript()->captureEnd();
// lancement du script (sera affiché dans le layout à la fin de la page
$this->inlineScript()->captureStart(); ?>
initialiser();
<?php $this->inlineScript()->captureEnd(); ?>
<h1>Adresse personnelle de <?php echo $nomEleve;?></h1>
<div id="carte-wrapper">
	<div id="carte-header" class="left-10px">
	<?php echo $this->form()->openTag($this->form);?>
	<?php echo $this->formHidden($this->form->get('eleveId'));?>
	<?php echo $this->formHidden($this->form->get('lat'));?>
	<?php echo $this->formHidden($this->form->get('lng'));?>
	   <fieldset class="sbm-page1">
	       <div id="ligne1">
	       <?php echo $this->formRow($this->form->get('chez'));?>
	       <?php echo $this->formRow($this->form->get('adresseL1'));?>
	       <?php echo $this->formRow($this->form->get('adresseL2'));?>
	       </div>
	       <div id="ligne2" class="top-6px">
	       <?php echo $this->formRow($this->form->get('codePostal'));?>
	       <?php echo $this->formRow($this->form->get('communeId'));?>
	       <?php echo $this->formSubmit($this->form->get('submit'));?>
	       <?php echo $this->formSubmit($this->form->get('remove'));?>
	       <?php echo $this->formSubmit($this->form->get('cancel'));?>
	       </div>
	   </fieldset>
    <?php echo $this->form()->closeTag();?>
<?php
//echo $this->form($this->form);
?>
		<p class="sbm-description">
			Indiquez l'adresse de l'élève puis positionnez la sur la carte avant de cliquer
			sur le bouton <b>'Enregistrer'</b>. Utilisez le zoom pour plus de précision.
		</p>
    </div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
