<?php
/**
 * Liste des élèves
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 juillet 2022
 * @version 2022-2.6.6
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/eleve', 'eleve-liste.css');
// gestion des checkbox selection et demande
$this->jQuery();
$this->themeJs('gestion-eleve', 'eleve-liste.js');

// gestion du hidden op des formulaires de liste : les arguments sont id, suffixe de l'id,
// valeur
// (ne pas mettre de guillemet dans la chaine)
$js_op = 'window.document.getElementById(\'op%s%s\').value=\'%s\';';

// le paginateur
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
try {
    $eleves = $this->paginator->getCurrentItems();
} catch (\Zend\Db\Adapter\Exception\InvalidQueryException $e) {
    // affichage d'une page d'erreur
    ?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-inner">
		<pre>
	  <?= $e->getMessage();?>
	</pre>
	</div>
	<div id="liste-footer">
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
        	<?= $this->form()->openTag($this->criteres_form);?>
            <?= $this->formCollection($this->criteres_form, true);?>
            <?= $this->form()->closeTag();?>
        <?php endif;?>
        </div>
	</div>
</div>
<?php
    return;
} // fin du catch (affichage d'une page d'erreur)
  // affichage d'un message description au bas du tableau si on utilise la couleur rouge
$afficheRouge = false;

// les url à utiliser
$url_deselection = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-selection',
        'page' => $this->page
    ]);
$url_ici = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-liste',
        'page' => $this->page
    ]);
$url_responsable = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-edit',
        'page' => $this->page
    ]);
$url_mail = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-mail'
]);
$url_edit = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-suppr',
        'page' => $this->page
    ]);
$url_group = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-group',
        'page' => $this->page
    ]);
$url_ajouter = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/eleve',
    [
        'action' => empty($this->groupe) ? 'eleve-pdf' : 'eleve-groupe-pdf',
        'page' => $this->page
    ]);
$url_map = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-localisation',
        'page' => $this->page
    ]);
$url_photos = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'photos',
        'page' => $this->page
    ]);
$url_cartes = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'cartes',
        'page' => $this->page
    ]);
$url_download = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-download'
]);
$url_duplicata = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'duplicata-carte',
        'page' => $this->page
    ]);
$url_add_photo = $this->url('sbmgestion/eleve',
    [
        'action' => 'envoiphoto',
        'page' => $this->page
    ]);
$url_gestioneleve = $this->url('sbmgestion/gestioneleve');
$url_majnotification = $this->url('sbmpaiement', [
    'action' => 'majnotification'
]);
$url_eleve_responsables = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-responsables',
        'page' => $this->page
    ]);

// définition de la barre de menu du haut de page pour l'aide de vue listeZoneActions()
if (! empty($this->groupe)) {
    $hiddens = [
        'op' => $this->groupe
    ]; // pour passer les éléments à prendre en compte pour eleve-groupe
} else {
    $hiddens = [];
}
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/eleve', [
        'action' => 'eleve-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens']; // mise à jour si nécessaire par l'ajout de
                                       // 'documentId'

$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_ici,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'cartes' => [
        'class' => 'fam-vcard',
        'formaction' => $url_cartes,
        'title' => 'Edition des cartes'
    ],
    'photos' => [
        'class' => 'fam-photos',
        'formaction' => $url_photos,
        'title' => 'Extraction d\un fichier de photos'
    ],
    'download' => [
        'class' => 'fam-cloud-download',
        'formaction' => $url_download,
        'formtarget' => '_blank',
        'title' => 'Extraction de la liste dans un fichier'
    ],
    'gestion' => [
        'class' => 'fam-application-side-expand',
        'formaction' => $url_gestioneleve,
        'title' => 'Gestion des inscriptions'
    ],
    'responsables' => [
        'class' => 'fam-user-female',
        'formaction' => $url_eleve_responsables,
        'title' => 'Sélectionner les responsables de ces élèves'
    ],
    'selection' => [
        'class' => 'fam-basket-delete',
        'formaction' => $url_deselection,
        'title' => 'Démarquer toutes les sélections'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel élève'
    ]
];
?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
<?= $this->flashMessenger()->render('success');?>
<?= $this->flashMessenger()->render('warning');?>
<?= $this->flashMessenger()->render('error');?>
<?= $this->flashMessenger()->render('info');?>
<?= $this->flashMessenger()->render('default');?>
</div>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Responsables</th>
					<th>Commune</th>
					<th>Établissement</th>
					<th>Classe</th>
					<th>Services</th>
					<th>Sél.</th>
					<th></th>
				</tr>
        		<?php foreach($eleves as $eleve): ?>
        		<?php
            // responsable 1
            // $r = htmlspecialchars(
            // str_replace(' ', '&nbsp;', $eleve['responsable1NomPrenom']), ENT_QUOTES,
            // 'utf-8', false);
            $r = htmlspecialchars($eleve['responsable1NomPrenom'], ENT_QUOTES, 'utf-8',
                false);
            $hiddensR1 = [
                'responsableId' => $eleve['responsable1Id'],
                'info' => $r,
                'origine' => $url_ici
            ];
            $buttonsR1 = [
                'r1' => [
                    'class' => 'fam-magnifier',
                    'formaction' => $url_responsable,
                    'title' => 'Voir sa fiche',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], 'r1', 'voir r1')
                ],
                'localiser' => [
                    'class' => 'fam-map-magnify',
                    'formaction' => $url_map,
                    'title' => 'Localiser cette adresse sur la carte',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], 'r1', 'localiser r1')
                ]
            ];
            if (! empty($eleve['emailR1'])) {
                $hiddensR1 = array_merge($hiddensR1,
                    [
                        'email' => $eleve['emailR1'],
                        'responsable' => sprintf('%s %s', $eleve['titreR1'],
                            $eleve['responsable1NomPrenom']),
                        'group' => $url_ici
                    ]);
                $buttonsR1['ecrire'] = [
                    'class' => 'fam-email',
                    'formaction' => $url_mail,
                    'title' => 'Envoyer un email'
                ];
            }
            $itemR1 = $this->listeLigneActions($eleve['eleveId'] . 'r1', $hiddensR1,
                $buttonsR1, [
                    'style' => 'display: inline;'
                ]);
            $itemR1 .= sprintf('<span title="%s">%s</span>', $eleve['lacommuneR1'], $r);
            // responsable 2
            if ($eleve['responsable2Id']) {
                $r = htmlspecialchars(
                    str_replace(' ', '&nbsp;', $eleve['responsable2NomPrenom']),
                    ENT_QUOTES, 'utf-8', false);
                $hiddensR2 = [
                    'responsableId' => $eleve['responsable2Id'],
                    'info' => $r,
                    'origine' => $url_ici
                ];
                $buttonsR2 = [
                    'r2' => [
                        'class' => 'fam-magnifier',
                        'formaction' => $url_responsable,
                        'title' => 'Voir sa fiche',
                        'onclick' => sprintf($js_op, $eleve['eleveId'], 'r2', 'voir r2')
                    ],
                    'localiser' => [
                        'class' => 'fam-map-magnify',
                        'formaction' => $url_map,
                        'title' => 'Localiser cette adresse sur la carte',
                        'onclick' => sprintf($js_op, $eleve['eleveId'], 'r2',
                            'localiser r2')
                    ]
                ];
                if (! empty($eleve['emailR2'])) {
                    $hiddensR2 = array_merge($hiddensR2,
                        [
                            'email' => $eleve['emailR2'],
                            'responsable' => sprintf('%s %s', $eleve['titreR2'],
                                $eleve['responsable2NomPrenom']),
                            'group' => $url_ici
                        ]);
                    $buttonsR2['ecrire'] = [
                        'class' => 'fam-email',
                        'formaction' => $url_mail,
                        'title' => 'Envoyer un email'
                    ];
                }
                $itemR2 = $this->listeLigneActions($eleve['eleveId'] . 'r2', $hiddensR2,
                    $buttonsR2, [
                        'style' => 'display: inline;'
                    ]);
                $itemR2 .= sprintf('<span title="%s">%s</span>', $eleve['lacommuneR2'], $r);
                $ga = true;
                $rowspan = ' rowspan="2"';
            } else {
                $itemR2 = '';
                $ga = false;
                $rowspan = '';
            }
            // tr css
            $tr_css = $this->cycle([
                "even",
                "odd"
            ])->next();
            if ($eleve['inscrit']) {
                $supprimer_title = 'supprimer ou rayer';
            } else {
                $tr_css .= ' barre';
                $supprimer_title = 'supprimer ou inscrire';
            }
            /*
             * if ($eleve['demandeR1'] == 2 || $eleve['demandeR2'] == 2) { $rouge =
             * $eleve['accordR1'] + $eleve['accordR2'] == 0; } else { $rouge =
             * ($eleve['district'] == 0 && $eleve['derogation'] == 0) ||
             * ($eleve['demandeR1'] + $eleve['demandeR2'] == 0) || ($eleve['distanceR1'] <
             * 1.0 && $eleve['distanceR2'] < 1.0); }
             */
            $rouge = $eleve['demandeR1'] == 1 || ($ga && $eleve['demandeR2'] == 1);
            if ($rouge) {
                $tr_css .= ' alert';
                $afficheRouge = true;
            }
            $inscrit = $eleve['paiementR1'];
            $inscrit |= $eleve['gratuit'] > 0;
            $inscrit |= ($eleve['demandeR1'] == 2 && $eleve['accordR1'] == 0 &&
                $eleve['subventionR1'] == 1);
            $inscrit |= ($eleve['demandeR2'] == 2 && $eleve['accordR2'] == 0 &&
                $eleve['subventionR2'] == 1);
            $affecte = ! is_null($eleve['affecteR1matin']);
            $affecte &= ! is_null($eleve['affecteR1soir']);
            if ($eleve['niveau'] >= 4) {
                $affecte &= ! is_null($eleve['affecteR1midi']);
            }
            // ajouter la même chose pour R2 si nécessaire
            if ($eleve['demandeR2']) {
                $affecte &= ! is_null($eleve['affecteR2matin']);
                $affecte &= ! is_null($eleve['affecteR2soir']);
                if ($eleve['niveau'] >= 4) {
                    $affecte &= ! is_null($eleve['affecteR2midi']);
                }
            }
            // =============================================
            $this->pictogrammes('init')
                ->addPreinscrit(! $inscrit)
                ->addSansAffectation($affecte)
                ->addSansPhoto($eleve['sansphoto'])
                ->addSansCarte($eleve['dateCarteR1'] < $this->dateDebut)
                ->addDistanceZero($eleve['demandeR1'], $eleve['distanceR1'],
                $eleve['demandeR2'], $eleve['distanceR2']);
            $hiddens = [
                'eleveId' => $eleve['eleveId'],
                'info' => $eleve['nom'] . ' ' . $eleve['prenom'],
                'origine' => $url_ici
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], '', 'modifier')
                ],
                'supprimer' => [
                    'class' => 'fam-cross',
                    'formaction' => $url_delete,
                    'title' => $supprimer_title,
                    'onclick' => sprintf($js_op, $eleve['eleveId'], '', 'supprimer')
                ],
                'majNotification' => [
                    'class' => 'fam-transmit-error',
                    'formaction' => $url_majnotification,
                    'title' => 'Vérifier les paiements en ligne',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], '', 'majNotification')
                ],
                'addphoto' => [
                    'class' => 'fam-camera-add',
                    'formaction' => $url_add_photo,
                    'title' => 'Envoyer une photo'
                ],
                'duplicata' => [
                    'class' => 'fam-vcard-add',
                    'formaction' => $url_duplicata,
                    'title' => 'duplicata de la carte de transport',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], '', 'duplicata')
                ],
                'famille' => [
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits de la même famille',
                    'onclick' => sprintf($js_op, $eleve['eleveId'], '',
                        trim($eleve['responsable1Id'] . '|' . $eleve['responsable2Id']),
                        '|')
                ]
            ];
            if (! $eleve['sansphoto']) {
                unset($buttons['addphoto']);
            }
            if ($inscrit || $eleve['appelNotifieOk']) {
                unset($buttons['majNotification']);
            }
            $itinerairesR1 = sprintf(
                $this->printItineraires($eleve['eleveId'], 1, $eleve['demandeR1'] == 1),
                $this->renderCheckbox('demande', 'traite', $eleve['eleveId'], 0,
                    [
                        'data-trajet' => 1,
                        'title' => 'Cochez pour marquer la fiche `traitée` si les itinéraires sont bons'
                    ]));
            if ($ga) {
                $itinerairesR2 = sprintf(
                    $this->printItineraires($eleve['eleveId'], 2, $eleve['demandeR2'] == 1),
                    $this->renderCheckbox('demande', 'traite', $eleve['eleveId'], 0,
                        [
                            'data-trajet' => 2,
                            'title' => 'Cochez pour marquer la fiche `traitée` si les itinéraires sont bons'
                        ]));
            }
            $checkbox_selection = $this->renderCheckbox('selection', 'chk',
                $eleve['eleveId'], $eleve['selectionEleve'],
                [
                    'title' => 'Cocher pour sélectionner la fiche'
                ]);
            ?>
                <tr class="petit <?= $tr_css;?>">
					<td <?= $rowspan;?>>
					<?= $this->pictogrammes();?>
                    </td>
					<td <?= $rowspan;?> class="nom">
						<?= $this->escapeHtml($eleve['nom']); ?></td>
					<td <?= $rowspan;?> class="prenom">
						<?= $this->escapeHtml($eleve['prenom']); ?></td>
					<td class="responsables"><?= $itemR1; ?></td>
					<td class="commune">
						<?= $this->escapeHtml($eleve['lacommuneR1']);?></td>
					<td <?= $rowspan;?> class="etablissement">
						<?= $this->escapeHtml($eleve['etablissement']);?> -
						<?= $this->escapeHtml($eleve['lacommuneEtablissement']);?></td>
					<td <?= $rowspan;?> class="classe">
						<?= $this->escapeHtml($eleve['classe']);?></td>
					<td class="service">
						<?= $itinerairesR1;?></td>
					<td <?= $rowspan;?> class="centre selection">
					<?= $checkbox_selection;?>
					</td>
					<td <?= $rowspan;?> class="boutons">
						<?= $this->listeLigneActions($eleve['eleveId'], $hiddens, $buttons);?></td>
				</tr>
				<?php if ($ga):?>
				<tr class="petit <?= $tr_css;?>">
					<td class="responsables"><?= $itemR2; ?></td>
					<td class="commune"><?= $this->escapeHtml($eleve['lacommuneR2']);?></td>
					<td class="service"><?= $itinerairesR2;?></td>
				</tr>
					<?php endif;?>
        <?php endforeach;?>
    </tbody>
		</table>
		<?php if ($afficheRouge) : ?>
		<p class="description">
			Les lignes écrites en <span class="alert">couleur rouge</span>
			correspondent à des élèves dont la demande n'est pas marquée <i>Traitée</i>.
		</p>
		<?php endif; ?>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
    		<?= $this->form()->openTag($this->criteres_form);?>
    		<?= $this->formCollection($this->criteres_form, true);?>
    		<?= $this->form()->closeTag();?>
    	<?php endif;?>
	    </div>
	</div>
</div>