<?php
/**
 * Page de localisation d'un élève dont les coordonnées sont données
 *
 * (La carte est centrée avec les mêmes paramètres que pour les cartes des parents)
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2019
 * @version 2019-2.5.0
 */
use SbmBase\Model\StdLib;

$nomEleve = implode(' ', [
    $this->eleve['nom'],
    $this->eleve['prenom']
]);
// calcul du contenu de l'infobulle
$description = '<b>' . $nomEleve . '</b>';

// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'localisation.js');
$this->themeJS('commun', 'StyledMarker.js');
// lancement du script (sera affiché dans le layout à la fin de la page
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?= $this->config['centre']['lng'];?>;
const INI_ZOOM = <?= $this->config['zoom'];?>;
initialiser("<?=$this->scheme;?>",'mon domicile', "<?= $description;?>", []);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?><h1>Adresse personnelle de <?= $nomEleve;?></h1>
<div id="carte-wrapper">
	<div id="carte-header" class="left-10px">
	<?= $this->form()->openTag($this->form);?>
	<?= $this->formHidden($this->form->get('eleveId'));?>
	<?= $this->formHidden($this->form->get('lat'));?>
	<?= $this->formHidden($this->form->get('lng'));?>
	   <fieldset class="sbm-page1">
			<div id="ligne1">
	       <?= $this->formRow($this->form->get('chez'));?>
	       <?= $this->formRow($this->form->get('adresseL1'));?>
	       <?= $this->formRow($this->form->get('adresseL2'));?>
	       </div>
			<div id="ligne2" class="top-6px">
	       <?= $this->formRow($this->form->get('codePostal'));?>
	       <?= $this->formRow($this->form->get('communeId'));?>
	       <?= $this->formSubmit($this->form->get('submit'));?>
	       <?= $this->formSubmit($this->form->get('remove'));?>
	       <?= $this->formSubmit($this->form->get('cancel'));?>
	       </div>
		</fieldset>
    <?= $this->form()->closeTag();?>
<?php

if ($this->form->getMessages()) {
    $msg = $this->form->getMessages();
    if (StdLib::array_keys_exists([
        'lat',
        'notBetween'
    ], $msg) || StdLib::array_keys_exists([
        'lng',
        'notBetween'
    ], $msg)) {
        ?>
            <p class="sbm-description important">La position indiquée
			n'est pas dans la zone géographique de l'organisateur.</p>
<?php
    }
}
?>
		<p class="sbm-description">
			Indiquez l'adresse de l'élève puis positionnez la sur la carte avant
			de cliquer sur le bouton <b>'Enregistrer'</b>. Utilisez le zoom pour
			plus de précision.
		</p>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
