<?php
/**
 * Page de suppression d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 21 mai 2022
 * @version 2022-2.6.6
 */
if ($this->rayer) {
    $titre = 'Supprimer ou rayer';
    $message = 'Pour supprimer l\'inscription tout en gardant sa trace dans l\'historique, cliquez sur le bouton "Rayer"';
} else {
    $titre = 'Supprimer ou inscrire';
    $message = 'Pour réinscrire l\'élève, cliquez sur le bouton "Inscrire"';
}
?>
<h1><?= $titre;?></h1>
<div id="suppr-wrapper">
	<p>Vous souhaitez modifier l'état d'inscription de :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->eleve['nom'] . ' ' . $this->eleve['prenom']; ?></li>
			<li>Scolarisé à <?= $this->eleve['etablissement'] . ' - ' . $this->eleve['lacommuneEtablissement']; ?></li>
	        <?php if ($this->affectations->count() > 0) : ?>
	        <li>Affecté sur :
				<ul>
	            <?php foreach ($this->affectations as $affectation) :?>
	               <li><?=$this->printAffectation($affectation);?></li>
	            <?php endforeach; ?>
	            </ul>
			</li>
	        <?php endif; ?>
        </ul>
	</div>
	<p>Pour supprimer définitivement la fiche de cet élève, cliquez sur le
		bouton "Supprimer".</p>
	<p><?=$message;?></p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>