<?php
/**
 * Page de modification d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 août 2016
 * @version 2016-2.1.10
 */
use SbmCommun\Model\DateLib;

function formatDate($date, $withTime = true)
{
    if ($withTime) {
        $d = DateLib::formatDateTimeFromMysql($date);
        if ($d == '01/01/1900 00:00:00') {
            return '';
        } else {
            return $d;
        }
    } else {
        $d = DateLib::formatDateFromMysql($date);
        if ($d == '01/01/1900') {
            return '';
        } else {
            return $d;
        }
    }
}

$structAffectations = array();
if (count($this->affectations)) {
    foreach ($this->affectations as $affectation) {
        $structAffectations[$affectation['trajet']][$affectation['jours']][$affectation['sens']][$affectation['correspondance']] = array(
            'service1Id' => $affectation['service1Id'],
            'station1Id' => $affectation['station1Id'],
            'station1' => $affectation['station1'],
            'service2Id' => $affectation['service2Id'],
            'station2Id' => $affectation['station2Id'],
            'station2' => $affectation['station2']
        );
    }
    unset($affectation);
}
$disableAccordR1 = isset($structAffectations[1]) ? 'true' : 'false';
$disableAccordR2 = isset($structAffectations[2]) ? 'true' : 'false';
// urls utilisées
$url_ici = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-edit',
    'page' => $this->page
));
$url_map = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-localisation',
    'page' => $this->page
));

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headLink()->prependStylesheet($this->basepath('/js/jquery-ui-1.11.4.custom/jquery-ui.min.css'));
$this->headScript()->appendFile($this->basePath('/js/jquery.min.js'));
$this->headScript()->appendFile($this->basePath('/js/jquery-ui-1.11.4.custom/jquery-ui.min.js'));
$this->headScript()->appendFile($this->basePath('/js/gestion-eleve.js'));
$this->headScript()->captureStart();
?>
const ELEVE_ID = <?php echo $this->eleveId;?>;
const IDENTITE = "<?php echo urlencode($this->identite)?>";
const URL_ICI = "<?php echo $url_ici;?>";
$(document).ready(function($) {
$("#duplicatamoins").click(function(){
    $.ajax({
        url:'/sbmajaxeleve/decrementeduplicata/eleveId:<?php echo $this->eleveId;?>',
	    dataType: 'json',
        success:function(data){
            var myid="#nbduplicata";
            var duplicata=data.duplicata;
            $(myid).empty();
			$(myid).append(duplicata.toString());
        },
        error:function(xhr,ajaxOptions,thrownError){
            alert(xhr.status+' '+thrownError);
        }
    });
});
$("#eleve-anneeComplete").click(function(){
    js_edit.montreDebutFin($(this).is(":checked"));
});
$("#eleve-derogation").click(function(){
    js_edit.montreMotifDerogation($(this).is(":checked"));
});
$("#eleve-ga").click(function(){
    js_edit.montreOngletGa($(this).is(":checked"));
});
$("#fiche-inner input[name=demandeR1]").click(function(){
    js_edit.montreDemande('r1');
});
$("#fiche-inner input[name=demandeR2]").click(function(){
    js_edit.montreDemande('r2');
});
$("#eleve-accordR1").click(function(){
    var action = ($(this).is(':checked'))?'check':'uncheck';
    var subvention = $("#eleve-subventionR1").is(':checked');
    $.ajax({
        url:'/sbmajaxeleve/'+action+'accordR1/eleveId:<?php echo $this->eleveId;?>',
        success:function(data){
            js_edit.montreMotifRefus(action=='check',subvention,'r1');
            js_edit.montreBlockAffectation(action=='check','r1');
        },
        error:function(xhr,ajaxOptions,thrownError){
            alert(xhr.status+' '+thrownError);
        }
    });
});
$("#eleve-subventionR1").click(function(){
    var accord = $("#eleve-accordR1").is(':checked');
    var subvention = $(this).is(':checked');
    js_edit.montreMotifRefus(accord,subvention,'r1');
});
$("#eleve-accordR2").click(function(){
    var action = ($(this).is(':checked'))?'check':'uncheck';
    var subvention = $("#eleve-subventionR2").is(':checked');
    $.ajax({
        url:'/sbmajaxeleve/'+action+'accordR2/eleveId:<?php echo $this->eleveId;?>',
        success:function(data){
            js_edit.montreMotifRefus(action=='check',subvention,'r2');
            js_edit.montreBlockAffectation(action=='check','r2');
        },
        error:function(xhr,ajaxOptions,thrownError){
            alert(xhr.status+' '+thrownError);
        }
    });
});
$("#eleve-subventionR2").click(function(){
    var accord = $("#eleve-accordR2").is(':checked');
    var subvention = $(this).is(':checked');
    js_edit.montreMotifRefus(accord,subvention,'r2');
});
$("input[type='text'][name^='distanceR']").dblclick(function(){
    $(this).css("cursor", "wait");
    var myid = '#'+$(this).attr('id');
    var name = $(this).attr('name');
    var n = 1;
    if (name.indexOf('1') == -1) {
        n = 2;
    }
    var id = '#eleve-responsable'+n+'Id';
    var responsableid = $(id).val();
    var etablissementid = $("#eleve-etablissementId").val();
    var args = 'etablissementId:'+etablissementid+'/responsableId:'+responsableid;
    $.ajax({
			url : '/sbmajaxeleve/donnedistance/'+args,
			type: 'GET',
			dataType: 'json',
			success : function(data){
			    $(myid).val(data.distance);
			    $(myid).css('cursor', 'auto');
            },
			error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
					$(myid).css('cursor','auto');
			}
	});
});
$("#eleve-responsable1Id").change(function(){
    var responsableid = $(this).val();
    $.ajax({
			url : '/sbmajaxeleve/getresponsable/responsableId:'+responsableid,
			success : function(data){js_edit.montreResponsable('r1',data);},
			error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
			}
	});
});
$("#eleve-responsable2Id").change(function(){
    var responsableid = $(this).val();
    $.ajax({
			url : '/sbmajaxeleve/getresponsable/responsableId:'+responsableid,
			success : function(data){js_edit.montreResponsable('r2',data);},
			error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
			}
	});
});
$("#tabs").on('click', "i[data-button=btnaffectation]", function(){
    var trajet = $(this).attr('data-trajet');
    var respid ='#eleve-responsable'+trajet+'Id';
    var href = '/sbmajaxeleve/formaffectation/eleveId:<?php echo $this->eleveId;?>/trajet:'+trajet+$(this).attr('data-href')+'/responsableId:';
    href = href.concat($(respid).val());
    $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:400,
            width:600,
            resizable: false,
            title:$(this).attr('title')//,
            //position:'center'
        });
        $("#winpopup").load(href);
        $("#winpopup").dialog("open");
         
        return false;
});
$("#eleve-btnpaiement").click(function(){
    var href = '/sbmajaxeleve/formpaiement/eleveId:<?php echo $this->eleveId;?>';
    $("#winpopup").dialog({
            draggable:true,
            modal:true,
            autoOpen:false,
            height:400,
            width:600,
            resizable:false,
            title:'Destinataire de la facture'    
    });
    $("#winpopup").load(href);
    $("#winpopup").dialog("open");
    
    return false;
});
});
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
$("#tabs").tabs();
js_edit.montreDebutFin($("#eleve-anneeComplete").is(":checked"));
js_edit.montreMotifDerogation($("#eleve-derogation").is(":checked"));
js_edit.montreOngletGa($("#eleve-ga").is(":checked"));
js_edit.montreMotifRefus($("#eleve-accordR1").is(":checked"),$("#eleve-subventionR1").is(":checked"),'r1');
js_edit.montreMotifRefus($("#eleve-accordR2").is(":checked"),$("#eleve-subventionR2").is(":checked"),'r2');
js_edit.montreBlockAffectation($("#eleve-accordR1").is(":checked"),'r1');
js_edit.montreBlockAffectation($("#eleve-accordR2").is(":checked"),'r2');
js_edit.initAccord(<?php echo $disableAccordR1;?>, <?php echo $disableAccordR2;?>);
$.ajax({
		url:'/sbmajaxeleve/getresponsable/responsableId:'+$("#eleve-responsable1Id").val(),
		success:function(data){js_edit.montreResponsable('r1',data);},
		error:function(xhr, ajaxOptions, thrownError) {
			alert(xhr.status + " " + thrownError);
		}
});
if ($("#eleve-responsable2Id").val()) {
    $.ajax({
		url:'/sbmajaxeleve/getresponsable/responsableId:'+$("#eleve-responsable2Id").val(),
		success:function(data){js_edit.montreResponsable('r2',data);},
		error:function(xhr, ajaxOptions, thrownError) {
			alert(xhr.status + " " + thrownError);
		}
    });
    js_edit.montreDemande('r1');
    js_edit.montreDemande('r2');
}
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
// ============= fin du Javascript et JQuery =================================

$hiddens = array(
    'eleveId' => $this->eleveId,
    'eleve' => $this->identite,
    'origine' => $url_ici
);
$actions = array(
    'cancel' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_ici, // traitement de cancel pour un redirectToOrigin()->back() proprement
        'title' => 'Retour'
    ),
    'localiser' => array(
        'class' => 'fam-map-magnify',
        'formaction' => $url_map,
        'title' => 'localiser cet élève sur la carte',
        'onclick' => sprintf($js, "'localiser'")
    )
);
?>
<div id="winpopup"></div>
<h1>Modification d'un élève</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">	    
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('eleveId'));
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset class="sbm-page1">
			<div id="commun" class="clearfix">
				<div id="commun-col1" class="float-left">
					<div id="wrapper-nom" class="row-inner edit"><?php echo $this->formRow($this->form->get('nom'));?></div>
					<div id="wrapper-prenom" class="row-inner edit"><?php echo $this->formRow($this->form->get('prenom'));?></div>
					<div id="wrapper-dateN" class="row-inner edit"><?php echo $this->formRow($this->form->get('dateN'));?></div>
					<div id="wrapper-joursTransport" class="row-inner edit"><?php echo $this->formRow($this->form->get('joursTransport'));?></div>
				</div>
				<div id="commun-col2" class="float-left left-10px">
					<div id="wrapper-etablissementId" class="row-inner edit"><?php echo $this->formRow($this->form->get('etablissementId'));?></div>
					<div id="wrapper-classeId" class="row-inner edit"><?php echo $this->formRow($this->form->get('classeId'));?></div>
					<div id="commun-col2-periode" class="clearfix">
						<div id="wrapper-anneeComplete" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('anneeComplete'));?></div>
						<div id="wrapper-dateDebut" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('dateDebut'));?></div>
						<div id="wrapper-dateFin" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('dateFin'));?></div>
					</div>
					<div id="commun-col2-derogation" class="clearfix">
						<div id="wrapper-derogation" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('derogation'));?></div>
						<div id="wrapper-motifDerogation"
							class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('motifDerogation'));?></div>
					</div>
				</div>
				<div id="commun-col3" class="float-left left-10px">
					<div id="wrapper-numero">
						<div class="label">N° carte</div>
						<div class="input"><?php echo $this->data['numero'];?></div>
					</div>
					<div id="wrapper-inscrit">
						<div class="label">Etat</div>
						<div class="input"><?php echo $this->data['etat'] == 'Rayé' ? '<span style="color: red;">Rayé</span>' : $this->data['etat'];?></div>
					</div>
					<div id="wrapper-paiement">
						<div class="label"><?php echo $this->formRow($this->form->get('btnpaiement'));?></div>
						<div class="input" id="inner-paiement"><?php echo $this->data['paiement'];?></div>
					</div>
					<div id="wrapper-district"><?php echo $this->formRow($this->form->get('district'));?></div>
					<div id="wrapper-fa"><?php echo $this->formRow($this->form->get('fa'));?></div>
					<div id="wrapper-ga"><?php echo $this->formRow($this->form->get('ga'));?></div>
				</div>
			</div>
			<div id="tabs" class="sbm-tabs-wrapper">
				<ul>
					<li><a href="#tabs-1">Responsable</a></li>
					<li><a href="#tabs-2">Garde alternée</a></li>
					<li><a href="#tabs-3">Historique</a>
				
				</ul>
				<div id="tabs-1" class="sbm-tabs-container"><?php // Responsable 1?>
				    <div id="tabs-1-r1" class="clearfix">
						<div class="float-left">
							<div id="wrapper-responsable1Id" class="row-inner edit"><?php echo $this->formRow($this->form->get('responsable1Id'));?></div>
							<div id="wrapper-responsable1" class="wrapper-responsable">
								<div id="r1-ligne1"></div>
								<div id="r1-ligne2"></div>
								<div id="r1-ligne3"></div>
								<div id="r1-ligne4"></div>
								<div id="r1-ligne5"></div>
							</div>
							<div class="clearfix">
								<div id="wrapper-distanceR1" class="float-left top-18px"><?php echo $this->formRow($this->form->get('distanceR1'));?></div>
								<div id="wrapper-demandeR1" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('demandeR1'));?></div>
							</div>
							<div id="block-demander1">
								<div class="clearfix">
									<div class="float-left">
										<div id="wrapper-accordR1"><?php echo $this->formRow($this->form->get('accordR1'));?></div>
										<div id="wrapper-subventionr1"><?php echo $this->formRow($this->form->get('subventionR1'));?></div>
									</div>
									<div id="wrapper-motifRefusr1" class="float-left"><?php echo $this->formRow($this->form->get('motifRefusR1'));?></div>
								</div>

							</div>
						</div>
						<div class="float-left left-10px">
							<div id="block-affectationsr1" class="block-affectations">
								<h3>
									Affectations&nbsp;&nbsp;&nbsp;&nbsp;<i class="fam-car-add"
										title="Ajouter une affectation pour <?php echo $this->identite;?>"
										data-button="btnaffectation" data-trajet="1"
										data-href="/op:add"></i>
								</h3>
								<?php
								if (isset($structAffectations[1])) {
								    echo $this->affectations(1, $structAffectations[1]);
								}
								?>
                            </div>
						</div>
					</div>
				</div>
				<div id="tabs-2" class="sbm-tabs-container">
					<div id="tabs-2-r2" class="clearfix">
						<div class="float-left">
							<div id="wrapper-responsable2Id" class="row-inner edit"><?php echo $this->formRow($this->form->get('responsable2Id'));?></div>
							<div id="wrapper-responsable2" class="wrapper-responsable">
								<div id="r2-ligne1"></div>
								<div id="r2-ligne2"></div>
								<div id="r2-ligne3"></div>
								<div id="r2-ligne4"></div>
								<div id="r2-ligne5"></div>
							</div>
							<div class="clearfix">
								<div id="wrapper-distanceR2" class="float-left top-18px"><?php echo $this->formRow($this->form->get('distanceR2'));?></div>
								<div id="wrapper-demandeR2" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('demandeR2'));?></div>
							</div>
							<div id="block-demander2">
								<div class="clearfix">
									<div class="float-left">
										<div id="wrapper-accordR2"><?php echo $this->formRow($this->form->get('accordR2'));?></div>
										<div id="wrapper-subventionr2"><?php echo $this->formRow($this->form->get('subventionR2'));?></div>
									</div>
									<div id="wrapper-motifRefusr2" class="float-left"><?php echo $this->formRow($this->form->get('motifRefusR2'));?></div>
								</div>
							</div>
						</div>
						<div class="float-left-10px">
							<div id="block-affectationsr2" class="block-affectations">
								<h3>
									Affectations&nbsp;&nbsp;&nbsp;&nbsp;<i class="fam-car-add"
										title="Ajouter une affectation pour <?php echo $this->identite;?>"
										data-button="btnaffectation" data-trajet="2"
										data-href="/op:add"></i>
								</h3>
								<?php
								if (isset($structAffectations[2])) {
								    echo $this->affectations(2, $structAffectations[2]);
								}
								?>
                            </div>
						</div>
					</div>
				</div>
				<div id="tabs-3" class="sbm-tabs-container">
					<div class="clearfix">
						<div id="tabs-3-col1" class="float-left">
							<h3>Identité de l'élève</h3>
							<div id="#eleve-dateCreation">
								<div class="eleve-tabs-3-col-1-label">Date de création</div><?php echo formatDate($this->historique['eleve']['dateCreation']);?></div>
							<div id="#eleve-dateModification">
								<div class="eleve-tabs-3-col-1-label">Date de modification</div><?php echo formatDate($this->historique['eleve']['dateModification']);?></div>
						</div>
						<div id="tabs-3-col2" class="float-left left-10px">
							<h3>Responsable 1</h3>
							<div id="#responsable1-dateCreation">
								<div class="eleve-tabs-3-col-2-label">Date de création</div><?php echo formatDate($this->historique['responsable1']['dateCreation']);?></div>
							<div id="#responsable1-dateModification">
								<div class="eleve-tabs-3-col-2-label">Date de modification</div><?php echo formatDate($this->historique['responsable1']['dateModification']);?></div>
							<div id="#responsable1-dateDemenagement">
								<div class="eleve-tabs-3-col-2-label">Date de déménagement</div><?php echo formatDate($this->historique['responsable1']['dateDemenagement'], false);?></div>
						</div>
				        <?php if (array_key_exists('responsable2', $this->historique)):?>
				        <div id="tabs-3-col3" class="float-left left-10px">
							<h3>Responsable 2</h3>
							<div id="#responsable2-dateCreation">
								<div class="eleve-tabs-3-col-3-label">Date de création</div><?php echo formatDate($this->historique['responsable2']['dateCreation']);?></div>
							<div id="#responsable2-dateModification">
								<div class="eleve-tabs-3-col-3-label">Date de modification</div><?php echo formatDate($this->historique['responsable2']['dateModification']);?></div>
							<div id="#responsable2-dateDemenagement">
								<div class="eleve-tabs-3-col-3-label">Date de déménagement</div><?php echo formatDate($this->historique['responsable2']['dateDemenagement'], false);?></div>
						</div>
				        <?php endif;?>
				    </div>
					<div class="clearfix">
						<div id="tabs-3-col1" class="float-left">
							<h3>Inscription cette année scolaire</h3>
							<div id="#scolarite-modeInscription">
								<div class="eleve-tabs-3-col-1-label">Mode d'inscription</div><?php echo $this->historique['scolarite']['internet'] ? 'par internet' : 'par formulaire papier';?></div>
							<div id="#scolarite-dateInscription">
								<div class="eleve-tabs-3-col-1-label">Date d'inscription</div><?php echo formatDate($this->historique['scolarite']['dateInscription']);?></div>
							<div id="#scolarite-dateModification">
								<div class="eleve-tabs-3-col-1-label">Date de modification</div><?php echo formatDate($this->historique['scolarite']['dateModification']);?></div>
						</div>
						<div id="tabs-3-col2" class="float-left left-10px">
							<h3>Eléments facturés</h3>
							<div id="#scolarite-tarif">
								<div class="eleve-tabs-3-col-2-label">Droits d'inscription</div><?php echo $this->historique['scolarite']['inscription'];?></div>
							<div id="#scolarite-duplicata">
								<div class="eleve-tabs-3-col-2-label">Nombre de duplicatas</div>
								<span id="nbduplicata" class="right-10px"><?php echo $this->historique['scolarite']['duplicata'];?></span>
								<input name="duplicata-moins" type="button" value="-"
									id="duplicatamoins">
							</div>
						</div>
					</div>
				</div>

			</div>
			<div id="wrapper-commentaire" class="row-inner edit top-6px"><?php echo $this->formRow($this->form->get('commentaire'));?></div>
		</fieldset>
		<div id="eleve-edit-buttons" class="row-inner edit left-95px">
            <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'));?>
        </div>
<?php echo $this->form()->closeTag();?>
	</div><?php // fiche_inner ?>
    <div id="fiche-footer"></div>
</div>
<?php
// fermeture du div fiche_wrapper

// gestion des messages d'erreur à améliorer
/*
 * if (count($this->form->getMessages())) {
 * echo '<p><u>DEBUG</u></p>';
 * var_dump($this->form->getMessages());
 * }
 */
?>