<?php
/**
 * Page de suppression d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 oct. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Suppression d'une inscription</h1>
<div id="suppr-wrapper">
	<p>Vous souhaitez supprimer l'inscription de :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->eleve['nom'] . ' ' . $this->eleve['prenom']; ?></li>
			<li>Scolarisé à <?= $this->eleve['etablissement'] . ' - ' . $this->eleve['communeEtablissement']; ?></li>
	        <?php if ($this->affectations->count() > 0) : ?>
	        <li>Affecté sur :
				<ul>
	            <?php foreach ($this->affectations as $affectation) :?>
	               <li><?= $affectation['service1Id'] . ' (' . $affectation['transporteur1'] . ')'; ?></li>
	            <?php endforeach; ?>
	            </ul>
			</li>
	        <?php endif; ?>
        </ul>
	</div>
	<p>Pour supprimer définitivement la fiche de cet élève, cliquez sur le
		bouton "Supprimer".</p>
	<p>Pour supprimer l'inscription tout en gardant sa trace dans
		l'historique, cliquez sur le bouton "Rayer"</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>