<?php
/**
 * Création d'un élève (phase 31)
 *
 * La création d'un élève se fait en plusieurs phases :
 * (Form1) : demande du nom, prénom, date de naissance, responsable1, garde_alternée, responsable2 (facultatif)
 * - recherche dans la base s'il existe des élèves ayant ces caractéristiques
 * - si oui, affichage de la liste trouvée (Liste1) avec possibilité de choisir un élève (21) ou de créer un nouvel élève (22)
 * - si non, création d'un nouvel élève (22)
 * (21) : recherche dans la table scolarites en année courante si la fiche existe
 * - si oui, passage en mode modification FIN
 * - si non, création de la scolarite (31)
 * (22) : enregistre le formulaire (Form1) et récupère le eleveId puis création de la scolarité (31)
 * (31) : formulaire (Form2) pour saisir la scolarité (sans les éléments de décision) : etablissement, classe, joursTransport, demandeR1, demandeR2, commentaire
 * - enregistre la scolarité
 * - passe en mode modification FIN
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-ajout31.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 jan. 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/eleve', 'eleve-ajout.css');
$this->jQuery();
$this->themeJS('gestion-eleve', 'ajout31.js');
$this->themeJS('commun', 'checkallbox.js');
$this->inlineScript()->captureStart();
?>
multicheckbox_actions.init("wrapper-joursTransport");
js_ajout31.init();
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
// ======================= fin js =================================================
$telephonesR1 = array_filter(
    [
        $this->telephone($this->data['telephoneFR1']),
        $this->telephone($this->data['telephonePR1']),
        $this->telephone($this->data['telephoneTR1'])
    ]);
$telephonesR2 = array_filter(
    [
        $this->telephone($this->data['telephoneFR2']),
        $this->telephone($this->data['telephonePR2']),
        $this->telephone($this->data['telephoneTR2'])
    ]);
$url_map = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-localisation',
        'page' => $this->page
    ]);
$url_ici = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-ajout31',
        'page' => $this->page
    ]);
$hiddens = [
    'eleveId' => $this->data['eleveId'],
    'eleveName' => $this->info,
    'origine' => $url_ici
];
$actions = [
    'localiser' => [
        'class' => 'fam-map-magnify',
        'formaction' => $url_map,
        'title' => 'localiser cet élève sur la carte',
        'onclick' => sprintf($js, "'localiser'")
    ]
];
?>
<h1>Création d'un nouvel élève</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="edit">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('eleveId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset class="sbm-page1">
			<div id="commun" class="clearfix">
				<div id="commun-col1" class="float-left">
					<div>
						<div class="label">Nom de l'élève</div>
							<?= $this->data['nom'];?></div>
					<div>
						<div class="label">Prénom de l'élève</div>
							<?= $this->data['prenom'];?></div>
					<div id="ligne-dateN-sexe">
						<div class="table-cell">
							<div class="label">Date de naissance</div>
							<?= DateLib::formatDateFromMysql($this->data['dateN']);?></div>
						<div class="table-cell">
							<div class="label2">Sexe</div>
							<?= $this->data['sexe'] == 1 ? 'masculin' : 'féminin';?></div>
					</div>
					<div id="wrapper-joursTransport" class="row-inner">
						<?= $this->formRow($this->form->get('joursTransport'));?></div>
				</div>
				<div id="commun-col2" class="float-left left-10px">
					<div id="wrapper-etablissementId" class="row-inner">
					<?= $this->formRow($this->form->get('etablissementId'));?>
					<br> <span class='annee-precedente etablissement-precedent'>
						<?= $this->scolarite_precedente['etablissement']; ?></span>
					</div>
					<div id="ligne-classe-regime">
						<div id="wrapper-classeId" class="row-inner table-cell">
							<?= $this->formRow($this->form->get('classeId'));?>
							<span class='annee-precedente classe-precedente'>
							<?= $this->scolarite_precedente['classe']; ?></span>
						</div>
						<div id="wrapper-regime" class="row-inner table-cell">
							<?=$this->formRow($this->form->get('regimeId'));?></div>
					</div>
					<div id="commun-col2-periode" class="clearfix">
						<div id="wrapper-anneeComplete" class="row-inner edit float-left">
							<?= $this->formRow($this->form->get('anneeComplete'));?></div>
						<div id="wrapper-dateDebut" class="row-inner edit float-left">
							<?= $this->formRow($this->form->get('dateDebut'));?></div>
						<div id="wrapper-dateFin" class="row-inner edit float-left">
							<?= $this->formRow($this->form->get('dateFin'));?></div>
					</div>
					<div id="commun-col2-derogation" class="clearfix">
						<div id="wrapper-derogation" class="row-inner float-left">
							<?= $this->formRow($this->form->get('derogation'));?></div>
						<div id="wrapper-motifDerogation" class="row-inner float-left">
								<?= $this->formRow($this->form->get('motifDerogation'));?></div>
					</div>
				</div>
				<div id="commun-col3" class="float-left left-10px">
					<div id="wrapper-numero">
						<div class="label">N° carte</div>
						<div class="input"><?= $this->data['numero'];?></div>
					</div>
					<div id="wrapper-inscrit">
						<div class="label">Etat</div>
						<div class="input">en cours...</div>
					</div>
					<div id="wrapper-fa">
						<?= $this->formRow($this->form->get('fa'));?></div>
					<div id="wrapper-ga">
						<?= empty($data['responsable2Id']) ? '' : 'Garde alternée';?></div>
				</div>
			</div>
			<div id="responsables" class="clearfix">
				<div id="responsables-col1" class="float-left cols">
				    <?= $this->formHidden($this->form->get('responsable1Id'));?>
					<div class="gras">Responsable<?= empty($data['responsable2Id']) ? '' : ' 1';?></div>
					<div id="wrapper-responsable1" class="wrapper-responsable">
						<div id="r1-ligne1">
							<?= $this->data['titreR1'];?>
							<?= $this->data['responsable1NomPrenom'];?></div>
						<div id="r1-ligne2">
						<?php
    echo implode(' ',
        array_filter(
            [
                $this->data['adresseL1R1'],
                $this->data['adresseL2R1'],
                $this->data['adresseL3R1']
            ]));
    ?>
						</div>
						<div id="r1-ligne3">
							<?= $this->data['codePostalR1'];?>
							<?= $this->data['communeR1'];?></div>
						<div id="r1-ligne4">email: <?= $this->data['emailR1'];?></div>
						<div id="r1-ligne5">
							Tél. <?= implode(' - ', $telephonesR1);?></div>
					</div>
					<div class="clearfix">
						<div id="wrapper-distanceR1" class="row-inner float-left top-18px">
							<?= $this->formRow($this->form->get('distanceR1'));?></div>
						<div id="wrapper-demandeR1" class="row-inner float-left">
							<?= $this->formRow($this->form->get('demandeR1'));?></div>
					</div>
				</div>
				<?php if (!empty($data['responsable2Id'])) : ?>
				<div id="responsables-col2" class="float-left cols left-10px">
				    <?= $this->formHidden($this->form->get('responsable2Id'));?>
					<div class="gras">Responsable 2</div>
					<div id="wrapper-responsable2" class="wrapper-responsable">
						<div id="r2-ligne1">
							<?= $this->data['titreR2'];?>
							<?= $this->data['responsable2NomPrenom'];?></div>
						<div id="r2-ligne2">
						<?php
    echo implode(' ',
        array_filter(
            [
                $this->data['adresseL1R2'],
                $this->data['adresseL2R2'],
                $this->data['adresseL3R2']
            ]));
    ?>
						</div>
						<div id="r2-ligne3">
							<?= $this->data['codePostalR2'];?>
							<?= $this->data['communeR2'];?></div>
						<div id="r2-ligne4">email: <?= $this->data['emailR2'];?></div>
						<div id="r2-ligne5">Tél. <?= implode(' - ', $telephonesR2);?></div>
					</div>
					<div class="clearfix">
						<div id="wrapper-distanceR2" class="float-left top-18px">
							<?= $this->formRow($this->form->get('distanceR2'));?></div>
						<div id="wrapper-demandeR2" class="row-inner float-left">
							<?= $this->formRow($this->form->get('demandeR2'));?></div>
					</div>
				</div>
				<?php endif;?>
			</div>
			<div id="wrapper-commentaire" class="row-inner top-6px">
				<?= $this->formRow($this->form->get('commentaire'));?></div>
		</fieldset>
		<div id="wrapper-buttons" class="row-inner left-95px">
        	<?= $this->formSubmit($this->form->get('submit'));?>
        	<?= $this->formSubmit($this->form->get('cancel'));?>
    </div>
	<?= $this->form()->closeTag();?>
	</div><?php // fiche_inner ?>
    <div id="fiche-footer">
    <?php // var_dump($this->form->getMessages());?>
    </div>
</div>