<?php
/**
 * Vue de l'action index du controller EleveController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/eleve/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_eleve_eleves = $this->url('sbmgestion/eleve', 
    [
        'action' => 'eleve-liste',
        'page' => $this->page
    ]);
$url_eleve_responsables = $this->url('sbmgestion/eleve', 
    [
        'action' => 'responsable-liste',
        'page' => $this->page
    ]);
$url_gestion = $this->url('sbmgestion');
?>
<h1>Gestion des élèves et des responsables</h1>
<div id="menugeneral-wrapper">
	<div id="menugeneral-header" class="clearfix">
		<div class="menu float-left">
		<?php
echo $this->listeZoneActions([], 
    [
        'retour' => [
            'class' => 'fam-door-out',
            'formaction' => $url_gestion,
            'title' => 'Retour'
        ]
    ]);
?>
        </div>
		<div class="flashMessenger float-right">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
        </div>
	</div>
	<div id="menugeneral-inner">
		<ul>
			<li><a href="<?php echo $url_eleve_eleves; ?>"><i
					class="fam-bullet-go"></i>Gestion des élèves</a></li>
			<li><a href="<?php echo $url_eleve_responsables; ?>"><i
					class="fam-bullet-go"></i>Gestion des responsables</a></li>
		</ul>
	</div>
</div>