<?php
/**
 * Vue de l'action index du controller EleveController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/eleve/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2014
 * @version 2014-1
 */
$url_eleve_eleves = $this->url('sbmgestion/eleve', array('action' => 'eleve-liste', 'page' => $this->page));
$url_eleve_responsables = $this->url('sbmgestion/eleve', array('action' => 'responsable-liste', 'page' => $this->page));
$url_gestion = $this->url('sbmgestion');
?>
<h1>Gestion des élèves</h1>
<ul>
<li><a href="<?php echo $url_eleve_eleves; ?>">Gestion des élèves</a></li>
<li><a href="<?php echo $url_eleve_responsables; ?>">Gestion des responsables</a></li>
<li><a href="<?php echo $url_gestion; ?>">Retour au menu général</a></li>
</ul>