<?php
/**
 * Page de laocalisation d'un responsable dont les coordonnées sont données
 *
 * (Cette page est identique à SbmParent/view/sbm-parent/config/localisation.phtml)
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource responsable-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 jan. 2020
 * @version 2020-2.6.0
 */
// calcul du contenu de l'infobulle
$description = [];
$description[] = $domicile = '<b>' .
    implode(' ',
        [
            $this->responsable->titre,
            $this->responsable->nom,
            $this->responsable->prenom
        ]) . '</b>';
$adresse = array_filter(
    [
        $this->responsable->adresseL1,
        $this->responsable->adresseL2,
        $this->responsable->adresseL3
    ]);
foreach ($adresse as $ligne) {
    $description[] = $ligne;
}
$domicile .= ', ' . implode(', ', $adresse);
$cp_ville = implode(' ', [
    $this->responsable->codePostal,
    $this->responsable->lacommune
]);
$description[] = $cp_ville;
$domicile .= ', ' . $cp_ville;
$telephones = array_filter(
    [
        $this->telephone($this->responsable->telephoneF),
        $this->telephone($this->responsable->telephoneP),
        $this->telephone($this->responsable->telephoneT)
    ]);
if (! empty($telephones)) {
    $description[] = 'Tél.' . implode(' - ', $telephones);
}
$description[] = $this->responsable->email;
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'localisation.js');
$this->themeJS('commun', 'StyledMarker.js');
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?= $this->config['centre']['lng'];?>;
const INI_ZOOM = <?= $this->config['zoom'];?>;
initialiser("<?=$this->scheme;?>",'mon domicile', "<?= implode('<br/>', $description);?>", []);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position de votre domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header">
		<p>
			Cliquez sur le domicile de <b><?= $domicile;?></b> puis <b>Enregistrer
				la localisation</b>. Utilisez le zoom pour plus de précision.
		</p>
		<?= $this->form($this->form); ?>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
