<?php
/**
 * Page de consultation des inscrits ayant le même responsable
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 août 2016
 * @version 2016-2.2.0
 */
use SbmBase\Model\Session;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-liste',
    'page' => $this->page
]);
$url_rapports = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-group-pdf',
    'page' => $this->page
]);
$url_ajouter = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-ajout',
    'page' => $this->page
]);
$url_origine = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-group',
    'page' => $this->page
]);
$url_duplicata = $this->url('sbmgestion/gestioneleve', [
    'action' => 'duplicata-carte',
    'page' => $this->page
]);
$url_edit = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-edit',
    'page' => $this->page
]);
$url_raye = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-rayer',
    'page' => $this->page
]);
$url_mail = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-mail'
]);
$hiddens = [
    'origine' => $url_origine,
    'responsableId' => $this->responsableId
];
$email = $this->responsable->email;
if (! empty($email)) {
    $hiddens = array_merge($hiddens, [
        'group' => $url_origine,
        'responsable' => sprintf('%s %s %s', $this->responsable->titre, $this->responsable->nom, $this->responsable->prenom),
        'email' => $this->responsable->email
    ]);
}
$menuImpression = $this->menuRapports($this->url('sbmgestion/eleve', [
    'action' => 'responsable-group'
]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Ajouter'
    ]
];
// die(var_dump($this->responsable));
if (! empty($email)) {
    $actions['ecrire'] = [
        'class' => 'fam-email',
        'formaction' => $url_mail,
        'title' => 'Envoyer un email'
    ];
}
?>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
		<h1>Elèves sous la responsabilité d'une personne</h1>
		<ul>
			<li><?php echo $this->escapehtml($this->responsable->nom); ?> <?php echo $this->escapehtml($this->responsable->prenom); ?>
			habitant <?php echo $this->escapehtml($this->responsable->adresseL1); ?> à <?php echo $this->escapehtml($this->responsable->commune); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="liste-inner">
	<?php foreach ($this->data['eleves'] as $key => $liste) : ?>
		<?php if ($liste->count()) : ?>
			<?php
        
        switch ($key) :
            case 'resp1':
                ?>
			          <h3>Liste des élèves ayant cette personne comme responsable
			1</h3>
			    <?php
                break;
            case 'resp2':
                ?>
                      <h3>Liste des élèves ayant cette personne comme
			responsable 2</h3>
			    <?php
                break;
            case 'fact':
                ?>
                      <h3>Liste des élèves ayant cette personne comme
			responsable financier</h3>                        
			    <?php
                break;
        endswitch
        ;
        ?>
			    <p>Il y a <?php echo count($liste); ?> élève<?php echo count($liste) > 1 ? 's' : ''; ?>.</p>
		<table class="libelles">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Inscrit en</th>
					<th>Etablissement scolaire</th>
					<th>Classe</th>
					<th>Services</th>
					<th>Garde alternée</th>
					<th></th>
				</tr>
			    <?php foreach ($liste as $row) : ?>
			    <?php
            $pictogrammes = [];
            $ga = is_null($row['responsable2Id']);
            if ($row['millesime'] == Session::get('millesime')) {
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'Modifier'
                    ],
                    'rayer' => [
                        'class' => $row['inscrit'] ? 'fam-pencil-delete' : 'fam-pencil-add',
                        'formaction' => $url_raye,
                        'title' => $row['inscrit'] ? 'Rayer' : 'Activer'
                    ],
                    'duplicata' => [
                        'class' => 'fam-vcard-add',
                        'formaction' => $url_duplicata,
                        'title' => 'duplicata de la carte de transport'
                    ]
                ];
                $inscrit = $row['paiement'] == 1;
                $inscrit |= $row['fa'] == 1;
                $inscrit |= $row['gratuit'] > 0;
                $inscrit |= ($row['demandeR1'] == 2 && $row['accordR1'] == 0 && $row['subventionR1'] == 1);
                $inscrit |= ($row['demandeR2'] == 2 && $row['accordR2'] == 0 && $row['subventionR2'] == 1);
                $this->pictogrammes('init')->addPreinscrit($row['inscrit'] == 1 && ! $inscrit);
                $tr_css = 'noir';
            } else {
                $url_edit = $this->url('sbmgestion/eleve', [
                    'action' => 'eleve-inscrire',
                    'page' => $this->page
                ]);
                $buttons = [
                    'inscrire' => [
                        'class' => 'fam-basket-put',
                        'formaction' => $url_edit,
                        'title' => 'Inscrire'
                    ]
                ];
                $tr_css = 'gris';
            }
            
            if (! $row['inscrit']) {
                $tr_css .= ' barre';
            }
            $hiddens = [
                'origine' => $url_origine,
                'info' => $row['nom'] . ' ' . $row['prenom'],
                'responsableId' => $this->responsableId,
                'eleveId' => $row['eleveId']
            ];
            $services = [];
            foreach ($this->data['fnc_affectations']($row['eleveId']) as $affectation) {
                $services[$affectation['service1Id']] = $affectation['service1Id'];
                if (! empty($affectation['service2Id'])) {
                    $services[$affectation['service2Id']] = $affectation['service2Id'];
                }
            }
            ?>
			    <tr
					class="<?php echo $tr_css . ' ' . $this->cycle(["even", "odd"])->next();?>">
					<td><?php echo $this->pictogrammes();?></td>
					<td><?php echo $row['nom']; ?></td>
					<td><?php echo $row['prenom']; ?></td>
					<?php if (is_null($row['millesime'])) : ?>
					<td colspan="4">Non inscrit</td>
					<?php else : ?>
					<td><?php echo $row['millesime']?></td>
					<td><?php echo $row['etablissement'] . ' - ' . $row['communeEtablissement'];?></td>
					<td class="centre"><?php echo $row['classe'];?></td>
					<td><?php echo implode(' / ', $services);?></td>
					<td><?php echo $this->data['fnc_ga']($key == 'resp1' ? $row['responsable2Id'] : $row['responsable1Id']);?></td>
					<?php endif;?>
					<td><?php  echo $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
			    <?php endforeach; ?>
			</tbody>
		</table>
		<?php endif;?>
    <?php endforeach; ?>
    </div>
	<div id="liste-footer"></div>
</div>