<?php
/**
 * Page de suppression d'un eleve
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 jan. 2020
 * @version 2020-2.6.0
 */
$adresse = array_filter(
    [
        $this->data->adresseL1,
        $this->data->adresseL2,
        $this->data->adresseL3,
        $this->data->codePostal . ' ' . $this->data->commune
    ]);
foreach ($adresse as &$ligne) {
    $ligne = $this->escapehtml($ligne);
}
?>
<h1>Suppression d'un responsable</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du responsable :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->nom); ?></li>
			<li><?= $this->escapeHtml($this->data->prenom); ?></li>
			<li>Adresse :<br>&nbsp;&nbsp;&nbsp;&nbsp;
			    <?= implode('<br>&nbsp;&nbsp;&nbsp;&nbsp;', $adresse); ?></li>
		</ul>
		<?php if ($this->data_dependantes->count()) : ?>
		    <?php if ($this->data_dependantes->count() == 1) : ?>
            <p>Cette personne est responsable de l'élève suivant :</p>
            <?php else : ?>
            <p>Cette personne est responsable des élèves suivants :</p>
            <?php endif; ?>
        <ul>
            <?php foreach ($this->data_dependantes as $eleve) : ?>
            <li><?= $eleve->nom, ' ', $eleve->prenom; ?></li>
            <?php endforeach; ?>
        </ul>
            <?php if ($this->data_dependantes->count() == 1) : ?>
        <p>La suppression de cette personne supprimera aussi cet élève.</p>
            <?php else : ?>
        <p>La suppression de cette personne supprimera aussi ces élèves.</p>
            <?php endif; ?>
        <?php else : ?>
        <p>Cette personne n'est responsable d'aucun élève.</p>
        <?php endif; ?>
    </div>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($form);?>
    <?= $this->formCollection($form);?>
    <?= $this->form()->closeTag();?>
</div>