<?php
/**
 * Page de laocalisation d'un responsable dont les coordonnées sont données
 *
 * (Cette page est identique à SbmParent/view/sbm-parent/config/localisation.phtml)
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource responsable-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 avr. 2015
 * @version 2015-1
 */
// calcul du contenu de l'infobulle
$description = array();
$description[] = '<b>' . implode(' ', array($this->responsable->titre, $this->responsable->nom, $this->responsable->prenom)) . '</b>';
$description[] = $this->responsable->adresseL1;
$tmp = $this->responsable->adresseL2;
if (!empty($tmp)) {
    $description[] = $this->responsable->adresseL2;
}
$description[] = implode(' ', array($this->responsable->codePostal, $this->responsable->commune));
$telephone = array();
$tmp = $this->responsable->telephoneF;
if (!empty($tmp)) {
    $telephone[] = $this->responsable->telephoneF;
}
$tmp = $this->responsable->telephoneP
if (!empty($tmp)) {
    $telephone[] = $this->responsable->telephoneP;
}
$tmp = $this->responsable->telephoneT;
if (!empty($tmp)) {
    $telephone[] = $this->responsable->telephoneT;
}
$tel = implode(' ', $telephone);
if (!empty($tel)) {
    $description[] = 'Tél.' . $tel;
}
$description[] = $this->responsable->email;
// mise en place des JS de googleMaps
$this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->captureStart();?>
var marker;
function initialiser() {
    var latlng = new google.maps.LatLng(44.54, 2.264);
    // initialisation des paramètres de la carte
    var options = {
        center: latlng,
        zoom: 12,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var carte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // initialisation du marker
    var optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(document.getElementById('lat').value, document.getElementById('lng').value),
        title: 'mon domicile'
    }
    marker = new google.maps.Marker(optionsMarqueur);
    
    var contentMarker = '<?php echo implode('<br/>', $description);?>';
 
var infoWindow = new google.maps.InfoWindow({
    content  : contentMarker,
    position : latlng
});
google.maps.event.addListener(marker, 'click', function() {
    infoWindow.open(carte,marker);
});
    
    google.maps.event.addListener(carte, 'click', function(event) {
        var latlng = event.latLng;
    	document.getElementById('lat').value = latlng.lat();
    	document.getElementById('lng').value = latlng.lng();
    	if (marker) {
    	   marker.setPosition(latlng);
    	} else {
    	   var optionsMarker = {
    	       map: carte,
    	       position: new google.maps.LatLng(latlng.lat(), latlng.lng()),
    	       title: 'mon domicile'
    	   }
    	   marker = Marker(optionsMarker);
        }
    });
}

<?php 
$this->headScript()->captureEnd();
// lancement du script (sera affiché dans le layout à la fin de la page
$this->inlineScript()->captureStart(); ?>
initialiser();
<?php $this->inlineScript()->captureEnd(); ?>
<h1>Position de votre domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header">
		<p>
			Cliquez sur la carte à l'emplacement de l'adresse puis cliquez
			sur le bouton <b>'Enregistrer la localisation'</b>. Utilisez le zoom pour plus de précision.
		</p>
<?php
echo $this->form($this->form);
?>
</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
