<?php
/**
 * Liste des responsables
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 juil. 2014
 * @version 2014-1
 */
$this->paginator->setDefaultItemCountPerPage($this->nb_responsable_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$responsables = $this->paginator->getCurrentItems();
?>
<h1>Liste des responsables</h1>
<div class="liste-wrapper">
	<div class="zone-actions">
<?php
$url_ajouter = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-ajout',
    'page' => $this->page
));
$url_imprimer = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-pdf',
    'page' => $this->page
));
$url_retour = $this->url('sbmgestion/eleve');
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$buttons = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'onclick' => $js_retour,
        'title' => 'Retour'
    ),
    'rapport' => array(
        'class' => 'fam-report',
        'formaction' => $url_imprimer,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau responsable'
    )
);
echo $this->listeZoneActions(array(), $buttons);
?>	
	</div>
	<table class="liste-inner responsables">
		<tbody>
			<tr>
				<th>Code</th>
				<th>Titre</th>
				<th>Nom</th>
				<th>Prénom</th>
				<th>Adresse</th>
				<th>Adresse</th>
				<th>Code postal</th>
				<th>Commune</th>
				<th>Nb élèves</th>
				<th>Dém.</th>
				<th>Sélection</th>
			</tr>
        <?php foreach($responsables as $responsable): ?>
         <tr
				class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				<td class="responsableId"><?php echo $this->escapehtml($responsable->responsableId); ?></td>
				<td class="titre"><?php echo $ttr = $this->escapeHtml($responsable->titre); ?></td>
				<td class="nom"><?php echo $nm = $this->escapeHtml($responsable->nom); ?></td>
				<td class="prenom"><?php echo $prn = $this->escapeHtml($responsable->prenom); ?></td>
				<td class="adresseL1"><?php echo $this->escapehtml($responsable->adresseL1); ?></td>
				<td class="adresseL2"><?php echo $this->escapehtml($responsable->adresseL2); ?></td>
				<td class="centre codePostal"><?php echo $this->escapeHtml($responsable->codePostal); ?></td>
				<td class="commune"><?php echo $cmn =$this->escapehtml($responsable->commune); ?></td>
				<td class="centre nbEleves"><?php echo $responsable->nbEleves; ?></td>
				<td class="centre demenagement"><?php echo $responsable->demenagement ? 'D' : ''; ?></td>
				<td class="centre selection"><?php echo $responsable->selection ? 'X' : ''; ?></td>
				<td class="boutons">
             <?php
            $identite = $ttr . ' ' . $nm . ' ' . $prn . ' de ' . $cmn;
            $url_edit = $this->url('sbmgestion/eleve', array(
                'action' => 'responsable-edit',
                'page' => $this->page
            ));
            $url_delete = $this->url('sbmgestion/eleve', array(
                'action' => 'responsable-suppr',
                'page' => $this->page
            ));
            $url_group = $this->url('sbmgestion/eleve', array(
                'action' => 'responsable-group',
                'page' => $this->page
            ));
            $url_euro = $this->url('sbmgestion/finance', array(
                'action' => 'paiement-liste'
            ));
            $hiddens = array(
                'responsableId' => $responsable->responsableId,
                'responsable' => $identite,
                'url1_retour' => $this->url('sbmgestion/eleve', array(
                    'action' => 'responsable-liste',
                    'page' => $this->page
                ))
            );
            // ne pas utiliser de guillement dans la chaine $js
            $js = 'javascript:window.document.getElementById(\'op' . $responsable->responsableId . '\').value=%s;';
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier le responsable ' . $identite,
                    'onclick' => sprintf($js, "'modifier'")
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer le responsable ' . $identite,
                    'onclick' => sprintf($js, "'supprimer'")
                ),
                'enfants' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'groupe des enfants de ' . $identite,
                    'onclick' => sprintf($js, "'enfants'")
                ),
                'paiements' => array(
                    'class' => 'fam-money-euro',
                    'formaction' => $url_euro,
                    'title' => 'paiements de ' . $identite,
                    'onclick' => sprintf($js, "'paiements'")
                )
            );
            echo $this->listeLigneActions($responsable->responsableId, $hiddens, $buttons);
            ?>
				</td>
			</tr>         
        <?php endforeach;?>
    </tbody>
	</table>
	<div class="zone-pagination"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
<?php echo $this->form()->openTag($this->criteres_form);?>
<?php echo $this->formCollection($this->criteres_form, true);?>
<?php echo $this->form()->closeTag();?>	
</div>