<?php
/**
 * Page de laocalisation d'un responsable dont les coordonnées sont données
 *
 * (Cette page est identique à SbmParent/view/sbm-parent/config/localisation.phtml)
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource responsable-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 nov. 2016
 * @version 2016-2.2.2
 */
// calcul du contenu de l'infobulle
$description = array();
$description[] = $domicile = '<b>' . implode(' ', array(
    $this->responsable->titre,
    $this->responsable->nom,
    $this->responsable->prenom
)) . '</b>';
$description[] = $this->responsable->adresseL1;
$domicile .= ' ' . $this->responsable->adresseL1;
$tmp = $this->responsable->adresseL2;
if (! empty($tmp)) {
    $description[] = $this->responsable->adresseL2;
    $domicile .= ' ' . $this->responsable->adresseL2;
}
$cp_ville = implode(' ', array(
    $this->responsable->codePostal,
    $this->responsable->commune
));
$description[] = $cp_ville;
$domicile .= ' ' . $cp_ville;
$telephone = array();
$tmp = $this->responsable->telephoneF;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneF;
}
$tmp = $this->responsable->telephoneP;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneP;
}
$tmp = $this->responsable->telephoneT;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneT;
}
$tel = implode(' ', $telephone);
if (! empty($tel)) {
    $description[] = 'Tél.' . $tel;
}
$description[] = $this->responsable->email;
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->appendFile('/js/maps/localisation.js');
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?php echo $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?php echo $this->config['centre']['lng'];?>;
const INI_ZOOM = <?php echo $this->config['zoom'];?>;
initialiser('mon domicile', "<?php echo implode('<br/>', $description);?>", []);
<?php 
$this->inlineScript()->captureEnd(); 
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position de votre domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header">
		<p>
			Cliquez sur le domicile de <b><?php echo $domicile;?></b>
			puis <b>Enregistrer la localisation</b>.
			Utilisez le zoom pour plus de précision.
		</p>
<?php
echo $this->form($this->form);
?>
</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
