<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource responsable-loger.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-liste',
    'page' => $this->page
));
$hiddens = array(
    'op' => 'retour'
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);
?>
<h1>Créer un compte pour un responsable</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé de créer un compte pour <?php echo $this->info;?>.</p>
<?php if (is_null($this->form)) : ?>
<p><?php echo $this->msg; ?></p>
	<div><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
<?php else : ?>
<p>Confirmez-vous ?</p>
<?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
<?php endif; ?>
</div>