<?php
/**
 * Page de consultation des paiements de ce responsable
 *
 * (comme paiement-list)
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource responsable-paiements.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$retour = $this->url('sbmgestion/eleve', 
    [
        'action' => 'responsable-liste',
        'page' => $this->page
    ]);

?>
<h1>Paiements effectués par une personne</h1>
<div class="groupe-wrapper">
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapehtml($this->datagroup->nom); ?> <?php echo $this->escapehtml($this->datagroup->prenom); ?></li>
			<li>habitant <?php echo $this->escapehtml($this->datagroup->adressL1); ?> à <?php echo $this->escapehtml($this->datagroup->commune); ?></li>
		</ul>
	</div>
	<div class="liste-wrapper">
		<div class="liste-inner">
			<?php foreach ($this->data as $key => $liste) : ?>
			    <?php if ($liste->count()) : ?>
			        <?php
        
        switch ($key) :
            case 'régisseur':
                ?>
			            <h3>Liste des paiements en caisse du régisseur</h3>
			        <?php
                
                break;
            case 'comptable':
                ?>
                        <h3>Liste des paiements déposés au comptable
				public</h3>
			        <?php
                
                break;
        endswitch
        ;
        ?>
			        <ul>
			            <?php foreach ($liste as $row) : ?>
			                
			            <?php endforeach; ?>
			        </ul>
			    <?php endif;?>
			<?php endforeach; ?>
		</div>
	</div>
</div>
