<?php
/**
 * Liste des responsables
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 31 août 2017
 * @version 2017-2.3.7
 */
use SbmCartographie\Model\Point;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';
// modèle pour le jsCallback de selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxeleve/'+action+'selectionresponsable/responsableId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;


$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$responsables = $this->paginator->getCurrentItems();
$url_edit = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-edit',
    'page' => $this->page
));
$url_delete = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-suppr',
    'page' => $this->page
));
$url_group = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-group',
    'page' => $this->page
));
$url_euro = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-liste'
));
$url_map = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-localisation',
    'page' => $this->page
));
$url_loger = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-loger',
    'page' => $this->page
));
$url_ajouter = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-ajout',
    'page' => $this->page
));
$url_rapports = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-pdf',
    'page' => $this->page
));
$url_ici = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-liste',
    'page' => $this->page
));
$url_mail = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-mail'
));
$url_retour = $this->url('sbmgestion');
$hiddens = array();
$menuImpression = $this->menuRapports($this->url('sbmgestion/eleve', array(
    'action' => 'responsable-liste'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens']; // mise à jour si nécessaire par l'ajout de 'documentId'
                                       // ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'onclick' => $js_retour,
        'title' => 'Retour'
    ),
    'rapports' => $menuImpression['content'],
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau responsable'
    )
);
?>
<h1>Liste des responsables</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="responsables">
			<tbody>
				<tr>
					<th></th>
					<th>Titre</th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Code<br>postal
					</th>
					<th>Commune</th>
					<th>Enfants</th>
					<th>Inscrits</th>
					<th>Préinscrits</th>
					<th>Dém.</th>
					<th>Sélect.</th>
				</tr>
        <?php foreach($responsables as $responsable): ?>
        <?php
            $pt = new Point($responsable['x'], $responsable['y']);
            $ptOk = $this->projection->isValid($pt, 'parent');
            // construction du JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $responsable['responsableId']);
            $jsCallback .= sprintf("$modele\n", $responsable['responsableId'], $responsable['responsableId']);
            // nombre d'inscrits
            $nbInscrits = $responsable['nbPreinscrits'] + $responsable['nbGratuits'] + $responsable['nbFa'];
            ?>
         <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td>
					<?php if (!$ptOk) : ?>
					   <i class="fam-error"></i>
					<?php endif;?>
					</td>
					<td class="titre"><?php echo $ttr = $this->escapeHtml($responsable['titre']); ?></td>
					<td class="nom"><?php echo $nm = $this->escapeHtml($responsable['nom']); ?></td>
					<td class="prenom"><?php echo $prn = $this->escapeHtml($responsable['prenom']); ?></td>
					<td class="adresse"><?php echo $this->escapehtml($responsable['adresseL1']); ?>
					<?php if(!empty($responsable['adresseL2'])):?>
					   <br /><?php echo $this->escapehtml($responsable['adresseL2']); ?>
					<?php endif;?>
					</td>
					<td class="centre codePostal"><?php echo $this->escapeHtml($responsable['codePostal']); ?></td>
					<td class="commune"><?php echo $cmn =$this->escapehtml($responsable['commune']); ?></td>
					<td class="centre gris nbEleves"><?php echo $responsable['nbEnfants']; ?></td>
					<td class="centre nbInscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre nbPreinscrits"><?php echo $responsable['nbPreinscrits']; ?></td>
					<td class="centre demenagement"><?php echo $responsable['demenagement'] ? 'D' : ''; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $responsable['responsableId'], $responsable['selection']); ?></td>
					<td class="boutons">
             <?php
            $identite = $ttr . ' ' . $nm . ' ' . $prn . ' de ' . $cmn;
            $hiddens = array(
                'responsableId' => $responsable['responsableId'],
                'info' => $identite,
                'nbInscrits' => $responsable['nbInscrits'],
                'nbPreinscrits' => $responsable['nbPreinscrits'],
                'nbDuplicata' => $responsable['nbDuplicata'],
                'url1_retour' => $url_ici,
                'email' => $responsable['email'],
                'responsable' => $identite,
                'group' => $url_ici
            );
            // ne pas utiliser de guillement dans la chaine $js
            $js = 'window.document.getElementById(\'op' . $responsable['responsableId'] . '\').value=%s;';
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier la fiche de ' . $identite,
                    'onclick' => sprintf($js, "'modifier'")
                ),
                'localiser' => array(
                    'class' => $ptOk ? 'fam-map-magnify' : 'fam-map-add',
                    'formaction' => $url_map,
                    'title' => $ptOk ? 'localiser le domicile de ' . $identite . ' sur la carte' : 'le domicile de ' . $identite . ' n\'est pas localisé sur la carte',
                    'onclick' => sprintf($js, "'localiser'")
                ),
                'loger' => array(
                    'class' => 'fam-user-add',
                    'formaction' => $url_loger,
                    'title' => 'créer un compte pour ' . $identite,
                    'onclick' => sprintf($js, "'loger'")
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer le responsable ' . $identite,
                    'onclick' => sprintf($js, "'supprimer'")
                ),
                'enfants' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'enfants de ' . $identite,
                    'onclick' => sprintf($js, "'enfants'")
                ),
                'paiements' => array(
                    'class' => 'fam-money-euro',
                    'formaction' => $url_euro,
                    'title' => 'paiements de ' . $identite,
                    'onclick' => sprintf($js, "'paiements'")
                )
            );
            if (! empty($responsable['email'])) {
                $buttons['ecrire'] = array(
                    'class' => 'fam-email',
                    'formaction' => $url_mail,
                    'title' => 'Envoyer un email'
                );
            }
            echo $this->listeLigneActions($responsable['responsableId'], $hiddens, $buttons);
            ?>
				</td>
				</tr>         
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper responsables">
<?php echo $this->form()->openTag($this->criteres_form);?>
<?php echo $this->formCollection($this->criteres_form, true);?>
<?php echo $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();