<?php
/**
 * Page de consultation des inscrits ayant le même responsable
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 mars 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\Session;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-liste',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-group-pdf',
        'page' => $this->page
    ]);
$url_ajouter = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-ajout',
        'page' => $this->page
    ]);
$url_origine = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-group',
        'page' => $this->page
    ]);
$url_duplicata = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'duplicata-carte',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-edit',
        'page' => $this->page
    ]);

$url_reprendre = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-en-attente',
        'page' => $this->page
    ]);
$url_raye = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-rayer',
        'page' => $this->page
    ]);
$url_mail = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-mail'
]);
$url_add_photo = $this->url('sbmgestion/eleve',
    [
        'action' => 'envoiphoto',
        'page' => $this->page
    ]);
$url_majnotification = $this->url('sbmpaiement', [
    'action' => 'majnotification'
]);
$hiddens = [
    'origine' => $url_origine,
    'responsableId' => $this->responsableId
];
$email = $this->responsable->email;
if (! empty($email)) {
    $hiddens = array_merge($hiddens,
        [
            'group' => $url_origine,
            'responsable' => sprintf('%s %s %s', $this->responsable->titre,
                $this->responsable->nom, $this->responsable->prenom),
            'email' => $this->responsable->email
        ]);
}
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/eleve', [
        'action' => 'responsable-group'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Ajouter'
    ]
];
// die(var_dump($this->responsable));
if (! empty($email)) {
    $actions['ecrire'] = [
        'class' => 'fam-email',
        'formaction' => $url_mail,
        'title' => 'Envoyer un email'
    ];
}
$personne = sprintf('%s %s %s', $this->responsable->titre, $this->responsable->prenom,
    $this->responsable->nom);
?>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
		<h1>Elèves sous la responsabilité d'une personne</h1>
		<ul>
			<li>
				<?= $this->escapehtml($this->responsable->nom); ?>
				<?= $this->escapehtml($this->responsable->prenom); ?>
				habitant
				<?php
    echo $this->escapehtml(
        implode(', ',
            array_filter(
                [
                    $this->responsable->adresseL1,
                    $this->responsable->adresseL2,
                    $this->responsable->adresseL3
                ])));
    ?>
				à <?= $this->escapehtml($this->responsable->commune); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="liste-inner">
	<?php foreach ($this->data['eleves'] as $key => $liste) : ?>
		<?php if ($liste->count()) : ?>
			<?php

        switch ($key) :
            case 'resp1':
                ?>
			          <h3>Liste des élèves ayant <?=$personne;?> pour responsable
			1</h3>
			    <?php
                break;
            case 'resp2':
                ?>
                      <h3>Liste des élèves ayant <?=$personne;?> pour
			responsable 2</h3>
			    <?php
                break;
            case 'fact':
                ?>
                      <h3>Liste des élèves ayant <?=$personne;?> pour
			responsable financier</h3>
			    <?php
                break;
        endswitch
        ;
        ?>
			    <p>Il y a <?= $liste->count(); ?> élève<?= $liste->count() > 1 ? 's' : ''; ?>.</p>
		<table class="libelles">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th class="centre">Inscrit<br>en
					</th>
					<th>Etablissement scolaire</th>
					<th>Classe</th>
					<th>Tarif</th>
					<th>Services</th>
					<th>Garde alternée</th>
					<th class="centre">Réinscription<br>prévue
					</th>
					<th></th>
				</tr>
			    <?php foreach ($liste as $row) : ?>
			    <?php
            $pictogrammes = [];
            $ga = is_null($row['responsable2Id']);
            if (array_key_exists('mailchimp', $row)) {
                $nePasRelancer = $row['mailchimp'] == 0;
            } else {
                $nePasRelancer = false;
            }
            if ($row['millesime'] == Session::get('millesime')) {
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'Modifier'
                    ],
                    'rayer' => [
                        'class' => $row['inscrit'] ? 'fam-pencil-delete' : 'fam-pencil-add',
                        'formaction' => $url_raye,
                        'title' => $row['inscrit'] ? 'Rayer' : 'Activer'
                    ],
                    'majNotification' => [
                        'class' => 'fam-transmit-error',
                        'formaction' => $url_majnotification,
                        'title' => 'Vérifier les paiements en ligne'
                    ],
                    'addphoto' => [
                        'class' => 'fam-camera-add',
                        'formaction' => $url_add_photo,
                        'title' => 'Envoyer une photo'
                    ],
                    'duplicata' => [
                        'class' => 'fam-vcard-add',
                        'formaction' => $url_duplicata,
                        'title' => 'duplicata de la carte de transport'
                    ]
                ];
                if (! $row['sansphoto']) {
                    unset($buttons['addphoto']);
                }
                $inscrit = $row['paiement'] == 1;
                $inscrit |= $row['fa'] == 1;
                $inscrit |= $row['gratuit'] > 0;
                $inscrit |= ($row['demandeR1'] == 2 && $row['accordR1'] == 0 &&
                    $row['subventionR1'] == 1);
                $inscrit |= ($row['demandeR2'] == 2 && $row['accordR2'] == 0 &&
                    $row['subventionR2'] == 1);
                $this->pictogrammes('init')
                    ->addPreinscrit($row['inscrit'] == 1 && ! $inscrit)
                    ->addSansPhoto($row['sansphoto'])
                    ->addEnAttente($row['enAttente'])
                    ->addSansCarte($row['dateCarte'] < $this->dateDebut);
                if ($row['enAttente']) {
                    unset($buttons['majNotification'], $buttons['addphoto'],
                        $buttons['duplicata']);
                    $buttons['modifier'] = [
                        'class' => 'fam-pencil-add',
                        'formaction' => $url_reprendre,
                        'title' => 'Reprendre cet enfant mis en attente'
                    ];
                } elseif ($inscrit || $row['appelNotifieOk']) {
                    unset($buttons['majNotification']);
                }
                $tr_css = 'noir';
            } else {
                $this->pictogrammes('init');
                $url_edit = $this->url('sbmgestion/eleve',
                    [
                        'action' => 'eleve-inscrire',
                        'page' => $this->page
                    ]);
                $buttons = [
                    'inscrire' => [
                        'class' => 'fam-basket-put',
                        'formaction' => $url_edit,
                        'title' => 'Inscrire'
                    ]
                ];
                $tr_css = 'gris';
            }

            if (! $row['inscrit']) {
                $tr_css .= ' barre';
            }
            $hiddens = [
                'origine' => $url_origine,
                'info' => $row['nom'] . ' ' . $row['prenom'],
                'responsableId' => $this->responsableId,
                'eleveId' => $row['eleveId']
            ];
            $services = [];
            foreach ($this->data['fnc_affectations']($row['eleveId']) as $affectation) {
                $services[$affectation['service1Id']] = $affectation['service1Id'];
                if (! empty($affectation['service2Id'])) {
                    $services[$affectation['service2Id']] = $affectation['service2Id'];
                }
            }
            if ($row['enAttente']) {
                $reinscription = 'En attente';
            } elseif ($nePasRelancer) {
                $url_change_reinscription = $this->url('sbmgestion/eleve',
                    [
                        'action' => 'eleve-reinscription-oui',
                        'page' => $this->page
                    ]);
                $reinscription = '<i class="fam-cancel" title="Cet élève ne doit pas se réinscrire"></i>';
                $buttons['mailchimp'] = [
                    'class' => 'fam-car-add',
                    'formaction' => $url_change_reinscription,
                    'title' => 'Indiquer que cet élève devrait se réinscrire'
                ];
            } else {
                $url_change_reinscription = $this->url('sbmgestion/eleve',
                    [
                        'action' => 'eleve-reinscription-non',
                        'page' => $this->page
                    ]);
                $reinscription = '<i class="fam-tick" title="Cet élève devrait se réinscrire"></i>';
                $buttons['mailchimp'] = [
                    'class' => 'fam-car-delete',
                    'formaction' => $url_change_reinscription,
                    'title' => 'Indiquer que cet élève ne doit pas se réinscrire'
                ];
            }
            ?>
			    <tr
					class="petit <?= $tr_css . ' ' . $this->cycle(["even", "odd"])->next();?>">
					<td><?= $this->pictogrammes();?></td>
					<td><?= $row['nom']; ?></td>
					<td><?= $row['prenom']; ?></td>
				<?php if (is_null($row['millesime'])) : ?>
					<td colspan="5">Non inscrit</td>
				<?php else : ?>
					<td><?= $row['millesime']?></td>
					<td><?= $row['etablissement'];?> - <?= $row['communeEtablissement'];?></td>
					<td class="centre"><?= $row['classe'];?></td>
					<td><?= $row['grilleTarifR1'];?> <?= $this->reductionTarif($row['reductionR1']);?></td>
					<td><?= implode(' / ', $services);?></td>
					<td><?= $this->data['fnc_ga']($key == 'resp1' ? $row['responsable2Id'] : $row['responsable1Id']);?></td>
				<?php endif;?>
					<td class="centre"><?= $reinscription; ?></td>
					<td><?= $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
			    <?php endforeach; ?>
			</tbody>
		</table>
		<?php endif;?>
    <?php endforeach; ?>
    </div>
	<div id="liste-footer"></div>
</div>