<?php
/**
 * Page de consultation des inscrits ayant le même responsable
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource eleve-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 juillet 2014
 * @version 2014-1
 */
use DafapSession\Model\Session;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-liste',
    'page' => $this->page
));
$url_pdf = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-group-pdf',
    'page' => $this->page
));
$url_ajouter = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-ajout',
    'page' => $this->page
));
$url_origine = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-group',
    'page' => $this->page
));
$hiddens = array(
    'origine' => $url_origine,
    'responsableId' => $this->responsableId
);

// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $url_origine,//$url_pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Ajouter'
    )
);

?>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
		<h1>Elèves sous la responsabilité d'une personne</h1>
		<ul>
			<li><?php echo $this->escapehtml($this->responsable->nom); ?> <?php echo $this->escapehtml($this->responsable->prenom); ?>
			habitant <?php echo $this->escapehtml($this->responsable->adresseL1); ?> à <?php echo $this->escapehtml($this->responsable->commune); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="liste-inner">
	<?php foreach ($this->data as $key => $liste) : ?>
		<?php if ($liste->count()) : ?>
			<?php
        
        switch ($key) :
            case 'resp1':
                ?>
			          <h3>Liste des élèves ayant cette personne comme responsable
			1</h3>
			    <?php
                break;
            case 'resp2':
                ?>
                      <h3>Liste des élèves ayant cette personne comme
			responsable 2</h3>
			    <?php
                break;
            case 'fact':
                ?>
                      <h3>Liste des élèves ayant cette personne comme
			responsable financier</h3>                        
			    <?php
                break;
        endswitch
        ;
        ?>
			    <p>Il y a <?php echo count($liste); ?> élève<?php echo count($liste) > 1 ? 's' : ''; ?>.</p>
		<table class="libelles">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Inscrit en</th>
					<th>Etablissement scolaire</th>
					<th>Classe</th>
					<th>Services</th>
					<th></th>
				</tr>
			    <?php foreach ($liste as $row) : ?>
			    <?php
			$pictogrammes = array();
            if ($row['millesime'] == Session::get('millesime')) {
                $url_edit = $this->url('sbmgestion/eleve', array(
                    'action' => 'eleve-edit',
                    'page' => $this->page
                ));
                $url_raye = $this->url('sbmgestion/eleve', array(
                    'action' => 'eleve-rayer',
                    'page' => $this->page
                ));
                $buttons = array(
                    'modifier' => array(
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'Modifier'
                    ),
                    'rayer' => array(
                        'class' => $row['inscrit'] ? 'fam-pencil-delete' : 'fam-pencil-add',
                        'formaction' => $url_raye,
                        'title' => $row['inscrit'] ? 'Rayer' : 'Activer'
                    )
                );
                if ($row['paiement'] == 0) {
                    $pictogrammes[] = '<i class="fam-tag-orange" title="Préinscrit"></i>';
                }
                $tr_css = 'noir';
            } else {
                $url_edit = $this->url('sbmgestion/eleve', array(
                    'action' => 'eleve-inscrire',
                    'page' => $this->page
                ));
                $buttons = array(
                    'inscrire' => array(
                        'class' => 'fam-basket-put',
                        'formaction' => $url_edit,
                        'title' => 'Inscrire'
                    )
                );
                $tr_css = 'gris';
            }
            if (! $row['inscrit']) {
                $tr_css .= ' barre';
            }
            $hiddens = array(
                'origine' => $url_origine,
                'info' => $row['nom'] . ' ' . $row['prenom'],
                'responsableId' => $this->responsableId,
                'eleveId' => $row['eleveId']
            );
            $services = array();
            foreach ($this->query->getServices($row['eleveId'], $this->responsableId) as $affectation) {
                $services[] = $affectation['service1Id'];
            }
            ?>
			    <tr
					class="<?php echo $tr_css . ' ' . $this->cycle(array("even", "odd"))->next();?>">
					<td><?php echo implode(' ', $pictogrammes);?></td>
					<td><?php echo $row['nom']; ?></td>
					<td><?php echo $row['prenom']; ?></td>
					<?php if (is_null($row['millesime'])) : ?>
					<td colspan="4">Non inscrit</td>
					<?php else : ?>
					<td><?php echo $row['millesime']?></td>
					<td><?php echo $row['etablissement'] . ' - ' . $row['communeEtablissement'];?></td>
					<td><?php echo $row['classe'];?></td>
					<td><?php echo implode(' / ', $services);?></td>
					<?php endif;?>
					<td><?php  echo $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
			    <?php endforeach; ?>
			</tbody>
		</table>
		<?php endif;?>
    <?php endforeach; ?>
    </div>
</div>
<div id="liste-footer"></div>
</div>