<?php
/**
 * Création d'un compte user pour un responsable déjà inscrit
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve
 * @filesource responsable-loger.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/eleve', 
    [
        'action' => 'responsable-liste',
        'page' => $this->page
    ]);
$hiddens = [
    'op' => 'retour'
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Créer un compte pour un responsable</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé de créer un compte pour <?php echo $this->info;?>.</p>
<?php if (is_null($this->form)) : ?>
<p><?php echo $this->msg; ?></p>
	<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
<?php else : ?>
<p>Confirmez-vous ?</p>
<?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
<?php endif; ?>
</div>