<?php
// Generated by Zend Framework 2
return array(
    'SbmMailChimp\Module'                                    => __DIR__ . '/Module.php',
    'SbmMailChimp\Controller\IndexController'                => __DIR__ . '/src/SbmMailChimp/Controller/IndexController.php',
    'SbmMailChimp\Controller\Service\IndexControllerFactory' => __DIR__ . '/src/SbmMailChimp/Controller/Service/IndexControllerFactory.php',
    'SbmMailChimp\Form\Field'                                => __DIR__ . '/src/SbmMailChimp/Form/Field.php',
    'SbmMailChimp\Form\Liste'                                => __DIR__ . '/src/SbmMailChimp/Form/Liste.php',
    'SbmMailChimp\Form\Segment'                              => __DIR__ . '/src/SbmMailChimp/Form/Segment.php',
    'SbmMailChimp\Model\Db\Service\Users'                    => __DIR__ . '/src/SbmMailChimp/Model/Db/Service/Users.php',
    'SbmMailChimp\Model\Paginator\Adapter\MailChimpAdapter'  => __DIR__ . '/src/SbmMailChimp/Model/Paginator/Adapter/MailChimpAdapter.php',
);