<?php
/**
 * Liste des circuits 
 * 
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource ccda-circuits.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 juill. 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmportail');
$url_ici = $this->url();
$url_circuits = $this->url('sbmportail', array('action' => 'tr-circuits'));

$hiddens = array();
$actions = array(
    'cancel' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);

$this->paginator->setDefaultItemCountPerPage(6);
$this->paginator->setCurrentPageNumber($this->page);
$services = $this->paginator->getCurrentItems();
?>
<h1>Liste des circuits</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="services">
			<tbody>
				<tr>
					<th>Service</th>
					<th>Nom</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Nb de places</th>
					<th>Effectif</th>
					<th>Etablissements desservis</th>
					<th></th>
				</tr>
        <?php foreach($services as $serviceId => $service): ?>
        <?php
            // etablissements
            $cr = array_walk($service['etablissements'], function(&$item, $key){
                $item = implode (' - ', $item);
            });
            $etablissements = implode("\n", $service['etablissements']);
                          // tr css
            $tr_css = $this->cycle(array(
                "even",
                "odd"
            ))->next();
            ?>
         <tr class="<?php echo $tr_css;?>">
					<td class="serviceId"><?php echo $this->escapeHtml($serviceId); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($service['nom']); ?></td>
					<td class="transporteur"><?php echo $this->escapeHtml($service['transporteur']); ?></td>
					<td class="operateur"><?php echo $this->escapeHtml($service['operateur']); ?></td>
					<td class="nb-places"><?php echo $service['nbPlaces'];?></td>
					<td class="effectif"><?php echo empty($this->statServices[$serviceId]['total']) ? 0 : $this->statServices[$serviceId]['total'];?></td>
					<td class="etablissements"><?php echo nl2br($this->escapeHtml($etablissements));?></td>
					<td class="boutons">
            <?php
            $hiddens = array(
                'serviceId' => $serviceId,
                'info' => $serviceId . ' - ' . $service['nom'],
                'origine' => 'ccda-circuits'
            );
            $buttons = array(
                'horaires' => array(
                    'class' => 'fam-clock-red',
                    'formaction' => $url_circuits,
                    'title' => 'Fiche horaires et informations',
                )
            );
            echo $this->listeLigneActions($serviceId, $hiddens, $buttons);
            ?>
				</td>
				</tr>         
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper"></div>
	</div>
</div>