<?php
/**
 * Page d'accueil du portail pour les établissements
 *
 * Les variables définies dans cette vue sont :
 * - elevesTransportes
 * - services
 * - statServices
 * 
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource tr-index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 août 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_horaires = $this->url('sbmdocument', array(
    'action' => 'horaires'
));
$url_eleves = $this->url('sbmportail', array(
    'action' => 'tr-eleves'
));
$url_circuits = $this->url('sbmportail', array(
    'action' => 'tr-circuits'
));
$url_carte_stations = $this->url('sbmportail', array(
    'action' => 'tr-carte-stations'
));
$url_carte_etablissements = $this->url('sbmportail', array(
    'action' => 'tr-carte-etablissements'
));

?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
    </div>
	<h1>Portail des transports scolaires</h1>
	<!-- h3>Pour les transporteurs</h3-->
	<div class="float-left">
	<?php if ($this->elevesTransportes):?>
		<table class="bleu">
			<tbody>
				<tr>
					<td>Nombre d'élèves transportés</td>
					<td class="effectif"><?php echo $this->elevesTransportes ?:0;?></td>
				</tr>
			</tbody>
		</table>
	<?php endif;?>
		<p></p>
	<?php if ($this->services):?>
		<table class="rose ">
			<tbody>
				<?php foreach ($this->services as $service):?>
				    <?php
        $hiddens = array(
            'serviceId' => $service['serviceId']
        );
        $buttons = array(
            'horaires' => array(
                'class' => 'fam-clock-red',
                'formaction' => $url_circuits,
                'title' => 'Fiche horaires et informations'
            )
        );
        ?>
				<tr>
					<td><?php echo $service['serviceId'];?></td>
					<td><?php echo $service['nom'];?></td>
					<td><?php echo $service['operateur'];?></td>
					<td><?php echo $service['transporteur'];?></td>
					<td class="effectif"><?php echo empty($this->statServices[$service['serviceId']]['total']) ? 0 : $this->statServices[$service['serviceId']]['total'];?></td>
					<td><?php echo $this->listeLigneActions($service['serviceId'], $hiddens, $buttons);?></td>
				</tr>
				<?php endforeach;?>				
			</tbody>
		</table>
	<?php endif;?>	
	</div>
	<div id="menugeneral" class="float-right">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?php echo $url_eleves; ?>"><i class="fam-bullet-go"></i>Liste
						des élèves</a></li>
				<li><a href="<?php echo $url_horaires; ?>"><i class="fam-bullet-go"></i>Fiches
						horaires des circuits</a></li>
				<li><a href="<?php echo $url_carte_stations; ?>"><i
						class="fam-bullet-go"></i>Carte des points d'arrêts</a></li>
				<li><a href="<?php echo $url_carte_etablissements; ?>"><i
						class="fam-bullet-go"></i>Carte des établissements scolaires</a></li>
			</ul>
		</div>
	</div>
</div>