<?php
/**
 * Liste des circuits 
 * 
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource org-circuits.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmportail');
$url_circuits = $this->url('sbmportail', [
    'action' => 'tr-circuits'
]);

$hiddens = [];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];

$this->paginator->setDefaultItemCountPerPage(6);
$this->paginator->setCurrentPageNumber($this->page);
$services = $this->paginator->getCurrentItems();
?>
<h1>Liste des circuits</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="services">
			<tbody>
				<tr>
					<th>Service</th>
					<th>Nom</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Nb de places</th>
					<th>Effectif</th>
					<th>Etablissements desservis</th>
					<th></th>
				</tr>
        		<?php foreach($services as $serviceId => $service): ?>
        		<?php
            // etablissements
            array_walk($service['etablissements'],
                function (&$item, $key) {
                    $item = implode(' - ', $item);
                });
            $etablissements = implode("\n", $service['etablissements']);
            // tr css
            $tr_css = $this->cycle([
                "even",
                "odd"
            ])->next();
            $hiddens = [
                'serviceId' => $serviceId,
                'info' => $serviceId . ' - ' . $service['nom'],
                'origine' => 'org-circuits'
            ];
            $buttons = [
                'horaires' => [
                    'class' => 'fam-clock-red',
                    'formaction' => $url_circuits,
                    'title' => 'Fiche horaires et informations'
                ]
            ];
            ?>
         		<tr class="<?= $tr_css;?>">
					<td class="serviceId">
						<?= $this->escapeHtml($serviceId); ?></td>
					<td class="nom">
						<?= $this->escapeHtml($service['nom']); ?></td>
					<td class="transporteur">
						<?= $this->escapeHtml($service['transporteur']); ?></td>
					<td class="operateur">
						<?= $this->escapeHtml($service['operateur']); ?></td>
					<td class="nb-places">
						<?= $service['nbPlaces'];?></td>
					<td class="effectif">
						<?= empty($this->statServices[$serviceId]['total']) ? 0 : $this->statServices[$serviceId]['total'];?></td>
					<td class="etablissements">
						<?= nl2br($this->escapeHtml($etablissements));?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($serviceId, $hiddens, $buttons);?></td>
				</tr>         
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination',[]); ?></div>
		<div class="criteres-wrapper"></div>
	</div>
</div>