<?php
/**
 * Page d'accueil du portail pour les services de l'organisateur
 *
 * Les variables définies dans cette vue sont :
 * - elevesEnregistres
 * - elevesInscrits
 * - elevesPreinscrits
 * - elevesRayes
 * - elevesFamilleAcceuil
 * - elevesGardeAlternee
 * - elevesMoins1km
 * - elevesDe1A3km
 * - eleves3kmEtPlus
 * - responsablesEnregistres
 * - responsablesAvecEnfant
 * - responsablesSansEnfant
 * - responsablesHorsZone
 * - responsablesDemenagement
 * - paiements
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource org-index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 août 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_horaires = $this->url('sbmdocument', [
    'action' => 'horaires'
]);
$url_eleves = $this->url('sbmportail', [
    'action' => 'org-eleves'
]);
$url_circuits = $this->url('sbmportail', [
    'action' => 'org-circuits'
]);
$url_carte_stations = $this->url('sbmportail', [
    'action' => 'tr-carte-stations'
]);
$url_carte_etablissements = $this->url('sbmportail',
    [
        'action' => 'tr-carte-etablissements'
    ]);

$nbDistanceInconnue = ($this->elevesDpEnregistres ?: 0) +
    ($this->elevesIntEnregistres ?: 0) - ($this->elevesMoins1km ?: 0) -
    ($this->elevesDe1A3km ?: 0) - ($this->eleves3kmEtPlus ?: 0);
?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
    </div>
	<h1>Portail du service</h1>
	<div class="float-left">
		<h2>Quelques chiffres</h2>
		<table class="bleu float-left">
			<tbody>
				<tr>
					<td>Nombre d'élèves enregistrés</td>
					<td class="effectif">
						<?= ($this->elevesDpEnregistres ?: 0) + ($this->elevesIntEnregistres ?: 0);?></td>
				</tr>
				<tr>
					<td class="align-right">dont <?=$this->elevesDpEnregistres ?: 0;?> DP</td>
				</tr>
				<tr>
					<td class="align-right">et <?=$this->elevesIntEnregistres ?: 0;?> Internes</td>
				</tr>
				<tr>
					<td>Nombre d'abonnements payés</td>
					<td class="effectif"><?= $this->elevesInscrits ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'abonnements payés puis rayés</td>
					<td class="effectif"><?= $this->elevesInscritsRayes ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre de demandes non payées</td>
					<td class="effectif"><?= $this->elevesPreinscrits ?:0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre de demandes non payées puis rayés</td>
					<td class="effectif"><?= $this->elevesPreinscritsRayes ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves à moins de 1 km</td>
					<td class="effectif"><?= $this->elevesMoins1km ?: 0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves de 1 à 3 km</td>
					<td class="effectif"><?= $this->elevesDe1A3km ?: 0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves à 3 km et plus</td>
					<td class="effectif"><?= $this->eleves3kmEtPlus ?: 0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves non géolocalisés</td>
					<td class="effectif"><?= $nbDistanceInconnue;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves en garde alternée</td>
					<td class="effectif"><?= $this->elevesGardeAlternee ?:0;?></td>
				</tr>
			</tbody>
		</table>
		<div class="float-left">
			<table class="rose ">
				<tbody>
					<tr>
						<td>Nombre de responsables</td>
						<td class="effectif"><?= $this->responsablesEnregistres;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant inscrit des enfants</td>
						<td class="effectif"><?= $this->responsablesAvecEnfant;?></td>
					</tr>
					<tr class="separateur">
						<td>Nombre de responsables sans enfant inscrit</td>
						<td class="effectif"><?= $this->responsablesSansEnfant;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables résidant hors périmètre</td>
						<td class="effectif"><?= $this->responsablesHorsZone;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant déménagé</td>
						<td class="effectif"><?= $this->responsablesDemenagement;?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div id="menugeneral" class="float-right">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?= $url_eleves; ?>"><i class="fam-bullet-go"></i>Liste
						des élèves</a></li>
				<li><a href="<?= $url_circuits;?>" target="_blank"><i
						class="fam-bullet-go"></i>Circuits et horaires</a></li>
				<li><a href="<?= $url_horaires; ?>" target="_blank"><i
						class="fam-bullet-go"></i>Horaires des circuits à imprimer</a></li>
				<li><a href="<?= $url_carte_stations; ?>"><i class="fam-bullet-go"></i>Carte
						des points d'arrêts</a></li>
				<li><a href="<?= $url_carte_etablissements; ?>"><i
						class="fam-bullet-go"></i>Carte des établissements scolaires</a></li>
			</ul>
		</div>
	</div>
</div>
