<?php
/**
 * Liste des élèves pour le protail de l'organisateur (secrétariat)
 *
 * La requête est basée sur SbmCommun\Model\Db\Service\Query\Eleve\ElevesSolarites::selectScolaritesR()
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource org-eleves.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 août 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// le paginateur
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
try {
    $eleves = $this->paginator->getCurrentItems();
} catch (\Zend\Db\Adapter\Exception\InvalidQueryException $e) {
    // affichage d'une page d'erreur
    ?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-inner">
		<pre>
	  <?= $e->getMessage();?>
	</pre>
	</div>
	<div id="liste-footer">
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
        	<?= $this->form()->openTag($this->criteres_form);?>
        	<?= $this->formCollection($this->criteres_form, true);?>
        	<?= $this->form()->closeTag();?>
        <?php endif;?>
        </div>
	</div>
</div>
<?php
    return; // fin du catch (affichage d'une page d'erreur)
}

// les url à utiliser
$url_ici = $this->url('sbmportail', [
    'action' => 'org-eleves',
    'page' => $this->page
]);
$url_rapports = $this->url('sbmportail', [
    'action' => 'org-pdf',
    'page' => $this->page
]);
$url_download = $this->url('sbmportail',
    [
        'action' => 'org-eleves-download',
        'page' => $this->page
    ]);
// le formulaire des actions du haut de page - aide de vue listeZoneActions()
$hiddens = [];

$menuImpression = $this->menuRapports(
    $this->url('sbmportail', [
        'action' => 'org-eleves'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];

$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_ici,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'download' => [
        'class' => 'fam-cloud-download',
        'formaction' => $url_download,
        'formtarget' => '_blank',
        'title' => 'Extraction de la liste dans un fichier'
    ]
];
?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
			<?= $this->listeZoneActions($hiddens, $actions);?>
		</div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Responsables</th>
					<th>Etablissement scolaire</th>
					<th>Classe</th>
					<th>Services</th>
					<th>Abonnement</th>
				</tr>
				<?php foreach($eleves as $eleve): ?>
				<?php
        $r = [];
        if ($eleve['responsable1NomPrenom']) {
            $r[] = htmlspecialchars(
                str_replace(' ', '&nbsp;', $eleve['responsable1NomPrenom']), ENT_QUOTES,
                'utf-8', false);
        }
        if ($eleve['responsable2NomPrenom']) {
            $r[] = htmlspecialchars(
                str_replace(' ', '&nbsp;', $eleve['responsable2NomPrenom']), ENT_QUOTES,
                'utf-8', false);
        }
        $nbResponsables = count($r);
        $tr_css = $this->cycle([
            "even",
            "odd"
        ])->next();
        // adresses
        $adresseR1 = implode('<br>',
            array_filter(
                array_unique(
                    [
                        $eleve['adresseL1R1'],
                        $eleve['adresseL2R1'],
                        $eleve['adresseL3R1'],
                        $eleve['lacommuneR1']
                    ])));
        $adresseR2 = implode('<br>',
            array_filter(
                array_unique(
                    [
                        $eleve['adresseL1R2'],
                        $eleve['adresseL2R2'],
                        $eleve['adresseL3R2'],
                        $eleve['lacommuneR2']
                    ])));
        $ga = (bool) $eleve['responsable2Id'];
        $itinerairesR1 = sprintf(
            $this->printItineraires($eleve['eleveId'], 1, $eleve['demandeR1'] == 1), '');
        if ($ga) {
            $itinerairesR2 = sprintf(
                $this->printItineraires($eleve['eleveId'], 2, $eleve['demandeR2'] == 1),
                '');
        }
        if (! $eleve['inscrit']) {
            $tr_css .= ' barre';
        }
        if ($eleve['paiementR1'] || $eleve['gratuit'] == 1) {
            $message = 'Payé';
        } else {
            $message = 'Impayé';
        }
        ?>
        		<tr class="petit <?= $tr_css;?>">
					<td class="nom"
						<?= $nbResponsables ? ' rowspan=' . $nbResponsables : ''?>>
					<?= $this->escapeHtml($eleve['nom']); ?></td>
					<td class="prenom"
						<?= $nbResponsables ? ' rowspan=' . $nbResponsables : ''?>>
					<?= $this->escapeHtml($eleve['prenom']); ?></td>
					<td class="adresse">
					<?= $adresseR1; ?></td>
					<td class="responsables">
					<?= $r[0]; ?></td>
					<td class="etablissement"
						<?= $nbResponsables ? ' rowspan=' . $nbResponsables : ''?>>
					<?= $this->escapeHtml($eleve['etablissement']);?></td>
					<td class="classe"
						<?= $nbResponsables ? ' rowspan=' . $nbResponsables : ''?>>
					<?= $this->escapeHtml($eleve['classe']);?></td>
					<td class="service"><?= $itinerairesR1;?></td>
					<td class="centre"><?= $message;?></td>
					<?php if ($nbResponsables == 2) :?>
				</tr>
				<tr class="petit <?= $tr_css;?>">
					<td class="adresse"><?= $adresseR2; ?></td>
					<td><?= $r[1]; ?></td>
					<td><?= $itinerairesR2;?></td>
					<?php endif;?>
        		</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<p class="sbm-description"></p>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?>
		</div>
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
    		<?= $this->form()->openTag($this->criteres_form);?>
    		<?= $this->formCollection($this->criteres_form, true);?>
    		<?= $this->form()->closeTag();?>
    	<?php endif;?>
	    </div>
	</div>
</div>