<?php
/**
 * Page de consultation des inscrits sur un point d'arrêt d'un circuit
 * 
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource tr-circuit-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 août 2015
 * @version 2015-1
 */

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmportail', array(
    'action' => 'tr-circuits',
    'page' => $this->page
));
$hiddens = array(
    'circuitId' => $this->circuit->circuitId,
    'serviceId' => $this->serviceId
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);
?>
<h1>Groupe des élèves inscrits sur un point d'arrêt d'un circuit</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li>Circuit : <?php echo $this->escapeHtml($this->circuit->serviceId); ?></li>
			<li>Arrêt : <?php echo $this->escapeHtml($this->circuit->station . ' - ' . $this->circuit->communeStation); ?></li>
			<li>Type d'arrêt : <?php echo $this->escapeHtml($this->circuit->typeArret); ?></li>
			<li>Commentaire aller : <?php echo $this->escapeHtml($this->circuit->commentaire1); ?></li>
			<li>Commentaire retour : <?php echo $this->escapeHtml($this->circuit->commentaire2); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php
foreach ($this->data as $row) {
    echo '<tr class="' . $this->cycle(array("even", "odd"))->next() . '">';
    foreach ($row as $item) {
        echo '<td>' . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
</div> 