<?php
/**
 * Détail d'un circuit pour les transporteurs : points d'arrêt, horaires, inscrits
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource tr-circuits.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 août 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// $this->paginator->setDefaultItemCountPerPage($this->count_per_page);
// $this->paginator->setCurrentPageNumber($this->page);
$circuits = $this->data; // ->paginator->getCurrentItems();

$url_group = $this->url('sbmportail',
    [
        'action' => 'tr-circuit-group',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmportail',
    [
        'action' => empty($this->origine) ? 'index' : $this->origine
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Détail du circuit <?=$this->escapeHtml($this->service->designation());?></h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
			<?=$this->listeZoneActions($hiddens, $actions);?>
		</div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr>
					<th>Arrêt</th>
					<th>Commune</th>
					<th>Emplacement</th>
					<th colspan="2">Commentaire</th>
					<th class="horaire">Arrivée</th>
					<th class="horaire">Départ</th>
					<th class="nbinscrits">Montée</th>
					<th class="nbinscrits">Descente</th>
					<th class="nbinscrits">Effectif</th>
					<th></th>
				</tr>
            <?php
            $effectif = 0;
            foreach ($circuits as $circuit) :
                ?>
            	<?php
                if (method_exists($this->effectifCircuits, 'transportes')) {
                    $nbInscrits = $this->effectifCircuits->transportes(
                        $circuit->circuitId);
                } else {
                    $nbInscrits = [
                        'montee' => 0,
                        'descente' => 0
                    ];
                }
                $effectif += $nbInscrits['montee'] - $nbInscrits['descente'];
                // echo '<pre>';var_dump($nbInscrits, $effectif);echo '</pre>';
                $hiddens = [
                    'ligneId' => $circuit->ligneId,
                    'sens' => $circuit->sens,
                    'moment' => $circuit->moment,
                    'ordre' => $circuit->ordre,
                    'circuitId' => $circuit->circuitId
                ];
                $buttons = [
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves du circuit %s à l\'arrêt %s',
                            $circuit->designationService(), $circuit->station)
                    ]
                ];
                ?>
                <tr class="<?=$this->cycle(["even","odd"])->next();?>">
					<td class="station">
						<?=$this->escapeHtml($circuit->station);?></td>
					<td class="commune">
						<?=$this->escapeHtml($circuit->communeStation);?></td>
					<td class="emplacement">
						<?=$this->escapeHtml($circuit->emplacement);?></td>
					<td class="commentaire1">
						<?=$this->escapeHtml($circuit->commentaire1);?></td>
					<td class="commentaire2">
						<?=$this->escapeHtml($circuit->commentaire2);?></td>
					<td class="horaire"><?=$circuit->horaireA;?></td>
					<td class="horaire"><?=$circuit->horaireD;?></td>
					<td class="nbinscrits"><?=$nbInscrits['montee'];?></td>
					<td class="nbinscrits"><?=$nbInscrits['descente'];?></td>
					<td class="nbinscrits"><?=$effectif;?></td>
					<td class="boutons">
             			<?=$this->listeLigneActions($circuit->circuitId, $hiddens, $buttons);?>
				</td>
				</tr>
            <?php endforeach;?>
            </tbody>
		</table>

	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?php //=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?>
		</div>
	</div>
</div>
