<?php
/**
 * Détail d'un circuit pour les transporteurs : points d'arrêt, horaires, inscrits
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource tr-circuits.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 sept. 2018
 * @version 2018-2.4.5
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$circuits = $this->paginator->getCurrentItems();

$url_group = $this->url('sbmportail',
    [
        'action' => 'tr-circuit-group',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmportail',
    [
        'action' => empty($this->origine) ? 'index' : $this->origine
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Détail du circuit <?= $this->escapeHtml($this->service->serviceId); ?> - <?= $this->escapeHtml($this->service->nom); ?></h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr>
					<th>Arrêt</th>
					<th>Commune</th>
					<th>Type</th>
					<th colspan="2">Commentaire</th>
					<th class="horaire">Matin</th>
					<th class="horaire">Soir</th>
					<th class="horaire">Mercredi</th>
					<th class="nbinscrits">Inscrits</th>
					<th></th>
				</tr>
            <?php foreach($circuits as $circuit): ?>
            <?php
                $nbInscrits = StdLib::getParamR([
                    $circuit->circuitId,
                    'total'
                ], $this->t_nb_inscrits, 0);
                $hiddens = [
                    'serviceId' => $circuit->serviceId,
                    'circuitId' => $circuit->circuitId
                ];
                $buttons = [
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves du circuit %s à l\'arrêt %s',
                            $circuit->serviceId, $circuit->station)
                    ]
                ];
                ?>
                <tr class="<?= $this->cycle(['even', 'odd'])->next();?>">
					<td class="station">
						<?= $this->escapeHtml($circuit->station); ?></td>
					<td class="commune">
						<?= $this->escapeHtml($circuit->communeStation); ?></td>
					<td class="type-arret">
						<?= $this->escapeHtml($circuit->typeArret); ?></td>
					<td class="commentaire1">
						<?= $this->escapeHtml($circuit->commentaire1); ?></td>
					<td class="commentaire2">
						<?= $this->escapeHtml($circuit->commentaire2); ?></td>
					<td class="horaire">
						<?= $circuit->m1; ?></td>
					<td class="horaire">
						<?= $circuit->s1; ?></td>
					<td class="horaire">
						<?= $circuit->s2; ?></td>
					<td class="nbinscrits">
						<?= $nbInscrits; ?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($circuit->circuitId, $hiddens, $buttons);?></td>
				</tr>          
            <?php endforeach;?>
            </tbody>
		</table>

	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination',[]); ?></div>
	</div>
</div>
