<?php
/**
 * Liste des élèves
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/index
 * @filesource tr-eleves.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 9 août 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// gestion du hidden op des formulaires de liste : les arguments sont id, suffixe de l'id,
// valeur
// (ne pas mettre de guillemet dans la chaine)
$js_op = 'window.document.getElementById(\'op%s%s\').value=\'%s\';';

// le paginateur
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
try {
    $eleves = $this->paginator->getCurrentItems();
} catch (\Zend\Db\Adapter\Exception\InvalidQueryException $e) {
    // affichage d'une page d'erreur
    ?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-inner">
		<pre>
	  <?= $e->getMessage();?>
	</pre>
	</div>
	<div id="liste-footer">
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
        	<?= $this->form()->openTag($this->criteres_form);?>
        	<?= $this->formCollection($this->criteres_form, true);?>
        	<?= $this->form()->closeTag();?>
        <?php endif;?>
        </div>
	</div>
</div>
<?php
    return; // fin du catch (affichage d'une page d'erreur)
}

// les url à utiliser
$url_ici = $this->url('sbmportail', [
    'action' => 'tr-eleves',
    'page' => $this->page
]);
$url_responsable = $this->url('sbmportail',
    [
        'action' => 'tr-responsable',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmportail', [
    'action' => 'tr-pdf',
    'page' => $this->page
]);
$url_telephones = $this->url('sbmportail',
    [
        'action' => 'tr-extraction-telephones',
        'page' => $this->page
    ]);
$url_download = $this->url('sbmportail',
    [
        'action' => 'tr-eleves-download',
        'page' => $this->page
    ]);
// le formulaire des actions du haut de page - aide de vue listeZoneActions()
$hiddens = [];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_ici,
        'title' => 'Retour'
    ],/*
    'rapports' => [
        'class' => 'fam-printer',
        'formaction' => $url_rapports,
        'title' => 'Liste à imprimer',
        'formtarget' => '_blank'
    ],*/
    'download' => [
        'class' => 'fam-cloud-download',
        'formaction' => $url_download,
        'formtarget' => '_blank',
        'title' => 'Extraction de la liste dans un fichier'
    ]
];
if ($this->categorieId == \SbmAuthentification\Model\CategoriesInterface::TRANSPORTEUR_ID) {
    $actions['telephones'] = [
        'class' => 'fam-telephone',
        'formaction' => $url_telephones,
        'title' => 'Extraction des numéros de téléphones portables'
    ];
}
?>
<h1>Liste des élèves</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Elève</th>
					<th>Responsables</th>
					<th>Téléphone</th>
					<th>Adresse</th>
					<th>Origine</th>
					<th>Etablissement scolaire</th>
					<th>Classe</th>
					<th>Services</th>
				</tr>
        <?php foreach($eleves as $eleve): ?>
        	<?php
            $resp = htmlspecialchars(str_replace(' ', '&nbsp;', $eleve['responsable']),
                ENT_QUOTES, 'utf-8', false);
            $tr_css = $this->cycle([
                "even",
                "odd"
            ])->next();
            // adresse
            $adresse = implode('<br>',
                array_filter(
                    array_unique(
                        [
                            $eleve['adresseL1'],
                            $eleve['adresseL2'],
                            $eleve['adresseL3'],
                            $eleve['commune']
                        ])));
            // téléphones
            $telephones = implode('<br>',
                array_filter(
                    [
                        $eleve['telephoneF'],
                        $eleve['telephoneP'],
                        $eleve['telephoneT']
                    ]));
            if (! $eleve['inscrit']) {
                $tr_css .= ' barre';
            }
            $itineraires = $this->printItineraires($eleve['eleveId'], $eleve['trajet'],
                false, $eleve['millesime']);
            ?>
         <tr class="petit <?= $tr_css;?>">
					<td class="nom">
						<?= $this->escapeHtml($eleve['eleve']); ?></td>
					<td class="responsable"><?= $resp; ?></td>
					<td class="telephones"><?= $telephones;?></td>
					<td class="adresse">
						<?= $adresse; ?></td>
					<td><?= $this->escapeHtml($eleve['origine']);?></td>
					<td class="etablissement">
						<?= $this->escapeHtml($eleve['etablissement'] /*. ' - ' . $eleve['lacommuneEtablissement']*/);?></td>
					<td class="classe">
						<?= $this->escapeHtml($eleve['classe']);?></td>
					<td><?= $itineraires;?></td>
				</tr>
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?>
		</div>
		<div class="criteres-wrapper">
		<?php if (! is_null($this->criteres_form)) :?>
    		<?= $this->form()->openTag($this->criteres_form);?>
    		<?= $this->formCollection($this->criteres_form, true);?>
    		<?= $this->form()->closeTag();?>
		<?php endif;?>
	    </div>
	</div>
</div>