<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DafapSession\Module'                                      => __DIR__ . '/Module.php',
    'DafapSession\Authentication\AdapterEmail'                 => __DIR__ . '/src/DafapSession/Authentication/AdapterEmail.php',
    'DafapSession\Authentication\AdapterToken'                 => __DIR__ . '/src/DafapSession/Authentication/AdapterToken.php',
    'DafapSession\Authentication\AuthenticationService'        => __DIR__ . '/src/DafapSession/Authentication/AuthenticationService.php',
    'DafapSession\Authentication\AuthenticationServiceFactory' => __DIR__ . '/src/DafapSession/Authentication/AuthenticationServiceFactory.php',
    'DafapSession\Authentication\Exception'                    => __DIR__ . '/src/DafapSession/Authentication/Exception.php',
    'DafapSession\Model\Exception'                             => __DIR__ . '/src/DafapSession/Model/Exception.php',
    'DafapSession\Model\Mdp'                                   => __DIR__ . '/src/DafapSession/Model/Mdp.php',
    'DafapSession\Model\Session'                               => __DIR__ . '/src/DafapSession/Model/Session.php',
    'DafapSession\Permissions\AclRoutes'                       => __DIR__ . '/src/DafapSession/Permissions/AclRoutes.php',
);
