<?php
/**
 * Page de suppression d'un document dans le menu d'impression d'une page
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource affectation-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 oct. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Suppression de l'affectation d'un document dans un menu</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du document <?= $this->data->libelle; ?> 
		dans le menu de la page <?= $this->data->route;?>.</p>
	<div class="header-wrapper"></div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($this->form);?>
	<?= $this->formCollection($this->form);?>
	<?= $this->form()->closeTag();?>
</div>