<?php
/**
 * Ecran de saisie d'une affectation d'un document dans un menu
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource affectation-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Liste des documents',
        'onclick' => sprintf($js, "'retour'")
    ]
];

if (strlen($this->document['recordSource']) > 450) {
    $sourceDocument = substr($this->document['recordSource'], 0, 450) . '...';
} else {
    $sourceDocument = $this->document['recordSource'];
}
?>
<h1>Placement d'un document pdf dans un menu</h1>
<ul>
	<li>Document: <?= $this->document['name'];?></li>
	<li>Source du document: <?= $sourceDocument;?></li>
</ul>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="clearfix">
		<fieldset class="sbm-page1">
    		<?= $this->form()->openTag($this->form);?>
    		<?= $this->formHidden($this->form->get('docaffectationId'));?>
    		<?= $this->formHidden($this->form->get('documentId'));?>
    		<?= $this->formHidden($this->form->get('name'));?>
    		<?= $this->formHidden($this->form->get('recordSource'));?>
    		<?= $this->formHidden($this->form->get('csrf'));?>
 			<div class="row-inner label-240"><?= $this->formRow($this->form->get('libelle'));?></div>
			<div class="row-inner label-240"><?= $this->formRow($this->form->get('ordinal_position'));?></div>
			<div class="row-inner label-240"><?= $this->formRow($this->form->get('route'));?></div>
			<div class="row-inner">
	    		<?= $this->formSubmit($this->form->get('submit')); ?>
	    		<?= $this->formSubmit($this->form->get('cancel')); ?>
        	</div>
        	<?= $this->form()->closeTag(); ?>
        </fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>