<?php
/**
 * Page de suppression d'un document dans le menu d'impression d'une page
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource affectation-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
?>
<h1>Suppression de l'affectation d'un document dans un menu</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du document <?= $this->data->libelle; ?> 
	dans le menu de la page <?= $this->data->route;?>.</p>
	<div class="header-wrapper"></div>
	<p>Confirmez-vous ?</p>
<?= $this->form()->openTag($form);?>
<?= $this->formCollection($form);?>
<?= $this->form()->closeTag();?>
</div>