<?php
/**
 * Vue de la liste des affecations d'un document pdf dans des menus
 *
 * Les menus sont caractérisés par la route de la page dans laquelle ils seront affichés
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource affectation-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_ajout = $this->url('sbmpdf',
    [
        'action' => 'affectation-ajout',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmpdf', [
    'action' => 'affectation-edit',
    'page' => $this->page
]);
$url_suppr = $this->url('sbmpdf',
    [
        'action' => 'affectation-suppr',
        'page' => $this->page
    ]);

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
];

$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Liste des documents'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajout,
        'title' => 'Nouvelle affectation dans un menu'
    ]
];

$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier l\'affectation ou le libellé du menu'
    ],
    'supprimer' => [
        'class' => 'fam-delete',
        'formaction' => $url_suppr,
        'title' => 'supprimer cette affectation'
    ]
];
if (strlen($this->document['recordSource']) > 450) {
    $sourceDocument = substr($this->document['recordSource'], 0, 450) . '...';
} else {
    $sourceDocument = $this->document['recordSource'];
}
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des affectations de ce document dans un menu</h1>
			<ul>
				<li>Document: <?= $this->document['name'];?></li>
				<li>Source du document: <?= $sourceDocument;?></li>
			</ul>
			<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>Page</th>
					<th>Libellé dans le menu</th>
					<th>Position</th>
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
            <?php $hiddens['docaffectationId'] = $row['docaffectationId'];?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="route">
						<?= $this->escapeHtml($row['route']); ?></td>
					<td class="libelle">
						<?= $this->escapeHtml($row['libelle']); ?></td>
					<td class="libelle align-right">
						<?= $row['ordinal_position']; ?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($row['docaffectationId'], $hiddens, $buttons);?></td>
				</tr>
        	<?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>