<?php
/**
 * Ecran de saisie d'une affectation d'un document dans un menu
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource affectation-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmpdf', array(
    'action' => 'pdf-liste',
    'page' => $this->page
));
$hiddens = array(
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Liste des documents',
        'onclick' => sprintf($js, "'retour'")
    )
);

if (strlen($this->document['recordSource']) > 450) {
    $sourceDocument = substr($this->document['recordSource'], 0, 450) . '...';
} else {
    $sourceDocument = $this->document['recordSource'];
}
?>
<h1>Placement d'un document pdf dans un menu</h1>
<ul>
	<li>Document: <?php echo $this->document['name'];?></li>
	<li>Source du document: <?php echo $sourceDocument;?></li>
</ul>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="clearfix">
		<fieldset class="sbm-page1">
	   <?php
    echo $this->form()->openTag($this->form);
    echo $this->formHidden($this->form->get('docaffectationId'));
    echo $this->formHidden($this->form->get('documentId'));
    echo $this->formHidden($this->form->get('name'));
    echo $this->formHidden($this->form->get('recordSource'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>
 			<div class="row-inner label-240"><?php echo $this->formRow($this->form->get('libelle'));?></div>
			<div class="row-inner label-240"><?php echo $this->formRow($this->form->get('ordinal_position'));?></div>
			<div class="row-inner label-240"><?php echo $this->formRow($this->form->get('route'));?></div>
			<div class="row-inner">
	    <?php echo $this->formSubmit($this->form->get('submit')); ?>
	    <?php echo $this->formSubmit($this->form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        </fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>