<?php
/**
 * Vue de la liste des colonnes d'un document pdf
 *
 * Actions possibles depuis cette vue :
 * - ajouter une colonne
 * - modifier une colonne
 * - dupliquer une colonne
 * - supprimer une colonne
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource colonne-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_cancel = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_ajout = $this->url('sbmpdf', [
    'action' => 'colonne-ajout',
    'page' => $this->page
]);
$url_edit = $this->url('sbmpdf', [
    'action' => 'colonne-edit',
    'page' => $this->page
]);
$url_dupliquer = $this->url('sbmpdf',
    [
        'action' => 'colonne-dupliquer',
        'page' => $this->page
    ]);
$url_suppr = $this->url('sbmpdf', [
    'action' => 'colonne-suppr',
    'page' => $this->page
]);
$url_retour = $this->url('sbmpdf', [
    'action' => 'table-liste',
    'page' => $this->page
]);

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'ordinal_table' => $this->document['ordinal_table'],
    'recordSource' => $this->document['recordSource'],
    'new_position' => count($this->data) + 1
];

$actions = [
    'homepdf' => [
        'class' => 'fam-door-out',
        'formaction' => $url_cancel,
        'title' => 'Liste des documents'
    ],
    'retour' => [
        'class' => 'fam-book-previous',
        'formaction' => $url_retour,
        'title' => 'Configuration du tableau'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajout,
        'title' => 'Nouvelle colonne'
    ]
];

$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier la colonne'
    ],
    'dupliquer' => [
        'class' => 'fam-page-copy',
        'formaction' => $url_dupliquer,
        'title' => 'dupliquer la colonne'
    ],
    'supprimer' => [
        'class' => 'fam-delete',
        'formaction' => $url_suppr,
        'title' => 'supprimer la colonne'
    ]
];
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des colonnes d'un tableau pour un document pdf</h1>
			<ul>
				<li>Document: <?= $this->document['name'];?></li>
				<li>Numéro du tableau: <?= $this->document['ordinal_table'];?></li>
				<li>Source du document: <?= $this->document['recordSource'];?></li>
			</ul>
			<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
            <?= $this->flashMessenger()->render('success');?>
            <?= $this->flashMessenger()->render('warning');?>
            <?= $this->flashMessenger()->render('error');?>
            <?= $this->flashMessenger()->render('info');?>
            <?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>N°</th>
					<th>Nom</th>
					<th>Champ</th>
					<th>Ligne du bas</th>
					<th>Largeur</th>
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
            	<?php
                $hiddens['doccolumnId'] = $row['doccolumnId'];
                $hiddens['ordinal_position'] = $row['ordinal_position'];
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="ordinal_position"><?= $row['ordinal_position']; ?></td>
					<td class="thead"><?= $this->escapeHtml($row['thead']); ?></td>
					<td class="tbody"><?= $this->escapeHtml($row['tbody']); ?></td>
					<td class="tfoot"><?= $this->escapeHtml($row['tfoot']); ?></td>
					<td class="width"><?= $row['width']; ?></td>
					<td class="boutons">
                		<?= $this->listeLigneActions($row['doccolumnId'], $hiddens, $buttons);?>
				    </td>
				</tr>
        	<?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>