<?php
/**
 * Page de suppression d'une colonne dans un document pdf en tableau
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource colonne-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
?>
<h1>Suppression d'une colonne dans un document Pdf</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de la colonne suivante :</p>
	<div class="header-wrapper">
		<ul>
			<li>Colonne n° : <?= $this->data->ordinal_position; ?></li>
			<li>En-tête de la colonne : <?= $this->escapeHtml($this->data->thead); ?></li>
			<li>Contenu de la colonne : <?= $this->escapeHtml($this->data->tbody); ?></li>
			<li>Dans la dernière ligne: <?= $this->escapeHtml($this->data->tfoot); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>