<?php
/**
 * Ecran de saisie des paramètres des étiquettes
 *
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource etiquette-format.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_cancel = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_retour = $this->url('sbmpdf', [
    'action' => 'pdf-edit',
    'page' => $this->page
]);
$url_fields = $this->url('sbmpdf', [
    'action' => 'field-liste',
    'page' => $this->page
]);

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
];

$actions = [
    'homepdf' => [
        'class' => 'fam-door-out',
        'formaction' => $url_cancel,
        'title' => 'Liste des documents'
    ],
    'retour' => [
        'class' => 'fam-book-previous',
        'formaction' => $url_retour,
        'title' => 'Configuration du document'
    ],
    'champs' => [
        'formaction' => $url_fields,
        'class' => 'button default',
        'value' => 'Liste des champs',
        'title' => 'Définition et mise en forme du contenu de l\'étiquette'
    ]
];
// le formulaire doit avoir id="accordion" pour que ça marche
?>
<h1>Paramétrage des étiquettes</h1>
<ul>
	<li>Document: <?= $this->document['name'];?></li>
	<li>Source du document: <?= $this->document['recordSource'];?></li>
</ul>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="clearfix">
		<fieldset class="sbm-page1">
    		<?= $this->form()->openTag($this->form);?> 
    		<?= $this->formHidden($this->form->get('doclabelId'));?>
    		<?= $this->formHidden($this->form->get('documentId'));?>
    		<?= $this->formHidden($this->form->get('name'));?>
    		<?= $this->formHidden($this->form->get('recordSource'));?>
    		<?= $this->formHidden($this->form->get('csrf'));?>
        	<div class="float-left">
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('cols_number'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('rows_number'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('label_width'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('label_height'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('margin_left'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('margin_top'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('x_space'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('y_space'));?></div>
			</div>
			<div class="float-left left-95px">
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('padding_top'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('padding_right'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('padding_bottom'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('padding_left'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('border'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('border_dash'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('border_width'));?></div>
				<div class="row-inner label-240">
					<?= $this->formRow($this->form->get('border_color'));?></div>
			</div>
			<div class="row-inner">
	    		<?= $this->formSubmit($this->form->get('submit')); ?>
	    		<?= $this->formSubmit($this->form->get('cancel')); ?>
        	</div>
        	<?= $this->form()->closeTag(); ?>
        </fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>