<?php
/**
 * Page montrant la liste des sous-étiquettes d'un document
 *
 * Cette vue reçoit les variables suivantes :
 * - document : tableau contenant au moins documentId, name, recordSource
 *
 * @project sbm
 * @package
 * @filesource etiquette-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 mai 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_ajout = $this->url('sbmpdf', [
    'action' => 'etiquette-ajout',
    'page' => $this->page
]);
$url_edit = $this->url('sbmpdf', [
    'action' => 'etiquette-edit',
    'page' => $this->page
]);
$url_suppr = $this->url('sbmpdf', [
    'action' => 'etiquette-suppr',
    'page' => $this->page
]);
$url_fields = $this->url('sbmpdf', [
    'action' => 'field-liste',
    'page' => $this->page
]);

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource'],
    'new_position' => count($this->data) + 1
];

$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Documents'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajout,
        'title' => 'Nouvelle zone d\'étiquette'
    ]
];

$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier la colonne'
    ],
    'supprimer' => [
        'class' => 'fam-delete',
        'formaction' => $url_suppr,
        'title' => 'supprimer la colonne'
    ],
    'champs' => [
        'formaction' => $url_fields,
        'class' => 'button default',
        'value' => 'Liste des champs',
        'title' => 'Définition et mise en forme du contenu de la zone d\'étiquette'
    ]
];
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des zones du document <?= $this->document['name'];?></h1>
			<ul>
				<li>Nombre de sous-étiquettes: <?= $this->nb_sublabel;?></li>
				<li>Source du document: <?= $this->document['recordSource'];?></li>
			</ul>
			<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>N°</th>
					<th>Gauche</th>
					<th>Haut</th>
					<th>Largeur</th>
					<th>Hauteur</th>
					<th>Nb lig.</th>
					<th>Nb col.</th>
					<th>Filigrane</th>
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
            	<?php
                $hiddens['documentId'] = $row->documentId;
                $hiddens['sublabel'] = $row->sublabel;
                $doclabelId = sprintf("%d.%d", $row->documentId, $row->sublabel); // remplace $row->doclabelId
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="sublabel"><?= $row->sublabel + 1;?></td>
					<td class="margin-left"><?= $row->margin_left; ?></td>
					<td class="margin-top"><?= $row->margin_top; ?></td>
					<td class="label-width"><?= $row->label_width; ?></td>
					<td class="label-height"><?= $row->label_height; ?></td>
					<td class="rows_number"><?= $row->rows_number?></td>
					<td class="cols-number"><?= $row->cols_number; ?></td>
					<td class="filigrane"><?= $row->filigrane; ?></td>
					<td class="boutons">
                		<?=$this->listeLigneActions($doclabelId,$hiddens,$buttons); // remplace $row->doclabelId?>
				    </td>
				</tr>
        	<?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>