<?php
/**
 * Vue de modification / ajout / duplication d'une champ (field)
 *
 *  Variables de la vue :
 * - form
 * - page
 * - document
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource field-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.4.7
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery('jquery-ui');
$this->headScript()->appendFile($this->basePath('/js/pdf/field-edit.js'));
$this->inlineScript()->captureStart();
?>
 $("#accordion").accordion();
 js_nature.init();
<?php
$this->inlineScript()->captureEnd();
// =============================================================================================
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmpdf', 
    [
        'action' => 'field-liste',
        'page' => $this->page
    ]);
$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Définition d'un champ d'un document</h1>
<ul>
	<li>Document: <?php echo $this->document['name'];?></li>
	<li>Source du document: <?php echo $this->document['recordSource'];?></li>
</ul>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<fieldset class="sbm-page1">
	   <?php
    echo $this->form()->openTag($this->form); // le formulaire doit avoir id="accordion" pour que ça marche
    echo $this->formHidden($this->form->get('docfieldId'));
    echo $this->formHidden($this->form->get('documentId'));
    echo $this->formHidden($this->form->get('name'));
    echo $this->formHidden($this->form->get('recordSource'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>

			<div id="accordion">
				<h3 id="data">Paramètres du champ</h3>
				<div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('ordinal_position'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('nature'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_width'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_align'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_stretch'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_precision'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_completion'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('filter'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('format'));?></div>
				</div>
				<h3 id="label">Paramètres du texte</h3>
				<div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('style'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('height'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_space'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_width'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_align'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_stretch'));?></div>
				</div>
				<h3 id="photo" style="display: none;">Paramètres pour une photo</h3>
				<div>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_x'));?></div>
					<p class="sbm-description">Une photo à gauche des lignes d'écriture
						sera obtenue par une abscisse négative.</p>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_y'));?></div>
					<p class="sbm-description">Une photo décalée vers le haut par
						rapport à la première ligne d'écriture sera obtenue par une
						ordonnée négative.</p>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_w'));?></div>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_h'));?></div>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_type'));?></div>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_align'));?></div>
					<div class="sbm-document-table"><?= $this->formRow($this->form->get('photo_resize'));?></div>
				</div>
			</div>
			<div id="pdf-edit-buttons" class="row-inner edit">
	    <?php echo $this->formSubmit($this->form->get('submit')); ?>
	    <?php echo $this->formSubmit($this->form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        </fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>