<?php
/**
 * Vue de la liste des champs (fields) d'un document pdf (hors présentation tabulaire)
 *
 * Actions possibles depuis cette vue :
 * - ajouter une colonne
 * - modifier une colonne
 * - dupliquer une colonne
 * - supprimer une colonne
 *  
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource field-liste.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_cancel = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_ajout = $this->url('sbmpdf', [
    'action' => 'field-ajout',
    'page' => $this->page
]);
$url_edit = $this->url('sbmpdf', [
    'action' => 'field-edit',
    'page' => $this->page
]);
$url_dupliquer = $this->url('sbmpdf',
    [
        'action' => 'field-dupliquer',
        'page' => $this->page
    ]);
$url_suppr = $this->url('sbmpdf', [
    'action' => 'field-suppr',
    'page' => $this->page
]);
// $url_retour = $this->url('sbmpdf');

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource'],
    'new_position' => count($this->data) + 1
];

$actions = [
    'homepdf' => [
        'class' => 'fam-door-out',
        'formaction' => $url_cancel,
        'title' => 'Liste des documents'
    ],
    /*'retour' => [
        'class' => 'fam-book-previous',
        'formaction' => $url_retour,
        'title' => 'Configuration du tableau'
    ],*/
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajout,
        'title' => 'Nouvelle colonne'
    ]
];

$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier la colonne'
    ],
    'dupliquer' => [
        'class' => 'fam-page-copy',
        'formaction' => $url_dupliquer,
        'title' => 'dupliquer la colonne'
    ],
    'supprimer' => [
        'class' => 'fam-delete',
        'formaction' => $url_suppr,
        'title' => 'supprimer la colonne'
    ]
];
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des champs contenus dans un document pdf (hors présentation
				tabulaire)</h1>
			<ul>
				<li>Document: <?= $this->document['name'];?></li>
				<li>Source du document: <?= $this->document['recordSource'];?></li>
			</ul>
			<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>N°</th>
					<th>Champ</th>
					<th>Largeur</th>
					<th>Alignement</th>
					<th>Libellé</th>
					<th>Largeur</th>
					<th>Hauteur</th>
					<th>Style</th>
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
            	<?php
                $hiddens['docfieldId'] = $row['docfieldId'];
                $hiddens['ordinal_position'] = $row['ordinal_position'];
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="ordinal_position">
						<?= $row['ordinal_position']; ?></td>
					<td class="fieldname">
						<?= $this->escapeHtml($row['fieldname']); ?></td>
					<td class="fieldname_width">
						<?= $row['fieldname_width']; ?></td>
					<td class="fieldname_align">
						<?= $row['fieldname_align']; ?></td>
					<td class="label">
						<?= $this->escapeHtml($row['label']); ?></td>
					<td class="label_width">
						<?= $row['label_width']; ?></td>
					<td class="height">
						<?= $row['height']; ?></td>
					<td class="style">
						<?= $this->escapeHtml($row['style']); ?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($row['docfieldId'], $hiddens, $buttons);?>
				    </td>
				</tr>
        <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>