<?php
/**
 * Page de suppression d'un champ dans un document pdf (hors présentation tabulaire)
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource field-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
?>
<h1>Suppression d'un champ dans un document Pdf (hors présentation
	tabulaire)</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du champ suivant :</p>
	<div class="header-wrapper">
		<ul>
			<li>Champ n° : <?= $this->data->ordinal_position; ?></li>
			<li>Champ : <?= $this->escapeHtml($this->data->fieldname); ?></li>
			<li>
			Libellé : <?= $this->data->label ?$this->escapeHtml($this->data->label) : '(sans étiquette)'; ?>
			</li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>