<?php
/**
 * Vue affichant la liste des documents pdf
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource pdf-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 juin 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$documents = $this->paginator->getCurrentItems();

$url_edit = $this->url('sbmpdf', [
    'action' => 'pdf-edit',
    'page' => $this->page
]);
$url_delete = $this->url('sbmpdf', [
    'action' => 'pdf-suppr',
    'page' => $this->page
]);
$url_dupliquer = $this->url('sbmpdf',
    [
        'action' => 'pdf-dupliquer',
        'page' => $this->page
    ]);
$url_apercu = $this->url('sbmpdf', [
    'action' => 'pdf-apercu',
    'page' => $this->page
]);
$url_ajouter = $this->url('sbmpdf', [
    'action' => 'pdf-ajout',
    'page' => $this->page
]);
$url_rapports = $this->url('sbmpdf', [
    'action' => 'pdf-pdf',
    'page' => $this->page
]);
$url_tableau = $this->url('sbmpdf', [
    'action' => 'table-liste',
    'page' => $this->page
]);
$url_affectation = $this->url('sbmpdf',
    [
        'action' => 'affectation-liste',
        'page' => $this->page
    ]);

$url_etiquette = $this->url('sbmpdf',
    [
        'action' => 'etiquette-liste',
        'page' => $this->page
    ]);
$url_texte = $this->url('sbmpdf', [
    'action' => 'texte-format',
    'page' => $this->page
]);
$url_retour = $this->url('sbmadmin');
$hiddens = [];
$menuImpression = $this->menuRapports('/pdf/pdf-liste', $url_rapports, 'fam-printer', null,
    $hiddens);
$hiddens = $menuImpression['hiddens'];
// die(var_dump($menuImpression));
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau document'
    ]
];
$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier'
    ],
    'disposition' => [],
    'dupliquer' => [
        'class' => 'fam-page-copy',
        'formaction' => $url_dupliquer,
        'title' => 'dupliquer'
    ],
    'supprimer' => [
        'class' => 'fam-delete',
        'formaction' => $url_delete,
        'title' => 'supprimer'
    ],
    'affecter' => [
        'class' => 'fam-page-link',
        'formaction' => $url_affectation,
        'title' => 'affecter'
    ],
    'apercu' => [
        'class' => 'fam-page-white-magnify',
        'formaction' => $url_apercu,
        'title' => 'aperçu',
        'formtarget' => '_blank'
    ]
];
?>

<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des documents pdf</h1>
			<div class="menu clearfix"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
			<?=$this->flashMessenger()->render('success');?>
			<?=$this->flashMessenger()->render('warning');?>
			<?=$this->flashMessenger()->render('error');?>
			<?=$this->flashMessenger()->render('info');?>
			<?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner pdf">
			<tbody>
				<tr class="petit">
					<th>Id</th>
					<th>Nom</th>
					<th>Source</th>
					<th>Filtre</th>
					<th>Ordre</th>
					<th>Format</th>
					<th title="Orientation">Or.</th>
					<th>Entête de doc.</th>
					<th>Fin de doc.</th>
					<th>Haut de page</th>
					<th>Pied de page</th>
					<th style="width: 110px;"></th>
				</tr>
            <?php

            foreach ($documents as $test => $doc) :
                ?>
                <?php
                $doc_title = $doc_footer = $page_title = $page_footer = '';
                if ($doc->docheader) {
                    $doc_title = 'title="' . $doc->title;
                    $tmp = $doc->docheader_subtitle;
                    if (! empty($tmp)) {
                        $doc_title .= "\n" . strip_tags($tmp);
                    }
                    $doc_title .= '"';
                }
                if ($doc->docfooter) {
                    $doc_footer = 'title="' . $doc->docfooter_title;
                    $tmp = $doc->docfooter_string;
                    if (! empty($tmp)) {
                        $doc_footer .= "\n" . strip_tags($tmp);
                    }
                    $doc_footer .= '"';
                }
                if ($doc->pageheader) {
                    $page_title = 'title="' . $doc->pageheader_title;
                    $tmp = $doc->pageheader_string;
                    if (! empty($tmp)) {
                        $doc_title .= "\n" . strip_tags($tmp);
                    }
                    $page_title .= '"';
                }
                if ($doc->pagefooter) {
                    $page_footer = 'title="' . $doc->pagefooter_string . '"';
                }
                switch ($doc->disposition) {
                    case 'Tabulaire':
                        $buttons['disposition'] = [
                            'class' => 'fam-table-edit',
                            'formaction' => $url_tableau,
                            'title' => 'configuration et contenu du tableau inclus dans le document'
                        ];
                        break;
                    case 'Etiquette':
                        $buttons['disposition'] = [
                            'class' => 'fam-table-edit',
                            'formaction' => $url_etiquette,
                            'title' => 'configuration et contenu des étiquettes'
                        ];
                        break;
                    default: // Texte
                        $buttons['disposition'] = [
                            'class' => 'fam-table-edit',
                            'formaction' => $url_texte,
                            'title' => 'configuration et contenu du texte'
                        ];
                        break;
                }
                $hiddens = [
                    'documentId' => $doc->documentId,
                    'name' => $doc->name,
                    'ordinal_table' => 1,
                    'recordSource' => $doc->recordSource
                ];
                ?>
                <tr class="petit <?=$this->cycle(["even","odd"])->next();?>">
					<td class="documentId"><?=$doc->documentId;?></td>
					<td class="name"><?=$this->escapeHtml($doc->name);?></td>
					<td class="recordSource">
						<div style="max-width: 400px;">
							<?=nl2br($this->escapeHtml($doc->recordSource));?>
						</div>
					</td>
					<td class="filter">
						<?=$this->escapeHtml($doc->filter);?></td>
					<td class="orderBy">
						<?=$this->escapeHtml($doc->orderBy);?></td>
					<td class="pdf_page_format">
						<?=$doc->page_format;?></td>
					<td class="pdf_page_orientation">
						<?=$doc->page_orientation;?></td>
					<td class="docheader" <?=$doc_title;?>>
						<?=$doc->docheader ? 'Oui' : '';?></td>
					<td class="docfooter" <?=$doc_footer;?>>
						<?=$doc->docfooter ? 'Oui' : '';?></td>
					<td class="pageheader" <?=$page_title;?>>
						<?=$doc->pageheader ? 'Oui' : '';?></td>
					<td class="pagefooter" <?=$page_footer;?>>
						<?=$doc->pagefooter ? 'Oui' : '';?></td>
					<td class="boutons">
                		<?=$this->listeLigneActions($doc->documentId, $hiddens, $buttons);?>
				    </td>
				</tr>
        <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?=$this->paginationControl($this->paginator,'Sliding','sbm/pagination',[]);?></div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
	    </div>
	</div>
</div>
