<?php
/**
 * Cette vue présente la liste des 3 parties d'un tableau dans un document pdf (thead, tbody, tfoot)
 * 
 * Variables de cette vue :
 * - data
 * - page
 * - document
 *
 * Depuis cette liste, il est possible de mettre en forme chaque partie et d'accéder à la liste des colonnes.
 * Il n'y a pas de bouton suppression car les parties sont détruites en cascade lorsqu'on demande la suppression du document.
 * Par contre, si elles ne sont pas utilisées, il suffit de les déclarer non visible dans la configuration.
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource table-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$js = 'window.document.getElementById(\'op\').value=%s;';

$url_cancel = $this->url('sbmpdf', [
    'action' => 'pdf-liste',
    'page' => $this->page
]);
$url_edit = $this->url('sbmpdf', [
    'action' => 'table-edit',
    'page' => $this->page
]);
$url_colonne = $this->url('sbmpdf', [
    'action' => 'colonne-liste',
    'page' => $this->page
]);
$retour = $this->url('sbmpdf', [
    'action' => 'pdf-edit',
    'page' => $this->page
]);

$hiddens = [
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'ordinal_table' => $this->document['ordinal_table'],
    'recordSource' => $this->document['recordSource']
];
$actions = [
    'homepdf' => [
        'class' => 'fam-door-out',
        'formaction' => $url_cancel,
        'title' => 'Liste des documents',
        'onclick' => sprintf($js, "'retour'")
    ],
    'retour' => [
        'class' => 'fam-book-previous',
        'formaction' => $retour,
        'title' => 'Configuration du document'
    ],
    'colonnes' => [
        'formaction' => $url_colonne,
        'class' => 'button default',
        'value' => 'Liste des colonnes',
        'title' => 'Définition et mise en forme des colonnes'
    ]
];
$buttons = [
    'modifier' => [
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier'
    ]
];
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des sections d'un tableau pour un document pdf</h1>
			<ul>
				<li>Document: <?= $this->document['name'];?></li>
				<li>Numéro du tableau: <?= $this->document['ordinal_table'];?></li>
				<li>Source du document: <?= $this->document['recordSource'];?></li>
			</ul>
			<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>Section</th>
					<th>Description</th>
					<th>Visible</th>
					<th>Largeur</th>
					<th>Hauteur<br />de ligne
					</th>
					<th></th>
				</tr>
            <?php foreach($data as $section => $row): ?>
            	<?php
                $hiddens = [
                    'doctableId' => $row['doctableId'],
                    'documentId' => $row['documentId'],
                    'name' => $this->document['name'],
                    'ordinal_table' => $row['ordinal_table'],
                    'recordSource' => $this->document['recordSource']
                ];
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="section"><?= $this->escapeHtml($row['section']); ?></td>
					<td class="description"><?= $this->escapeHtml($row['description']); ?></td>
					<td class="visible"><?= $row['visible'] ? 'Oui' : 'Non'; ?></td>
					<td class="width"><?= $row['width']; ?></td>
					<td class="row_height"><?= $row['row_height']; ?></td>
					<td class="boutons">
                <?= $this->listeLigneActions($row['doctableId'], $hiddens, $buttons);?>
                
				    </td>
				</tr>         
        	<?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>
