<?php
/**
 * Statistiques par circuit
 *
 * Ce modèle est utilisé dans les actions tousParCircuit, internetParCircuit et fichePapierParCircuit
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-destion/statistiques
 * @filesource par-circuit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 nov. 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/statistiques');
$n = $this->millesime;
$as0 = sprintf('%d-%d', $n, $n + 1);
$as1 = sprintf('%d-%d', $n - 1, $n);
$totaux = array(
    'annee_courante' => array(
        'inscrits' => 0,
        'internet' => 0,
        'papier' => 0
    ),
    'annee_precedente' => array(
        'inscrits' => 0,
        'internet' => 0,
        'papier' => 0
    )
);
?>
<h1>Effectifs des élèves transportés par circuit</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
		<?php
echo $this->listeZoneActions(array(), array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
));
?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="statistiques">
			<thead>
				<tr>
					<th rowspan="2">Circuit</th>
					<th colspan="3" class="border-bold centre">Année <?php echo $as1;?></th>
					<th colspan="3" class="border-bold centre">Année <?php echo $as0;?></th>
				</tr>
				<tr>
					<th class="centre border-bold">Inscrits par<br>internet
					</th>
					<th class="centre">Inscrits par<br>fiche papier
					</th>
					<th class="centre">Tous les<br>élèves
					</th>
					<th class="centre border-bold">Inscrits par<br>internet
					</th>
					<th class="centre">Inscrits par<br>fiche papier
					</th>
					<th class="centre">Tous les<br>élèves
					</th>
				</tr>
			</thead>
			<tbody>
				<?php for ($i = 0; $i < count($this->statistiques['annee_courante']); $i++):?>
				<?php
        // année précédente
        $inscrits_a_p = $this->statistiques['annee_precedente'][$i]['inscrits'] ?  : 0;
        $totaux['annee_precedente']['inscrits'] += $inscrits_a_p;
        $internet_a_p = $this->statistiques['annee_precedente'][$i]['internet'] ?  : 0;
        $totaux['annee_precedente']['internet'] += $internet_a_p;
        $papier_a_p = $this->statistiques['annee_precedente'][$i]['papier'] ?  : 0;
        $totaux['annee_precedente']['papier'] += $papier_a_p;
        // année courante
        $inscrits_a_c = $this->statistiques['annee_courante'][$i]['inscrits'] ?  : 0;
        $totaux['annee_courante']['inscrits'] += $inscrits_a_c;
        $internet_a_c = $this->statistiques['annee_courante'][$i]['internet'] ?  : 0;
        $totaux['annee_courante']['internet'] += $internet_a_c;
        $papier_a_c = $this->statistiques['annee_courante'][$i]['papier'] ?  : 0;
        $totaux['annee_courante']['papier'] += $papier_a_c;
        ?>
				<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td><?php echo $this->statistiques['annee_courante'][$i]['nom'];?></td>
					<td class="border-bold align-right"><?php echo $internet_a_p;?></td>
					<td class=" align-right"><?php echo $papier_a_p;?></td>
					<td class=" align-right"><?php echo $inscrits_a_p;?></td>
					<td class="border-bold align-right"><?php echo $internet_a_c;?></td>
					<td class=" align-right"><?php echo $papier_a_c;?></td>
					<td class=" align-right"><?php echo $inscrits_a_c;?></td>
				</tr>
				<?php endfor;?>
			</tbody>
			<tr>
				<th>Total</th>
				<th class="invisible"></th>
				<th class="border-bold align-right"><?php echo $totaux['annee_precedente']['internet'];?></th>
				<th class=" align-right"><?php echo $totaux['annee_precedente']['papier'];?></th>
				<th class=" align-right"><?php echo $totaux['annee_precedente']['inscrits'];?></th>
				<th class="border-bold align-right"><?php echo $totaux['annee_courante']['internet'];?></th>
				<th class=" align-right"><?php echo $totaux['annee_courante']['papier'];?></th>
				<th class=" align-right"><?php echo $totaux['annee_courante']['inscrits'];?></th>
			</tr>
			<tfoot>
			</tfoot>
		</table>
	</div>
	<div id="liste-footer">
		<p class="sbm-description">Dans ce tableau, chaque élève n'est compté
			qu'une seule fois dans chaque circuit sur lequel il est inscrit.</p>
	</div>
</div>