<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SbmParent\Module'                      => __DIR__ . '/Module.php',
    'SbmParent\Controller\ConfigController' => __DIR__ . '/src/SbmParent/Controller/ConfigController.php',
    'SbmParent\Controller\IndexController'  => __DIR__ . '/src/SbmParent/Controller/IndexController.php',
    'SbmParent\Form\Enfant'                 => __DIR__ . '/src/SbmParent/Form/Enfant.php',
    'SbmParent\Form\Responsable2'           => __DIR__ . '/src/SbmParent/Form/Responsable2.php',
    'SbmParent\Model\Exception'             => __DIR__ . '/src/SbmParent/Model/Exception.php',
    'SbmParent\Model\Responsable'           => __DIR__ . '/src/SbmParent/Model/Responsable.php',
);
