<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SbmParent\Module'                                     => __DIR__ . '/Module.php',
    'SbmParent\Controller\ConfigController'                => __DIR__ . '/src/SbmParent/Controller/ConfigController.php',
    'SbmParent\Controller\IndexController'                 => __DIR__ . '/src/SbmParent/Controller/IndexController.php',
    'SbmParent\Controller\Service\ConfigControllerFactory' => __DIR__ . '/src/SbmParent/Controller/Service/ConfigControllerFactory.php',
    'SbmParent\Controller\Service\IndexControllerFactory'  => __DIR__ . '/src/SbmParent/Controller/Service/IndexControllerFactory.php',
    'SbmParent\Form\AbstractResponsable2'                  => __DIR__ . '/src/SbmParent/Form/AbstractResponsable2.php',
    'SbmParent\Form\Enfant'                                => __DIR__ . '/src/SbmParent/Form/Enfant.php',
    'SbmParent\Form\Responsable2Complet'                   => __DIR__ . '/src/SbmParent/Form/Responsable2Complet.php',
    'SbmParent\Form\Responsable2Restreint'                 => __DIR__ . '/src/SbmParent/Form/Responsable2Restreint.php',
    'SbmParent\Form\Service\EnfantFactory'                 => __DIR__ . '/src/SbmParent/Form/Service/EnfantFactory.php',
);
