<?php
/**
 * Partial pour pagination
 *
 *
 * @project sbm
 * @package SbmCommun/view/partial
 * @filesource pagination.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 27 sept. 2018
 * @version 2019-2.5.0
 */
$firstClassCss = 'first';
$previousClassCss = 'previous';
$nextClassCss = 'next';
$lastClassCss = 'last';
if (! isset($this->previous)) {
    $firstClassCss .= ' disabled';
    $previousClassCss .= ' disabled';
}
if (! isset($this->next)) {
    $nextClassCss .= ' disabled';
    $lastClassCss .= ' disabled';
}
?>
<?php if (1 < (int) $this->pageCount) :?>
<div class="pagination">
	<span class="nbItems">Il y a <?= $this->totalItemCount;?> enregistrements</span>
	<a
		href="<?= $this->url($this->route, ['page' => $this->first], false, true); ?>"
		class="<?= $firstClassCss; ?>"><i class="fam-resultset-first"></i></a>
	<a
		href="<?= $this->url($this->route, ['page' => $this->previous], false, true); ?>"
		class="<?= $previousClassCss; ?>"><i class="fam-resultset-previous"></i></a>
<?php foreach ($this->pagesInRange as $p) :?>
    <?php if ($p == $this->current) : ?>
            <span class="current"><?= $p;?>/<?= $this->pageCount;?></span>
    <?php else : ?>  
            <a
		href="<?= $this->url($this->route, ['page' => $p], false, true);?>" class="page"><?= $p;?></a>
    <?php endif;?>
<?php endforeach;?>
        <a
		href="<?= $this->url($this->route, ['page' => $this->next], false, true); ?>"
		class="<?= $nextClassCss; ?>"><i class="fam-resultset-next"></i></a> <a
		href="<?= $this->url($this->route, ['page' => $this->last], false, true); ?>"
		class="<?= $lastClassCss; ?>"><i class="fam-resultset-last"></i></a>
</div>
<?php else:?>
<div class="pagination">
	<span class="current">Il y a <?= $this->totalItemCount;?> enregistrements</span>
</div>
<?php endif;?>