<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 *
 * @project sbm
 * @package
 * @filesource carte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 oct. 2020
 * @version 2020-2.6.0
 */
$aMarkers = [];
foreach ($this->ptStations as $pt) {
    $station = $pt->getAttribute('station');
    $d = [
        '<b>' . $this->escapeHtml($station->nom) . '</b>',
        $this->escapeHtml($station->alias),
        implode(' ', [
            $station->codePostal,
            $station->lacommune
        ])
    ];
    $desservie = false;
    $aServices = [];
    foreach ($station->services as $service) {
        if ($service->ligneId) {
            $aServices[] = explode(' ', $service->service);
            $desservie = true;
        }
    }
    if ($desservie && $station->ouverte) {
        // $color = "#00ff00";
        $color = "green";
        $text = 'O';
        $nature = "ouverte";
        $index = 'ouvert';
    } elseif ($station->ouverte) {
        // $color = "#ffff00";
        $color = "yellow";
        $text = 'N';
        $nature = "non desservie";
        $index = "nonDesservi";
    } else {
        // $color = "#ff0000";
        $color = "red";
        $text = 'F';
        $nature = "fermée";
        $index = "ferme";
    }
    $d[] = 'Station ' . $nature;
    if (count($aServices)) {
        $table = '<table>';
        foreach ($aServices as $ligne) {
            $table .= '<tr><td>' . implode('</td><td>', $ligne) . '</td></tr>';
        }
        $table .= '</table>';
    }
    if ($pt->getAttribute('color') == 'current') {
        // $color = "#FFA500";
        $color = "purple";
        $text = 'A';
    }
    $aMarkers[$index][] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'color' => $color,
        'text' => $text,
        'title' => $station->lacommune . ' - ' . $station->nom,
        'info' => implode('<br>', array_filter($d)) . $table
    ];
}
$carte_init_parametres = sprintf('"%s","%s","%s",%f,%f,%d,%s', 'stationcheckbox',
    'carte-inner', $this->scheme, $this->config['centre']['lat'],
    $this->config['centre']['lng'], $this->config['zoom'], json_encode($aMarkers));
$this->headStyle()->captureStart();
?>
#carte-inner {
    width: 90%;
    height: 500px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 20px;
    margin-bottom: 20px;
}
<?php
$this->headStyle()->captureEnd();
$this->headScript()->prependFile($this->url_api);
$this->JQuery();
$this->ThemeJs('commun', 'carte.js');
$this->headScript()->captureStart();
?>
carte.init(<?=$carte_init_parametres;?>);
<?php
$this->headScript()->captureEnd();
?>
<h1>Points d'arrêt</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="menu float-left">
		<?= $this->listeZoneActions($hiddens,$actions);?>
		</div>
		<div>
			Choix des points d'arrêt sur la carte : <input name="stationcheckbox"
				type="checkbox" checked value="ouvert">Ouverts <input
				name="stationcheckbox" type="checkbox" checked value="ferme">Fermés
			<input name="stationcheckbox" type="checkbox" checked
				value="nonDesservi">Non desservis
		</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;">
	</div>
	<div class="float-right right-10px sbm-description">
		<ul>
			<li><?= implode('</li><li>', $legende) ?></li>
		</ul>

	</div>
</div>