<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DafapMail\Module'                     => __DIR__ . '/Module.php',
    'DafapMail\Controller\IndexController' => __DIR__ . '/src/DafapMail/Controller/IndexController.php',
    'DafapMail\Form\Mail'                  => __DIR__ . '/src/DafapMail/Form/Mail.php',
    'DafapMail\Model\EnvoiMail'            => __DIR__ . '/src/DafapMail/Model/EnvoiMail.php',
    'DafapMail\Model\Exception'            => __DIR__ . '/src/DafapMail/Model/Exception.php',
    'DafapMail\Model\Template'             => __DIR__ . '/src/DafapMail/Model/Template.php',
);
