<?php
// Generated by Zend Framework 2
return array(
    'DafapMail\Module'                                    => __DIR__ . '/Module.php',
    'DafapMail\Controller\IndexController'                => __DIR__ . '/src/DafapMail/Controller/IndexController.php',
    'DafapMail\Controller\Service\IndexControllerFactory' => __DIR__ . '/src/DafapMail/Controller/Service/IndexControllerFactory.php',
    'DafapMail\Form\Mail'                                 => __DIR__ . '/src/DafapMail/Form/Mail.php',
    'DafapMail\Model\EnvoiMail'                           => __DIR__ . '/src/DafapMail/Model/EnvoiMail.php',
    'DafapMail\Model\Exception'                           => __DIR__ . '/src/DafapMail/Model/Exception.php',
    'DafapMail\Model\Service\ConfigServiceFactory'        => __DIR__ . '/src/DafapMail/Model/Service/ConfigServiceFactory.php',
    'DafapMail\Model\Service\EnvoiMailFactory'            => __DIR__ . '/src/DafapMail/Model/Service/EnvoiMailFactory.php',
    'DafapMail\Model\Template'                            => __DIR__ . '/src/DafapMail/Model/Template.php',
);