<p>Du %2$s au %4$s en inscrivant vos enfants par internet vous b&eacute;n&eacute;ficiez d'un tarif r&eacute;duit.&nbsp;</p>
<p>En cas de garde altern&eacute;e, du %2$s au %4$s une seconde carte de transport sera d&eacute;livr&eacute;e gratuitement &agrave; votre demande. Pass&eacute; cette date, le tarif normal sera appliqu&eacute;.</p>
<p><strong>INSCRIPTIONS</strong></p>
<ol>
<li class=""><strong>Si vous aviez d&eacute;j&agrave; inscrit vos enfants l'an dernier,</strong> cliquez sur <strong><span style="color: #ff6600;">Mot de passe oubli&eacute;</span></strong>&nbsp;dans le cadre <strong>Identifiez-vous</strong>, remplissez le formulaire et vous recevrez la proc&eacute;dure &agrave; suivre dans votre messagerie. <strong>Sinon cr&eacute;ez votre compte parent</strong> et confirmez votre activation de compte dans votre messagerie mail. Si vous ne recevez rien, pensez &agrave; regarder dans votre boite de Spam.</li>
<li class="">Cr&eacute;ez votre fiche parentale</li>
<li><strong>Pour chacun de vos enfants &agrave; transporter</strong>, remplissez le formulaire et transmettez leur photo</li>
<li><div id="content-tarif" style="display: none;">
<p>Les tarifs du PASS ANNUEL JUNIOR d&eacute;pendent du lieu de r&eacute;sidence de votre enfant :</p>
<table class="grille-tarifs">
<tbody>
<tr>
<th class="none" colspan="2" rowspan="2">&nbsp;</th>
<th colspan="4">TARIF PAR ENFANT</th>
</tr>
<tr>
<th>1<sup>er</sup></th>
<th>2<sup>e</sup></th>
<th>3<sup>e</sup></th>
<th>4<sup>e</sup> &amp; +</th>
</tr>
<tr>
<td rowspan="2">R&eacute;sidents&nbsp;Arlys&egrave;re</td>
<td>Tarif normal</td>
<td class="centre">165 &euro;</td>
<td class="centre">165 &euro;</td>
<td class="centre">83 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td>Tarif r&eacute;duit <span class="orange">*</span></td>
<td class="centre">110 &euro;</td>
<td class="centre">110 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td colspan="2">R&eacute;sidents et point de mont&eacute;e hors Arlys&egrave;re</td>
<td class="centre">200 &euro;</td>
<td class="centre">200 &euro;</td>
<td class="centre">100 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td rowspan="2">RPI &eacute;cole &agrave; &eacute;cole</td>
<td>Tarif normal</td>
<td class="centre">82,50 &euro;</td>
<td class="centre">82,50 &euro;</td>
<td class="centre">41,50 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td>Tarif r&eacute;duit <span class="orange">*</span></td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">28 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td rowspan="2">Double domiciliation (2<sup>e</sup> carte Garde altern&eacute;e)</td>
<td>jusqu'au 10/07</td>
<td colspan="4" class="centre">gratuit</td>
</tr>
<tr>
<td>&agrave; partir du 11/07</td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td colspan="2">Duplicata</td>
<td class="centre" colspan="4">15 &euro;</td>
</tr>
</tbody>
</table>
<p><strong><span class="orange">*</span> Le tarif r&eacute;duit est consenti exclusivement &agrave; la condition suivante :</strong></p>
<ul>
<li><strong>si</strong> l'inscription est effectu&eacute;e entre le %2$s et le %3$s inclus</li>
<li><strong>ou si</strong> l'&eacute;l&egrave;ve n'a jamais voyag&eacute; avec un abonnement annuel TRA sur le territoire de Arlys&egrave;re</li>
<li><strong>ou si</strong> un changement de domiciliation est av&eacute;r&eacute; apr&egrave;s le %3$s (justificatif &agrave; fournir)</li>
<li><strong>ou si</strong> l'insciption de l'&eacute;l&egrave;ve dans l'&eacute;tablissement scolaire est av&eacute;r&eacute;e apr&egrave;s le %3$s (justificatif &agrave; fournir)</li>
</ul>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<div id="content-payer" style="display: none;">
<p>Paiement de l'abonnement</p>
<ul>
<li><strong>Par carte bleue <span class="orange">*</span></strong> uniquement sur le site internet au moment de l'inscription.</li>
<li><strong>Par ch&egrave;que <span class="orange">**</span></strong> &agrave; libeller &agrave; <strong>TRANSDEV ALBERTVILLE</strong>.</li>
<li><strong>En esp&egrave;ces,</strong> au POINT INFO BUS, Place de la Gare &agrave; Albertville durant les heures d'ouverture.</li>
</ul>
<div style="display:table;">
<div style="display: table-row; margin-top: 4px;">
<div style="display:table-cell"><span class="orange">*</span></div>
<div style="display:table-cell">Facilit&eacute; de paiement en 3 fois</div>
</div>
<div style="display: table-row; margin-top: 4px;">
<div style="display:table-cell"><span class="orange">**</span></div>
<div style="display:table-cell">Facilit&eacute; de paiement en 3 fois : contacter le POINT INFO BUS<br>IMPORTANT : mentionner au dos du ch&egrave;que :<ul><li>le nom du responsable l&eacute;gal</li><li>le nom de l'&eacute;l&egrave;ve</li></ul></div>
</div>
</div>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<strong>&Agrave; la fin de l'inscription en ligne de votre/vos enfants</strong>, vous devez r&eacute;gler le PASS ANNUEL JUNIOR selon <span id="help-tarif" class="cursor-help orange">la grille tarifaire<em class="fam-help">&nbsp;</em></span> et les <span id="help-payer" class="cursor-help orange">modalités de r&egrave;glement en vigueur<em class="fam-help">&nbsp;</em></span></li>
<li>Votre demande sera valid&eacute;e une fois le paiement effectu&eacute;</li>
<li>Vous recevrez les PASS ANNUEL JUNIOR par voie postale &agrave; l'adresse indiqu&eacute;e &agrave; partir du %13$s.</li>
</ol>
<p>Pour en savoir plus :</p>
<ul>
<li>
<div id="content-2019" style="display: none;">
<p>Si votre enfant avait d&eacute;j&agrave; un abonnement PASS ANNUEL SCOLAIRE en 2019-2020, vous ne devez pas cr&eacute;er votre compte, c'est d&eacute;j&agrave; fait !</p>
<ul><li>Cliquez sur lien <span class="orange"><strong>Mot de passe oubli&eacute;</strong></span> et remplissez le formulaire en utilisant <strong>la m&ecirc;me adresse mail que l'an dernier</strong> puis suivez les instructions qui vous seront adress&eacute;es.
</li><li><strong>En cas de changement d'adresse mail</strong>, prenez contact avec le POINT INFO BUS pour faire enregistrer votre nouvelle adresse.</li></ul>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<span id="help-2019" class="cursor-help orange"><strong>&Eacute;l&egrave;ves inscrits sur le r&eacute;seau TRA MOBILIT&Eacute; en 2019-2020&nbsp;<em class="fam-help">&nbsp;</em> </strong></span></li>
<li>
<div id="content-horszone" style="display: none;">
<p>Si votre enfant est scolaris&eacute; en dehors du territoire d'Arlys&egrave;re (&agrave; l'exception des 2 coll&egrave;ges de M&eacute;g&egrave;ve) :</p>
<ul>
<li>S'il doit emprunter le r&eacute;seau TRA MOBILIT&Eacute; pour se rendre &agrave; la Gare routi&egrave;re d'Albertville, indiquez comme &eacute;tablissement scolaire lors de son inscription : &Eacute;TABLISSEMENT HORS ARLYS&Egrave;RE PAR ALBERTVILLE.</li>
<li>S'il doit emprunter le r&eacute;seau TRA MOBILIT&Eacute; pour se rendre &agrave; la Gare routi&egrave;re d'Ugine, indiquez comme &eacute;tablissement scolaire lors de son inscription : &Eacute;TABLISSEMENT HORS ARLYS&Egrave;RE PAR UGINE.</li>
<li>Pour les autres cas, conformez-vous aux instructions publi&eacute;es sur le site de la <a href="%10$s" target="_blank">R&eacute;gion Auvergne-Rh&ocirc;ne-Alpes</a>.</li>
</ul>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<span id="help-horszone" class="cursor-help orange"><strong>&Eacute;l&egrave;ve scolaris&eacute; en dehors du territoire d'Arlys&egrave;re&nbsp;</strong><em class="fam-help">&nbsp;</em></span></li>
</ul>
<p>Pour tout autre renseignement, adressez-vous directement &agrave; TRA MOBILIT&Eacute; :</p>
<div>
<ul>
	<li style='list-style-type: "\00261B"'><strong>Point Info Bus</strong>, Place de la Gare à Albertville / 04.79.89.77.32 - info-tra&#64;transdev.com</li>
	<li style='list-style-type: none'>du lundi au vendredi, de 9h &agrave; 12h et de 15h
	&agrave; 17h45 et le samedi de 9h &agrave; 12h</li>
</ul>
</div>