<?php
/**
 * Page de création de la fiche du parent responsable
 *
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/config
 * @filesource create.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery('jquery-ui');
$this->themeJS('commun', 'form-responsable.js');
$hiddens = [];
$actions = [];
?>
<div id="winpopup">
	<div id="winpopup-content"
		style="margin-left: 30px; margin-right: 30px;"></div>
</div>
<div class="flashMessenger float-right">
	<?= $this->flashMessenger()->render('success');?>
	<?= $this->flashMessenger()->render('warning');?>
	<?= $this->flashMessenger()->render('error');?>
	<?= $this->flashMessenger()->render('info');?>
	<?= $this->flashMessenger()->render('default');?>
</div>
<h1>Création de la fiche du responsable</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('responsableId'));?>
		<?= $this->formHidden($this->form->get('userId'));?>
		<?= $this->formHidden($this->form->get('nature'));?>
		<?= $this->formHidden($this->form->get('titre'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
		<?php
$elementTitre = new \Zend\Form\Element\Text('titre');
$elementTitre->setValue($this->identity['titre'])
    ->setAttributes(
    [
        'id' => 'titre1-readonly',
        'class' => 'sbm-width-10c',
        'readonly' => 'readonly'
    ])
    ->setOptions([
    'label' => 'Identité du responsable'
]);

?>
    	<fieldset class="sbm-page1">
			<div id="responsable-edit-email" class="row-inner edit">
				<?= $this->formRow($this->form->get('email')); ?></div>
			<div id="responsable-edit-ligne1" class="clearfix">
				<div id="responsable-edit-titre" class="row-inner edit float-left">
					<?= $this->formRow($elementTitre); ?></div>
				<div id="responsable-edit-nom" class="row-inner edit float-left">
					<?= $this->formRow($this->form->get('nom')); ?></div>
				<div id="responsable-edit-prenom" class="row-inner edit float-left">
					<?= $this->formRow($this->form->get('prenom')); ?></div>
			</div>
			<div id="responsable-edit-ligne2" class="clearfix">
				<div id="responsable-edit-titre2" class="row-inner edit float-left">
					<?= $this->formRow($this->form->get('titre2')); ?></div>
				<div id="responsable-edit-nom2" class="row-inner edit float-left">
					<?= $this->formRow($this->form->get('nom2')); ?></div>
				<div id="responsable-edit-prenom2" class="row-inner edit float-left">
					<?= $this->formRow($this->form->get('prenom2')); ?></div>
			</div>
			<div id="wrapper-telephones" class="row-inner edit clearfix">
				<div id="wrapper-telephone-numbers" class="float-left">
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneF'));?></div>
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneP'));?></div>
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneT'));?></div>
				</div>
				<?php if ($this->layout()->hassbmservicesms) :?>
				<div id="wrapper-acceptsms" class="left-20px float-left">
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsF'));?></div>
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsP'));?></div>
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsT'));?></div>
				</div>
				<?php endif;?>
			</div>
			<div id="responsable-edit-adresseL1" class="row-inner edit">
				<?= $this->formRow($this->form->get('adresseL1')); ?></div>
			<div id="responsable-edit-adresseL2" class="row-inner edit">
				<?= $this->formRow($this->form->get('adresseL2')); ?></div>
			<div id="responsable-edit-codePostal" class="row-inner edit">
				<?= $this->formRow($this->form->get('codePostal')); ?></div>
			<div id="responsable-edit-communeId" class="row-inner edit">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="responsable-edit-buttons" class="row-inner edit">
				<?= $this->formSubmit($this->form->get('submit')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>
<div id="help-r2-content" class="invisible">
	<p>Il s'agit de personnes vivant en couple à la même adresse,
		responsables des enfants qui vont être inscrits.</p>
	<p>Si les deux personnes ont le même nom, indiquez seulement le prénom
		de la deuxième.</p>
	<p></p>
	<h3>Attention !</h3>
	<p>Il ne s'agit pas de responsables d'enfants en garde alternée. Pour
		ces cas particuliers, l'information sera demandée au moment de
		l'inscription des enfants.</p>
</div>