<?php
/**
 * Liste des responsables ayant le même nom et le même prénom que l'utilisateur.
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/config
 * @filesource existe.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
$url_create = $this->url('sbmparentconfig', [
    'action' => 'create'
]);
$id_ligne = 1;
$boutons_ligne = [
    'cmoi' => [
        'class' => 'button ligne',
        'formaction' => $url_create,
        'value' => 'Je suis cette personne'
    ]
];
$bouton_autre = [
    'nouveau' => [
        'class' => 'button ligne',
        'formaction' => $url_create,
        'value' => 'Je suis une autre personne'
    ]
];
$autre = [
    'titre' => $this->identity['titre'],
    'nom' => $this->identity['nom'],
    'prenom' => $this->identity['prenom'],
    'email' => $this->identity['email']
]?>
<h1>Création de la fiche du responsable</h1>
<div id="liste-wrapper">
	<div id="liste-header"></div>
	<div id="liste-inner">
		<table>
			<tbody>
	        <?php foreach ($this->data as $responsable):?>
	        <?php
            $hiddens = [
                'responsableId' => $responsable->responsableId,
                'userId' => $responsable->userId,
                'nature' => $responsable->nature,
                'titre' => $responsable->titre,
                'nom' => $responsable->nom,
                'prenom' => $responsable->prenom,
                'titre2' => $responsable->titre2,
                'nom2' => $responsable->nom2,
                'prenom2' => $responsable->prenom2,
                'adresseL1' => $responsable->adresseL1,
                'adresseL2' => $responsable->adresseL2,
                'codePostal' => $responsable->codePostal,
                'communeId' => $responsable->communeId,
                'telephoneF' => $responsable->telephoneF,
                'telephoneP' => $responsable->telephoneP,
                'telephoneT' => $responsable->telephoneT,
                'email' => $this->identity['email']
            ];
            ?>
	            <tr class='<?= $this->cycle(['even', 'odd'])->next();?>'>
					<td>
	                <?= sprintf('%s %s %s', $responsable->titre, $responsable->nom, $responsable->prenom);?>
	                <br>
	                <?php $adresse = implode(' ', [$responsable->adresseL1, $responsable->adresseL2]);?>
	                <?= sprintf('%s %s %s', $adresse, $responsable->codePostal, $responsable->commune);?>
	                </td>
					<td><?= $this->listeLigneActions($id_ligne++, $hiddens, $boutons_ligne);?></td>
				</tr>
	        <?php endforeach;?>
	        </tbody>
		</table>
		<p><?= $this->listeLigneActions($id_ligne++, $autre, $bouton_autre);?></p>
	</div>
	<div id="liste-footer"></div>
</div>