<?php
/**
 * Page présentant une carte interactive aux parents
 *
 * Un clic sur la carte pour placer ou déplacer le repère de l'emplacement du domicile
 * 
 * @project sbm
 * @package SbmParent/view/sbm-parent/config
 * @filesource localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 mai 2016
 * @version 2016-2.1.1
 */
// calcul du contenu de l'infobulle et du libellé du domicile
$description = array();
$description[] = '<b>' . implode(' ', array(
    $this->responsable->titre,
    $this->responsable->nom,
    $this->responsable->prenom
)) . '</b>';
$description[] = $this->responsable->adresseL1;
$domicile = $this->responsable->adresseL1;
$tmp = $this->responsable->adresseL2;
if (! empty($tmp)) {
    $description[] = $this->responsable->adresseL2;
    $domicile .= ' ' . $this->responsable->adresseL2;
}
$cp_commune = implode(' ', array(
    $this->responsable->codePostal,
    $this->responsable->commune
));
$description[] = $cp_commune;
$domicile .= ' ' . $cp_commune;
$telephone = array();
$tmp = $this->responsable->telephoneF;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneF;
}
$tmp = $this->responsable->telephoneP;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneP;
}
$tmp = $this->responsable->telephoneT;
if (! empty($tmp)) {
    $telephone[] = $this->responsable->telephoneT;
}
$tel = implode(' ', $telephone);
if (! empty($tel)) {
    $description[] = 'Tel.' . $tel;
}
$description[] = $this->responsable->email;
// mise en place des JS de googleMaps
$this->headScript()->appendFile('https://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->captureStart();
?>
var marker;
function initialiser() {
    var latlng = new google.maps.LatLng(<?php echo $this->config['centre']['lat'];?>, <?php echo $this->config['centre']['lng'];?>);
    // initialisation des paramètres de la carte
    var options = {
        center: latlng,
        zoom: <?php echo $this->config['zoom'];?>,
        //mapTypeId: google.maps.MapTypeId.ROADMAP
        mapTypeId: "OSM",
        mapTypeControl: true,
        mapTypeControlOptions: {
            mapTypeIds: [
                "OSM",
                //google.maps.MapTypeId.ROADMAP, 
                //google.maps.MapTypeId.SATELLITE, 
                google.maps.MapTypeId.HYBRID, 
                google.maps.MapTypeId.TERRAIN
            ],
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        streetViewControl: true
    };
    var carte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // define OSM map type pointing at the OpenStreetMap tile server
    carte.mapTypes.set("OSM", new google.maps.ImageMapType({
        getTileUrl: function(coord, zoom) {
            return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
        },
        tileSize: new google.maps.Size(256,256),
        name: "OpenStreetMap",
        maxZoom: 18,
        opacity: 1,
        alt: "Carte OpenStreetMap"
    }));
    // initialisation du marker
    var optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(document.getElementById('lat').value, document.getElementById('lng').value),
        title: 'mon domicile'
    }
    marker = new google.maps.Marker(optionsMarqueur);
    
    var contentMarker = "<?php echo implode('<br/>', $description);?>";
 
    var infoWindow = new google.maps.InfoWindow({
        content  : contentMarker,
        position : latlng
    });
    google.maps.event.addListener(marker, 'click', function() {
        infoWindow.open(carte,marker);
    });    
    google.maps.event.addListener(carte, 'click', function(event) {
        var latlng = event.latLng;
    	document.getElementById('lat').value = latlng.lat();
    	document.getElementById('lng').value = latlng.lng();
    	if (marker) {
    	   marker.setPosition(latlng);
    	} else {
    	   var optionsMarker = {
    	       map: carte,
    	       position: new google.maps.LatLng(latlng.lat(), latlng.lng()),
    	       title: 'mon domicile'
    	   }
    	   marker = Marker(optionsMarker);
        }
    });
}

<?php
$this->headScript()->captureEnd();
// lancement du script (sera affiché dans le layout à la fin de la page
$this->inlineScript()->captureStart();
?>
initialiser();
<?php $this->inlineScript()->captureEnd(); ?>
<h1>Position de votre domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header">
		<p>
			Cliquez sur la carte à l'emplacement de votre domicile <b><?php echo $domicile;?></b>
			puis cliquez sur le bouton <b>Enregistrer la localisation</b>.
			Utilisez le zoom pour plus de précision.
		</p>
<?php
echo $this->form($this->form);
?>
</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
