<?php
/**
 * Page présentant une carte interactive aux parents
 *
 * Un clic sur la carte pour placer ou déplacer le repère de l'emplacement du domicile
 * 
 * @project sbm
 * @package SbmParent/view/sbm-parent/config
 * @filesource localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 fév. 2019
 * @version 2019-2.4.7
 */
// calcul du contenu de l'infobulle et du libellé du domicile
$description = [];
$description[] = '<b>' . implode(' ', 
    [
        $this->responsable->titre,
        $this->responsable->nom,
        $this->responsable->prenom
    ]) . '</b>';
$description[] = $this->responsable->adresseL1;
$domicile = $this->responsable->adresseL1;
$tmp = $this->responsable->adresseL2;
if (! empty($tmp)) {
    $description[] = $this->responsable->adresseL2;
    $domicile .= ' ' . $this->responsable->adresseL2;
}
$cp_commune = implode(' ', 
    [
        $this->responsable->codePostal,
        $this->responsable->commune
    ]);
$description[] = $cp_commune;
$domicile .= ' ' . $cp_commune;
$telephones = array_filter(
    [
        $this->telephone($this->responsable->telephoneF),
        $this->telephone($this->responsable->telephoneP),
        $this->telephone($this->responsable->telephoneT)
    ]);
if (! empty($telephones)) {
    $description[] = 'Tél.' . implode(' - ', $telephones);
}
$description[] = $this->responsable->email;
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->appendFile('/js/maps/localisation.js');
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?php echo $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?php echo $this->config['centre']['lng'];?>;
const INI_ZOOM = <?php echo $this->config['zoom'];?>;
initialiser('mon domicile', "<?php echo implode('<br/>', $description);?>", []);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position de votre domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header">
		<p>
			Cliquez sur la carte à l'emplacement de votre domicile <b><?php echo $domicile;?></b>
			puis cliquez sur le bouton <b>Enregistrer la localisation</b>.
			Utilisez le zoom pour plus de précision.
		</p>
<?php
echo $this->form($this->form);
?>
</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
