<?php
/**
 * Modification du compte d'un parent
 *
 * La modification sera d'abord effectuée dans la table responsables puis dans la table users
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/config
 * @filesource modif-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery('jquery-ui');
$this->inlineScript()->appendFile($this->basePath() . '/js/form-responsable.js');
$hiddens = [];
$actions = [];
?>
<div id="winpopup">
	<div id="winpopup-content"
		style="margin-left: 30px; margin-right: 30px;"></div>
</div>
<div class="flashMessenger float-right">
	<?=$this->flashMessenger()->render('success');?>
	<?=$this->flashMessenger()->render('warning');?>
	<?=$this->flashMessenger()->render('error');?>
	<?=$this->flashMessenger()->render('info');?>
	<?=$this->flashMessenger()->render('default');?>
</div>
<h1>Modification de la fiche du responsable</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?=$this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?=$this->form()->openTag($this->form);?>
		<?=$this->formHidden($this->form->get('responsableId'));?>
		<?=$this->formHidden($this->form->get('nature'));?>
		<?=$this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="responsable-edit-ligne1" class="clearfix">
				<div id="responsable-edit-titre" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('titre'));?></div>
				<div id="responsable-edit-nom" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('nom'));?></div>
				<div id="responsable-edit-prenom" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('prenom'));?></div>
			</div>
			<div id="responsable-edit-ligne2" class="clearfix">
				<div id="responsable-edit-titre2" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('titre2'));?></div>
				<div id="responsable-edit-nom2" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('nom2'));?></div>
				<div id="responsable-edit-prenom2" class="row-inner edit float-left">
					<?=$this->formRow($this->form->get('prenom2'));?></div>
			</div>
			<div id="responsable-telephones" class="row-inner edit clearfix">
				<div id="responsable-telephone-numbers" class="float-left">
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneF'));?></div>
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneP'));?></div>
					<div class="erreur-a-droite"><?=$this->formRow($this->form->get('telephoneT'));?></div>
				</div>
				<?php

    if ($this->layout()->hassbmservicesms) :
        ?>
				<div id="responsable-acceptsms" class="left-20px float-left">
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsF'));?></div>
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsP'));?></div>
					<div>Accepte les SMS<?=$this->formRadio($this->form->get('smsT'));?></div>
				</div>
				<?php endif;

    ?>
			</div>
    <?php

    if ($this->hasEnfantInscrit) :
        ?>
            <?=$this->formHidden($this->form->get('email'));?>
            <?=$this->formHidden($this->form->get('adresseL1'));?>
            <?=$this->formHidden($this->form->get('adresseL2'));?>
            <?=$this->formHidden($this->form->get('codePostal'));?>
            <?=$this->formHidden($this->form->get('communeId'));?>
            <?=$this->formHidden($this->form->get('demenagement'));?>
            <div id="responsable-edit-email" class="row-inner edit"><?='<div class="enfant-label">Email</div>' .$this->responsable['email'];?></div>
			<div id="responsable-edit-adresseL1" class="row-inner edit"><?='<div class="enfant-label">Adresse</div>' .$this->responsable['adresseL1'];?></div>
			<div id="responsable-edit-adresseL2" class="row-inner edit"><?='<div class="enfant-label">Complément d\'adresse</div>' .$this->responsable['adresseL2'];?></div>
			<div id="responsable-edit-codePostal" class="row-inner edit"><?='<div class="enfant-label">Code postal</div>' .$this->responsable['codePostal'];?></div>
			<div id="responsable-edit-communeId" class="row-inner edit"><?='<div class="enfant-label">Commune</div>' .$this->responsable['commune'];?></div>
    <?php

    else :
        ?>
            <div id="responsable-edit-email" class="row-inner edit"><?='<div class="enfant-label">Email</div>' .$this->responsable['email'];?></div>
			<div id="responsable-edit-adresseL1" class="row-inner edit"><?=$this->formRow($this->form->get('adresseL1'));?></div>
			<div id="responsable-edit-adresseL2" class="row-inner edit"><?=$this->formRow($this->form->get('adresseL2'));?></div>
			<div id="responsable-edit-codePostal" class="row-inner edit"><?=$this->formRow($this->form->get('codePostal'));?></div>
			<div id="responsable-edit-communeId" class="row-inner edit"><?=$this->formRow($this->form->get('communeId'));?></div>
			<div id="responsable-edit-demenagement" class="row-inner edit"><?=$this->formRow($this->form->get('demenagement'));?></div>
    <?php

    endif;
    ?>
    <div id="responsable-edit-blocAncien"
				<?=$this->demenagement ? '' : 'style="display: none;"';?>>
				<div id="responsable-edit-dateDemenagement" class="row-inner edit"><?=$this->formRow($this->form->get('dateDemenagement'));?></div>
				<div id="responsable-edit-ancienAdresseL1" class="row-inner edit"><?=$this->formRow($this->form->get('ancienAdresseL1'));?></div>
				<div id="responsable-edit-ancienAdresseL2" class="row-inner edit"><?=$this->formRow($this->form->get('ancienAdresseL2'));?></div>
				<div id="responsable-edit-ancienCodePostal" class="row-inner edit"><?=$this->formRow($this->form->get('ancienCodePostal'));?></div>
				<div id="responsable-edit-ancienCommuneId" class="row-inner edit"><?=$this->formRow($this->form->get('ancienCommuneId'));?></div>
			</div>
			<div id="responsable-edit-buttons" class="row-inner edit">
    			<?=$this->formSubmit($this->form->get('submit'));?>
    			<?=$this->formSubmit($this->form->get('cancel'));?>
    		</div>
		</fieldset>
		<?=$this->form()->closeTag();?>
    </div>
	<div id="fiche-footer"></div>
</div>
<div id="help-r2-content" class="invisible">
	<p>Il s'agit de personnes vivant en couple à la même adresse,
		responsables des enfants qui vont être inscrits.</p>
	<p>Si les deux personnes ont le même nom, indiquez seulement le prénom
		de la deuxième.</p>
	<p></p>
	<h3>Attention !</h3>
	<p>Il ne s'agit pas de responsables d'enfants en garde alternée. Pour
		ces cas particuliers, l'information sera demandée au moment de
		l'inscription des enfants.</p>
</div>