<?php
/**
 * Application Sbm
 * Dessin du pied de page
 * 
 * L'appel se fait par :
 * $this->partial('layout/footer', array('client_name' => 'COBAS', 'footer_elements' => array('mentions légales' => 'SbmFront\about'))); 
 *
 * @project sbm
 * @package module/SbmFront
 * @filesource view/layout/footer.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 21 avr. 2014
 * @version 2014-1
 */
?>
<div id="footer">
  <div class="float-left">
  <?php echo $this->translate('School Bus Manager');?> : <a href="http://www.dafap.fr" target="_blank" title="R&eacute;alisation">Dafap informatique</a>
  &copy;2013 - <?php echo date('Y')?> - <a href="https://www.ex2.com" title=" H&eacute;bergement web">Ex2Hosting</a> - <?php  echo $this->client_name; ?> 
  </div>
  <div class="float-right"> 
  <?php 
  // mentions légales, plan du site ... passés dans un tableau associatif {$name => $url}
  $sep = '';
  foreach ((array) $this->footer_elements as $name => $url) {
      if (is_array($url)) {
          $href= array_key_exists('href', $url) ? $url['href'] : '';
          $accesskey = array_key_exists('accesskey', $url) ? ' accesskey="' . $url['accesskey'] .'"' : '';
          $title = array_key_exists('title', $url) ? ' title="' . $url['title'] .'"' : '';
          $css = array_key_exists('class', $url) ? ' class="' . $url['class'] .'"' : '';
      } elseif (is_string($url)) {
          $href = $url;
          $accesskey = '';
          $title = '';
          $css = '';
      }
      echo $sep . '<a' . $title . $accesskey . $css. ' href="' . $href . '">' . $name . '</a>';
      $sep = ' | ';
  }
  ?>
  </div>
</div>