<?php
/**
 * Dessin des pages de l'application School Bus Manager
 *
 * Voir la documentation dans docs/application/views/layouts/layout.textile
 *
 * Le partial('common/stats.phtml') est prévu pour inclure un compteur de visites
 *
 * @project sbm
 *
 * @package module/SbmFront
 * @filesource view/layout/layout.phtml
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2019-2.5.0
 */
use SbmBase\Model\StdLib;

// paramètres du layout
$appl_name = StdLib::getParam('appl_name', $this->parameter);
$layoutParameters = StdLib::getParam('layout', $this->parameter);

echo $this->doctype();
?>

<html lang="fr">
<head>
<meta charset="utf-8">
<base href="<?= $this->basePath(); ?>" />
<?php
echo $this->headTitle('SBM ' . $appl_name)
    ->setSeparator(' - ')
    ->setAutoEscape(false);
echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->setName('author', 'Alain Pomirol - DAFAP Informatique')
    ->setName('generator', 'ZendFramework 2.3')
    ->setName('language', 'fr') . PHP_EOL;

// headLink : Le favicon et les styles
$this->headLink(
    [
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath(StdLib::getParam('favicon', $layoutParameters))
    ]);
foreach (StdLib::getParamR([
    'css',
    'append'
], $layoutParameters, []) as $css_file) {
    if (is_string($css_file)) {
        $this->headLink()->appendStylesheet($this->basePath($css_file));
    } elseif (is_array($css_file)) {
        $href = StdLib::getParam('href', $css_file);
        $media = StdLib::getParam('media', $css_file) ?: 'all';
        $conditionalStylesheet = StdLib::getParam('conditionalStylesheet', $css_file) ?: true;
        $extras = StdLib::getParam('extras', $css_file) ?: [];
        if (! is_null($href)) {
            $this->headLink()->appendStylesheet($this->basePath($href), $media,
                $conditionalStylesheet, $extras);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition des fichiers css dans la section append.');
    }
}
foreach (StdLib::getParamR([
    'css',
    'prepend'
], $layoutParameters, []) as $css_file) {
    if (is_string($css_file)) {
        $this->headLink()->prependStylesheet($this->basePath($css_file));
    } elseif (is_array($css_file)) {
        $href = StdLib::getParam('href', $css_file);
        $media = StdLib::getParam('media', $css_file) ?: 'all';
        $conditionalStylesheet = StdLib::getParam('conditionalStylesheet', $css_file) ?: true;
        $extras = StdLib::getParam('extras', $css_file) ?: [];
        if (! is_null($href)) {
            $this->headLink()->prependStylesheet($this->basePath($href), $media,
                $conditionalStylesheet, $extras);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition des fichiers css dans la section prepend.');
    }
}
echo $this->headLink();

// headScript : les scripts
foreach (StdLib::getParamR([
    'js',
    'file',
    'prepend'
], $layoutParameters, []) as $js_file) {
    if (is_string($js_file)) {
        $this->headScript()->prependFile($this->basePath($js_file));
    } elseif (is_array($js_file)) {
        $src = StdLib::getParam('src', $js_file);
        $type = StdLib::getParam('type', $js_file);
        $attrs = StdLib::getParam('attrs', $js_file);
        if (! is_null($src)) {
            $head_script = $this->headScript()->prependFile($this->basePath($src), $type,
                $attrs);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition des fichiers js dans la section prepend.');
    }
}
foreach (StdLib::getParamR([
    'js',
    'file',
    'append'
], $layoutParameters, []) as $js_file) {
    if (is_string($js_file)) {
        $this->headScript()->appendFile($this->basePath($js_file));
    } elseif (is_array($js_file)) {
        $src = StdLib::getParam('src', $js_file);
        $type = StdLib::getParam('type', $js_file);
        $attrs = StdLib::getParam('attrs', $js_file);
        if (! is_null($src)) {
            $head_script = $this->headScript()->appendFile($this->basePath($src), $type,
                $attrs);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition des fichiers js dans la section append.');
    }
}
foreach (StdLib::getParamR([
    'js',
    'script',
    'prepend'
], $layoutParameters, []) as $js_script) {
    if (is_string($js_script)) {
        $this->headScript()->prependScript($js_script);
    } elseif (is_array($js_script)) {
        $template = StdLib::getParam('template', $js_script);
        $type = StdLib::getParam('type', $js_script);
        $attrs = StdLib::getParam('attrs', $js_script);
        if (! is_null($template)) {
            $this->headScript()->prependScript($template, $type, $attrs);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition d\'un script dans la section prepend');
    }
}
foreach (StdLib::getParamR([
    'js',
    'script',
    'append'
], $layoutParameters, []) as $js_script) {
    if (is_string($js_script)) {
        $this->headScript()->appendScript($js_script);
    } elseif (is_array($js_script)) {
        $template = StdLib::getParam('template', $js_script);
        $type = StdLib::getParam('type', $js_script);
        $attrs = StdLib::getParam('attrs', $js_script);
        if (! is_null($template)) {
            $this->headScript()->appendScript($template, $type, $attrs);
        }
    } else {
        throw new Exception(
            'Erreur de structure pour la définition d\'un script dans la section append');
    }
}
echo $this->headScript();
?>        
</head>
<body id="main_body">
	<div id="container-general">
		<?= $this->partial('layout/header', StdLib::getParam('header', $layoutParameters));?>
		<!-- conteneur de la page -->
		<div id="container-interface"
			class="<?= StdLib::getParam('page', $layoutParameters, 'page1'); ?>">
			<!-- header -->
			<div id="header">
				<div class="container_banner">
					<!-- a href="<?= StdLib::getParam('accueil', $layoutParameters, ''); ?>" title="Retour à l'accueil"-->
					<div id="bandeau"
						class="<?= StdLib::getParam('page', $layoutParameters, 'page1'); ?>"></div>
					<!--/a-->
				</div>
			</div>
			<!-- bienvenue  -->
			<?= $this->bienvenue(); ?>
			<!-- corps de page -->
			<div class="content">
			<?php  //echo $this->navigation('navigation')->menu()->setPartial('menu')->render(); //test menu dynamique ?> 
			<?= $this->layout()->content; ?>
			</div>

		</div>
		<!-- Footer -->
		<?= $this->partial('layout/footer', StdLib::getParam('footer', $layoutParameters));?>
	</div>
	<!-- Statistiques (comme par exemple Google Analytics) -->
	<?= $this->partial('layout/stats'); ?>
	<!-- Scripts éventuels de validation -->
	<?= $this->inlineScript(); ?>
</body>