<?php
/**
 * Application Sbm
 * Zone de script pour statistiques :
 * On mettra ici le scripts permettant d'activer les stats (script fourni par le dispositif choisi comme google analytic).
 *
 * @project sbm
 * @package module/SbmFront
 * @filesource view/layout/stats.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 avr. 2018
 * @version 2018-2.4.0
 */
?> 