<?php
/**
 * Application Sbm
 * Zone de script pour statistiques :
 * On mettra ici le scripts permettant d'activer les stats (script fourni par le dispositif choisi comme google analytic).
 *
 * @project sbm
 * @package module/SbmFront
 * @filesource view/layout/stats.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 21 avr. 2014
 * @version 2014-1
 */

?> 