<?php
/**
 * Page de saisie du premier mot de passe, entrée par token
 *
 * Un contrôle du mot de passe est assuré.
 * 
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource confirm.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept.2018
 * @version 2018-2.4.5
 */
?>
<h1>Choisissez un mot de passe</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions"></div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('userId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
		<fieldset class="sbm-page1">
			<div id="user-first-mdp" class="row-inner edit">
				<?= $this->formRow($this->form->get('mdp')); ?></div>
			<div id="user-first-ctrl" class="row-inner edit">
				<?= $this->formRow($this->form->get('ctrl')); ?></div>
			<div id="user-edit-buttons" class="row-inner top-6px">
    			<?= $this->formSubmit($this->form->get('submit'));?>
    			<?= $this->formSubmit($this->form->get('cancel'));?>
    		</div>
		</fieldset>
		<?= $this->form()->closeTag();?>
		<div class="sbm-description">
			<p>Le mot de passe doit avoir au moins 6 caractères, au moins une
				lettre en majuscule, au moins une lettre en minuscule et au moins un
				chiffre.</p>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>