<?php
/**
 * Page de création d'un compte
 *
 * On remplit le formulaire et on recevra un lien pour entrer et choisir son mot de passe.
 * 
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource creer-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept.2018
 * @version 2018-2.4.5
 */
if (is_null($this->form)) {
    var_dump($this->data);
} else {
    ?>
<h1>Création d'un compte</h1>
<div class="fiche-wrapper">
	<div class="zone-actions"></div>
    <?= $this->form()->openTag($this->form);?>
    <?= $this->formHidden($this->form->get('userId'));?>
    <?= $this->formHidden($this->form->get('csrf'));?>    
	<fieldset class="sbm-page1">
		<div id="user-edit-ligne1" class="clearfix">
			<div id="user-edit-titre" class="row-inner edit float-left">
				<?= $this->formRow($this->form->get('titre')); ?> </div>
			<div id="user-edit-nom" class="row-inner edit float-left">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="user-edit-prenom" class="row-inner edit float-left">
				<?= $this->formRow($this->form->get('prenom')); ?></div>
		</div>
		<div id="user-edit-email" class="row-inner edit">
			<?= $this->formRow($this->form->get('email')); ?></div>
		<div id="user-edit-buttons" class="row-inner top-6px">
			<?= $this->formSubmit($this->form->get('submit'));?>
			<?= $this->formSubmit($this->form->get('cancel')); ?>
		</div>
		<?= $this->form()->closeTag(); ?>
		<div class="sbm-description">
			<p>
				Pour créer votre compte, remplissez tous les champs puis cliquez sur
				le bouton <i>Demander la création du compte</i>. Par la suite, vous
				allez recevoir un mail et vous devrez cliquer sur le lien pour
				activer votre compte.
			</p>
		</div>
	</fieldset>
</div>
<?php } ?>