<?php
/**
 * Page de changement d'email
 *
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource email-change.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 avr. 2015
 * @version 2015-1
 */
?>
<h1>Changement d'email</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions"></div>
	</div>
	<div id="fiche-inner">
	<p>Votre email actuel est : <b><?php echo $this->email; ?></b></p>
<?php echo $this->form()->openTag($this->form); ?>
<?php echo $this->formHidden($this->form->get('csrf')); ?>
    <fieldset class="sbm-page1">
			<div id="commun-edit-mdp" class="row-inner edit"><?php echo $this->formRow($this->form->get('mdp')); ?></div>
			<div id="commun-edit-email-new" class="row-inner edit"><?php echo $this->formRow($this->form->get('email_new')); ?></div>
			<div id="commun-edit-email-ctrl" class="row-inner edit"><?php echo $this->formRow($this->form->get('email_ctrl')); ?></div>
			<div id="commun-edit-buttons" class="row-inner edit">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?>
        </div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    <div class="sbm-description">
			<p>Donnez d'abord votre mot de passe puis votre nouvel email. Confirmez-le en l'écrivant à nouveau.</p>
			<p>Votre email sera changé dans toutes les fiches des enfants que vous avez inscrits.</p>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>