<?php
/**
 * Page de changement de mot de passe
 *
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource mdp-change.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 févr. 2015
 * @version 2015-1
 */
?>
<h1>Changement du mot de passe</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions"></div>
	</div>
	<div id="fiche-inner">
<?php echo $this->partial('sbm/mdpchange'); ?>
  </div>
	<div id="fiche-footer"></div>
</div>