<?php
/**
 * Ecran de demande d'un nouveau mot de passe
 *
 * Mot de passe oublié
 * 
 * @project sbm
 * @package SbmFront\view\sbm-front\index
 * @filesource mdp-demande.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept.2018
 * @version 2018-2.4.5
 */
?>
<h1>Oubli du mot de passe</h1>
<div class="fiche-wrapper">
	<div class="zone-actions"></div>
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('csrf'));?>
		<fieldset class="sbm-page1">
		<div id="front-edit-email" class="row-inner edit">
				<?= $this->formRow($this->form->get('email')); ?></div>
		<div id="front-edit-buttons" class="top-6px">
				<?= $this->formSubmit($this->form->get('submit'));?>
				<?= $this->formSubmit($this->form->get('cancel')); ?>
			</div>
		<div class="sbm-description">
			<p>
				Donnez votre email.<br />Si vous avez créé un compte avec cet email,
				le service vous enverra à cette adresse la méthode pour saisir un
				nouveau de mot de passe.
			</p>
		</div>
	</fieldset>
	<?= $this->form()->closeTag(); ?>
	<p></p>
</div>
