<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource mdp-change.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 févr. 2015
 * @version 2015-1
 */
?>
<h1>Changement du mot de passe</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
  </div>
<?php echo $this->partial('sbm/mdpchange'); ?>
</div>