<?php
/**
 * Ecran de demande d'un nouveau mot de passe
 *
 * Mot de passe oublié
 * 
 * @project sbm
 * @package SbmFront\view\sbm-front\index
 * @filesource mdp-demande.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 févr. 2015
 * @version 2015-1
 */
?>
<h1>Renvoi d'un mot de passe</h1>
<div class="fiche-wrapper">
	<div class="zone-actions"></div>
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('csrf'));
?>
<fieldset class="sbm-page1">
		<div id="front-edit-email" class="row-inner edit"><?php echo $this->formRow($this->form->get('email')); ?></div>
		<div id="front-edit-buttons" class="top-6px"><?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		<div class="sbm-description">
			<p>
				Donnez votre email.<br />Si vous avez créé un compte avec cet email,
				le service vous enverra un nouveau mot de passe à cette adresse.
			</p>
		</div>
	</fieldset>
<?php echo $this->form()->closeTag(); ?>
<p></p>
</div>
