<?php
/**
 * Page de changement de mot de passe
 *
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource mdp-change.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept.2018
 * @version 2018-2.4.5
 */
?>
<h1>Changement du mot de passe</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions"></div>
	</div>
	<div id="fiche-inner">
<?= $this->partial('sbm/mdpchange'); ?>
  </div>
	<div id="fiche-footer"></div>
</div>