<?php
/**
 * Page de modification d'un compte
 *
 * @project sbm
 * @package SbmFront/view/sbm-front/login
 * @filesource modif-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 févr. 2015
 * @version 2015-1
 */
//die(var_dump($this->form));
?>
<h1>Modification de compte</h1>
<div class="fiche-wrapper">
	<div class="zone-actions"></div>
<?php
    echo $this->form()->openTag($this->form);
    echo $this->formHidden($this->form->get('userId'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>
<fieldset class="sbm-page1">
  <div id="user-edit-ligne1" class="clearfix">
	<div id="user-edit-titre" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('titre')); ?> </div>
	<div id="user-edit-nom" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('nom')); ?></div>
	<div id="user-edit-prenom" class="row-inner edit float-left"><?php echo $this->formRow($this->form->get('prenom')); ?></div>
  </div>	
	<div id="user-edit-buttons" class="row-inner top-6px">
<?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?>
</div>
		<div class="sbm-description">
			<p></p>
		</div>
	</fieldset>
<?php echo $this->form()->closeTag(); ?>
</div>