<?php
/**
 * Affiche la liste des éléments d'une année scolaire
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource calendar.inc.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 août 2016
 * @version 2016-2.2.0
 */
use SbmBase\Model\DateLib;

?>
<table class="liste-inner annee-scolaire">
	<tbody>
		<tr>
			<th></th>
			<th>Nature</th>
			<th>Libellé</th>
			<th>Description</th>
			<th>Date de début</th>
			<th>Date de fin</th>
			<th>Echéance</th>
			<th>Exercice</th>
			<th></th>
		</tr>
    <?php foreach ($this->table as $element) : ?>
    <?php $url_edit = $this->url('sbmgestion/anneescolaire', array('action' => 'edit', 'millesime' => $this->millesime, 'id' => $element['calendarId'])); ?>
        <tr class="<?php echo $this->cycle(array(
            "even",
            "odd"
        ))->next();?>">
			<td><?php echo $element['ordinal'];?></td>
			<td><?php echo $element['nature'];?></td>
			<td><?php echo $element['libelle'];?></td>
			<td><?php echo $element['description'];?></td>
			<td><?php echo DateLib::formatDateFromMysql($element['dateDebut']);?></td>
			<td><?php echo DateLib::formatDateFromMysql($element['dateFin']);?></td>
			<td><?php echo DateLib::formatDateFromMysql($element['echeance']);?></td>
			<td><?php echo $element['exercice'];?></td>
			<td><a href="<?php echo $url_edit;?>" class="bouton" title="Editer"><i
					class="fam-date-edit"></i></a></td>
		</tr>
    <?php endforeach;?>
    </tbody>
</table>
