<?php
/**
 * Affiche la liste des éléments d'une année scolaire
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource calendar.inc.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 sept. 2018
 * @version 2018-2.4.5
 */
use SbmBase\Model\DateLib;

?>
<table class="liste-inner annee-scolaire">
	<tbody>
		<tr>
			<th></th>
			<th>Nature</th>
			<th>Libellé</th>
			<th>Description</th>
			<th>Date de début</th>
			<th>Date de fin</th>
			<th>Echéance</th>
			<th>Exercice</th>
			<th></th>
		</tr>
    <?php foreach ($this->table as $element) : ?>
    <?php
        $url_edit = $this->url('sbmgestion/anneescolaire',
            [
                'action' => 'edit',
                'millesime' => $this->millesime,
                'id' => $element['calendarId']
            ]);
        ?>
        <tr class="<?=$this->cycle(["even","odd"])->next();?>">
			<td><?= $element['ordinal'];?></td>
			<td><?= $element['nature'];?></td>
			<td><?= $element['libelle'];?></td>
			<td><?= $element['description'];?></td>
			<td><?= DateLib::formatDateFromMysql($element['dateDebut']);?></td>
			<td><?= DateLib::formatDateFromMysql($element['dateFin']);?></td>
			<td><?= DateLib::formatDateFromMysql($element['echeance']);?></td>
			<td><?= $element['exercice'];?></td>
			<td><a href="<?= $url_edit;?>" class="bouton" title="Editer"><i
					class="fam-date-edit"></i></a></td>
		</tr>
    <?php endforeach;?>
    </tbody>
</table>
