<?php
/**
 * Page de modification d'un élément de `calendar`
 *
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 nov. 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$as_libelle = sprintf("%4d-%4d", $this->millesime, $this->millesime + 1);
$url_retour = $this->url('sbmgestion/anneescolaire', array(
    'action' => 'voir',
    'millesime' => $this->millesime
));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);
?>
<h1>Modification d'un élément du calendrier de l'année scolaire <?php echo $as_libelle;?></h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions">
            <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('calendarId'));
echo $this->formHidden($this->form->get('millesime'));
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset class="edit">
			<div id="wrapper-description" class="row-inner edit"><?php echo $this->formRow($this->form->get('description'));?></div>
			<div id="wrapper-dateDebut" class="row-inner edit"><?php echo $this->formRow($this->form->get('dateDebut'));?></div>
			<div id="wrapper-dateFin" class="row-inner edit"><?php echo $this->formRow($this->form->get('dateFin'));?></div>
			<div id="wrapper-echeance" class="row-inner edit"><?php echo $this->formRow($this->form->get('echeance'));?></div>
			<div id="wrapper-exercice" class="row-inner edit"><?php echo $this->formRow($this->form->get('exercice'));?></div>
			<div id="wrapper-buttons" class="row-inner edit">
                <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'));?>
            </div>
		</fieldset>
<?php echo $this->form()->closeTag();?>
    </div>
</div>