<?php
/**
 * Page de modification d'un élément de `calendar`
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
/*
 * On n'utilise pas le datepicker parce qu'il faudrait écrire les conversions de format de
 * date à l'entrée et à la sortie. Sinon, le jquery fonctionne bien ! $this->jQuery('jquery-ui');
 * $this->headScript()->captureStart(); ?> $(document).ready(function($){
 * $("#-calendar-dateDebut").datepicker({ showOtherMonths:true, selectOtherMonth: true });
 * $("#calendar-dateFin").datepicker({ showOtherMonths:true, selectOtherMonth: true });
 * $("#calendar-echeance").datepicker({ showOtherMonths:true, selectOtherMonth: true });
 * });
 * <?php $this->headScript()->captureEnd();
 */

$as_libelle = sprintf("%4d-%4d", $this->millesime, $this->millesime + 1);
$url_retour = $this->url('sbmgestion/anneescolaire',
    [
        'action' => 'voir',
        'millesime' => $this->millesime
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];

switch ($this->data['nature']) {
    case 'INS':
        $element = $this->form->get('echeance');
        $element->setLabel('Date limite');
        break;
    case 'PERM':
        $element = $this->form->get('dateDebut');
        $element->setLabel('Date 1');
        $element = $this->form->get('dateFin');
        $element->setLabel('Date 2');
        $element = $this->form->get('echeance');
        $element->setLabel('Date 3');
        $element = $this->form->get('date1');
        $element->setLabel('Date 4');
        $element = $this->form->get('date2');
        $element->setLabel('Date 5');
        $element = $this->form->get('date3');
        $element->setLabel('Date 6');
        $element = $this->form->get('date4');
        $element->setLabel('Date 7');
    default:
        ;
        break;
}
?>
<h1>Modification d'un élément du calendrier de l'année scolaire <?= $as_libelle;?></h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
            <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('calendarId'));?>
		<?= $this->formHidden($this->form->get('millesime'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset class="sbm-page1">
			<div id="wrapper-nature">
				<div class="label">Nature</div><?= $this->data['nature'];?></div>
			<div id="wrapper-libelle">
				<div class="label">Libellé</div><?= $this->data['libelle'];?></div>
			<div id="wrapper-description" class="row-inner edit">
			    <?= $this->formRow($this->form->get('description'));?></div>
			<div id="wrapper-dateDebut" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('dateDebut'));?></div>
			<div id="wrapper-dateFin" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('dateFin'));?></div>
			<div id="wrapper-echeance" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('echeance'));?></div>
			<div id="wrapper-date1" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('date1'));?></div>
			<div id="wrapper-date2" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('date2'));?></div>
			<div id="wrapper-date3" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('date3'));?></div>
			<div id="wrapper-date4" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('date4'));?></div>
			<div id="wrapper-exercice" class="row-inner edit">
			    <?= $this->formRow($this->form->get('exercice'));?></div>
			<div id="wrapper-buttons" class="row-inner edit">
                <?= $this->formSubmit($this->form->get('submit'));?>
                <?= $this->formSubmit($this->form->get('cancel'));?>
            </div>
		</fieldset>
		<?= $this->form()->closeTag();?>
    </div>
</div>