<?php
/**
 * Page de modification d'un élément de `calendar`
 *
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 nov. 2014
 * @version 2014-1
 */
$as_libelle = sprintf("%4d-%4d", $this->millesime, $this->millesime + 1);
$retour = $this->url('sbmgestion/anneescolaire', array('action'=> 'voir', 'millesime' => $this->millesime));
?>
<h1>Modification d'un élément du calendrier de l'année scolaire <?php echo $as_libelle;?></h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la vue du calendrier de l'année scolaire <?php echo $as_libelle;?>"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('calendarId'));
echo $this->formHidden($this->form->get('millesime'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div id="classe-edit-nom" class="row-inner edit">' . $this->formRow($this->form->get('description')) . '</div>';
echo '<div id="classe-edit-aliasCG" class="row-inner edit">' . $this->formRow($this->form->get('dateDebut')) . '</div>';
echo '<div id="classe-edit-aliasCG" class="row-inner edit">' . $this->formRow($this->form->get('dateFin')) . '</div>';
echo '<div id="classe-edit-niveau" class="row-inner edit">' . $this->formRow($this->form->get('echeance')) . '</div>';
echo '<div id="classe-edit-niveau" class="row-inner edit">' . $this->formRow($this->form->get('exercice')) . '</div>';
echo '<div id="classe-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</fieldset>';
echo $this->form()->closeTag();
?>
</div>