<?php
/**
 * Vue de l'action index du controller AnneeScolaireController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/annee-scolaire/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2014
 * @version 2014-1
 */
function formatDate($d)
{
    if (empty($d)) {
        return '';
    } else {
        $date= DateTime::createFromFormat('Y-m-d', $d);
        return $date->format('d/m/Y');
    }
}

$col_date_width = 100;
$url_retour = $this->url('sbmgestion');
$url_nouvelle = $this->url('sbmgestion/anneescolaire', array('action' => 'new'));

?>
<h1>Gestion des années scolaires</h1>
<div class="liste-wrapper">
<div class="zone-actions">
<a href="<?php echo $url_retour; ?>" class="bouton" title="retour au menu de gestion">
<i class="fam-door-out"></i>Retour</a>
<a href="<?php echo $url_nouvelle; ?>" class="bouton" title="créer une nouvelle année scolaire">
<i class="fam-date-add"></i>Nouvelle année scolaire</a>
</div>
<table class="liste-inner annees-scolaires">
<tbody>
<tr>
<th>Année scolaire</th><th style="text-align: center; width: <?php echo $col_date_width; ?>px;">Date de début</th><th style="text-align: center; width: <?php echo $col_date_width; ?>px;">Date de fin</th>
</tr>
<?php foreach ($this->anneesScolaires as $as) :?>
<?php 
$url_voir = $this->url('sbmgestion/anneescolaire', array('action' => 'voir', 'millesime' => $as['millesime']));
$url_activer = $this->url('sbmgestion/anneescolaire', array('action' => 'active', 'millesime' => $as['millesime']));
$classes_css = $this->cycle(array("even", "odd"))->next();
if (!$as['valid']) {
    $classes_css .= ' incomplet';
}
?>
<tr class="<?php echo $classes_css;?>">
<td><?php echo $as['description'];?></td>
<td style="text-align: center; width: <?php echo $col_date_width; ?>px;"><?php echo formatDate($as['dateDebut']);?></td>
<td style="text-align: center; width: <?php echo $col_date_width; ?>px;"><?php echo formatDate($as['dateFin']);?></td>
<td>
<?php if ($as['valid']) :?>
<?php if ($as['millesime'] == $this->millesimeActif) :?>
<i class="fam-date-go"></i>Activer
<?php else :?>
<a href="<?php echo $url_activer;?>" class="bouton" title="activer"><i class="fam-date"></i>Activer</a>
<?php endif;?>
<?php endif;?>
<a href="<?php echo $url_voir;?>" class="bouton" title="activer"><i class="fam-date-magnify"></i><?php echo $as['valid'] ? 'Calendrier' : 'Définir les dates';?></a></td>
</tr>
<?php endforeach;?>
</tbody>
</table>
</div>