<?php
/**
 * Vue de l'action index du controller AnneeScolaireController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/annee-scolaire
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2014
 * @version 2014-1
 */
use SbmCommun\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$col_date_width = 100;
$url_retour = $this->url('sbmgestion');
$url_nouvelle = $this->url('sbmgestion/anneescolaire', array(
    'action' => 'new'
));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ),
    'ajouter' => array(
        'class' => 'fam-date-add',
        'formaction' => $url_nouvelle,
        'title' => 'Nouvelle année scolaire'
    )
);
?>
<h1>Gestion des années scolaires</h1>
<div id="liste-wrapper">
    <div id="liste-header" class="clearfix">
        <div class="zone-actions">
            <div class="float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
            <div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
		</div>
	</div>
	<div id="liste-inner">
        <table class="liste-inner annees-scolaires">
            <tbody>
                <tr>
				    <th>Année scolaire</th>
				    <th style="text-align: center; width: <?php echo $col_date_width; ?>px;">Date de début</th>
				    <th style="text-align: center; width: <?php echo $col_date_width; ?>px;">Date de fin</th>
				    <th>Etat</th>
				    <th></th>
                </tr>
<?php foreach ($this->anneesScolaires as $as) :?>
<?php
    $url_voir = $this->url('sbmgestion/anneescolaire', array(
        'action' => 'voir',
        'millesime' => $as['millesime']
    ));
    $url_activer = $this->url('sbmgestion/anneescolaire', array(
        'action' => 'active',
        'millesime' => $as['millesime']
    ));
    $classes_css = $this->cycle(array(
        "even",
        "odd"
    ))->next();
    if (! $as['valid']) {
        $classes_css .= ' incomplet';
    }
    ?>
                <tr class="<?php echo $classes_css;?>">
                    <td><?php echo $as['description'];?></td>
                    <td style="text-align: center; width: <?php echo $col_date_width; ?>px;"><?php echo DateLib::formatDateFromMysql($as['dateDebut']);?></td>
				    <td style="text-align: center; width: <?php echo $col_date_width; ?>px;"><?php echo DateLib::formatDateFromMysql($as['dateFin']);?></td>
				    <td><?php echo $as['ouvert'] ? 'Ouverte' : 'Fermée';?></td>
				    <td>
<?php if ($as['valid']) :?>
    <?php if ($as['millesime'] == $this->millesimeActif) :?>
        <i class="fam-date-go"></i>
    <?php else :?>
        <a href="<?php echo $url_activer;?>" class="bouton" title="Activer"><i
						class="fam-date"></i></a>
    <?php endif;?>
<?php endif;?>
        <a href="<?php echo $url_voir;?>" class="bouton" title="<?php echo $as['valid'] ? 'Calendrier' : 'Définir les dates';?>"><i
						class="fam-date-magnify"></i></a>
				    </td>
                </tr>
<?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>