<?php
/**
 * Page de paramétrage de la préparation
 *
 * Formulaire de paramétrage indiquant les classes reprises ou non
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/annee-scolaire
 * @filesource simulation-preparer.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 31 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/annee-scolaire', 'simulation-preparer.css');
$this->jQuery('jquery-ui');
$this->themeJS('gestion-annee-scolaire', 'simulation-preparer.js');
$this->inlineScript()->captureStart();
?>
js_object.init();
<?php
$this->inlineScript()->captureEnd();
$url_retour = $this->url('sbmgestion/anneescolaire');
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Préparation d'une simulation</h1>
<div id="liste-wrapper">
	<div class="clearfix">
		<div class="zone-actions">
			<div class="menu"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
	</div>
	<div class="left-10px">
		<p class="sbm-description">Pour modifier ces listes, allez dans la
			gestion des classes.</p>
		<div style="display: table;">

			<div style="display: table-cell;">
				<p>
					Vous souhaitez préparer une simulation en reprenant les circuits de
					l'année indiquée <br />et les élèves des classes suivantes :
				</p>
				<ul>
			<?php foreach ($this->repris as $row) : ?>
			<li>les <?= $row->nom;?> vont en <?= $row->suivant;?></li>
			<?php endforeach;?>
			</ul>
			</div>
			<div style="display: table-cell; padding-left: 40px;">
				<p>Les élèves des classes suivantes ne seront pas repris :</p>
				<ul>
			<?php foreach ($this->non_repris as $row) : ?>
			<li><?= $row->nom;?></li>
			<?php endforeach;?>
			</ul>
			</div>
		</div>
		<div id="simulation-preparer" class="row-inner">
		<?= $this->form()->openTag($form);?>
		<?= $this->formCollection($form);?>
		<?= $this->form()->closeTag();?>
	    </div>
	</div>
</div>