<?php
/**
 * Page de confirmation avant de vider le réseau pour une année scolaire
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/annee-scolaire
 * @filesource simulation-vider.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/annee-scolaire', 'vider-reseau.css');
$this->jQuery('jquery-ui');
$this->themeJS('gestion-annee-scolaire', 'vider-reseau.js');
$url_retour = $this->url('sbmgestion/anneescolaire');
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<div class="top-18px">
	<h1>Supprimer le réseau de transport d'une année scolaire</h1>
	<div id="liste-wrapper">
		<div id="liste-header" class="clearfix">
			<div class="zone-actions">
				<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
			</div>
		</div>
		<div id="vider-reseau">
			<p>
				Si vous confirmez, les tables décrivant le réseau de transport pour
				l'année scolaire <b><?= $this->as;?></b> seront vidées.
			</p>
			<p>Confirmez-vous ?</p>
		<?= $this->form()->openTag($form);?>
		<?= $this->formCollection($form);?>
		<?= $this->form()->closeTag();?>
	</div>
	</div>
</div>