<?php
/**
 * Page de présentation des éléments d'une année scolaire
 *
 * Cette page vérifie si le paramétrage est complet. Elle permet d'ouvrir ou de fermer l'année scolaire.
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/anneescolaire
 * @filesource voir.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_ici = $this->url('sbmgestion/anneescolaire', [
    'action' => 'voir',
    'millesime' => $this->millesime
]);
$url_retour = $this->url('sbmgestion/anneescolaire');
$url_ouvrir = $this->url('sbmgestion/anneescolaire', [
    'action' => 'ouvrir'
]);
$url_dupliquer = $this->url('sbmgestion/anneescolaire', [
    'action' => 'dupliquer-reseau'
]);
$url_vider = $this->url('sbmgestion/anneescolaire', [
    'action' => 'vider-reseau'
]);
$hiddens = [
    'millesime' => $this->millesime
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
$etat = true;
$ouvert = true;
foreach ($this->table as $row) {
    $etat &= ! is_null($row['dateDebut']) && ! is_null($row['dateFin']) &&
        ! is_null($row['echeance']);
    $ouvert &= $row['ouvert'] == 1;
}
if ($etat) {
    if (/*$this->admin*/ true) {
        if ($ouvert) {
            $msg = 'L\'année scolaire est ouverte.';
            $hiddens['ouvert'] = 0;
            $actions['ouvrir'] = [
                'class' => 'fam-date-delete',
                'formaction' => $url_ouvrir,
                'title' => 'Fermer l\'année scolaire'
            ];
        } else {
            $msg = 'L\'année scolaire est fermée.';
            $hiddens['origine'] = $url_ici;
            if ($this->circuitsVides) {
                $msg .= ' Avant de l\'ouvrir, créez le réseau de transport ou dupliquez le.';
                $actions['dupliquer'] = [
                    'class' => 'fam-plugin-add',
                    'formaction' => $url_dupliquer,
                    'title' => 'Générer les circuits pour cette année scolaire ' .
                    $this->as
                ];
            } else {
                $actions['dupliquer'] = [
                    'class' => 'fam-plugin-delete',
                    'formaction' => $url_vider,
                    'title' => 'Supprimer le réseau de transport de cette année scolaire ' .
                    $this->as
                ];
                $hiddens['ouvert'] = 1;
                $actions['ouvrir'] = [
                    'class' => 'fam-date-go',
                    'formaction' => $url_ouvrir,
                    'title' => 'Ouvrir l\'année scolaire'
                ];
            }
        }
    } else {
        if ($ouvert) {
            $msg = 'L\'année scolaire est ouverte.';
        } else {
            $msg = 'L\'année scolaire est fermée.';
        }
        $msg .= ' Pour modifier son état passez en administrateur.';
    }
} else {
    $msg = '<p>Complétez chaque ligne en précisant les dates de début, de fin et d\'échéance de chaque période.</p>';
}

?>
<h1>Edition de l'année scolaire <?= $this->as_libelle;?></h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="zone-actions">
			<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
	<div class="flashMessenger warning"><?= $msg;?></div>
    <?php include 'calendar.inc.phtml';?>
    </div>
</div>