<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SbmFront\Module'                               => __DIR__ . '/Module.php',
    'SbmFront\Controller\IndexController'           => __DIR__ . '/src/SbmFront/Controller/IndexController.php',
    'SbmFront\Controller\LoginController'           => __DIR__ . '/src/SbmFront/Controller/LoginController.php',
    'SbmFront\Factory\View\Helper\BienvenueFactory' => __DIR__ . '/src/SbmFront/Factory/View/Helper/BienvenueFactory.php',
    'SbmFront\Form\CreerCompte'                     => __DIR__ . '/src/SbmFront/Form/CreerCompte.php',
    'SbmFront\Form\EmailChange'                     => __DIR__ . '/src/SbmFront/Form/EmailChange.php',
    'SbmFront\Form\Login'                           => __DIR__ . '/src/SbmFront/Form/Login.php',
    'SbmFront\Form\MdpChange'                       => __DIR__ . '/src/SbmFront/Form/MdpChange.php',
    'SbmFront\Form\MdpDemande'                      => __DIR__ . '/src/SbmFront/Form/MdpDemande.php',
    'SbmFront\Form\MdpFirst'                        => __DIR__ . '/src/SbmFront/Form/MdpFirst.php',
    'SbmFront\Form\ModifCompte'                     => __DIR__ . '/src/SbmFront/Form/ModifCompte.php',
    'SbmFront\Model\Exception'                      => __DIR__ . '/src/SbmFront/Model/Exception.php',
    'SbmFront\Model\Mdp'                            => __DIR__ . '/src/SbmFront/Model/Mdp.php',
    'SbmFront\Model\Validator\Mdp'                  => __DIR__ . '/src/SbmFront/Model/Validator/Mdp.php',
    'SbmFront\View\Helper\Bienvenue'                => __DIR__ . '/src/SbmFront/View/Helper/Bienvenue.php',
);
