<?php
/**
 * Formulaire d'appel de la plate-forme de paiement
 *
 * Cette vue reçoit l'objet 'plugin_plateforme' qui possède une méthode getForm() renvoyant un
 * formulaire ne présentant que les champs à envoyer à PayBox en hidden.
 * Le formulaire n'a ni csrf, ni bouton.
 * Un script en jQuery envoie le formulaire dès le chargement terminé.
 * Si le jQuery échoue la page est vice (malgré tout avec le thème du site contenu dans le layer).
 *
 * @project sbm
 * @package SbmPaiement/Plugin/PayBox/view
 * @filesource formulaire.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 22 avr. 2020
 * @version 2020-2.6.0
 */
$this->jQuery();
$this->themeJS('sbm-paiement', 'formulaire.js');
// tout est en hidden
$form = $this->oPlateforme->getForm();
if ($form) {
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
}