<?php
/**
 * Détail d'une notification de paiement
 *
 * @project sbm
 * @package SbmPaiement/Plugin/payBox/view
 * @filesource voir.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 avr. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmpaiement', [
    'action' => 'liste',
    'page' => $this->page
]);
$hiddens = [
    'op' => 'retour'
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Détail d'une notification de paiement</h1>
<div class="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="fiche-inner">
		<table class="plugin">
			<tbody>
				<tr>
					<td>Autorisation</td>
					<td><b><?= $this->notification->auto; ?></b></td>
				</tr>
				<tr>
					<td>Montant</td>
					<td><b><?= $this->notification->montant; ?></b></td>
				</tr>
				<tr>
					<td>Référence</td>
					<td><b><?= $this->notification->ref; ?></b></td>
				</tr>
				<tr>
					<td>Id transaction</td>
					<td><b><?= $this->notification->idtrans; ?></b></td>
				</tr>
				<tr>
					<td>Date de la transaction</td>
					<td><b><?= $this->notification->datetrans;?></b></td>
				</tr>
				<tr>
					<td>Heure de la transaction</td>
					<td><b><?= $this->notification->heuretrans; ?></b></td>
				</tr>
				<tr>
					<td>Carte</td>
					<td><b><?= $this->notification->carte; ?></b></td>
				</tr>
				<tr>
					<td>Début n° carte</td>
					<td><b><?= $this->notification->bin6; ?></b></td>
				</tr>
				<tr>
					<td>Fin n° carte</td>
					<td><b><?= $this->notification->bin2; ?></b></td>
				</tr>
				<tr>
					<td>Pays de la carte</td>
					<td><b><?= $this->notification->pays; ?></b></td>
				</tr>
				<tr>
					<td>Pays de l'internaute</td>
					<td><b><?= $this->notification->ip; ?></b></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>