<?php
/**
 * Vue pour l'action create du controleur SbmInstallation
 *
 *
 * @project sbm
 * @package module/SbmInstallation/view/sbm-installation/index
 * @filesource create.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 oct. 2018
 * @version 2019-2.5.0
 */
use Zend\Db\Adapter\Driver\ResultInterface;

function printResult($args)
{
    if (! is_array($args)) {
        echo "Résultat inconnu\n";
        var_dump($args);
        echo "\n";
    } else {
        foreach ($args as $result) {
            if (is_string($result)) {
                echo "$result\n";
            } elseif ($result instanceof ResultInterface) {
                echo $result->getResource()->queryString;
                echo "\n";
            } elseif (is_array($result)) {
                printResult($result);
            } else {
                echo "Résultat inconnu\n";
                var_dump($result);
                echo "\n";
            }
        }
    }
}
// ------------------------------ DEBUT -----------------------------------------
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$retour = $this->url("sbminstall", [
    'action' => 'gestion-config'
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Création des tables et des vues</h1>
<div id="data-wrapper">
	<div id="data-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
<?php if (is_null($this->form)) : ?>
	<div id="data-inner">
		<pre><?php printResult($this->args);?></pre>
		<p>Création terminée.</p>
	</div>
<?php else : ?>
    <div id="data-inner">
		<table class="installation">
			<thead>
				<tr class="odd">
					<th>name</th>
					<th>type</th>
					<th>drop</th>
					<th>edit_entity</th>
					<th>add_data</th>
					<th>data</th>
				</tr>
			</thead>
			<tbody>
	<?php foreach ($this->args as $row) : ?>
		        <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td><?= $row['name'];?></td>
					<td><?= $row['type'];?></td>
					<td><?= $row['drop'];?></td>
					<td><?= $row['edit_entity'];?></td>
					<td><?= $row['add_data'];?></td>
					<td><?= $row['data'];?></td>
				</tr>
	<?php endforeach; ?>
	</tbody>
		</table>
		<p>Confirmez-vous que vous voulez créer les tables comme indiqué dans
			cette configuration ?</p>
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formCollection($this->form);?>
		<?= $this->form()->closeTag();?>
    </div>
<?php endif;?>
</div>