<?php
/**
 * Vue pour l'action create du controleur SbmInstallation
 *
 *
 * @project sbm
 * @package module/SbmInstallation/view/sbm-installation/index
 * @filesource create.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 sept. 2018
 * @version 2018-2.4.5
 */
use Zend\Db\Adapter\Driver\ResultInterface;

function getResult($args)
{    
    if (! is_array($args)) {
        ob_start();
        var_dump($args);        
        return sprintf("Résultat inconnu\n%s\n", html_entity_decode(strip_tags(ob_get_clean())));
    } else {
        $html = '';
        foreach ($args as $result) {
            if (is_string($result)) {
                $html .= "$result\n";
            } elseif ($result instanceof ResultInterface) {
                $html.= $result->getResource()->queryString . "\n";
            } elseif (is_array($result)) {
                $html .= getResult($result);
            } else {
                ob_start();
                var_dump($result);
                return sprintf("Résultat inconnu\n%s\n", html_entity_decode(strip_tags(ob_get_clean())));
            }
        }
        return $html;
    }
}
// ------------------------------ DEBUT -----------------------------------------
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$retour = $this->url("sbminstall");
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Création des tables et des vues</h1>
<div id="data-wrapper">
	<div id="data-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
        <?= $this->flashMessenger()->render('success');?>
        <?= $this->flashMessenger()->render('warning');?>
        <?= $this->flashMessenger()->render('error');?>
        <?= $this->flashMessenger()->render('info');?>
        <?= $this->flashMessenger()->render('default');?>
        </div>
	</div>
<?php if (is_null($this->form)) : ?>        	
	<div id="data-inner">
		<pre><?= getResult($this->args); ?></pre>
		<p>Création terminée.</p>
	</div>
<?php else : ?>
    <div id="data-inner">
		<table class="installation">
			<thead>
				<tr class="odd">
					<th>name</th>
					<th>type</th>
					<th>drop</th>
					<th>edit_entity</th>
					<th>add_data</th>
					<th>data</th>
				</tr>
			</thead>
			<tbody>
	<?php foreach ($this->args as $row) : ?>
		        <tr class="<?= $this->cycle(["even", "odd"])->next(); ?>">
					<td><?= $row['name'];?></td>
					<td><?= $row['type'];?></td>
					<td><?= $row['drop'];?></td>
					<td><?= $row['edit_entity'];?></td>
					<td><?= $row['add_data'];?></td>
					<td><?= $row['data'];?></td>
				</tr>
	<?php endforeach; ?>
	</tbody>
		</table>

		<p>Confirmez-vous que vous voulez créer les tables comme indiqué dans
			cette configuration ?</p>
<?= $this->form()->openTag($form);?>
<?= $this->formCollection($form);?>
<?= $this->form()->closeTag();?>
    </div>
<?php endif; ?>
</div>