<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource dump-tables.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 oct. 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$retour = $this->url("sbminstall");
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ]
];

// pour afficher le résultat, il faut conserver la balise <pre> et échapper le texte à l'intérieur
preg_match('/^<pre>(.*)<\/pre>\z/si', $this->description, $inner);
if (! empty($inner)) {
    $escaper = new \Zend\Escaper\Escaper('utf-8');
    $output = '<pre>' . $escaper->escapeHtmlAttr($inner[1]) . '</pre>';
} else {
    $output = $this->description;
}
?>
<h1><?php echo $this->titre; ?></h1>
<div id="data-wrapper">
    <div id="data-inner">
	<p><?php echo $output; ?></p>
<?php if (is_null($this->form)) : ?>
  <?php
    // liste des tables copiées
    echo var_dump($this->tables);
    ?>
<a href="<?php echo $retour; ?>" class="bouton" title="Retour"><i
		class="fam-door-out"></i></a>
<?php else : ?>
  <?php
    // formulaire
    $this->form->prepare();
    $this->form->setAttribute('action', $this->url('sbminstall', [
        'action' => 'dump-tables'
    ]));
    
    echo $this->form()->openTag($this->form);
    
    $element = $this->form->get('tables');
    echo $this->formRow($element);
    $element = $this->form->get('systems');
    echo $this->formRow($element);
    $element = $this->form->get('onscreen');
    $element->setValue(0);
    echo $this->formRow($element);
    echo $this->formElement($this->form->get('cancel'));
    echo $this->formElement($this->form->get('copy'));
    
    echo $this->form()->closeTag();
    ?> 
<?php endif; ?>
    </div>
</div>
