<?php
/**
 * Page de gestion des fichiers log
 *
 * La page affiche pour chaque fichier log la taille, le nombre de lignes et la date de dernière entrée
 * On peut les télécharger ou les vider
 * 
 * @project sbm
 * @package SbmInstallation/view
 * @filesource fichierslog.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 fév. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $this->url('sbminstall'),
        'title' => 'Retour'
    ]
];
?>
<h1>Téléchargement de fichiers log</h1>
<div id="suppr-wrapper">
	<div id="fichierlog-header">
		<div class="menu clearfix"><?= $this->listeZoneActions([], $actions)?></div>
	</div>
	<div id="fichierlog-inner">
		<dl>
			<dt>Historique des transactions de la plateforme de paiement</dt>
			<dd>Date de dernière écriture: <?= $this->paiement['date'];?></dd>
			<dd>Nombre de lignes: <?= $this->paiement['lignes'];?></dd>
			<dd>Taille: <?= $this->paiement['taille'];?></dd>
			<dd>
				<?= $this->form()->openTag($this->form1);?>
				<?= $this->formCollection($this->form1);?>
				<?= $this->form()->closeTag();?>
        	</dd>
			<dt>Fichier d'erreur PHP</dt>
			<dd>Date de dernière écriture: <?= $this->errors['date'];?></dd>
			<dd>Nombre de lignes: <?= $this->errors['lignes'];?></dd>
			<dd>Taille: <?= $this->errors['taille'];?></dd>
			<dd>
				<?= $this->form()->openTag($this->form2);?>
				<?= $this->formCollection($this->form2);?>
				<?= $this->form()->closeTag();?>
        	</dd>
		</dl>
	</div>
	<div id=fichierlog-footer></div>
</div>