<?php
/**
 * Vue de l'action index du controleur IndexController du module SbmInstallation
 *
 *
 * @project sbm
 * @package module/SbmInstallation/view/sbm-installation/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_create = $this->url('sbminstall', [
    'action' => 'create-tables'
]);
$url_dumpdoc = $this->url('sbminstall', [
    'action' => 'dump-tables'
]);
$url_tablealias = $this->url('sbminstall', [
    'action' => 'table-alias'
]);
$url_requetes = $this->url('sbminstall', [
    'action' => 'requetes'
]);
$url_version = $this->url('sbminstall', [
    'action' => 'version'
]);
$url_fichierslog = $this->url('sbminstall', [
    'action' => 'fichierslog'
]);
$url_admin = $this->url('sbmadmin');
$url_gestion = $this->url('sbmgestion');
$url_portail = $this->url('sbmportail');
$url_parent = $this->url('sbmparent');
$url_change_reinscription = $this->url('sbmmailchimp');
$url_images = $this->url('sbminstall', [
    'action' => 'gestion-images'
]);
$url_config = $this->url('sbminstall', [
    'action' => 'gestion-config'
]);
$url_update_hostname_validation = $this->url('sbminstall',
    [
        'action' => 'update-hostname-validator'
    ]);
$url_update_cacert = $this->url('sbminstall', [
    'action' => 'update-cacert'
]);
?>
<h1>Installation de l'application <?=$this->translate('School Bus Manager');?></h1>
<div id="menugeneral">
	<div class="flashMessenger">
		<?=$this->flashMessenger()->render('success');?>
		<?=$this->flashMessenger()->render('warning');?>
		<?=$this->flashMessenger()->render('error');?>
		<?=$this->flashMessenger()->render('info');?>
		<?=$this->flashMessenger()->render('default');?>
    </div>
	<div id="menugeneral-inner">
		<div class="float-left left-15px">
			<fieldset class="sbm-page1">
				<legend>Accès aux autres espaces</legend>
				<ul>
					<li><a href="<?=$url_portail;?>"><i class="fam-bullet-go"></i>Portail
							de consultation</a></li>
					<li><a href="<?=$url_admin;?>"><i class="fam-bullet-go"></i>Espace
							de l'administrateur</a></li>
					<li><a href="<?=$url_gestion;?>"><i class="fam-bullet-go"></i>Espace
							du gestionnaire</a></li>
					<li><a href="<?=$url_parent;?>"><i class="fam-bullet-go"></i>Espace
							parent</a></li>
					<li>&nbsp;</li>
				</ul>
			</fieldset>
		</div>
		<div class="float-left left-15px">
			<fieldset class="sbm-page1">
				<legend>Actions réservées</legend>
				<ul>
					<li><a href="<?=$url_version;?>"><i class="fam-bullet-go"></i>Versions
							des logiciels</a></li>
					<li><a href="<?=$url_fichierslog;?>"><i class="fam-bullet-go"></i>Fichiers
							de log</a></li>
					<li><a href="<?=$url_tablealias;?>"><i class="fam-bullet-go"></i>Liste
							des alias des tables</a></li>
					<li><a href="<?=$url_requetes;?>"><i class="fam-bullet-go"></i>Liste
							des requêtes</a></li>
					<li><a href="<?=$url_dumpdoc;?>"><i class="fam-bullet-go"></i>Copie
							des tables</a></li>
					<li><a href="<?=$url_config;?>"><i class="fam-bullet-go"></i>Configuration
							de l'application</a></li>
					<li><a href="<?=$url_update_hostname_validation;?>" target="_blank"><i
							class="fam-bullet-go"></i>Mise à jour du validateur des hostnames</a></li>
					<li><a href="<?=$url_update_cacert;?>"><i class="fam-bullet-go"></i>Mise
							à jour du fichier cacert.pem</a></li>
					<li><a href="<?=$url_change_reinscription;?>"><i
							class="fam-bullet-go"></i>Gestion des listes de diffusion de
							MailChimp</a></li>
				</ul>
			</fieldset>
		</div>

	</div>
</div>

