<?php
/**
 * Vue de l'action index du controleur IndexController du module SbmInstallation
 *
 *
 * @project sbm
 * @package module/SbmInstallation/view/sbm-installation/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2016
 * @version 2016-2.1.4
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_create = $this->url('sbminstall', [
    'action' => 'create-tables'
]);
$url_dumpdoc = $this->url('sbminstall', [
    'action' => 'dump-tables'
]);
$url_tablealias = $this->url('sbminstall', [
    'action' => 'table-alias'
]);
$url_version = $this->url('sbminstall', [
    'action' => 'version'
]);
$url_fichierslog = $this->url('sbminstall', [
    'action' => 'fichierslog'
]);
$url_admin = $this->url('sbmadmin');
$url_gestion = $this->url('sbmgestion');
$url_portail = $this->url('sbmportail');
$url_parent = $this->url('sbmparent');
$url_change_reinscription = $this->url('sbmmailchimp');
$url_images = $this->url('sbminstall', [
    'action' => 'gestion-images'
]);
?>
<h1>Installation de l'application <?php echo $this->translate('School Bus Manager'); ?></h1>
<div id="menugeneral">
	<div class="flashMessenger">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
    </div>
	<div id="menugeneral-inner">
		<div class="float-left left-15px">
			<fieldset class="sbm-page1">
				<legend>Accès aux autres espaces</legend>
				<ul>
					<li><a href="<?php echo $url_portail;?>"><i class="fam-bullet-go"></i>Portail
							de consultation</a></li>
					<li><a href="<?php echo $url_admin;?>"><i class="fam-bullet-go"></i>Espace
							de l'administrateur</a></li>
					<li><a href="<?php echo $url_gestion;?>"><i class="fam-bullet-go"></i>Espace
							du gestionnaire</a></li>
					<li><a href="<?php echo $url_parent; ?>"><i class="fam-bullet-go"></i>Espace
							parent</a></li>
					<li>&nbsp;</li>
				</ul>
			</fieldset>
		</div>
		<div class="float-left left-15px">
			<fieldset class="sbm-page1">
				<legend>Actions réservées</legend>
				<ul>
					<li><a href="<?php echo $url_version;?>"><i class="fam-bullet-go"></i>Versions
							des logiciels</a></li>
					<li><a href="<?php echo $url_fichierslog;?>"><i
							class="fam-bullet-go"></i>Fichiers de log</a></li>
					<li><a href="<?php echo $url_create; ?>"><i class="fam-bullet-go"></i>Création
							des tables</a></li>
					<li><a href="<?php echo $url_dumpdoc;?>"><i class="fam-bullet-go"></i>Copie
							des tables</a></li>
					<li><a href="<?php echo $url_tablealias;?>"><i
							class="fam-bullet-go"></i>Liste des alias des tables</a></li>

					<li><a href="<?php echo $url_change_reinscription;?>"><i class="fam-bullet-go"></i>Gestion
							des listes de diffusion de MailChimp</a></li>

					<li><a href="<?php echo $url_images;?>"><i class="fam-bullet-go"></i>Gestion
							des images de l'application</a></li>
				</ul>
			</fieldset>
		</div>

	</div>
</div>

