<?php
/**
 * Vue de l'action index du controleur IndexController du module SbmInstallation
 *
 *
 * @project sbm
 * @package module/SbmInstallation/view/sbm-installation/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 22 janv. 2014
 * @version 2014-1
 */

?>
<h1>Installation de l'application <?php echo $this->translate('School Bus Manager'); ?></h1>
<pre><?php var_dump($this->args); ?></pre>

