<?php
/**
 * Liste des alias de tables et de vues gérées par ce module
 * 
 * @project sbm
 * @package SbmInstallation/view
 * @filesource table-alias.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 oct. 2017
 * @version 2017-2.3.12
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$retour = $this->url("sbminstall");
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Liste des tables et des vues enregistrées</h1>
<div id="data-wrapper">
	<div id="data-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="data-inner">
	    <h3>Tables</h3>
	    <pre>
<?php var_dump($this->tables); ?>
        </pre>	    
        <h3>Systems</h3>
	    <pre>
<?php var_dump($this->systems); ?>
        </pre>	    
        <h3>Vues</h3>
	    <pre>
<?php var_dump($this->vues); ?>
    </pre></div>
</div>