<?php
/**
 * Page du formulaire d'envoi d'un fichier image
 *
 * @project sbm
 * @package SbmInstallation/view/sbm-installation/index
 * @filesource upload-image.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 avr. 2018
 * @version 2018-2.4.1
 */
$this->form->prepare(); // met le bon enctype

$ratio = 1;
if ($this->descriptif['width'] > 400 || $this->descriptif['height'] > 100) {
    $ratio1 = 400 / $this->descriptif['width'];
    $ratio2 = 100 / $this->descriptif['height'];
    $ratio = $ratio1 < $ratio2 ? $ratio1 : $ratio2;
}
$width = (int) $this->descriptif['width'] * $ratio;
$height = (int) $this->descriptif['height'] * $ratio;
?>
<h1>Choix d'un nouveau fichier image</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<h3><?php echo $this->label;?></h3>
		<img alt="<?= $this->label;?>" src="<?= $this->image;?>" width="
			<?php echo $width;?>" height="<?php echo $height;?>">
	</div>
	<div id="fiche-inner">
	<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('fname'));
echo $this->formHidden($this->form->get('label'));
echo $this->formHidden($this->form->get('width'));
echo $this->formHidden($this->form->get('height'));
echo $this->formHidden($this->form->get('type'));
echo $this->formHidden($this->form->get('mime'));
?>
        <fieldset class="sbm-page1">
			<div class="form-element row-inner">
            <?php $fileElement = $form->get('image-file'); ?>
            <?php echo $this->formLabel($fileElement); ?>
            <?php echo $this->formFile($fileElement); ?>
            <?php echo $this->formElementErrors($fileElement, $fileElement->getOption('error_attributes')); ?>
            </div>
			<div id="classe-edit-buttons" class="row-inner edit">
            <?php
            echo $this->formSubmit($this->form->get('submit')) .
                 $this->formSubmit($this->form->get('cancel'));
            ?>
            </div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
