<?php
/**
 * Page du formulaire d'envoi d'un fichier image
 *
 * @project sbm
 * @package SbmInstallation/view/sbm-installation/index
 * @filesource upload-image.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 oct. 2018
 * @version 2019-2.5.0
 */
$this->form->prepare(); // met le bon enctype

$ratio = 1;
if ($this->descriptif['width'] > 400 || $this->descriptif['height'] > 100) {
    $ratio1 = 400 / $this->descriptif['width'];
    $ratio2 = 100 / $this->descriptif['height'];
    $ratio = $ratio1 < $ratio2 ? $ratio1 : $ratio2;
}
$width = (int) $this->descriptif['width'] * $ratio;
$height = (int) $this->descriptif['height'] * $ratio;
?>
<h1>Choix d'un nouveau fichier image</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<h3><?= $this->label;?></h3>
		<img alt="<?= $this->label;?>" src="<?= $this->image;?>" width="
			<?= $width;?>" height="<?= $height;?>">
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('fname'));?>
		<?= $this->formHidden($this->form->get('label'));?>
		<?= $this->formHidden($this->form->get('width'));?>
		<?= $this->formHidden($this->form->get('height'));?>
		<?= $this->formHidden($this->form->get('type'));?>
		<?= $this->formHidden($this->form->get('mime'));?>
        <fieldset class="sbm-page1">
			<div class="form-element row-inner">
            <?php $fileElement = $form->get('image-file'); ?>
            <?= $this->formLabel($fileElement); ?>
            <?= $this->formFile($fileElement); ?>
            <?= $this->formElementErrors($fileElement, $fileElement->getOption('error_attributes')); ?>
            </div>
			<div id="classe-edit-buttons" class="row-inner edit">
            	<?= $this->formSubmit($this->form->get('submit'));?>
            	<?= $this->formSubmit($this->form->get('cancel'));?>
            </div>
		</fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>
