<?php
/**
 * Version du logiciel et de PHP, de ZF2
 *
 * @project sbm
 * @package SbmInstallation\view
 * @filesource version.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 28 juillet 2018
 * @version 2018-2.4.2
 */
use Zend\Version\Version;
use Zend\Json\Json;

define('SBM_VERSION', '2.4.2');

function versionTcpdfGitHub()
{
    $context = stream_context_create(
        [
            'http' => [
                'user_agent' => sprintf('Sbm/%s', SBM_VERSION)
            ]
        ]);
    $url = 'https://api.github.com/repos/tecnickcom/TCPDF/tags';
    $apiResponse = file_get_contents($url, false, $context);
    $decodedResponse = Json::decode($apiResponse, Json::TYPE_ARRAY);
    return $decodedResponse[0]['name'];
}

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath('/js/jquery.min.js'));
$this->inlineScript()->captureStart();
?>
$(function() {
    $("#jquery").html($.fn.jquery);
});
<?php
$this->inlineScript()->captureEnd();
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $this->url('sbminstall'),
        'title' => 'Retour'
    ]
];
$gdInfo = gd_info();
$gd_infos = 'Version ' . $gdInfo['GD Version'];
$sep = ' avec ';
if ($gdInfo['JPEG Support']) {
    $gd_infos .= $sep . 'support JPEG';
    $sep = ' et ';
}
if ($gdInfo['PNG Support']) {
    $gd_infos .= $sep . 'support PNG';
}
if ($gdInfo['GIF Read Support']) {
    $gd_infos .= $sep . 'lecture de GIF';
}
?>
<h1>Versions installées</h1>
<div id="version-wrapper" class="left-10px">
	<div id="version-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions([], $actions)?></div>
	</div>
	<div id="version-inner">
		<dl>
			<dt>Version de School bus manager</dt>
			<dd><?php echo SBM_VERSION; ?></dd>
			<dt>Version de PHP</dt>
			<dd><?php echo phpversion();?></dd>
			<dt>Version bibliothèque GD</dt>
			<dd><?php echo $gd_infos;?></dd>
			<dt>Version de ZF2</dt>
			<dd>Version installée: <?php echo Version::VERSION;?><br>
	    <?php if (Version::isLatest()):?>
	    C'est la dernière version.
	    <?php else :?>
	    Il y a une nouvelle version <?php echo Version::getLatest();?>
	    <?php endif;?>
	        </dd>
			<dt>Version JQuery</dt>
			<dd>Version installée: <span id="jquery"></span></dd>
			<dt>Version de TCPDF</dt>
			<dd>Version installée: <?php echo $vtcpdf = \TCPDF_STATIC::getTCPDFVersion();?><br>
		<?php if ($vtcpdf == versionTcpdfGitHub()) :?>
		C'est la dernière version.
		<?php else :?>
		Il y a une nouvelle version <?php echo versionTcpdfGitHub();?>
		<?php endif;?>
			</dd>
		</dl>
	</div>
	<div id="version-footer">
		<p class="sbm-description">Pour une nouvelle version de School Bus
			Manager, noter son numéro dans le fichier `version.phtml` du module
			SbmInstallation.</p>
	</div>
</div>