<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SbmPaiement\Module'                                              => __DIR__ . '/Module.php',
    'SbmPaiement\Controller\IndexController'                          => __DIR__ . '/src/SbmPaiement/Controller/IndexController.php',
    'SbmPaiement\Listener\AbstractListener'                           => __DIR__ . '/src/SbmPaiement/Listener/AbstractListener.php',
    'SbmPaiement\Listener\AppelPlateforme'                            => __DIR__ . '/src/SbmPaiement/Listener/AppelPlateforme.php',
    'SbmPaiement\Listener\PaiementOK'                                 => __DIR__ . '/src/SbmPaiement/Listener/PaiementOK.php',
    'SbmPaiement\Listener\ScolariteOK'                                => __DIR__ . '/src/SbmPaiement/Listener/ScolariteOK.php',
    'SbmPaiement\Plugin\AbstractPlateforme'                           => __DIR__ . '/src/SbmPaiement/Plugin/AbstractPlateforme.php',
    'SbmPaiement\Plugin\Exception'                                    => __DIR__ . '/src/SbmPaiement/Plugin/Exception.php',
    'SbmPaiement\Plugin\PlateformeInterface'                          => __DIR__ . '/src/SbmPaiement/Plugin/PlateformeInterface.php',
    'SbmPaiement\Plugin\SystemPay\Db\ObjectData\ObjectData'           => __DIR__ . '/src/SbmPaiement/Plugin/SystemPay/Db/ObjectData/ObjectData.php',
    'SbmPaiement\Plugin\SystemPay\Db\Table\TablePlugin'               => __DIR__ . '/src/SbmPaiement/Plugin/SystemPay/Db/Table/TablePlugin.php',
    'SbmPaiement\Plugin\SystemPay\Db\TableGateway\PluginTableGateway' => __DIR__ . '/src/SbmPaiement/Plugin/SystemPay/Db/TableGateway/PluginTableGateway.php',
    'SbmPaiement\Plugin\SystemPay\Form'                               => __DIR__ . '/src/SbmPaiement/Plugin/SystemPay/Form.php',
    'SbmPaiement\Plugin\SystemPay\Plateforme'                         => __DIR__ . '/src/SbmPaiement/Plugin/SystemPay/Plateforme.php',
    'SbmPaiement\Plugin\TablePluginInterface'                         => __DIR__ . '/src/SbmPaiement/Plugin/TablePluginInterface.php',
);
