<?php
/**
 * Vue de la liste des colonnes d'un document pdf
 *
 * Actions possibles depuis cette vue :
 * - ajouter une colonne
 * - modifier une colonne
 * - dupliquer une colonne
 * - supprimer une colonne
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource colonne-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 juil. 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_cancel = $this->url('sbmpdf');
$url_ajout = $this->url('sbmpdf', array(
    'action' => 'colonne-ajout',
    'page' => $this->page
));
$url_edit = $this->url('sbmpdf', array(
    'action' => 'colonne-edit',
    'page' => $this->page
));
$url_dupliquer = $this->url('sbmpdf', array(
    'action' => 'colonne-dupliquer',
    'page' => $this->page
));
$url_suppr = $this->url('sbmpdf', array(
    'action' => 'colonne-suppr',
    'page' => $this->page
));
$url_retour = $this->url('sbmpdf', array(
    'action' => 'table-liste',
    'page' => $this->page
));

$hiddens = array(
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'ordinal_table' => $this->document['ordinal_table'],
    'recordSource' => $this->document['recordSource'],
    'new_position' => count($this->data) + 1
);

$actions = array(
    'homepdf' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_cancel,
        'title' => 'Liste des documents'
    ),
    'retour' => array(
        'class' => 'fam-book-previous',
        'formaction' => $url_retour,
        'title' => 'Configuration du tableau'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajout,
        'title' => 'Nouvelle colonne'
    )
);

$buttons = array(
    'modifier' => array(
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier la colonne'
    ),
    'dupliquer' => array(
        'class' => 'fam-page-copy',
        'formaction' => $url_dupliquer,
        'title' => 'dupliquer la colonne'
    ),
    'supprimer' => array(
        'class' => 'fam-delete',
        'formaction' => $url_suppr,
        'title' => 'supprimer la colonne'
    )
);
?>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des colonnes d'un tableau pour un document pdf</h1>
			<ul>
				<li>Document: <?php echo $this->document['name'];?></li>
				<li>Numéro du tableau: <?php echo $this->document['ordinal_table'];?></li>
				<li>Source du document: <?php echo $this->document['recordSource'];?></li>
			</ul>
            <div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
            </div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="pdf">
			<tbody>
				<tr>
					<th>N°</th>
					<th>Nom</th>
					<th>Champ</th>
					<th>Ligne du bas</th>
					<th>Largeur</th>					
					<th></th>
				</tr>
            <?php foreach($data as $row): ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="ordinal_position"><?php echo $row['ordinal_position']; ?></td>
					<td class="thead"><?php echo $this->escapeHtml($row['thead']); ?></td>
					<td class="tbody"><?php echo $this->escapeHtml($row['tbody']); ?></td>
					<td class="tfoot"><?php echo $this->escapeHtml($row['tfoot']); ?></td>
					<td class="width"><?php echo $row['width']; ?></td>
					<td class="boutons">
            <?php
                $hiddens['doccolumnId'] = $row['doccolumnId'];
                $hiddens['ordinal_position'] = $row['ordinal_position'];
                echo $this->listeLigneActions($row['doccolumnId'], $hiddens, $buttons);
                ?>
				    </td>
				</tr>
        <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>