<?php
/**
 * Vue de modification / ajout / duplication d'une champ (field)
 *
 *  Variables de la vue :
 * - form
 * - page
 * - document
 * 
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource field-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 juil. 2015
 * @version 2015-1
 */
$this->headLink()
    ->prependStylesheet($this->basePath('/js/jquery-ui-1.11.4.custom/jquery-ui.min.css'))
    ->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()
    ->appendFile($this->basePath('/js/jquery.min.js'))
    ->appendFile($this->basePath('/js/jquery-ui-1.11.4.custom/jquery-ui.min.js'));
$this->inlineScript()->captureStart();
?>
 $("#accordion").accordion();
<?php
$this->inlineScript()->captureEnd();
// =============================================================================================

$url_retour = $this->url('sbmpdf', array(
    'action' => 'field-liste',
    'page' => $this->page
));
$hiddens = array(
    'documentId' => $this->document['documentId'],
    'name' => $this->document['name'],
    'recordSource' => $this->document['recordSource']
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
);
?>
<h1>Définition d'un champ d'un document</h1>
<ul>
	<li>Document: <?php echo $this->document['name'];?></li>
	<li>Source du document: <?php echo $this->document['recordSource'];?></li>
</ul>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="zone-actions">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<fieldset class="sbm-page1">
	   <?php
    echo $this->form()->openTag($this->form); // le formulaire doit avoir id="accordion" pour que ça marche
    echo $this->formHidden($this->form->get('docfieldId'));
    echo $this->formHidden($this->form->get('documentId'));
    echo $this->formHidden($this->form->get('name'));
    echo $this->formHidden($this->form->get('recordSource'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>

			<div id="accordion">
				<h3>Définition et configuration du champ</h3>
				<div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('ordinal_position'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_width'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_align'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_stretch'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_precision'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('fieldname_completion'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('filter'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('is_date'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('format'));?></div>
				</div>
				<h3>Contexte et position</h3>
				<div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('style'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('height'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_space'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_width'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_align'));?></div>
					<div class="sbm-document-table"><?php echo $this->formRow($this->form->get('label_stretch'));?></div>
				</div>
			</div>
			<div id="pdf-edit-buttons" class="row-inner edit">
	    <?php echo $this->formSubmit($this->form->get('submit')); ?>
	    <?php echo $this->formSubmit($this->form->get('cancel')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
        </fieldset>
	</div>
	<div id="fiche-footer"></div>
</div>