<?php
/**
 * Vue affichant la liste des documents pdf
 *
 *
 * @project sbm
 * @package SbmPdf/view/sbm-pdf/document
 * @filesource pdf-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 juil. 2015
 * @version 2015-2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$documents = $this->paginator->getCurrentItems();

$url_edit = $this->url('sbmpdf', array(
    'action' => 'pdf-edit',
    'page' => $this->page
));
$url_delete = $this->url('sbmpdf', array(
    'action' => 'pdf-suppr',
    'page' => $this->page
));
$url_dupliquer = $this->url('sbmpdf', array(
    'action' => 'pdf-dupliquer',
    'page' => $this->page
));
$url_apercu = $this->url('sbmpdf', array(
    'action' => 'pdf-apercu',
    'page' => $this->page
));
$url_ajouter = $this->url('sbmpdf', array(
    'action' => 'pdf-ajout',
    'page' => $this->page
));
$url_pdf = $this->url('sbmpdf', array(
    'action' => 'pdf-pdf',
    'page' => $this->page
));
$url_tableau = $this->url('sbmpdf', array(
    'action' => 'table-liste',
    'page' => $this->page
));
$url_etiquette = $this->url('sbmpdf', array('action' => 'etiquette-format', 'page' => $this->page));
$url_texte = $this->url('sbmpdf', array('action' => 'texte-format', 'page' => $this->page));
$url_retour = $this->url('sbmadmin');
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-report',
        'formaction' => $url_pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau document'
    )
);
$buttons = array(
    'modifier' => array(
        'class' => 'fam-pencil',
        'formaction' => $url_edit,
        'title' => 'modifier'
    ),
    'disposition' => array(),
    'dupliquer' => array(
        'class' => 'fam-page-copy',
        'formaction' => $url_dupliquer,
        'title' => 'dupliquer'
    ),
    'supprimer' => array(
        'class' => 'fam-delete',
        'formaction' => $url_delete,
        'title' => 'supprimer'
    ),
    'apercu' => array(
        'class' => 'fam-page-white-magnify',
        'formaction' => $url_apercu,
        'title' => 'aperçu'
    )
);
?>

<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left">
			<h1>Liste des documents pdf</h1>
	        <?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner pdf">
			<tbody>
				<tr>
					<th>Id</th>
					<th>Nom</th>
					<th>Source</th>
					<th>Filtre</th>
					<th>Ordre</th>
					<th>Format</th>
					<th title="Orientation">Or.</th>
					<th>Entête de doc.</th>
					<th>Fin de doc.</th>
					<th>Haut de page</th>
					<th>Pied de page</th>
					<th style="width: 110px;"></th>
				</tr>
            <?php foreach($documents as $test => $doc): ?>
                <?php
                $doc_title = $doc_footer = $page_title = $page_footer = '';
                if ($doc->docheader) {
                    $doc_title = 'title="' . $doc->title;
                    $tmp = $doc->docheader_subtitle;
                    if (! empty($tmp)) {
                        $doc_title .= "\n$tmp";
                    }
                    $doc_title .= '"';
                }
                if ($doc->docfooter) {
                    $doc_footer = 'title="' . $doc->docfooter_title;
                    $tmp = $doc->docfooter_string;
                    if (! empty($tmp)) {
                        $doc_footer .= "\n$tmp";
                    }
                    $doc_footer .= '"';
                }
                if ($doc->pageheader) {
                    $page_title = 'title="' . $doc->pageheader_title;
                    $tmp = $doc->pageheader_string;
                    if (! empty($tmp)) {
                        $doc_title .= "\n$tmp";
                    }
                    $page_title .= '"';
                }
                if ($doc->pagefooter) {
                    $page_footer = 'title="' . $doc->pagefooter_string . '"';
                }
                switch ($doc->disposition) {
                    case 'Tabulaire':
                        $buttons['disposition'] = array(
                            'class' => 'fam-table-edit',
                            'formaction' => $url_tableau,
                            'title' => 'configuration et contenu du tableau inclus dans le document'
                        );
                        break;
                    case 'Etiquette':
                        $buttons['disposition'] = array(
                            'class' => 'fam-table-edit',
                            'formaction' => $url_etiquette,
                            'title' => 'configuration et contenu des étiquettes'
                        );
                        break;
                    default: // Texte
                        $buttons['disposition'] = array(
                            'class' => 'fam-table-edit',
                            'formaction' => $url_texte,
                            'title' => 'configuration et contenu du texte'
                        );
                        break;
                }
                ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="documentId"><?php echo $doc->documentId; ?></td>
					<td class="name"><?php echo $this->escapeHtml($doc->name); ?></td>
					<td class="recordSource"><div style="max-width: 400px;"><?php echo nl2br($this->escapeHtml($doc->recordSource)); ?></div></td>
					<td class="filter"><?php echo $this->escapeHtml($doc->filter); ?></td>
					<td class="orderBy"><?php echo $this->escapeHtml($doc->orderBy); ?></td>
					<td class="pdf_page_format"><?php echo $doc->page_format; ?></td>
					<td class="pdf_page_orientation"><?php echo $doc->page_orientation; ?></td>
					<td class="docheader" <?php echo $doc_title;?>><?php echo $doc->docheader ? 'Oui' : ''; ?></td>
					<td class="docfooter" <?php echo $doc_footer;?>><?php echo $doc->docfooter ? 'Oui' : ''; ?></td>
					<td class="pageheader" <?php echo $page_title;?>><?php echo $doc->pageheader ? 'Oui' : ''; ?></td>
					<td class="pagefooter" <?php echo $page_footer;?>><?php echo $doc->pagefooter ? 'Oui' : ''; ?></td>
					<td class="boutons">
            <?php
                $hiddens = array(
                    'documentId' => $doc->documentId,
                    'name' => $doc->name,
                    'ordinal_table' => 1,
                    'recordSource' => $doc->recordSource
                );
                echo $this->listeLigneActions($doc->documentId, $hiddens, $buttons);
                ?>
				    </td>
				</tr>         
        <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
	    </div>
	</div>
</div>
