<?php
/**
 * Modèle de courrier pour l'avertissement des transporteurs en cours d'année
 * lorsqu'il y a des modifications d'inscriptions les concernant.
 *
 * Ce modèle doit recevoir les variables suivantes :
 * - services : tableau des serviceId sur lesquels il y a des modifications
 * - url_portail : url du portail des transporteurs
 *
 * @project sbm
 * @package SbmMail/template
 * @filesource avertissement-transporteur.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 avr. 2020
 * @version 2020-2.6.0
 */
if (count($this->services) == 1) {
    $lescircuits = 'le circuit suivant';
} else {
    $lescircuits = 'les circuits suivants';
}
?>
<p>Bienvenue au réseau TRA MOBILITÉ.</p>
<p>Des modifications ont été enregistrées dans les inscriptions des
	enfants inscrits sur <?= $lescircuits;?> :</p>
<ul>
<?php foreach ($this->services as $serviceId) :?>
    <li><?= $serviceId;?></li>
<?php endforeach;?>
</ul>
<p>
	Vous pouvez consulter l'état des inscriptions en vous connectant au
	portail des transporteurs à l'adresse :<br>
<?= $this->url_portail;?></p>
