<?php
/**
 * Modèle de courrier pour l'envoi du lien lors de la création d'un compte
 *
 * @project sbm
 * @package SbmMail/template
 * @filesource nouveau-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 avr. 2018
 * @version 2018-2.4.0
 */
?>
<p>Bonjour <?php echo $this->titre . ' ' . $this->prenom . ' ' . $this->nom;?>,</p>
<p>Bienvenue au service des transports de la <?php echo $this->client['name'];?>.</p>

<p>
	Pour éviter la création non autorisée d'un compte en votre nom, nous
	avons mis en place un dispositif nécessitant votre validation.<br> Si
	vous n'avez pas demandé à ouvrir ce compte, nous vous recommandons de
	suivre les instructions pour l'annuler.
</p>

<p>
	<b>CONFIRMER LE COMPTE</b><br> Pour confirmer cette demande d'ouverture
	de compte, suivez le lien suivant :<br>
    <?php echo $this->url_confirme;?></p>
<p>Si ce lien n'est pas actif dans vote logiciel de courrier, copiez le
	puis collez le dans la barre d'adresse de votre navigateur.</p>

<p>
	<b>ANNULER LE COMPTE</b><br> Si vous n'avez pas demandé l'ouverture de
	ce compte avec cette adresse de messagerie et si vous souhaitez annuler
	cette demande, suivez le lien suivant :<br>
    <?php echo $this->url_annule;?></p>
<p>Si ce lien n'est pas actif dans vote logiciel de courrier, copiez le
	puis collez le dans la barre d'adresse de votre navigateur.</p>

<p>En cas d'anomalie, merci de bien vouloir prévenir le service.</p>
<div style="text-align: center;">
	<b><?php echo $this->client['name'];?></b> <br><?php echo implode(' - ', $this->client['adresse']);?> - <?php echo $this->client['code_postal'] . ' ' . $this->client['commune'];?>
	<br>Tél. <?php echo $this->client['telephone'];?> - Email: <?php echo $this->client['email'];?>
</div>