<?php
/**
 * Modèle de courrier pour l'envoi du mail lors de l'oubli du mot de passe
 *
 * @project sbm
 * @package SbmMail/templates
 * @filesource oubli-mdp.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 avr. 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\StdLib;
?>
<p>Bonjour <?= $this->titre . ' ' . $this->prenom . ' ' . $this->nom;?>,</p>
<p>Bienvenue au réseau TRA MOBILITÉ.</p>
<p>Vous ne connaissez pas votre mot de passe.</p>
<div style="border: 1px solid black; padding-left: 4px;">
	<p>
		Pour en créer un nouveau, suivez le lien suivant :<br>
    <?= $this->url_confirme;?></p>
	<ul>
		<li style='list-style-type: "\00261B";'>Si ce lien n'est pas actif
			dans votre messagerie mail, copiez-le puis collez-le dans la barre
			URL de votre navigateur.</li>
	</ul>
	<p>Attention ! Ce lien ne fonctionne qu'une seule fois.</p>
</div>
<p>En cas d'anomalie, merci de bien vouloir prévenir le service.</p>
<div style="text-align: center;">
	<b><?= $this->client['name'];?></b> <br><?= implode(' - ', $this->client['adresse']);?> -
	<?= $this->client['code_postal'];?> <?= $this->client['commune'];?>
	<br>Tél. <?= StdLib::formatTelephone($this->client['telephone'], '.');?> - Email: <?= $this->client['email'];?>
</div>
