<?php
/**
 * Modèle de courrier pour l'envoi du lien lors de la création d'un compte
 *
 * @project sbm
 * @package SbmMail/template
 * @filesource ouverture-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 avr. 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\StdLib;
use SbmBase\Model\Session;

$dateenvoi = (new \DateTime(Session::get('as')['dateDebut']))->modify('8 days ago')->format(
    'd/m/Y');
?>
<p>Bonjour <?= $this->titre . ' ' . $this->prenom . ' ' . $this->nom;?>,</p>
<p>Bienvenue au réseau TRA MOBILITÉ.</p>
<p>
	Votre ou vos enfants ont besoin d'un PASS ANNUEL JUNIOR. Dorénavant,
	vous pouvez formuler vos demandes, suivre l'évolution de leur
	traitement et contrôler les informations qui vous concernent en vous
	connectant au site du réseau TRA MOBILITÉ par le lien suivant :<br>
    <?= $this->url_confirme;?></p>
<ul>
	<li style='list-style-type: "\00261B";'>Si ce lien n'est pas actif dans
		votre messagerie mail, copiez-le puis collez-le dans la barre URL de
		votre navigateur.</li>
	<li style='list-style-type: "\00261B";'>Les circuits sur lesquels vos
		enfants sont affectés et leurs horaires seront publiés à partir du <?=$dateenvoi;?>.</li>
</ul>
<p>En cas d'anomalie, merci de bien vouloir prévenir le service.</p>
<div style="text-align: center;">
	<b><?= $this->client['name'];?></b> <br><?= implode(' - ', $this->client['adresse']);?> -
	<?= $this->client['code_postal'];?> <?= $this->client['commune'];?>
	<br>Tél. <?= StdLib::formatTelephone($this->client['telephone'], '.');?> - Email: <?= $this->client['email'];?>
</div>