<?php
/**
 * Modèle de courrier pour l'envoi du lien lors de la création d'un compte
 *
 * @project sbm
 * @package SbmMail/template
 * @filesource ouverture-compte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 sept. 2018
 * @version 2018-2.4.5
 */
?>
<p>Bonjour <?= $this->titre . ' ' . $this->prenom . ' ' . $this->nom;?>,</p>
<p>Vous avez demandé l'inscription de vos enfants au service des
	transports de la <?= $this->client['name'];?>.</p>

<p>
	A partir de maintenant, vous pouvez suivre l'évolution du traitement de
	votre demande et contrôler les informations qui vous concernent en vous
	connectant au site de la communauté de communes par le lien suivant :<br>
    <?= $this->url_confirme;?></p>

<p>Le circuits sur lesquels vos enfants sont affectés et les horaires
	seront publiés durant la dernière semaine d'août.</p>

<p>Si ce lien n'est pas actif dans vote logiciel de courrier, copiez le
	puis collez le dans la barre d'adresse de votre navigateur.</p>
<p>En cas d'anomalie, merci de bien vouloir prévenir le service.</p>
<div style="text-align: center;">
	<b><?= $this->client['name'];?></b><br><?= implode(' - ', $this->client['adresse']);?> - <?= $this->client['code_postal'] . ' ' . $this->client['commune'];?>
	<br>Tél. <?= $this->client['telephone'];?> - Email: <?= $this->client['email'];?>
</div>