<p>&Agrave; la rentr&eacute;e scolaire %1$s votre enfant emprunte une ligne scolaire ou urbaine du r&eacute;seau TRA.</p>
<p>Du %2$s au %3$s un tarif r&eacute;duit vous est consenti. Pass&eacute; cette date, le tarif normal sera appliqu&eacute; et le r&eacute;seau TRA-mobilit&eacute; ne pourra garantir une place pour votre enfant.</p>
<p>INSCIPTIONS :</p>
<ul><li>Pour chacun de vos enfants &agrave; transporter, remplissez le formulaire et transmettez la photo</li>
<li>Lorsque tous vos enfants sont inscrits, payez selon le moyen de votre choix</li>
<li>Votre demande sera valid&eacute;e une fois le paiement effectu&eacute;</li>
<li>Vous recevrez les cartes de transport &agrave; partir du 24 ao&ucirc;t</li>
</ul>

<p>Pour en savoir plus :</p>
<ul>
	<li><span id="help-tarif" class="cursor-help orange"><strong>Voir la grille tarifaire<em class="fam-help">&nbsp;</em>
	</strong></span></li>
	<li><span id="help-payer" class="cursor-help orange"><strong>Comment payer l'abonnement&nbsp;<em class="fam-help">&nbsp;</em>
	</strong></span></li>
	<li><span id="help-internet" class="cursor-help orange"><strong>Si vous n'avez pas acc&egrave;s &agrave; Internet&nbsp;<em class="fam-help">&nbsp;</em>
	</strong></span></li>
	<li><span id="help-horszone" class="cursor-help orange"><strong>&Eacute;l&egrave;ve scolaris&eacute;
			en dehors du territoire Arlys&egrave;re&nbsp;</strong><em
		class="fam-help">&nbsp;</em></span></li>
</ul>
<div id="content-tarif" style="display: none;">
	Les tarifs d&eacute;pendent du lieu de r&eacute;sidence de l'&eacute;l&egrave;ve et du nombre d'enfants transport&eacute;s.
	Le tarif r&eacute;duit est consenti dans les cas :<ul><li>de renouvellement d'inscription effectu&eacute; avant la
	date limite du %4$s inclus,</li><li>d'&eacute;l&egrave;ve n'ayant jamais b&eacute;n&eacute;fici&eacute; de carte de transports scolaires sur le
	territoire Arlys&egrave;re,</li><li>de d&eacute;m&eacute;nagement effectu&eacute; apr&egrave;s la date limite des inscriptions,</li><li>d'inscription
	dans un &eacute;tablissement scolaire effectu&eacute; apr&egrave;s la date limite des inscriptions.</li></ul>
	<p class="cursor-zoom-out orange retour">
		<em class="fam-cancel">&nbsp;</em> Cacher
	</p>
</div>
<div  id="content-payer" style="display: none;">
	<p>Paiement de l'abonnement</p>
	<ul><li><strong>Par carte bancaire,</strong> par paiement en ligne s&eacute;curis&eacute; PAYBOX. Je re&ccedil;ois le re&ccedil;u de paiement par e-mail.</li>
		<li><strong>Par ch&egrave;que,</strong> &agrave; l'ordre de <strong>TRANSDEV ALBERTVILLE</strong>. J'inscris mon identifiant au dos du ch&egrave;que et je l'envoie par courrier &agrave; <strong>POINT INFO BUS, Place de la Gare - 73200 Albertville</strong></li>
		<li><strong>En esp&egrave;ces,</strong> en me pr&eacute;sentant au POINT INFO BUS, Place de la Gare &agrave; Albertville</li>
	</ul>
	<p class="cursor-zoom-out orange retour">
		<em class="fam-cancel">&nbsp;</em> Cacher
	</p>
</div>
<div id="content-internet" style="display: none;">
	<p>
		Vous avez la possibilit&eacute; d&rsquo;inscrire vos enfants en vous
		rendant &agrave; <strong>POINT INFO BUS, Place de la Gare &agrave; Albertville</strong>
		o&ugrave; un ordinateur est &agrave; votre disposition en libre service. Pensez &agrave;
		apporter les photos de vos enfants et &agrave; vous munir de votre moyen de paiement.
	</p>
	<p>Vous recevrez en retour la carte par courrier.</p>
	<p class="cursor-zoom-out orange retour">
		<em class="fam-cancel">&nbsp;</em> Cacher
	</p>
</div>
<div id="content-horszone" style="display: none;">
	<p>
		Si votre enfant est scolaris&eacute; en dehors du territoire Arlys&egrave;re, conformez-vous aux instructions publi&eacute;es sur le site de la <a
			href="%10$s" target="_blank">R&eacute;gion Auvergne Rhone Alpes</a>.
	</p>
	<p class="cursor-zoom-out orange retour">
		<em class="fam-cancel">&nbsp;</em> Cacher
	</p>
</div>
<p>Pour tout autre renseignement, adressez-vous directement au r&eacute;seau TRA-mobilit&eacute; &agrave; l'adresse :</p>
<p style="text-align: center;"><strong>POINT INFO BUS</strong><br>Place de la Gare<br>73200 Albertville<br>du lundi au vendredi, de 9h &agrave; 14h et de 15h &agrave; 17h45<br>le samedi de 9h &agrave; 12h</p>