<p>&Agrave; la rentr&eacute;e scolaire %1$s votre enfant emprunte une ligne du r&eacute;seau TRA.</p>
<p>Du %2$s au %4$s un tarif r&eacute;duit vous est consenti. Pass&eacute; cette date, le tarif normal sera appliqu&eacute; et le r&eacute;seau TRA ne pourra garantir une place pour votre enfant.</p>
<p>INSCRIPTIONS :</p>
<ul>
<li><strong>Pour chacun de vos enfants &agrave; transporter</strong>, remplissez le formulaire et transmettez leur photo</li>
<li>
<div id="content-tarif" style="display: none;">
<p>Les tarifs du PASS ANNUEL JUNIOR d&eacute;pendent du lieu de r&eacute;sidence de votre enfant :</p>
<table class="grille-tarifs">
<tbody>
<tr>
<th class="none" colspan="2" rowspan="2">&nbsp;</th>
<th colspan="4">TARIF PAR ENFANT</th>
</tr>
<tr>
<th>1<sup>er</sup></th>
<th>2<sup>e</sup></th>
<th>3<sup>e</sup></th>
<th>4<sup>e</sup> &amp; +</th>
</tr>
<tr>
<td rowspan="2">R&eacute;sidents&nbsp;Arlys&egrave;re</td>
<td>Tarif normal</td>
<td class="centre">165 &euro;</td>
<td class="centre">165 &euro;</td>
<td class="centre">83 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td>Tarif r&eacute;duit <span class="orange">*</span></td>
<td class="centre">110 &euro;</td>
<td class="centre">110 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td colspan="2">R&eacute;sidents et point de mont&eacute;e hors Arlys&egrave;re</td>
<td class="centre">200 &euro;</td>
<td class="centre">200 &euro;</td>
<td class="centre">100 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td rowspan="2">RPI &Eacute;cole &agrave; &Eacute;cole</td>
<td>Tarif normal</td>
<td class="centre">82,50 &euro;</td>
<td class="centre">82,50 &euro;</td>
<td class="centre">41,50 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td>Tarif r&eacute;duit <span class="orange">*</span></td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">28 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td rowspan="2">Double domiciliation <span class="orange">**</span><br />(d&eacute;livrance du 2<sup>&egrave;me</sup> PASS ANNUEL JUNIOR)</td>
<td>jusqu'au 10/07</td>
<td class="centre" colspan="4">gratuit</td>
</tr>
<tr>
<td>&agrave; partir du 11/07</td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">55 &euro;</td>
<td class="centre">gratuit</td>
</tr>
<tr>
<td colspan="2">Duplicata</td>
<td class="centre" colspan="4">15 &euro;</td>
</tr>
</tbody>
</table>
<p><strong><span class="orange">*</span> Le tarif r&eacute;duit est consenti exclusivement &agrave; la condition suivante :</strong></p>
<ul>
<li><strong>si</strong> l'inscription est effectu&eacute;e entre le %2$s et le %3$s inclus</li>
<li><strong>ou si</strong> l'&eacute;l&egrave;ve n'a jamais voyag&eacute; avec un abonnement annuel TRA sur le territoire de Arlys&egrave;re</li>
<li><strong>ou si</strong> un changement de domiciliation est av&eacute;r&eacute; apr&egrave;s le %3$s (justificatif &agrave; fournir)</li>
<li><strong>ou si</strong> l'insciption de l'&eacute;l&egrave;ve dans l'&eacute;tablissement scolaire est av&eacute;r&eacute;e apr&egrave;s le %3$s (justificatif &agrave; fournir)</li>
</ul>
<p><strong><span class="orange">**</span>DOUBLE DOMICILIATION (GARDE ALTERN&Eacute;E) :</strong></p>
<ul>
<li>Lorsque l&rsquo;enfant dispose de 2 adresses de domiciliation durant l&rsquo;ann&eacute;e scolaire, un 2<sup>&egrave;me</sup> PASS ANNUEL JUNIOR vous sera d&eacute;livr&eacute; &agrave; l&rsquo;adresse du 2<sup>&egrave;me</sup> parent.</li>
<li><strong><span class="orange">ATTENTION !</span></strong> Renseignez-les au moment de l&rsquo;inscription en ligne entre le 1er mai et le 10 juillet pour obtenir une gratuit&eacute;. &Agrave; partir du 11 juillet il vous sera appliqu&eacute; un tarif de 55&euro; par enfant. De plus, le r&eacute;seau TRA ne pourra garantir une place pour votre enfant.</li>
</ul>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<div id="content-payer" style="display: none;">
<p>Paiement de l'abonnement</p>
<ul>
<li><strong>Par carte bleue <span class="orange">*</span></strong> uniquement sur le site internet au moment de l'inscription.</li>
<li><strong>Par ch&egrave;que <span class="orange">**</span></strong> &agrave; libeller &agrave; <strong>TRANSDEV ALBERTVILLE</strong>.</li>
<li><strong>En esp&egrave;ces,</strong> &agrave; l'AGENCE TRA MOBILIT&Eacute;, Place de la Gare &agrave; Albertville durant les heures d'ouverture.</li>
</ul>
<div style="display: table;">
<div style="display: table-row; margin-top: 4px;">
<div style="display: table-cell;"><span class="orange">*</span></div>
<div style="display: table-cell;">Facilit&eacute; de paiement en 3 fois</div>
</div>
<div style="display: table-row; margin-top: 4px;">
<div style="display: table-cell;"><span class="orange">**</span></div>
<div style="display: table-cell;">Facilit&eacute; de paiement en 3 fois : contacter l'AGENCE TRA MOBILIT&Eacute; <br />IMPORTANT : mentionner au dos du ch&egrave;que :
<ul>
<li>le nom du responsable l&eacute;gal</li>
<li>le nom de l'&eacute;l&egrave;ve</li>
</ul>
</div>
</div>
</div>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<strong>&Agrave; la fin de l'inscription en ligne de votre/vos enfants</strong>, vous devez r&eacute;gler le PASS ANNUEL JUNIOR selon <span id="help-tarif" class="cursor-help orange">la grille tarifaire<em class="fam-help">&nbsp;</em> </span> et les <span id="help-payer" class="cursor-help orange">modalit&eacute;s de r&egrave;glement<em class="fam-help">&nbsp;</em> </span> en vigueur</li>
<li>Votre demande sera valid&eacute;e une fois le paiement effectu&eacute;</li>
<li>Vous recevrez le / les PASS ANNUEL JUNIOR directement par voie postale &agrave; l&rsquo;adresse indiqu&eacute;e &agrave; partir du %13$s.</li>
</ul>
<p><strong><em>V&eacute;rifiez votre adresse et vos num&eacute;ros de t&eacute;l&eacute;phone</em></strong> puis cliquez sur le bouton <strong><em>Inscrire un enfant</em></strong> pour commencer les inscriptions.</p>
<blockquote>%5$s</blockquote>
<div class="menu clearfix">%7$s</div>
<p>Pour en savoir plus :</p>
<ul>
<li>
<div id="content-horszone" style="display: none;">
<p>Si votre enfant est scolaris&eacute; en dehors du territoire d'Arlys&egrave;re (&agrave; l'exception des 2 coll&egrave;ges de M&eacute;g&egrave;ve) :</p>
<ul>
<li>S'il doit emprunter le r&eacute;seau TRA pour se rendre &agrave; la Gare routi&egrave;re d'Albertville, indiquez comme &eacute;tablissement scolaire lors de son inscription : &Eacute;TABLISSEMENT HORS ARLYS&Egrave;RE PAR ALBERTVILLE.</li>
<li>S'il doit emprunter le r&eacute;seau TRA pour se rendre &agrave; la Gare routi&egrave;re d'Ugine, indiquez comme &eacute;tablissement scolaire lors de son inscription : &Eacute;TABLISSEMENT HORS ARLYS&Egrave;RE PAR UGINE.</li>
<li>Pour les autres cas, conformez-vous aux instructions publi&eacute;es sur le site de la <a href="%10$s" target="_blank" rel="noopener">R&eacute;gion Auvergne Rh&ocirc;ne-Alpes</a>.</li>
</ul>
<p class="cursor-zoom-out orange retour"><em class="fam-cancel">&nbsp;</em> Cacher</p>
</div>
<span id="help-horszone" class="cursor-help orange"><strong>&Eacute;l&egrave;ve scolaris&eacute; en dehors du territoire d'Arlys&egrave;re&nbsp;</strong><em class="fam-help">&nbsp;</em></span></li>
</ul>
<p>Pour tout autre renseignement, adressez-vous directement &agrave; TRA MOBILIT&Eacute; :</p>
<div>
<ul>
<li style="list-style-type: '☛';"><strong>AGENCE TRA MOBILIT&Eacute;</strong>, Place de la Gare &agrave; Albertville / 04.79.89.77.32 - info-tra@transdev.com</li>
<li style="list-style-type: none;">du lundi au vendredi, de 9h &agrave; 12h et de 15h &agrave; 17h45 et le samedi de 9h &agrave; 12h</li>
</ul>
</div>