<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SbmAdmin\Module'                         => __DIR__ . '/Module.php',
    'SbmAdmin\Controller\IndexController'     => __DIR__ . '/src/SbmAdmin/Controller/IndexController.php',
    'SbmAdmin\Form\DocumentPdf'               => __DIR__ . '/src/SbmAdmin/Form/DocumentPdf.php',
    'SbmAdmin\Form\Libelle'                   => __DIR__ . '/src/SbmAdmin/Form/Libelle.php',
    'SbmAdmin\Form\User'                      => __DIR__ . '/src/SbmAdmin/Form/User.php',
    'SbmAdmin\Model\Db\Service\Libelle\Liste' => __DIR__ . '/src/SbmAdmin/Model/Db/Service/Libelle/Liste.php',
    'SbmAdmin\Model\Exception'                => __DIR__ . '/src/SbmAdmin/Model/Exception.php',
);
