<?php
/**
 * Détail d'une notification de paiement
 *
 *
 * @project sbm
 * @package SbmPaiement/Plugin/PayFiP/view
 * @filesource voir.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 28 juin 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmpaiement', [
    'action' => 'liste',
    'page' => $this->page
]);
$hiddens = [
    'op' => 'retour'
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
$dateheure = \DateTime::createFromFormat('dmYHi',
    $this->notification->dattrans . $this->notification->heurtrans)->format('d/m/Y H:i');
?>
<h1>Détail d'une notification de paiement</h1>
<div class="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="fiche-inner">
		<table class="plugin">
			<tbody>
				<tr>
					<td>Mode</td>
					<td><b><?= $this->notification->saisie; ?></b></td>
				</tr>
				<tr>
					<td>Titulaire</td>
					<td><b><?= $this->notification->titulaire; ?></b></td>
				</tr>
				<tr>
					<td>Montant</td>
					<td><b><?= $fmt->formatCurrency($this->notification->montant/100, 'EUR'); ?></b></td>
				</tr>
				<tr>
					<td>Exercice</td>
					<td><b><?= $this->notification->exer; ?></b></td>
				</tr>
				<tr>
					<td>Date de la transaction</td>
					<td><b><?= $dateheure;?></b></td>
				</tr>
				<tr>
					<td>Résultat de la transaction</td>
					<td><b><?= $this->notification->resultrans; ?></b></td>
				</tr>
				<tr>
					<td>Objet de la transaction</td>
					<td><b><?= $this->notification->objet; ?></b></td>
				</tr>
				<tr>
					<td>Référence de la dette</td>
					<td><b><?= $this->notification->refdet; ?></b></td>
				</tr>
				<tr>
					<td>Autorisation n°</td>
					<td><b><?= $this->notification->numauto; ?></b></td>
				</tr>
				<tr>
					<td>Email</td>
					<td><b><?= $this->notification->mel; ?></b></td>
				</tr>
				<tr>
					<td>Identifiant de l'opération</td>
					<td><b><?= $this->notification->idOp; ?></b></td>
				</tr>
				<tr>
					<td>Numéro client PayFiP</td>
					<td><b><?= $this->notification->numcli; ?></b></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>