<?php
/**
 * Page de modification d'un champ d'une liste de diffusion
 *
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource edit-segment.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2016
 * @version 2016-2.1
 */
use SbmCommun\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmmailchimp', [
    'action' => 'fields-liste'
]);
$hiddens = [
    'id_liste' => StdLib::getParam('id', $this->liste_info)
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1><?php echo $this->h1_msg; ?></h1>
<table>
  <tr>
    <th><?php echo StdLib::getParam('id', $this->liste_info); ?></th>
    <th><?php echo StdLib::getParam('name', $this->liste_info); ?></th>
    <th><?php echo StdLib::getParamR(['campaign_defaults','subject'], $this->liste_info);?></th>
    <th><?php ?></th>
  </tr>
</table>

<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id_liste'));
echo $this->formHidden($this->form->get('segment_id'));
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset class="sbm-page1">
			<div id="edit-name" class="row-inner edit"><?php echo $this->formRow($this->form->get('name')); ?></div>
			<div id="edit-name" class="row-inner edit"><?php echo $this->formRow($this->form->get('match')); ?></div>
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>
 