<?php
/**
 * Page de modification d'un champ d'une liste de diffusion
 *
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource edit-field.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 avr. 2018
 * @version 2018-2.4.0
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmmailchimp', [
    'action' => 'fields-liste'
]);
$hiddens = [
    'id_liste' => StdLib::getParam('id', $this->liste_info)
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1><?php echo $this->h1_msg; ?></h1>
<table>
	<tr>
		<th><?php echo StdLib::getParam('id', $this->liste_info); ?></th>
		<th><?php echo StdLib::getParam('name', $this->liste_info); ?></th>
		<th><?php echo StdLib::getParamR(['campaign_defaults','subject'], $this->liste_info);?></th>
		<th><?php ?></th>
	</tr>
</table>

<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('id_liste'));
echo $this->formHidden($this->form->get('csrf'));
?>
        <fieldset class="sbm-page1">
        <?php if ($this->form->has('merge_id')):?>
			<div id="edit-merge_id" class="row-inner edit"><?php echo $this->formRow($this->form->get('merge_id')); ?></div>
		<?php endif;?>
			<div id="edit-tag" class="row-inner edit"><?php echo $this->formRow($this->form->get('tag')); ?></div>
			<div id="edit-name" class="row-inner edit"><?php echo $this->formRow($this->form->get('name')); ?></div>
			<div id="edit-type" class="row-inner edit"><?php echo $this->formRow($this->form->get('type')); ?></div>
			<div id="edit-required" class="row-inner ajout"><?php echo $this->formRow($this->form->get('required')); ?></div>
			<div id="edit-default_value" class="row-inner ajout"><?php echo $this->formRow($this->form->get('default_value')); ?></div>
			<div id="edit-buttons" class="row-inner edit">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>