<?php
/**
 * Page de modification d'un champ d'une liste de diffusion
 *
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource edit-segment.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 oct. 2018
 * @version 2019-2.5.0
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmmailchimp', [
    'action' => 'segments-liste'
]);
$url_ajax = '';
$hiddens = [
    'id_liste' => StdLib::getParam('id', $this->liste_info)
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
$ajoutregle = [
    'addcondition' => [
        'class' => 'fam-add',
        'formaction' => $url_ajax,
        'title' => 'Ajouter une règle'
    ]
];
?>
<h1><?= $this->h1_msg; ?></h1>
<table>
	<tr>
		<th><?= StdLib::getParam('id', $this->liste_info); ?></th>
		<th><?= StdLib::getParam('name', $this->liste_info); ?></th>
		<th><?= StdLib::getParamR(['campaign_defaults','subject'], $this->liste_info);?></th>
		<th><?php ?></th>
	</tr>
</table>

<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="clearfix">

		<div id="formulaire">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('id_liste'));?>
        <?= $this->formHidden($this->form->get('segment_id'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
			<div id="colonne1" class="float-left">
				<fieldset class="sbm-page1">
					<legend>Définition</legend>
					<div id="edit-name" class="row-inner edit">
			         <?= $this->formRow($this->form->get('name')); ?>
			        </div>
					<div id="edit-match" class="row-inner edit">
			         <?= $this->formRow($this->form->get('match')); ?>
			        </div>
				</fieldset>
				<div class="top-6px">
					<span class="left-95px"><?= $this->formSubmit($this->form->get('submit'));?></span>
					<span class="left-10px"><?= $this->formSubmit($this->form->get('cancel')); ?></span>
				</div>
			</div>
			<div id="colonne2" class="float-left clearfix"
				style="min-width: 50%;">
				<fieldset id="conditions-wrapper" style="width: 100%;"
					class="float-left sbm-page1 left-10px">
					<legend>Les règles du filtre</legend>
					<div id="conditions-header" class="menu clearfix">
				    	<?= $this->listeZoneActions([], $ajoutregle);?>
				    </div>
					<div id="conditions"></div>
				</fieldset>
			</div>
			<?= $this->form()->closeTag();?>
		</div>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">Les règles sont combinées par l'opérateur
			logique indiqué.</p>
	</div>
</div>
<pre><?php print_r($this->segment);?></pre>
