<?php
/**
 * Affiche la liste des champs d'une liste de diffusion
 *
 * Reçoit les attributs 'fields' et 'liste_info'
 * 
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource fields-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 août 2016
 * @version 2016-2.2.0
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$categorieId = $this->auth->getCategorieId();
$url_retour = $this->url('sbmmailchimp');
if ($this->acl->hasResource('edit-field') && $this->acl->isAllowed($categorieId, 'edit-field')) {
    $url_edit = $this->url('sbmmailchimp', [
        'action' => 'edit-field'
    ]);
} else {
    $url_edit = false;
}
if ($this->acl->hasResource('dupliquer-field') && $this->acl->isAllowed($categorieId, 'dupliquer-field')) {
    $url_duplique = $this->url('sbmmailchimp', [
        'action' => 'dupliquer-field'
    ]);
} else {
    $url_duplique = false;
}
if ($this->acl->hasResource('creer-field') && $this->acl->isAllowed($categorieId, 'creer-field')) {
    $url_creer = $this->url('sbmmailchimp', [
        'action' => 'creer-field'
    ]);
} else {
    $url_creer = false;
}
if ($this->acl->hasResource('suppr-field') && $this->acl->isAllowed($categorieId, 'suppr-field')) {
    $url_suppr = $this->url('sbmmailchimp', [
        'action' => 'suppr-field'
    ]);
} else {
    $url_suppr = false;
}
$hiddens = [
    'id_liste' => StdLib::getParam('id', $this->liste_info),
    'liste_name' => StdLib::getParam('name', $this->liste_info)
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
if ($url_creer) {
    $actions['creer'] = [
        'class' => 'fam-add',
        'formaction' => $url_creer,
        'title' => 'Créer une nouvelle liste de diffusion'
    ];
}
$this->source->setItemCountPerPage(20);
$this->source->setCurrentPageNumber($this->page);
$data = $this->source->getCurrentItems();
?>
<h1>Listes des champs d'une liste de diffusion de MailChimp</h1>
<table>
	<tr>
		<th><?php echo StdLib::getParam('id', $this->liste_info); ?></th>
		<th><?php echo StdLib::getParam('name', $this->liste_info); ?></th>
		<th><?php echo StdLib::getParamR(['campaign_defaults','subject'], $this->liste_info);?></th>
		<th><?php ?></th>
	</tr>
</table>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="circuits">
			<tbody>
				<tr>
					<th style="min-width: 2em;">Identifiant</th>
					<th style="min-width: 10em;">Tag</th>
					<th style="min-width: 15em">Nom</th>
					<th style="min-width: 5em;">Type</th>
					<th style="min-width: 5em;">Obligatoire</th>
					<th>Valeur par défaut</th>
					<th></th>
				</tr>
	    <?php foreach($data as $field): ?>
	    <?php $hiddens['merge_id'] = $field['merge_id']; ?>
	    <?php $hiddens['field_name'] = $field['name']; ?>
	    <?php
        $buttons = [];
        if ($url_edit) {
            $buttons['edit'] = [
                'class' => 'fam-pencil',
                'formaction' => $url_edit,
                'title' => 'modifier le champ'
            ];
        }
        if ($url_duplique) {
            $buttons['dupliquer'] = [
                'class' => 'fam-page-copy',
                'formaction' => $url_duplique,
                'title' => 'dupliquer le champ'
            ];
        }
        if ($url_suppr) {
            $buttons['suppr'] = [
                'class' => 'fam-delete',
                'formaction' => $url_suppr,
                'title' => 'supprimer le champ'
            ];
        }
        ?>
	    <tr class="<?php echo $this->cycle(['even', 'odd'])->next();?>">
					<td><?php echo $field['merge_id'];?></td>
					<td><?php echo $this->escapeHtml($field['tag']);?></td>
					<td><?php echo $this->escapeHtml($field['name']);?></td>
					<td><?php echo $this->escapeHtml($field['type']);?></td>
					<td><?php echo $field['required'] ? 'Oui' : 'Non';?></td>
					<td><?php echo $this->escapeHtml($field['default_value']);?></td>
					<td><?php echo $this->listeLigneActions($field['merge_id'], $hiddens, $buttons);?></td>
				</tr>
	    <?php endforeach;?>
	    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->source, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
</div>
