<?php
/**
 * Page de gestion des listes de diffusion
 *
 * Utilise l'API de MailChimp
 * 
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('login', [
    'action' => 'home-page'
]);
$categorieId = $this->auth->getCategorieId();
if ($this->acl->hasResource('edit-liste') &&
    $this->acl->isAllowed($categorieId, 'edit-liste')) {
    $url_edit = $this->url('sbmmailchimp', [
        'action' => 'edit-liste'
    ]);
} else {
    $url_edit = false;
}
if ($this->acl->hasResource('dupliquer-liste') &&
    $this->acl->isAllowed($categorieId, 'dupliquer-liste')) {
    $url_duplique = $this->url('sbmmailchimp', [
        'action' => 'dupliquer-liste'
    ]);
} else {
    $url_duplique = false;
}
if ($this->acl->hasResource('creer-liste') &&
    $this->acl->isAllowed($categorieId, 'creer-liste')) {
    $url_creer = $this->url('sbmmailchimp', [
        'action' => 'creer-liste'
    ]);
} else {
    $url_creer = false;
}
if ($this->acl->hasResource('suppr-liste') &&
    $this->acl->isAllowed($categorieId, 'suppr-liste')) {
    $url_suppr = $this->url('sbmmailchimp', [
        'action' => 'suppr-liste'
    ]);
} else {
    $url_suppr = false;
}
if ($this->acl->hasResource('fields-liste') &&
    $this->acl->isAllowed($categorieId, 'fields-liste')) {
    $url_fields = $this->url('sbmmailchimp', [
        'action' => 'fields-liste'
    ]);
} else {
    $url_fields = false;
}
if ($this->acl->hasResource('segments-liste') &&
    $this->acl->isAllowed($categorieId, 'segments-liste')) {
    $url_segments = $this->url('sbmmailchimp', [
        'action' => 'segments-liste'
    ]);
} else {
    $url_segments = false;
}
if ($this->acl->hasResource('liste-members') &&
    $this->acl->isAllowed($categorieId, 'liste-members')) {
    $url_members = $this->url('sbmmailchimp', [
        'action' => 'liste-members'
    ]);
} else {
    $url_members = false;
}
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
if ($url_creer) {
    $actions['creer'] = [
        'class' => 'fam-add',
        'formaction' => $url_creer,
        'title' => 'Créer une nouvelle liste de diffusion'
    ];
}
if ($this->source->count()) {
    $this->source->setItemCountPerPage(20);
    $this->source->setCurrentPageNumber($this->page);
    $data = $this->source->getCurrentItems();
} else {
    $data = [];
}
?>
<h1>Gestion des listes de diffusion par MailChimp</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
			<?php if ($this->message) :?>
			    <?= sprintf('<ul class="%s"><li>%s</li><ul>', 'info', $this->message);?>
			<?php endif;?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="circuits">
			<tbody>
				<tr>
					<th style="min-width: 8em;">Identifiant</th>
					<th style="min-width: 30em;">Nom de la liste</th>
					<th style="min-width: 5em;">Inscrits</th>
					<th></th>
				</tr>
	    <?php foreach($data as $liste): ?>
	    <?php
        $hiddens = [
            'id_liste' => $liste['id'],
            'liste_name' => $liste['name']
        ];
        ?>
	    <?php
        $buttons = [];
        if ($url_edit) {
            $buttons['edit'] = [
                'class' => 'fam-pencil',
                'formaction' => $url_edit,
                'title' => 'modifier'
            ];
        }
        if ($url_duplique) {
            $buttons['dupliquer'] = [
                'class' => 'fam-page-copy',
                'formaction' => $url_duplique,
                'title' => 'dupliquer la liste'
            ];
        }
        if ($url_suppr) {
            $buttons['suppr'] = [
                'class' => 'fam-delete',
                'formaction' => $url_suppr,
                'title' => 'supprimer la liste'
            ];
        }
        if ($url_fields) {
            $buttons['fields'] = [
                'class' => 'fam-table',
                'formaction' => $url_fields,
                'title' => 'liste des champs'
            ];
        }
        if ($url_segments) {
            $buttons['segments'] = [
                'class' => 'fam-basket',
                'formaction' => $url_segments,
                'title' => 'liste des segments'
            ];
        }
        if ($url_members) {
            $buttons['members'] = [
                'class' => 'fam-group',
                'formaction' => $url_members,
                'title' => 'liste des membres'
            ];
        }
        ?>
	    <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td><?= $liste['id'];?></td>
					<td><?= $this->escapeHtml($liste['name']);?></td>
					<td><?= $liste['stats']['member_count'];?></td>
					<td><?= $this->listeLigneActions($liste['id'], $hiddens, $buttons);?></td>
				</tr>
	    <?php endforeach;?>
	    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
		<?php if ($this->source->count()) :?>
    		<?= $this->paginationControl($this->source, 'Sliding', 'sbm/pagination', []);?>
		<?php endif;?>
		</div>
	</div>
</div>