<?php
/**
 * Affiche la liste des champs d'une liste de diffusion
 *
 * Reçoit les attributs 'segments' et 'liste_info'
 * 
 * @project sbm
 * @package SbmMailChimp/view/sbm-mail-chimp/index
 * @filesource segments-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2016
 * @version 2016-2.1
 */
use SbmCommun\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmmailchimp');
$url_edit = $this->url('sbmmailchimp', [
    'action' => 'edit-segment'
]);
$url_duplique = $this->url('sbmmailchimp', [
    'action' => 'dupliquer-segment'
]);
$url_creer = $this->url('sbmmailchimp', [
    'action' => 'creer-segment'
]);
$url_suppr = $this->url('sbmmailchimp', [
    'action' => 'suppr-segment'
]);
$url_members = $this->url('sbmmailchimp', [
    'action' => 'segment-members'
]);
$hiddens = [
    'id_liste' => StdLib::getParam('id', $this->liste_info),
    'liste_name' => StdLib::getParam('name', $this->liste_info)
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'creer' => [
        'class' => 'fam-add',
        'formaction' => $url_creer,
        'title' => 'Créer un nouveau segment dans une liste de diffusion'
    ]
];
$id_liste = StdLib::getParam('id', $this->liste_info);
$liste_name = StdLib::getParam('name', $this->liste_info);
$this->source->setItemCountPerPage(20);
$this->source->setCurrentPageNumber($this->page);
$data = $this->source->getCurrentItems();
?>
<h1>Listes des segments d'une liste de diffusion de MailChimp</h1>
<table>
	<tr>
		<th><?php echo $id_liste; ?></th>
		<th><?php echo $liste_name; ?></th>
		<th><?php echo StdLib::getParamR(['campaign_defaults','subject'], $this->liste_info);?></th>
		<th><?php ?></th>
	</tr>
</table>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
if ($this->message) {
    $ligne = sprintf('<ul class="%s"><li>%s</li><ul>','info', $this->message);
    echo $ligne;
}
?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="circuits">
			<tbody>
				<tr>
					<th style="min-width: 5em;">Identifiant</th>
					<th style="min-width: 15em">Nom</th>
					<th style="min-width: 5em;">Conditions</th>
					<th style="min-width: 5em;">Inscrits</th>
					<th></th>
				</tr>
	    <?php foreach($data as $segment): ?>
	    <?php $hiddens['id_liste'] = $id_liste; ?>
	    <?php $hiddens['liste_name'] = $liste_name; ?>
	    <?php $hiddens['segment_id'] = $segment['id']; ?>
	    <?php $hiddens['segment_name'] = $segment['name']; ?>
	    <?php
        $buttons = [
            'edit' => [
                'class' => 'fam-pencil',
                'formaction' => $url_edit,
                'title' => 'modifier le segment'
            ],
            'dupliquer' => [
                'class' => 'fam-page-copy',
                'formaction' => $url_duplique,
                'title' => 'dupliquer le segment'
            ],
            'suppr' => [
                'class' => 'fam-delete',
                'formaction' => $url_suppr,
                'title' => 'supprimer le segment'
            ],
            'members' => [
                'class' => 'fam-group',
                'formaction' => $url_members,
                'title' => 'liste des membres'
            ]
        ];
        $match = StdLib::getParamR([
            'options',
            'match'
        ], $segment, '') == 'any' ? 'OU' : 'ET';
        $n_conditions = count(StdLib::getParamR([
            'options',
            'conditions'
        ], $segment, []));
        $conditions = sprintf('%s (%d)', $match, $n_conditions);
        ?>
	    <tr
					class="<?php echo $this->cycle(['even', 'odd'])->next();?>">
					<td><?php echo $segment['id'];?></td>
					<td><?php echo $this->escapeHtml($segment['name']);?></td>
					<td><?php echo $conditions;?></td>
					<td><?php echo $this->escapeHtml($segment['member_count']);?></td>
					<td><?php echo $this->listeLigneActions($segment['id'], $hiddens, $buttons);?></td>
				</tr>
	    <?php endforeach;?>
	    </tbody>
		</table>
	</div>
	<div id="liste-footer">
	    <div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->source, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
</div>