<?php
/**
 * Page reçue par les parents habitant hors zone autorisée.
 * 
 * @project sbm
 * @package SbmFront/view/sbm-front/index
 * @filesource hors-zone.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 29 sept. 2018
 * @version 2019-2.5.0
 */
$format = <<<EOT
<p>Vous habitez dans la commune de %s.</p>
<p>Les inscriptions en ligne ne sont pas autorisées pour les habitants de cette commune.</p>
<p>Remplissez votre demande sur un formulaire papier et transmettez le au service Transport à l'adresse :</p>
<div class="centre">
<a href="%s" class="accueil">%s</a><br>
%s<br>
%s<br>
%s %s<br>
Tél : %s<br>
Mail : %s</br>
</div>
EOT;

$explication = sprintf($format, $this->commune, $this->accueil, $this->client['name'],
    $this->client['adresse'][0], $this->client['adresse'][1], $this->client['code_postal'],
    $this->client['commune'], $this->telephone($this->client['telephone']),
    $this->client['email']);

?>
<h1>Inscription en ligne non autorisée</h1>
<div class="fiche-wrapper">
	<div class="zone-actions"></div>
	<div class="flashMessenger float-right">
	<?= $this->flashMessenger()->render('success');?>
	<?= $this->flashMessenger()->render('warning');?>
	<?= $this->flashMessenger()->render('error');?>
	<?= $this->flashMessenger()->render('info');?>
	<?= $this->flashMessenger()->render('default');?>
	</div>
	<div class="explication"><?= $explication;?></div>
</div>