<?php
/**
 * Page d'accueil après la période d'inscription
 *
 *
 * @project sbm
 * @package module/SbmFront
 * @filesource view/sbm-front/index/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 avr. 2018
 * @version 2018-2.4.0
 */
$url_gestion = $this->url('sbmgestion');
$url_install = $this->url('sbminstall');
$url_admin = $this->url('sbmadmin');
$url_carte = $this->url('sbmcarte', [
    'action' => 'etablissements'
]);


    // après la période d'inscription
    $format = <<<EOT
<p class="premiere">La période d'inscription %s est close.</p>
<p>Si vous avez indiqué votre adresse email, vous pouvez consulter l’affectation de vos enfants, 
    trouver les horaires, correspondre avec le service grâce à votre compte personnel.</p>
<p>Pour tout renseignement ou pour une nouvelle inscription, adressez vous directement au 
    service Transport à l'adresse :</p>
<div class="centre">
<a href="%s" class="accueil">%s</a><br>
%s<br>
%s<br>
%s %s<br>
Tél : %s<br>
Mail : %s</br>

</div>
EOT;
    
    $msg = sprintf($format, 
        $this->as,
        $this->accueil,
        $this->client['name'],
        $this->client['adresse'][0],
        $this->client['adresse'][1],
        $this->client['code_postal'],
        $this->client['commune'],
        $this->telephone($this->client['telephone']),
        $this->client['email']
        );
?>
<div class="table-page1">
	<div class="row">
		<div class="column1 compressed">
			<div class="centre">
				<h1>Transports scolaires</h1>
				<h3 class="accueil">Inscription et paiement en ligne</h3>
			</div>
		    <?php echo $msg; ?>
		</div>
		<div class="column2">
			<div class="flashMessenger">
		    <?php
    echo $this->flashMessenger()->render('success');
    echo $this->flashMessenger()->render('warning');
    echo $this->flashMessenger()->render('error');
    echo $this->flashMessenger()->render('info');
    echo $this->flashMessenger()->render('default');
    ?>
		    </div>
		    <?php echo $this->form()->openTag($this->form); ?>
		    <fieldset class="sbm-page1">
				<div class="centre">
					<h3>Identifiez-vous</h3>
					<div class="sbm-description">(si vous avez déjà créé votre compte)</div>
				</div>	
		    <?php echo $this->formRow($this->form->get('email')); ?>
		    <br>
		    <?php echo $this->formRow($this->form->get('mdp')); ?>
		    <br>
				<div class="centre"><?php echo $this->formSubmit($this->form->get('signin')); ?></div>
				<div class="centre top-6px">
					<a
						href="<?php echo $this->url('login', ['action' => 'mdp-demande']); ?>">Mot
						de passe oublié ?</a>
				</div>
			</fieldset>
			<p></p>
			<?php if ($this->etat['etat'] == 1): ?>
			<fieldset class="sbm-page1">
				<div class="centre">
					<h3>Nouvel utilisateur</h3>
					<div class="sbm-description">(si vous n'avez pas de compte)</div>
					<div class="centre">
					    <?php echo $this->formSubmit($this->form->get('signup')); ?>
					</div>
				</div>
			</fieldset>
			<p></p>
			<?php endif;?>
			<?php echo $this->form()->closeTag(); ?>
			<div class="sbm-page1">
				<a href="<?php echo $url_carte;?>"><img
					alt="carte des établissements desservis"
					src="img/logocarteetablissements.png"></a>
			</div>
		</div>
	</div>
</div>
