<?php
/**
 * Page d'accueil avant la période d'inscription
 *
 *
 * @project sbm
 * @package module/SbmFront/view/sbm-front/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2019
 * @version 2019-2.5.0
 */
$msg = include 'index-avant/demo.php';

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->headScript()->appendFile($this->basepath('/js/front/index.js'));

$url_carte = $this->url('sbmcarte', [
    'action' => 'etablissements'
]);
?>
<div class="table-page1">
	<div class="row">
		<div class="column1 compressed">
			<div class="centre">
				<h1>Transports scolaires</h1>
				<h3 class="accueil">Inscription et paiement en ligne</h3>
			</div>
		    <?= $msg; ?>
		</div>
		<div class="column2">
			<div class="vecartement-6px">
            <?= $this->flashMessenger()->render('success');?>
            <?= $this->flashMessenger()->render('warning');?>
            <?= $this->flashMessenger()->render('error');?>
            <?= $this->flashMessenger()->render('info');?>
            <?= $this->flashMessenger()->render('default');?>
		    </div>
		    <?= $this->form()->openTag($this->form); ?>
		    <fieldset class="sbm-page1">
				<div class="centre">
					<h3>Identifiez-vous</h3>
					<div class="sbm-description">(si vous avez déjà créé votre compte)</div>
				</div>	
		    <?= $this->formRow($this->form->get('email')); ?>
		    <br>
		    <?= $this->formRow($this->form->get('mdp')); ?>
		    <br>
				<div class="centre"><?= $this->formSubmit($this->form->get('signin')); ?></div>
				<div class="centre top-6px">
					<a href="<?= $this->url('login', ['action' => 'mdp-demande']); ?>">Mot
						de passe oublié ?</a>
				</div>
			</fieldset>
			<div class="vecartement-6px"></div>
			<?= $this->form()->closeTag(); ?>
			<div class="sbm-page1">
				<a href="<?= $url_carte;?>"><img
					alt="carte des établissements desservis"
					src="img/logocarteetablissements.png"></a>
			</div>
		</div>
	</div>
</div>
