<?php
/**
 * Page d'accueil
 *
 *
 * @project sbm
 * @package module/SbmFront
 * @filesource view/sbm-front/index/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept.2018
 * @version 2018-2.4.5
 */
$url_gestion = $this->url('sbmgestion');
$url_install = $this->url('sbminstall');
$url_admin = $this->url('sbmadmin');
$url_carte = $this->url('sbmcarte', ['action' => 'etablissements']);

if ($this->etat['etat'] == 0) {
    // avant le début de la période d'inscription
    $format = <<<EOT
<p class="premiere">La période d'inscription %s sera ouverte du %s au %s.</p>
<p>Durant cette période, vous pourrez inscrire ici vos enfants au service de transport scolaire organisé par %s. Les inscriptions ne seront définitives qu'après paiement des prestations demandées.</p>
<p>Les paiements pourront se faire :</p><ul>
<li>en ligne par carte bancaire, sur une connexion sécurisée, avant le %s pour recevoir la carte de transport par courrier ;</li>
<li>au-delà, par chèque ou espèces, lors des permanences à %s.</li></ul>
<p>Pour tout autre renseignement ou tout autre mode d'inscription, vous pouvez vous adresser directement au service Transport à l'adresse :</p>
EOT;
    
    $msg = sprintf($format, $this->as, $this->etat['dateDebut']->format('d/m/Y'), $this->etat['dateFin']->format('d/m/Y'), $this->client['name'], $this->etat['echeance']->format('d/m/Y'), $this->client['name']);
} elseif ($this->etat['etat'] == 1) {
    // durant la période d'inscriptions
    $format = <<<EOT
<p class="premiere">Le site de démonstration est ouvert du %s au %s.</p>
<p>Durant cette période, vous pouvez créer votre propre compte en tant que parent et simuler une ou plusieurs inscriptions.</p>
<p>Vous pouvez également entrer avec les rôles suivants :</p><ul>
<li>en tant que <b>parent</b> avec le compte <em>parent.demo@dafap.fr</em>;</li>
<li>en tant que <b>administrateur</b> avec le compte <em>admin.demo@dafap.fr</em>;</li>
<li>en tant que <b>gestionnaire</b> avec le compte <em>gestion.demo@dafap.fr</em>;</li>
<li>en tant que <b>secrétariat</b> avec le compte <em>secretariat.demo@dafap.fr</em>;</li>
<li>en tant que <b>établissement</b> avec le compte <em>etablissement.demo@dafap.fr</em>;</li>
<li>en tant que <b>transporteur</b> avec le compte <em>transporteur.demo@dafap.fr</em>.</li></ul>
<p>Pour tous les comptes démo, le mot de passe est <b>essai33SBM</b> (le même pour tous).</p>
<p>Pour tout autre renseignement, vous pouvez vous adresser à :</p>
EOT;
    
    $msg = sprintf($format, $this->etat['dateDebut']->format('d/m/Y'), $this->etat['dateFin']->format('d/m/Y'));    
} else {

    // après la période d'inscription
    $format = <<<EOT
<p class="premiere">La période de test est close.</p>
<p>Actuellement, vous pouvez accéder, en consultation seulement, à l'espace parent par le compte <em>parent.demo@dafap.fr</em> et le mot de passe <em>essai33SBM</em></p>
<p>L'application propose aussi les rôles d'administrateur et de gestionnaire, ainsi qu'un portail pour les établissements scolaires, pour les transporteurs et pour le service de renseignement des organisateurs.</p>
<p>Pour l'ouverture d'une période de test complet ou pour tout renseignement, adressez vous directement à School Bus Manager par courrier ou SMS :</p>
EOT;
    
    $msg = sprintf($format, $this->as);
}
?>
<div class="centre">
	<h1>Transports scolaires</h1>
	<h3 class="accueil">Inscription et paiement en ligne</h3>
</div>
<div class="table-page1">
	<div class="row">
		<div class="column1">
		    <?= $msg; ?>
			<div class="centre">
				<a href="<?= $this->accueil;?>" class="accueil"><?= $this->client['name'];?></a><br>
				<?= $this->client['adresse'][0]; ?><br>
				<?php if (!empty($this->client['adresse'][1])) :?>
					<?= $this->client['adresse'][1]; ?>
					<br>
				<?php endif;?>
				<?= $this->client['code_postal']; ?> 
				<?= $this->client['commune']; ?>
				<br>
				Tél. <?= $this->telephone($this->client['telephone']); ?>
			</div>
		</div>
		<div class="column2">
		    <div class="flashMessenger">
		    	<?= $this->flashMessenger()->render('success');?>
		    	<?= $this->flashMessenger()->render('warning');?>
		    	<?= $this->flashMessenger()->render('error');?>
		    	<?= $this->flashMessenger()->render('info');?>
		    	<?= $this->flashMessenger()->render('default');?>
		    </div>
		    <?= $this->form()->openTag($this->form); ?>
		    <fieldset class="sbm-page1">
				<div class="centre">
					<h3>Identifiez-vous</h3>
					<div class="sbm-description">(si vous avez déjà créé votre compte)</div>
				</div>	
		    <?= $this->formRow($this->form->get('email')); ?>
		    <br>
		    <?= $this->formRow($this->form->get('mdp')); ?>
		    <br>
				<div class="centre"><?= $this->formSubmit($this->form->get('signin')); ?></div>
				<div class="centre top-6px">
					<a
						href="<?= $this->url('login', ['action' => 'mdp-demande']); ?>">Mot
						de passe oublié ?</a>
				</div>
			</fieldset>
			<p></p>
			<?php if ($this->etat['etat'] == 1): ?>
			<fieldset class="sbm-page1">
			<div class="centre">
					<h3>Nouvel utilisateur</h3>
					<div class="sbm-description">(si vous n'avez pas de compte)</div>
					<div class="centre"><?= $this->formSubmit($this->form->get('signup')); ?></div>
				</div>
			</fieldset>
			<p></p>
			<?php endif;?>
			<?= $this->form()->closeTag(); ?>
			<div class="sbm-page1"><a href="<?= $url_carte;?>"><img alt="carte des établissements desservis" src="img/logocarteetablissements.png"></a></div>
		</div>
	</div>
</div>
