<?php
/**
 * Mes tests
 *
 *
 * @project sbm
 * @package SbmFront
 * @filesource 
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 mai 2014
 * @version 2014-1
 */
echo '<div class="clearfix"></div>';
echo '<div style="overflow:scroll">';
echo 'args<pre>';

if ($this->args instanceof \Traversable) {
    foreach ($this->args as $row) {
        print_r($row);
    }
} else {
    print_r($this->args);
}
echo '</pre>var_dump(args) donne :';
var_dump($this->args);
echo 'X = ' . $this->x;
echo '</div>';
?>
<form method="post">
<div class="centre">
<a href="<?php echo $this->url('home', array('action'=> 'test', 'param' => 'signup'));?>">
<input type="submit" name="signup" value="Créer un compte" id="sbm-signup" class="default sbm-signup">
</a>
</div>
</form>
