<?php
/**
 * Mes tests
 *
 *
 * @project sbm
 * @package SbmFront
 * @filesource
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 juin 2019
 * @version 2019-2.5.0
 */
?>
<h1>DEBUG &amp; TESTS</h1>
<div style="overflow: scroll;">
	<h3>var_dump</h3>
	<?php var_dump($this->obj);?>
<h3>print_r</h3>
	<pre>
	<?php print_r($this->obj);?>
</pre>

</div>