<?php
/**
 * Mes tests
 *
 *
 * @project sbm
 * @package SbmFront
 * @filesource
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 fév. 2018
 * @version 2019-2.5.0
 */
if ($this->type == 'html') {
    $this->jQuery();
    $this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
    $this->headScript()->captureStart();
    ?>
tinymce.init({
    selector: ".tinymce-body",
    language: "fr_FR",
    menubar : false,
    //statusbar: false,
     plugins: [
    'advlist autolink lists link image charmap print preview anchor textcolor noneditable',
    'searchreplace visualblocks code fullscreen save',
    'insertdatetime media table contextmenu paste code wordcount'
  ],
  toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | preview | code | save',
 });
<?php
$this->headScript()->captureEnd();
}
?>
<h1>DEBUG</h1>
<form method="post"></form>
<!--textarea name="content" style="width:1000px; height:400px;"-->
<?=$this->obj;//$this->escapeHtml($this->obj);?><!--/textarea-->
<!--input type="submit" name="submit" value="Enregistrer"-->
