<?php 
$this->declarevars(array('parameter'=>array('appl_name' => 'School Bus Manager', 'css' => array('/css/style.css', '/css/bootstrap-theme.min.css','/css/bootstrap.min.css'), 'js' => array(),)));
$appl_name = $this->translate($this->parameter['appl_name']);
echo $this->doctype(); 
?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SBM '. $appl_name)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->getHeadLinks($this->basePath(), 'img/favicon.ico', $this->parameter['css']); ?>
        <!-- Scripts -->
        <?php echo $this->getHeadScripts($this->basePath(), $this->parameter['js']);?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/sbm-logo.gif') ?>" alt="School bus manager" class="carre-40"/>&nbsp;<?php echo $appl_name ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y'); ?> par <a href="http://www.dafap.fr" target=_blank>DAFAP Informatique</a>. <?php echo $this->translate('All rights reserved.'); ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
