<?php
/**
 * Page d'erreur
 *
 * @project sbm
 * @package SbmCommun/view/layout
 * @filesource error.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 27 sept. 2018
 * @version 2019-2.5.0
 */
$this->declarevars(
    [
        'parameter' => [
            'appl_name' => 'School Bus Manager',
            'css' => [
                '/css/style.css',
                '/css/bootstrap-theme.min.css',
                '/css/bootstrap.min.css'
            ],
            'js' => []
        ]
    ]);
$appl_name = $this->translate($this->parameter['appl_name']);
?>
<?= $this->doctype();?>
<html lang="fr">
<head>
<meta charset="utf-8">
        <?= $this->headTitle('SBM '. $appl_name)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=$this->headMeta()->appendName('viewport','width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible','IE=edge');?>
        <!-- Le styles -->
        <?= $this->getHeadLinks($this->basePath(), 'img/favicon.ico', $this->parameter['css']); ?>
        <!-- Scripts -->
        <?= $this->getHeadScripts($this->basePath(), $this->parameter['js']);?>
    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?= $this->url('home') ?>"><img
					src="<?= $this->basePath('img/sbm-logo.gif') ?>"
					alt="School bus manager" class="carre-40" />&nbsp;<?= $appl_name ?></a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container">
            <?= $this->content; ?>
            <hr>
		<footer>
			<p>&copy; 2013 - <?= date('Y'); ?> par <a href="https://www.dafap.fr"
					target=_blank>DAFAP Informatique</a>. <?= $this->translate('All rights reserved.'); ?></p>
		</footer>
	</div>
	<!-- /container -->
        <?= $this->inlineScript() ?>
    </body>
</html>
