<?php
$appl_name = $this->translate($this->getParameter('appl_name', $this->parameter));
echo $this->doctype();
?>
<html lang="fr">
<head>
<?php if ($this->doctype()->getDoctype() == 'HTML5') : ?>
<meta charset="utf-8">
<?php else:?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php endif; ?>
        <?php echo $this->headTitle('SBM '. $appl_name)->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php echo $this->getHeadLinks($this->basePath(), $this->getParameter('favicon', $this->parameter), $this->getParameter('css', $this->parameter)); ?>
        <!-- Scripts -->
        <?php echo $this->getHeadScripts($this->basePath(), $this->getParameter('js', $this->parameter));?>

    </head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
					src="<?php echo $this->basePath($this->getParameter('logo_file', $this->parameter)); ?>"
					alt="<?php echo $appl_name;?>" class="carre-40" />&nbsp;<?php echo $appl_name ?></a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container">
            <?php if (count($this->flashMessages) > 0):?>
                <?php foreach ($this->flashMessages as $key => $messages):?>
                    <?php foreach ($messages as $message):?>
                        <div class="alert alert-<?php echo $key;?>">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <?php echo $message;?>
                        </div>
                    <?php endforeach;?>
                <?php endforeach;?>
            <?php endif; ?>
            <?php echo $this->content; ?>
            <hr>
		<footer>
			<p>&copy; 2013 - <?php echo date('Y'); ?> par <a
					href="http://www.dafap.fr" target=_blank>DAFAP Informatique</a>. <?php echo $this->translate('All rights reserved.'); ?></p>
		</footer>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
