<?php
/**
 * Page de contrôle d'envoi des mails aux transporteurs
 *
 * En principe, cette page est appelée par un cron
 * 
 * @project sbm
 * @package DafapMail/view/index
 * @filesource last-day-changes.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 janv. 2016
 * @version 2016-1
 */
?>
<h1>Avertissements envoyés aux transporteurs</h1>
<?php if (count($this->destinataires)) : ?>
<p>Suite aux modifications d'inscription qui ont eu lieu durant les
	dernières 24 heures les transporteurs suivants ont reçu un email
	d'information.</p>
<ul>
<?php foreach ($this->destinataires as $nom) : ?>
<li><?php echo $nom;?></li>
<?php endforeach;?>
</ul>
<?php else : ?>
<p>Durant les dernières 24 heures, il n'y a pas eu de modification
	d'inscription. Par conséquent, aucun mail n'a été envoyé.</p>
<?php endif;?>