<?php
/**
 * Envoi d'un mail à une ou plusieurs adresses destinataires
 *
 * Si l'envoi se fait à une seule adresse, le destinataire est indiqué au dessus du formulaire d'envoi.
 * Sinon, la liste des destinataires est placée en dessous du formulaire.
 * 
 * La zone de saisie utilise tinymce pour mettre en forme le message envoyé.
 * 
 * @project sbm
 * @package DafapMail/view/dafap-mail
 * @filesource send.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headScript()->appendFile($this->basePath('js/jquery.min.js'));
$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
$this->headScript()->captureStart();
?>
tinymce.init({
    selector: "textarea",
    language: "fr_FR",
    menubar : false,
    statusbar: false
 });
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
var bodyWrapper = $("#body-wrapper");
var label = $('<label class="sbm-label required" for="mail-body">Message</label>'); 
var textArea = $('<textarea name="body" id="mail-body"></textarea>');
bodyWrapper.append(label);
bodyWrapper.append(textArea);
<?php
$this->inlineScript()->captureEnd();

$this->destinataires = (array) $this->destinataires;
$liste = count($this->destinataires) > 1;
?>
<h1>Envoi d'un message du service de transport</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
	<?php if ($liste):?>
	    <p class="description">Voir la liste des destinataires en dessous
			du formulaire.</p>
	<?php else :?>
	<?php $to = $this->destinataires[0];?>
	    <dl>
			<dt>Destinataire</dt>
			<dd><?php echo $to['responsable'] . ' (' . $to['email'] . ')';?></dd>
		</dl>
	<?php endif;?>
	</div>
	<div id="fiche-inner">
	<?php echo $this->form()->openTag($this->form);?>
	<?php echo $this->formHidden($this->form->get('csrf'));?>
	    <fieldset class="sbm-page1">
	        <div><?php echo $this->formRow($this->form->get('subject'));?></div>
	        <div id="body-wrapper"></div>
	        <div><?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'))?></div>
	    </fieldset>
	<?php $this->form()->closeTag();?>
	</div>
	<div id="fiche-footer">
	<?php if ($liste):?>
	    <h3>Liste des destinataires</h3>
		<ul>
	    <?php foreach ($this->destinataires as $to):?>
	        <li><?php echo $to['titre'] . ' ' . $to['nom'] . ' ' . $to['prenom'] . ' (' . $to['email'] . ')';?></li>
	    <?php endforeach;?>
	    </ul>
	<?php endif;?>
	</div>
</div>