<?php
/**
 * Liste des paiements pour la table `systempay`
 *
 * @project sbm
 * @package SbmPaiement/Plugin/SystemPay/view
 * @filesource liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2015
 * @version 2015-1
 */
 
function formatDate($date)
{
    return \DateTime::createFromFormat('YmdHis', $date)->format('d/m/Y H:i:s');
}

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
    ->setAttribute('id', $id)
    ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$datas = $this->paginator->getCurrentItems();
$url_rapports = $this->url('sbmpaiement', array(
    'action' => 'pdf',
    'page' => $this->page
));

$config = include __DIR__ . '/../config/systempay.config.php';
$url_marchand = $config['url_marchand'];
$retour = $this->url('sbmgestion/finance');
$hiddens = array();
$menuImpression = $this->menuRapports('/paiement/liste', $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => $menuImpression['content'],
    'systempay' => array(
        'class' => 'fam-house-link',
        'formaction' => $url_marchand,
        'title' => 'Systempay Back Office'
    )
);
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Liste des notifications de paiement</h1>
<div class="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
	</div>
	<div id="liste-inner">
		<table class="notifications">
			<tbody>
				<tr>
					<th>Prénom Nom</th>
					<th>Email</th>
					<th>Date</th>
					<th>Id</th>
					<th>Statut</th>
					<th>Autorisation</th>
					<th>Montant</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($datas as $test => $notification): ?>
            <?php $montant = $fmt->formatCurrency($notification->vads_amount/100, 'EUR'); ?>
            <?php $date_trans = formatDate($notification->vads_trans_date); ?>
            <?php 
            // selection
            $modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectionnotification/id:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;
            
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $notification->systempayId);
            $jsCallback .= sprintf("$modele\n", $notification->systempayId, $notification->systempayId);
            ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="vads_cust_name"><?php echo $this->escapeHtml($notification->vads_cust_name); ?></td>
					<td class="vads_cust_email"><?php echo $this->escapeHtml($notification->vads_cust_email); ?></td>
					<td class="vads_trans_date"><?php echo $date_trans; ?></td>
					<td class="vads_trans_id"><?php echo $this->escapeHtml($notification->vads_trans_id); ?></td>
					<td class="vads_trans_status"><?php echo $this->escapeHtml($notification->vads_trans_status); ?></td>
					<td class="vads_auth_number"><?php echo $this->escapeHtml($notification->vads_auth_number); ?></td>
					<td class="vads_amount"><?php echo $montant; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $notification->systempayId, $notification->selection)?></td>
					<td class="boutons">
            <?php
            $url_voir = $this->url('sbmpaiement', array(
                'action' => 'voir',
                'page' => $this->page,
            ));
            $title_voir = <<<EOT
Mode : $notification->vads_ctx_mode
Type d'opération : $notification->vads_operation_type
Date de la transaction : $date_trans
Référence de la transaction : $notification->vads_trans_id
Statut de la transaction : $notification->vads_trans_status
Résultat de la transaction : $notification->vads_result
Complément du résultat : $notification->vads_extra_result
Réponse de la banque : $notification->vads_auth_result
Autorisation n° : $notification->vads_auth_number
Email : $notification->vads_cust_email
Référence du responsable : $notification->vads_cust_id
Nom du responsable : $notification->vads_cust_name
Référence de la commande : $notification->vads_order_id
Référence des élèves concernés : $notification->ref_eleveIds
Certificat de paiement : $notification->vads_payment_certificate
Configuration du paiement : $notification->vads_payment_config
Erreur retournée : $notification->vads_payment_error
Numéro de l'échéance : $notification->vads_sequence_number
Délai de remise : $notification->vads_capture_delay
Montant : $montant
Monnaie : $notification->vads_currency
Carte enrôlée 3DSecure : $notification->vads_threeds_enrolled
Statut 3DSecure : $notification->vads_threeds_status
Carte bancaire : $notification->vads_card_brand
Pays origine de la carte bancaire : $notification->vads_card_country
Numéro de la carte : $notification->vads_card_number
Date d'expiration de la carte : $notification->vads_expiry_month/$notification->vads_expiry_year
Code de la banque : $notification->vads_expiry_year
Code du produit de paiement : $notification->vads_bank_product
EOT;
            $hiddens = array(
                'notificationId' => $notification->systempayId
            );
            $buttons = array(
                'voir' => array(
                    'class' => 'fam-zoom',
                    'formaction' => $url_voir,
                    'title' => $title_voir
                ),
            );
            echo $this->listeLigneActions($notification->systempayId, $hiddens, $buttons);
            ?>
					</td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();