<?php
/**
 * Liste des lignes donnant accès aux services
 *
 * Chaque ligne propose un bouton permettant d'ouvrir la liste des services
 *
 * Les variables définies dans cette vue sont :
 *
 * @project sbm
 * @package SbmPortail/view/sbm-portail/transporteur
 * @filesource lignes.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 24 sept. 2020
 * @version 2020-2.6.1
 */
