<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource layout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 mai 2015
 * @version 2015-1
 */

?>
<html>
<body>
<?php echo $this->content;?>
<img alt="Communauté de communes du bassin Decazeville-Aubin" src="http://cc-decazeville-aubin.dafap.fr/img/logo-ccda-email.png" width="426" height="128">
<img alt="School bus manager" src="http://cc-decazeville-aubin.dafap.fr/img/sbm-logo.gif">
</body>
</html> 