<?php
/**
 * Layout des mail envoyés
 *
 * Place les logos en signature (sous le message)
 * 
 * @project sbm
 * @package DafapMail/templates
 * @filesource layout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 04 nov. 2015
 * @version 2015-1.6.6
 */

?>
<html>
<body>
<?php echo $this->content;?>
<img alt="Communauté de communes du bassin Decazeville-Aubin" src="http://cc-decazeville-aubin.dafap.fr/img/bas-de-mail-service-gestion.png" width="427" height="128">
</body>
</html> 