<?php
/**
 * Modèle de courrier pour l'envoi du lien lors de la création d'un compte
 *
 * @project sbm
 * @package DafapMail/template
 * @filesource nouveau-compte.phtml.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 17 mai 2015
 * @version 2015-1
 */
?>
<p>Bonjour <?php echo $this->titre . ' ' . $this->prenom . ' ' . $this->nom;?>,</p>
<p>Vous avez demandé l'inscription de vos enfants au service des
	transports de la Communauté de communes du bassin Decazeville-Aubin.</p>

<p>
	A partir de mainteanant, vous pouvez suivre l'évolution du traitement
	de votre demande et contrôler les informations qui vous concernent en
	vous connectant au site de la communauté de communes par le lien
	suivant :<br>
    <?php echo $this->url_confirme;?></p>

<p>Le circuits sur lesquels vos enfants sont affectés et les horaires
	seront publiés durant la dernière semaine d'août.</p>

<p>En cas d'anomalie, merci de bien vouloir prévenir le service.</p>
<div style="text-align: center;">
	<b>Communauté de communes du bassin Decazeville-Aubin</b><br>Maison de
	l'industrie - BP68 - 12300 DECAZEVILLE<br>Tél. 05 65 43 95 00 - Email:
	transport@cc-decazeville-aubin.fr
</div>
