<?php
/**
 * Vue de l'action index du controller FinanceController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/finance/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 juil. 2021
 * @version 2021-2.6.2
 */
use SbmBase\Model\DateLib;

define('CAISSE1', 'Régisseur');
define('LABEL_CAISSE1', 'Total de la caisse de régie');
define('CAISSE2', 'DFT');
define('LABEL_CAISSE2', 'Total de la caisse DFT');
define('CAISSE3', 'Comptable');
define('LABEL_CAISSE3', 'Total des encaissements déposés');

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_finance_encaissements = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-liste',
        'page' => 1,
        'id' => 'tous'
    ]);
$url_finance_tarifs = $this->url('sbmgestion/finance', [
    'action' => 'tarif-liste'
]);
$url_organisme_liste = $this->url('sbmgestion/finance', [
    'action' => 'organisme-liste'
]);
$url_flux_financiers = $this->url('sbmgestion/finance', [
    'action' => 'flux-financiers'
]);
// $url_finance_factures = $this->url('sbmgestion/finance');
// $url_finance_prelevements = $this->url('sbmgestion/finance');
$url_paiement_liste = $this->url('sbmpaiement');
$url_gestion = $this->url('sbmgestion');

$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
$anneeScolaire = sprintf("%d-%d", $this->millesime, $this->millesime + 1);

$nouveauBordereauCheques = (empty($this->resultats['dateBordereau']['chèque']) &&
    ! empty($this->resultats['datePaiement']['chèque'])) ||
    (! empty($this->resultats['dateBordereau']['chèque']) &&
    ! empty($this->resultats['datePaiement']['chèque']) &&
    $this->resultats['dateBordereau']['chèque'] <
    $this->resultats['datePaiement']['chèque']);
$nouveauBordereauEspeces = (empty($this->resultats['dateBordereau']['espèces']) &&
    ! empty($this->resultats['datePaiement']['espèces'])) ||
    (! empty($this->resultats['dateBordereau']['espèces']) &&
    ! empty($this->resultats['datePaiement']['espèces']) &&
    $this->resultats['dateBordereau']['espèces'] <
    $this->resultats['datePaiement']['espèces']);
$nouveauBordereauCB = (empty($this->resultats['dateBordereau']['CB']) &&
    ! empty($this->resultats['datePaiement']['CB'])) ||
    (! empty($this->resultats['dateBordereau']['CB']) &&
    ! empty($this->resultats['datePaiement']['CB']) &&
    $this->resultats['dateBordereau']['CB'] < $this->resultats['datePaiement']['CB']);
?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
        <?= $this->flashMessenger()->render('success');?>
        <?= $this->flashMessenger()->render('warning');?>
        <?= $this->flashMessenger()->render('error');?>
        <?= $this->flashMessenger()->render('info');?>
        <?= $this->flashMessenger()->render('default');?>
    </div>
	<h1>Gestion financière</h1>
	<div class="float-left">
		<div class="clearfix">
			<fieldset class="rose float-left">
				<legend>Derniers paiements</legend>
				<dl class="statistiques">
					<dt>Date du dernier bordereau de chèques</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateBordereau']['chèque']);?></dd>
					<dt>Date du dernier paiement par chèque</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateDernierPaiement']['chèque']);?></dd>
					<?php if ($nouveauBordereauCheques) : ?>
					<dd class="alert">Il faudra préparer un nouveau bordereau de
						chèques.</dd>
					<?php endif;?>
				</dl>
				<dl class="statistiques separateur">
					<dt>Date du dernier bordereau d'espèces</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateBordereau']['espèces']);?></dd>
					<dt>Date du dernier paiement en espèces</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateDernierPaiement']['espèces']);?></dd>
					<?php if ($nouveauBordereauEspeces) : ?>
					<dd class="alert">Il faudra préparer un nouveau bordereau
						d'espèces.</dd>
					<?php endif;?>
				</dl>
				<dl class="statistiques separateur">
					<dt>Date du dernier bordereau de CB</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateBordereau']['CB']);?></dd>
					<dt>Date du dernier paiement par CB</dt>
					<dd><?= DateLib::formatDateTimeFromMysql($this->resultats['dateDernierPaiement']['CB']);?></dd>
					<?php if ($nouveauBordereauCB) : ?>
					<dd class="alert">Il faudra préparer un nouveau bordereau de CB.</dd>
					<?php endif;?>
				</dl>
			</fieldset>
			<div class="float-left">
				<fieldset class="jaune">
					<legend>Bordereaux en cours</legend>
					<dl class="statistiques">
						<dt>Bordereau de chèques</dt>
						<dd><?= $fmt->formatCurrency($this->resultats['encours']['chèque'] ?:0, 'EUR');?></dd>
						<dt>Bordereau d'espèces</dt>
						<dd><?= $fmt->formatCurrency($this->resultats['encours']['espèces'] ?:0, 'EUR');?></dd>
						<dt>Bordereau de CB</dt>
						<dd><?= $fmt->formatCurrency($this->resultats['encours']['CB'] ?:0, 'EUR');?></dd>
					</dl>
					<dl class="statistiques separateur">
						<dt>Total des bordereaux en cours</dt>
						<dd><?= $fmt->formatCurrency($this->resultats['encoursTotal'] ?:0, 'EUR');?></dd>
					</dl>
				</fieldset>
				<?php if (array_key_exists('Titre individuel', $this->codesModeDePaiement)):?>
				<fieldset class="bleu">
					<legend>Titres individuels émis</legend>
					<dl class="statistiques">
						<dt>Pour l'année scolaire</dt>
						<dd>
						<?= $fmt->formatCurrency($this->resultats[2]['as']['Titre individuel'] ?:0, 'EUR');?>
						</dd>
						<dt>Pour l'exercice <?= $this->millesime;?></dt>
						<dd>
						<?= $fmt->formatCurrency($this->resultats[2]['exercice1']['Titre individuel'] ?:0, 'EUR');?>
						</dd>
						<dt>Pour l'exercice <?= $this->millesime + 1;?></dt>
						<dd>
						<?= $fmt->formatCurrency($this->resultats[2]['exercice2']['Titre individuel'] ?:0, 'EUR');?>
						</dd>
					</dl>
				</fieldset>
				<?php endif;?>
			</div>
		</div>
	</div>
	<div id="menugeneral" class="float-right">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?= $url_finance_encaissements; ?>"><i
						class="fam-bullet-go"></i>Gestion des encaissements</a></li>
				<li><a href="<?= $url_flux_financiers; ?>"><i class="fam-bullet-go"></i>Suivi
						des flux financiers</a></li>
				<li><a href="<?= $url_paiement_liste; ?>"><i class="fam-bullet-go"></i>Notifications de paiement en ligne</a></li>
				<li><a href="<?= $url_finance_tarifs; ?>"><i class="fam-bullet-go"></i>Gestion
						des tarifs</a></li>
				<li><a href="<?= $url_organisme_liste; ?>"><i class="fam-bullet-go"></i>Gestion
						des organismes payeurs</a></li>
				<li><a href="<?= $url_gestion; ?>"><i class="fam-door-out"></i>Retour
						au menu général</a></li>
			</ul>
		</div>
	</div>
</div>
<div class="clearfix">
	<fieldset class="bleu float-left">
		<legend>Année scolaire <?= $anneeScolaire;?></legend>
		<dl class="statistiques">
			<dt>Paiements par chèques non déposés</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['as']['chèque'] ?:0, 'EUR');?></dd>
			<dt>Paiements en espèces non déposés</dt>
			<dd class="statistiques">
			<?= $fmt->formatCurrency($this->resultats[2]['as']['espèces'] ?:0, 'EUR');?></dd>
		</dl>
		<dl class="statistiques separateur">
		    <?php if (array_key_exists(CAISSE1, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE1;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['as'][CAISSE1] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE2, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE2;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['as'][CAISSE2] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE3, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE3;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['as'][CAISSE3] ?:0, 'EUR');?></dd>
			<?php endif;?>
		</dl>
		<dl class="statistiques separateur">
			<dt>Total des encaissements</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[1]['as'] ?:0, 'EUR');?></dd>
		</dl>
	</fieldset>
	<fieldset class="rose float-left">
		<legend>Exercice budgétaire <?= $this->millesime;?></legend>
		<dl class="statistiques">
			<dt>Paiements par chèques non déposés</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice1']['chèque'] ?:0, 'EUR');?></dd>
			<dt>Paiements en espèces non déposés</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice1']['espèces'] ?:0, 'EUR');?></dd>
		</dl>
		<dl class="statistiques separateur">
		    <?php if (array_key_exists(CAISSE1, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE1;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice1'][CAISSE1] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE2, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE2;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice1'][CAISSE2] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE3, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE3;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice1'][CAISSE3] ?:0, 'EUR');?></dd>
			<?php endif;?>
		</dl>
		<dl class="statistiques separateur">
			<dt>Total des encaissements</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[1]['exercice1'] ?:0, 'EUR');?></dd>
		</dl>
	</fieldset>
	<fieldset class="jaune float-left">
		<legend>Exercice budgétaire <?= $this->millesime + 1;?></legend>
		<dl class="statistiques">
			<dt>Paiements par chèques non déposés</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice2']['chèque'] ?:0, 'EUR');?></dd>
			<dt>Paiements en espèces non déposés</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice2']['espèces']  ?:0, 'EUR');?></dd>
		</dl>
		<dl class="statistiques separateur">
		    <?php if (array_key_exists(CAISSE1, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE1;?></dt>
			<dd class=""><?= $fmt->formatCurrency($this->resultats[2]['exercice2'][CAISSE1] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE2, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE2;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice2'][CAISSE2] ?:0, 'EUR');?></dd>
			<?php endif;?>
			<?php if (array_key_exists(CAISSE3, $this->codesCaisse)):?>
			<dt><?=LABEL_CAISSE3;?></dt>
			<dd><?= $fmt->formatCurrency($this->resultats[2]['exercice2'][CAISSE3] ?:0, 'EUR');?></dd>
			<?php endif;?>
		</dl>
		<dl class="statistiques separateur">
			<dt>Total des encaissements</dt>
			<dd><?= $fmt->formatCurrency($this->resultats[1]['exercice2'] ?:0, 'EUR');?></dd>
		</dl>
	</fieldset>
</div>