<?php
/**
 * Page de création d'un organisme
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource organisme-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance',
    [
        'action' => 'organisme-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'un nouvel organisme payeur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
    	<?= $this->form()->openTag($this->form);?>
    	<?= $this->formHidden($this->form->get('organismeId'));?>
    	<?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="wrapper-nom" class="row-inner ajout">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="wrapper-adresse1" class="row-inner ajout">
				<?= $this->formRow($this->form->get('adresse1')); ?></div>
			<div id="wrapper-adresse2" class="row-inner ajout">
				<?= $this->formRow($this->form->get('adresse2')); ?></div>
			<div id="wrapper-codePostal" class="row-inner ajout">
				<?= $this->formRow($this->form->get('codePostal')); ?></div>
			<div id="wrapper-comuneId" class="row-inner ajout">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="wrapper-telephone" class="row-inner ajout">
				<?= $this->formRow($this->form->get('telephone')); ?></div>
			<div id="wrapper-fax" class="row-inner ajout">
				<?= $this->formRow($this->form->get('fax')); ?></div>
			<div id="wrapper-email" class="row-inner ajout">
				<?= $this->formRow($this->form->get('email')); ?></div>
			<div id="wrapper-siret" class="row-inner ajout">
				<?= $this->formRow($this->form->get('siret')); ?></div>
			<div id="wrapper-naf" class="row-inner ajout">
				<?= $this->formRow($this->form->get('naf')); ?></div>
			<div id="wrapper-tvaIntraCommunautaire"
				class="row-inner ajout">
				<?= $this->formRow($this->form->get('tvaIntraCommunautaire')); ?></div>
			<div id="wrapper-buttons" class="row-inner ajout">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>