<?php
/**
 * Page de création d'un organisme
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource organisme-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 déc. 2015
 * @version 2015-1.6.9
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'javascript:window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance', array(
    'action' => 'organisme-liste',
    'page' => $this->page
));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
?>
<h1>Création d'un nouvel organisme payeur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('organismeId'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
			<div id="organisme-ajout-nom" class="row-inner ajout"><?php echo $this->formRow($this->form->get('nom')); ?></div>
			<div id="organisme-ajout-adresse1" class="row-inner ajout"><?php echo $this->formRow($this->form->get('adresse1')); ?></div>
			<div id="organisme-ajout-adresse2" class="row-inner ajout"><?php echo $this->formRow($this->form->get('adresse2')); ?></div>
			<div id="organisme-ajout-codePostal" class="row-inner ajout"><?php echo $this->formRow($this->form->get('codePostal')); ?></div>
			<div id="organisme-ajout-comuneId" class="row-inner ajout"><?php echo $this->formRow($this->form->get('communeId')); ?></div>
			<div id="organisme-ajout-telephone" class="row-inner ajout"><?php echo $this->formRow($this->form->get('telephone')); ?></div>
			<div id="organisme-ajout-fax" class="row-inner ajout"><?php echo $this->formRow($this->form->get('fax')); ?></div>
			<div id="organisme-ajout-email" class="row-inner ajout"><?php echo $this->formRow($this->form->get('email')); ?></div>
			<div id="organisme-ajout-siret" class="row-inner ajout"><?php echo $this->formRow($this->form->get('siret')); ?></div>
			<div id="organisme-ajout-naf" class="row-inner ajout"><?php echo $this->formRow($this->form->get('naf')); ?></div>
			<div id="organisme-ajout-tvaIntraCommunautaire"
				class="row-inner ajout"><?php echo $this->formRow($this->form->get('tvaIntraCommunautaire')); ?></div>
			<div id="organisme-ajout-buttons" class="row-inner ajout">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>