<?php
/**
 * Liste des organismes payeurs
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource organisme-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.4.7
 */
use SbmBase\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle pour les jsCallback de selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectionorganisme/organismeId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$organismes = $this->paginator->getCurrentItems();

$url_ajouter = $this->url('sbmgestion/finance', 
    [
        'action' => 'organisme-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/finance', 
    [
        'action' => 'organisme-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/finance');
$url_edit = $this->url('sbmgestion/finance', 
    [
        'action' => 'organisme-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/finance', 
    [
        'action' => 'organisme-suppr',
        'page' => $this->page
    ]);
$url_group = $this->url('sbmgestion/finance', 
    [
        'action' => 'organisme-group',
        'id' => $this->page
    ]);
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/finance', [
        'action' => 'organisme-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel organisme'
    ]
];
?>
<h1>Liste des organismes payeurs</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="organismes">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Fax</th>
					<th>Email</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($organismes as $test => $organisme): ?>
            <?php
                $nbInscrits = StdLib::getParamR(
                    [
                        $organisme->organismeId,
                        'transportes'
                    ], $this->t_nb_inscrits, 0) . ' / ';
                $nbInscrits .= StdLib::getParamR(
                    [
                        $organisme->organismeId,
                        'demandes'
                    ], $this->t_nb_inscrits, 0);
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", 
                    $organisme->organismeId);
                $jsCallback .= sprintf("$modele\n", $organisme->organismeId, 
                    $organisme->organismeId);
                ?>
                <tr
					class="<?php echo $this->cycle(["even", "odd"])->next();?>">
					<td class="nom"><?php echo $this->escapeHtml($organisme->nom); ?></td>
					<td class="commune"><?php echo $this->escapeHtml($organisme->commune); ?></td>
					<td class="codepostal"><?php echo $this->escapeHtml($organisme->codePostal); ?></td>
					<td class="telephone"><?php echo $this->telephone($organisme->telephone); ?></td>
					<td class="fax"><?php echo $this->telephone($organisme->fax); ?></td>
					<td class="email"><?php echo $this->escapeHtml($organisme->email); ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $organisme->organismeId, $organisme->selection)?></td>
					<td class="boutons">
            <?php
                $hiddens = [
                    'organismeId' => $organisme->organismeId
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves pris en chage par ' . $organisme->nom
                    ]
                ];
                echo $this->listeLigneActions($organisme->organismeId, $hiddens, $buttons);
                ?>
					</td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();
 