<?php
/**
 * Page de suppression d'un organisme payeur
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource organisme-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
?>
<h1>Suppression d'un organisme payeur</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de l'organisme :</p>
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapeHtml($this->data->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->data->commune); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>
