<?php
/**
 * Liste des paiements
 *
 * Cette liste peut être donner les paiements d'un responsable ou de tous les paiements (éventuellement filtrée par les critères indiqués)
 * La vue reçoit la propriété `url_retour` du controller.
 * 
 * Chaque bouton `group` est implémenté dans un formulaire de façon à envoyer en post la route_retour, l'action_retour et la page_retour.
 * Ce bouton n'est visible que dans la gestion des paiements (liste complète ou groupée). Il est invisible pour les paiements relatifs à un
 * responsable indiqué.
 * 
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 22 janv. 2015
 * @version 2015-1
 */
use SbmCommun\Model\DateLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);

$paiements = $this->paginator->getCurrentItems();

$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);

if (! $this->h2) {
    $url_retour_pour_group = $this->url('sbmgestion/finance', array(
        'action' => 'paiement-liste',
        'page' => $this->page
    ));
}
?>

<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
		<h1>Liste des paiements</h1>
<?php if ($this->h2): ?>
        <h2>Paiements effectués par <?php echo $this->responsable; ?></h2>
        <?php $totalDu = ($this->nbInscrits + $this->nbPreinscrits - $this->nbGratuits - $this->nbFa) * $this->inscription + $this->nbDuplicata * $this->duplicata; ?>
		<p class="left-10px">Total du : <?php echo $fmt->formatCurrency($totalDu, 'EUR');?>
            <span class="left-95px">Payé : <?php echo $fmt->formatCurrency($this->totalPaye, 'EUR');?></span>
			<span class="left-95px">Reste du : <?php echo $fmt->formatCurrency($totalDu - $this->totalPaye, 'EUR');?></span>
		</p>
<?php endif; ?>	
		<div class="menu float-left">
<?php
$url_retour = empty($this->url2_retour) ? $this->url1_retour : $this->url2_retour;
$url_ajouter = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-ajout',
    'page' => $this->page
));
$url_imprimer = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-depot',
    'page' => $this->page
));
$url_edit = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-edit',
    'page' => $this->page
));
$url_delete = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-suppr',
    'page' => $this->page
));
if (! $this->h2) {
    $url_group = $this->url('sbmgestion/finance', array(
        'action' => 'paiement-liste'
    ));
}
$url_detail = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-detail',
    'page' => $this->page
));

$hiddens = array(
    'url1_retour' => $this->url1_retour,
    'url2_retour' => $this->url2_retour,
    'h2' => $this->h2,
    /*
     * Pour la compatibilité de traitement avec les formulaires de ligne (voir plus bas)
     * - si h2 == true alors $responsableId est celui de la liste
     * - si h2 == false alors $responsableId = -1 et le responsableId de la liste est aussi -1.
     */
    'responsableId' => $this->responsableId,
    'responsable' => $this->escapeHtml($this->responsable)
);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'onclick' => $js_retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-printer',
        'formaction' => $url_imprimer,
        'title' => 'Bordereaux de remise de valeurs'
    ),
    'detail' => array(
        'class' => 'fam-group-gear',
        'formaction' => $url_detail,
        'title' => 'Justification des montants encaissés'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau paiement'
    )
);
if (! $this->h2) {
    unset($actions['detail']);
}
echo $this->listeZoneActions($hiddens, $actions);
?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="paiements">
			<tbody>
				<tr>
					<th>Responsable</th>
					<th>Montant</th>
					<th>Caisse</th>
					<th>Mode de paiement</th>
					<th>Date de paiement</th>
					<th>Date de valeur</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($paiements as $test => $paiement): ?>
        <?php
            // selection
            $modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectionpaiement/paiementId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
    //alert(action);
  });
EOT;
            
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $paiement->paiementId);
            $jsCallback .= sprintf("$modele\n", $paiement->paiementId, $paiement->paiementId);
            ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="responsable"><?php echo $r = $this->escapeHtml($paiement->responsable); ?></td>
					<td class="montant"><?php echo $m = $fmt->formatCurrency($paiement->montant, 'EUR'); ?></td>
					<td class="caisse"><?php echo $cs = $this->escapeHtml($paiement->caisse); ?></td>
					<td class="mode-de-paiement"><?php echo $mp = $this->escapeHtml($paiement->modeDePaiement); ?></td>
					<td class="date-paiement"><?php echo $dp = DateLib::formatDateTimeFromMysql($paiement->datePaiement); ?></td>
					<td class="date-valeur"><?php echo $dv = DateLib::formatDateFromMysql($paiement->dateValeur); ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $paiement->paiementId, $paiement->selection);?></td>
					<td class="boutons">
             <?php
            $title_voir = 'Année scolaire : ' . $paiement->anneeScolaire . "\n" . 'Exercice budgétaire : ' . $paiement->exercice . "\n" . 'Titulaire : ' . $paiement->titulaire . "\n" . 'Banque : ' . $paiement->banque . "\n" . 'Référence : ' . $paiement->reference . "\n" . 'Date de dépôt : ' . DateLib::formatDateTimeFromMysql($paiement->dateDepot);
            $texte_voir = 'Responsable : ' . $r . "\n" . 'Montant : ' . $m . "\n" . 'Caisse :' . $cs . "\n" . 'Mode de paiement : ' . $mp . "\n" . 'Date de paiement : ' . $dp . "\n" . 'Date de valeur : ' . $dv . "\n" . $title_voir;
            $js_voir = 'javascript:window.prompt(\'Copier dans le presse-papier : Ctrl+C ou click droit et Copier\', \'' . str_replace("\n", '; ', $texte_voir) . '\');return false;';
            $hiddens['paiementId'] = $paiement->paiementId;
            /*
             * Pour responsableId il y a 2 cas :
             * - si h2 == true alors responsableId correspond au responsableId de la liste et de la ligne (liste des paiements d'un responsable)
             * - si h2 == false alors responsableId correspond au responsableId de la ligne. Dans ce cas, le responsableId de la liste est -1.
             */
            $hiddens['responsableId'] = $paiement->responsableId;
            $hiddens['responsable'] = $this->escapeHtml($paiement->responsable);
            // ne pas utiliser de guillement dans la chaine $js
            $js = 'javascript:window.document.getElementById(\'op' . $paiement->paiementId . '\').value=%s;';
            $buttons = array(
                'voir' => array(
                    'class' => 'fam-zoom',
                    'title' => $title_voir,
                    'onclick' => $js_voir
                ),
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier l\'encaissement de ' . $m . ' de ' . $r,
                    'onclick' => sprintf($js, "'modifier'")
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer le paiement de ' . $m . ' de ' . $r,
                    'onclick' => sprintf($js, "'supprimer'")
                )
            );
            if (! $this->h2) {
                // ne pas utiliser de guillement dans la chaine $js
                $js = sprintf($js, "'grouper'") . 'window.document.getElementById(\'url2_retour' . $paiement->paiementId . '\').value=\'' . $url_retour_pour_group . '\';';
                $buttons['groupe'] = array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'liste de tous les paiements de ' . $r,
                    'onclick' => $js
                );
            }
            echo $this->listeLigneActions($paiement->paiementId, $hiddens, $buttons);
            ?>                           
				</td>
				</tr>         
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
        <?php
        if (! is_null($this->criteres_form)) {
            echo $this->form()->openTag($this->criteres_form);
            echo $this->formCollection($this->criteres_form, true);
            echo $this->form()->closeTag();
        }
        ?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();
