<?php
/**
 * Journal des rectifications
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource paiement-rectifications.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 21 oct. 2019
 * @version 2019-2.5.2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/finance', 'paiement-rectifications.css');
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
$url_retour = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-liste',
        'page' => $this->id
    ]);
$url_imprimer = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-rectifications-pdf'
    ]);
$hiddens = [
    'exercice' => $this->exercice
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/finance', [
        'action' => 'paiement-rectifications'
    ]), $url_imprimer, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content']
];
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Journal des rectifications</h1>
<div>
	<div id="liste-wrapper">
		<div id="liste-header" class="clearfix">
			<div class="menu float-left">
			<?=$this->listeZoneActions($hiddens, $actions);?></div>
			<div class="flashMessenger float-right"></div>
		</div>
		<div id="liste-inner">
			<table class="rectifications">
				<tbody>
					<tr>
						<th>Date</th>
						<th>Action</th>
						<th>Date paiement</th>
						<th>Date dépôt</th>
						<th>Montant</th>
						<th>Responsable</th>
						<th>Titulaire</th>
						<th>Mode</th>
						<th>Caisse</th>
						<th>Banque</th>
						<th>Note</th>
					</tr>
                <?php foreach ($data as $row) : ?>
                <?php
                    $modif = $row['action'] == $this->historique::GET_ACTION_UPDATE;
                    $css = [
                        $this->cycle([
                            "even",
                            "odd"
                        ])->next(),
                        $modif ? 'modif' : 'suppr'
                    ];
                    ?>
                <tr class="petit <?=implode(' ',$css);?>">
						<td class="date">
						<?=$row['date'];?></td>
						<td class="action">
						<?=$row['action'];?></td>
						<td class="date-paiement">
						<?=$row['datePaiement'];?></td>
						<td class="date-depot">
						<?=$row['dateDepot'];?></td>
						<td class="montant align-right">
						<?php if ($modif):?>
						    <?php if (count($row['aMontant']) == 1):?>
						        <?=$fmt->formatCurrency($row['aMontant'][0], 'EUR');?>
						    <?php else :?>
						        <span class='modif'><?=$fmt->formatCurrency($row['aMontant'][0], 'EUR');?>
						        </span><br><?=$fmt->formatCurrency($row['aMontant'][1], 'EUR');?>
						    <?php endif;?>
						<?php else :?>
						    <?=$fmt->formatCurrency($row['aMontant'][0], 'EUR');?>
						<?php endif;?>
						</td>
						<td class="responsable">
						<?php if ($modif):?>
						    <?php if (count($row['aResponsable']) == 1):?>
						        <?=$row['aResponsable'][0];?>
						    <?php else :?>
						        <span class='modif'><?=$row['aResponsable'][0];?>
						        </span><br><?=$row['aResponsable'][0];?>
						    <?php endif;?>
						<?php else :?>
						    <?=$row['aResponsable'][0];?>
						<?php endif;?>
						</td>
						<td class="titulaire">
						<?php if ($modif):?>
						    <?php if (count($row['aTitulaire']) == 1):?>
						        <?=$row['aTitulaire'][0];?>
						    <?php else :?>
						        <span class='modif'><?=$row['aTitulaire'][0];?>
						        </span><br><?=$row['aTitulaire'][1];?>
						    <?php endif;?>
						<?php else :?>
						    <?=$row['aTitulaire'][0];?>
						<?php endif;?>
						</td>
						<td class="mode-paiement">
						<?php if ($modif):?>
						    <?php if (count($row['aModePaiement']) == 1):?>
						        <?=$row['aModePaiement'][0];?>
						    <?php else :?>
						        <span class='modif'><?=$row['aModePaiement'][0];?>
						        </span><br><?=$row['aModePaiement'][1];?>
						    <?php endif;?>
						<?php else :?>
						    <?=$row['aModePaiement'][0];?>
						<?php endif;?>
						</td>
						<td class="caisse">
						<?php if ($modif):?>
						    <?php if (count($row['aCaisse']) == 1):?>
						        <?=$row['aCaisse'][0];?>
						    <?php else :?>
						        <span class='modif'><?=$row['aCaisse'][0];?>
						        </span><br><?=$row['aCaisse'][1];?>
						    <?php endif;?>
						<?php else :?>
						    <?=$row['aCaisse'][0];?>
						<?php endif;?>
						</td>
						<td class="banque">
						<?php if ($modif):?>
						    <?php if (count($row['aBanque']) == 1):?>
						        <?=$row['aBanque'][0];?>
						    <?php else :?>
						        <span class='modif'><?=$row['aBanque'][0];?>
						        </span><br><?=$row['aBanque'][1];?>
						    <?php endif;?>
						<?php else :?>
						    <?=$row['aBanque'][0];?>
						<?php endif;?>
						</td>
						<td class="note">
						<?=$row['note'];?></td>
					</tr>
                <?php endforeach; ?>
            </tbody>
			</table>
		</div>
		<div id="liste-footer">
			<div class="pagination-wrapper clearfix">
				<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?>
			</div>
			<div class="criteres-wrapper"></div>
		</div>
	</div>
</div>
