<?php
/**
 * Affiche le formulaire de paramétrage de la création d'un bordereau
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/finance
 * @filesource paiement-depot.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2015
 * @version 2015-1
 */
use SbmCommun\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

?>
<div id="fiche-wrapper">
	<h1>Gestion des dépôts de valeurs au comptable</h1>
	<div id="fiche-header" class="clearfix">
		<div class="flashMessenger float-right">
		<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
        </div>
	</div>
	<div id="fiche-inner">	  
	<?php if ($this->voirForm1) : ?>
		<?php echo $this->form()->openTag($this->form1); ?>
	    <fieldset class="sbm-page1">
			<legend>Bordereaux en cours</legend>
			<p>Sélectionnez un bordereau en cours dans la liste déroulante pour
				l'imprimer, le supprimer ou le cloturer :</p>
			<div class="row-inner"><?php echo $this->formRow($this->form1->get('bordereau'));?></div>
			<div class="row-inner"><?php echo $this->formSubmit($this->form1->get('editer')) . $this->formSubmit($this->form1->get('supprimer')) . $this->formSubmit($this->form1->get('cloturer')) . $this->formSubmit($this->form1->get('cancel')); ?></div>
			<p class="sbm-description">Il ne peut y avoir qu'un seul bordereau en
				cours par mode de paiement.</p>
		</fieldset>
	    <?php echo $this->form()->closeTag(); ?>  
	    <p></p>
	<?php endif;?>
	<?php if ($this->voirForm2) : ?>
		<?php echo $this->form()->openTag($this->form2); ?>
		<?php echo $this->formHidden($this->form2->get('csrf'));?>
	    <fieldset class="sbm-page1">
			<legend>Préparer un nouveau bordereau</legend>
			<p>Si vous souhaitez préparer un nouveau bordereau, remplissez ce
				formulaire.</p>
			<div class="" row-inner><?php echo $this->formRow($this->form2->get('codeModeDePaiement'))?></div>
			<div class="" row-inner><?php echo $this->formRow($this->form2->get('codeCaisse'))?></div>
			<div class="" row-inner><?php echo $this->formRow($this->form2->get('exercice'))?></div>
			<div class="" row-inner><?php echo $this->formRow($this->form2->get('anneeScolaire'))?></div>
			<div class="row-inner"><?php echo $this->formSubmit($this->form2->get('preparer')) . $this->formSubmit($this->form2->get('cancel')); ?></div>
			<p class="sbm-description">
				Lorsqu'un bordereau en cours existe déjà avec le mode de paiement
				désiré, vous devez le supprimer ou le clôturer avant de pouvoir
				créer un nouveau bordereau.<br>Par contre, vous pouvez créer un
				bordereau en cours pour chaque mode de paiement.
			</p>
		</fieldset> 		
	    <?php echo $this->form()->closeTag(); ?>
	    <p></p>
	<?php endif;?>
	<?php if ($this->voirForm3) : ?>	   
	    <?php echo $this->form()->openTag($this->form3); ?>
		<fieldset class="sbm-page1">
			<legend>Editer un bordereau clôturé</legend>
			<div class="row-inner"><?php echo $this->formRow($this->form3->get('bordereau'));?></div>
			<div class="row-inner"><?php echo $this->formSubmit($this->form3->get('editer')) . $this->formSubmit($this->form3->get('cancel')); ?></div>
		</fieldset>
		<?php echo $this->form()->closeTag(); ?>
		<p></p>
	<?php endif;?>
	</div>
	<div id="fiche-footer"></div>
</div>