<?php
/**
 * Liste des paiements
 *
 * Cette liste peut être donner les paiements d'un responsable ou de tous les paiements (éventuellement filtrée par les critères indiqués)
 * La vue reçoit la propriété `url_retour` du controller.
 *
 * Chaque bouton `group` est implémenté dans un formulaire de façon à envoyer en post la route_retour, l'action_retour et la page_retour.
 * Ce bouton n'est visible que dans la gestion des paiements (liste complète ou groupée). Il est invisible pour les paiements relatifs à un
 * responsable indiqué.
 *
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 juil. 2021
 * @version 2021-2.5.13
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modele de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectionpaiement/paiementId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
    //alert(action);
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$paiements = $this->paginator->getCurrentItems();
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
// hiddens sera modifié par la suite en fonction de h2
$hiddens = [
    'url1_retour' => $this->url1_retour,
    'url2_retour' => $this->url2_retour,
    'h2' => $this->h2,
    'namespacectrl' => $this->namespacectrl,
    /*
     * Pour la compatibilité de traitement avec les formulaires de ligne (voir plus bas)
     * - si h2 == true alors $responsableId est celui de la liste
     * - si h2 == false alors $responsableId = -1 et le responsableId de la liste est aussi -1.
     */
    'responsableId' => $this->responsableId,
    'responsable' => $this->escapeHtml($this->responsable)
];
$url_retour = empty($this->url2_retour) ? $this->url1_retour : $this->url2_retour;
$url_ajouter = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-ajout',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-suppr',
        'page' => $this->page
    ]);
$url_detail = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-detail',
        'page' => $this->page
    ]);
$url_rectifications = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-rectifications',
        'page' => $this->page
    ]);
if ($this->h2) {
    $url_lesfactures = $this->url('sbmdocument', [
        'action' => 'les-factures'
    ]);
    $url_unefacture = $this->url('sbmdocument', [
        'action' => 'facture'
    ]);
    $rapports = [
        'class' => 'fam-printer',
        'label' => true,
        'menu' => [
            'lesfactures' => [
                'formaction' => $url_lesfactures,
                'value' => 'Imprimer toutes les factures',
                'formtarget' => '_blank'
            ],
            'unefacture' => [
                'formaction' => $url_unefacture,
                'value' => 'Imprimer la dernière facture',
                'formtarget' => '_blank'
            ]
        ]
    ];
} else {
    $url_imprimer = $this->url('sbmgestion/finance',
        [
            'action' => 'paiement-depot',
            'page' => $this->page
        ]);
    $rapports = [
        'class' => 'fam-printer',
        'formaction' => $url_imprimer,
        'title' => 'Bordereaux de remise de valeurs'
    ];
    $url_retour_pour_group = $this->url('sbmgestion/finance',
        [
            'action' => 'paiement-liste',
            'page' => $this->page
        ]);
    $url_group = $this->url('sbmgestion/finance', [
        'action' => 'paiement-liste'
    ]);
}

// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'onclick' => $js_retour,
        'title' => 'Retour'
    ],
    'rapports' => $rapports,
    'detail' => [
        'class' => 'fam-coins',
        'formaction' => $url_detail,
        'title' => 'Facturation'
    ],
    'rectifications' => [
        'class' => 'fam-bug-error',
        'formaction' => $url_rectifications,
        'title' => 'Journal des rectifications'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Encaissement'
    ]
];
if ($this->h2) {
    unset($actions['rectifications']);
} else {
    unset($actions['detail']);
}
?>

<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
		<h1>Liste des paiements</h1>
<?php if ($this->h2): ?>
        <h2>État du compte de <?= $this->responsable; ?></h2>
        <?php
    $totalDu = $this->resultats->getSolde();
    ?>
		<p class="left-10px">Total du : <?= $fmt->formatCurrency($this->resultats->getMontantTotal(), 'EUR');?>
            <span class="left-95px">
            	Payé : <?= $fmt->formatCurrency($this->resultats->getPaiementsMontant(), 'EUR');?></span>
			<span class="left-95px">
				Reste du : <?= $fmt->formatCurrency($this->resultats->getSolde(), 'EUR');?></span>
		</p>
<?php endif; ?>
		<div class="menu float-left">
			<?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="liste-inner">
		<table class="paiements">
			<tbody>
				<tr>
					<th>Responsable</th>
					<th>Montant</th>
					<th>Caisse</th>
					<th>Mode de paiement</th>
					<th>Date de paiement</th>
					<th>Date de valeur</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($paiements as $paiement): ?>
        <?php
            // construction des JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n",
                $paiement->paiementId);
            $jsCallback .= sprintf("$modele\n", $paiement->paiementId,
                $paiement->paiementId);
            $r = $this->escapeHtml($paiement->responsable);
            $m = $fmt->formatCurrency($paiement->montant, 'EUR');
            $cs = $this->escapeHtml($paiement->caisse);
            $mp = $this->escapeHtml($paiement->modeDePaiement);
            $dp = DateLib::formatDateTimeFromMysql($paiement->datePaiement);
            $dv = DateLib::formatDateFromMysql($paiement->dateValeur);
            $title_voir = 'Année scolaire : ' . $paiement->anneeScolaire . "\n" .
                'Exercice budgétaire : ' . $paiement->exercice . "\n" . 'Titulaire : ' .
                $paiement->titulaire . "\n" . 'Banque : ' . $paiement->banque . "\n" .
                'Référence : ' . $paiement->reference . "\n" . 'Date de dépôt : ' .
                DateLib::formatDateTimeFromMysql($paiement->dateDepot);
            $texte_voir = 'Responsable : ' . $r . "\n" . 'Montant : ' . $m . "\n" .
                'Caisse :' . $cs . "\n" . 'Mode de paiement : ' . $mp . "\n" .
                'Date de paiement : ' . $dp . "\n" . 'Date de valeur : ' . $dv . "\n" .
                $title_voir;
            $js_voir = 'window.prompt(\'Copier dans le presse-papier : Ctrl+C ou click droit et Copier\', \'' .
                str_replace("\n", '; ', $texte_voir) . '\');return false;';
            $hiddens['paiementId'] = $paiement->paiementId;
            /*
             * Pour responsableId il y a 2 cas : - si h2 == true alors responsableId
             * correspond au responsableId de la liste et de la ligne (liste des paiements
             * d'un responsable) - si h2 == false alors responsableId correspond au
             * responsableId de la ligne. Dans ce cas, le responsableId de la liste est
             * -1.
             */
            $hiddens['responsableId'] = $paiement->responsableId;
            $hiddens['responsable'] = $this->escapeHtml($paiement->responsable);
            // ne pas utiliser de guillement dans la chaine $js
            $js = 'window.document.getElementById(\'op' . $paiement->paiementId .
                '\').value=%s;';
            $buttons = [
                'voir' => [
                    'class' => 'fam-zoom',
                    'title' => $title_voir,
                    'onclick' => $js_voir
                ],
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier l\'encaissement de ' . $m . ' de ' . $r,
                    'onclick' => sprintf($js, "'modifier'")
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer le paiement de ' . $m . ' de ' . $r,
                    'onclick' => sprintf($js, "'supprimer'")
                ]
            ];
            if (! $this->h2) {
                // ne pas utiliser de guillement dans la chaine $js
                $js = sprintf($js, "'grouper'") .
                    'window.document.getElementById(\'url2_retour' . $paiement->paiementId .
                    '\').value=\'' . $url_retour_pour_group . '\';';
                $buttons['groupe'] = [
                    'class' => 'fam-money-euro',
                    'formaction' => $url_group,
                    'title' => 'état du compte de ' . $r,
                    'onclick' => $js
                ];
            }
            ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="responsable"><?= $r;?></td>
					<td class="montant align-right"><?= $m;?></td>
					<td class="caisse"><?= $cs;?></td>
					<td class="mode-de-paiement"><?= $mp;?></td>
					<td class="date-paiement"><?= $dp;?></td>
					<td class="date-valeur"><?= $dv; ?></td>
					<td class="centre selection">
					    <?= $this->renderCheckbox('selection', 'chk', $paiement->paiementId, $paiement->selection);?></td>
					<td class="boutons">
						<?= $this->listeLigneActions($paiement->paiementId, $hiddens, $buttons);?></td>
				</tr>
        <?php endforeach;?>
    </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        <?php if (! is_null($this->criteres_form)) :?>
            <?= $this->form()->openTag($this->criteres_form);?>
            <?= $this->formCollection($this->criteres_form, true);?>
            <?= $this->form()->closeTag();?>
        <?php endif;?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?= $jsTrigger;?>}
<?= $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();
