<?php

/**
 * Justificatif du montant encaissé pour un responsable
 *
 * Variables de vue :
 * liste (liste des enfants payant)
 * args : array(url1_retour, url2_retour, h2, responsableId, responsable)
 *
 * @project sbm
 * @package SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-detail.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 mai 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;
use SbmBase\Model\StdLib;

// Les montants de la facture (avant l'initialisation du JavaScript)
$montantDuplicatas = $this->resultats->getMontantDuplicatas(0, 'tous');
$montantAbonnements = $this->resultats->getAbonnementsMontant(0, 'tous');
$aboInscrits = $this->resultats->getAbonnementsMontant(0, 'inscrits');
$montantTotal = $this->resultats->getMontantTotal(0, 'tous');
$dejaPaye = $this->resultats->getPaiementsMontant();
// styles css et scripts
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/finance', 'paiement-detail.css');
$this->jQuery('jquery.formatCurrency');
$this->themeJS('gestion-finance', 'paiement-detail.js');
$this->inlineScript()->captureStart();
?>
js_paiement_detail.init(<?=$this->args['responsableId']?>);
<?php
$this->inlineScript()->captureEnd();
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
$url_retour = $this->url('sbmgestion/finance',
    [
        'action' => 'paiement-liste',
        'page' => $this->page
    ]);
$url_lesfactures = $this->url('sbmdocument', [
    'action' => 'les-factures'
]);
$url_unefacture = $this->url('sbmdocument', [
    'action' => 'facture'
]);
$url_debit = $this->url('sbmgestion/finance', [
    'action' => 'paiement-debit'
]);
$hiddens = [
    'namespacectrl' => $this->namespacectrl,
    'h2' => $this->args['h2'],
    'responsableId' => $this->args['responsableId'],
    'responsable' => $this->args['responsable']
];
/*
 * Impression spéciale de la facture qui déroge à la méthode habituelle $menuImpression =
 * $this->menuRapports( $this->url('sbmgestion/finance', [ 'action' => 'paiement-detail'
 * ]), $url_rapports, 'fam-printer', null, $hiddens); $hiddens =
 * $menuImpression['hiddens']; // puis rajouter dans $actions[] 'rapports' =>
 * $menuImpression['content']
 */
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => [
        'class' => 'fam-printer',
        'label' => true,
        'menu' => [
            'lesfactures' => [
                'formaction' => $url_lesfactures,
                'value' => 'Imprimer toutes les factures',
                'formtarget' => '_blank'
            ],
            'unefacture' => [
                'formaction' => $url_unefacture,
                'value' => 'Imprimer la dernière facture',
                'formtarget' => '_blank'
            ]
        ]
    ],
    'debit' => [
        'class' => 'fam-coins-delete',
        'formaction' => $url_debit,
        'title' => 'Remboursement'
    ]
];
if ($montantTotal >= $dejaPaye) {
    unset($actions['debit']);
}
?>
<div id="liste-wrapper">
	<div id="liste-title">
		<h1>Détail des sommes à payer pour l'année en cours</h1>
		<h3>Responsable :
				<?= $this->escapehtml($this->args['responsable']); ?></h3>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="liste-inner">
		<div id="facture-wrapper" class="clearfix">
			<fieldset class="float-left">
				<legend>Facture</legend>
				<table class="ligne-facture">
					<tr>
						<td>Coût des duplicatas :</td>
						<td><span class="formatEuro">
				<?= $montantDuplicatas;?></span></td>
					</tr>
					<tr>
						<td>Coût des abonnements :
							<ul class="detail-abonnements">
								<li>Élèves inscrits : <span id="abo-inscrits" class="formatEuro">
						<?= $aboInscrits;?></span>
								</li>
								<li>Élèves préinscrits : <span id="abo-preinscrits"
									class="formatEuro">
						<?= $montantAbonnements- $aboInscrits;?>
						</span>
								</li>
							</ul>
						</td>
						<td><span class="formatEuro">
				<?= $montantAbonnements;?></span></td>
					</tr>
					<tr class="separateur">
						<td>Coût total :

						<td><span class="formatEuro">
				<?= $montantTotal;?></span></td>
					</tr>
					<tr>
						<td>Montant encaissé :</td>
						<td><span class="formatEuro">
				<?= $dejaPaye;?></span></td>
					</tr>
					<tr>

						<td class="">Reste à payer :</td>



						<td><span class="formatEuro">
			    <?= $montantTotal - $dejaPaye;?></span></td>
					</tr>
				</table>
			</fieldset>
			<fieldset class="float-left">
				<legend>Abonnements facturés</legend>
				<table class="liste-tarifs">
					<tbody id="tbody-grille">
						<tr>
							<th>Tarif</th>
							<th>Nature</th>
							<th>Montant</th>
						</tr>
					<?php foreach($this->resultats->getAbonnementsDetail() as $row):?>
					<tr>
							<td>
							<?=StdLib::getParam($row->getGrille(), $this->grilles,'');?>
							</td>
							<td><?=$row->getReduit() ? 'Réduit' : 'Normal';?></td>
							<td><span class="formatEuro"><?=$row->getMontant();?></span></td>
						</tr>
					<?php endforeach;?>
				</tbody>
				</table>
			</fieldset>
			<fieldset class="float-left">
				<legend>Liste des enfants</legend>
				<table class="liste-eleves">
					<tbody id="tbody-payants">
						<tr>
							<th>Nom</th>
							<th>Prénom</th>
							<th>Tarif</th>
							<th>Nb de<br>duplicatas
							</th>
							<th>Abonnement<br>payé
							</th>
						</tr>
	            <?php foreach ($this->resultats->getListeEleves() as $eleveId => $enfant) : ?>
	            <?php
                // $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $eleveId);
                // $jsCallback .= sprintf("$modele\n", $eleveId, $eleveId);
                ?>
	            <tr>
							<td><?= $this->escapeHtml($enfant['nom']);?></td>
							<td><?= $this->escapeHtml($enfant['prenom']);?></td>
							<td>
								<?= $enfant['grilleTarif'];?>
								<?= $this->reductionTarif($enfant['reduction']);?></td>
							<td>
						<?= $enfant['duplicata'];?></td>
							<td>
							<?php if (!$enfant['gratuit']):?>
							<?= $this->renderCheckbox('paiement', 'chk', $eleveId, $enfant['paiement']);?>
							<?php endif;?>
							</td>
						</tr>
	            <?php endforeach;?>
	       </tbody>
				</table>
				<p class="sbm-description">Si nécessaire, cochez ou décochez les
					abonnements payés.</p>
			</fieldset>
		</div>
		<div class="clearfix">
			<div id="paiements-wrapper" class="float-left">
				<fieldset>
					<legend>Liste des paiements</legend>
					<table class="liste-paiements">
						<tbody id="tbody-paiements">
							<tr>
								<th>Date de paiement</th>
								<th>Mode de paiement</th>
								<th>Montant</th>
							</tr>
					<?php foreach ($this->resultats->getPaiementsDetail() as $row) :?>
					<?php
					$css = $row['mouvement'] == -1 ? 'rouge' : '';
					?>
							<tr class='<?=$css;?>'>
								<td><?=DateLib::formatDateFromMysql($row['datePaiement']);?></td>
								<td><?=$row['mouvement'] == -1 ? 'Remboursement ' : '';?>
									<?=$row['modeDePaiement'];?></td>
								<td><span class="formatEuro"><?=$row['montant'] * $row['mouvement'];?></span></td>
							</tr>
					<?php endforeach;?>
				</tbody>
					</table>
				</fieldset>
			</div>
			<div id="factures-wrapper" class="float-left">
				<fieldset>
					<legend>Liste des factures émises</legend>
					<table class="liste-factures">
						<tbody id="tbody-paiements">
							<tr>
								<th>Exercice</th>
								<th>Numéro</th>
								<th>Année scolaire</th>
								<th>Date</th>
								<th>Montant</th>
							</tr>
							<?php foreach ($this->factures as $row) :?>
							<tr>
								<td><?=$row->exercice;?></td>
								<td><?=$row->numero;?></td>
								<td><?=$row->millesime;?>-<?=$row->millesime + 1;?></td>
								<td><?=DateLib::formatDateFromMysql($row->date);?></td>
								<td><span class="formatEuro"><?=$row->montant;?></span></td>
							</tr>
							<?php endforeach;?>
						</tbody>
					</table>
				</fieldset>
			</div>
		</div>
		<p class="sbm-description">
			Pour créer, numéroter et enregistrer une facture, il suffit d'en
			demander l'impression.<br>Une nouvelle facture sera créée si les
			éléments à facturer sont modifiés (abonnements ou duplicatas de carte
			de transport).
		</p>
	</div>
	<div id="liste-footer"></div>
</div>