<?php
/**
 * Ecran de saisie d'un encaissement
 *
 * S'il s'agit d'une entrée où le responsable n'est pas connu, on propose de choisir le responsable dans un Select
 * sinon (appel depuis la liste des paiements d'un responsables ou de la fiche d'un responsable), le responsableId est dans un Hidden.
 *
 * En ajax, une fois le responsable précisé, on présente la liste des élèves préinscrits avec une case à cocher pour le sélectionner.
 * La sélection d'un enfant entraine le recalcul de la somme à payer, mais il est possible de surcharge cette valeur manuellement.
 *
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-ajout.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->themeJS('gestion-finance','paiement-ajout.js');
$this->inlineScript()->captureStart();
?>
js_paiement_ajout.init();
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance', [
    'action' => 'paiement-ajout'
]);
$hiddens = [
    'op' => $this->hidden_responsableId ? '' : 'retour'
];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Enregistrement d'un nouveau paiement</h1>
<?php if ($this->hidden_responsableId):?>
<h2>Paiement concernant <?= $this->responsable; ?></h2>
<?php endif;?>
<div id="fiche-wrapper">
	<div id="fiche-header">

		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        <div id="somme-due" class="float-left"></div>
        <div id="somme-payee"class="float-left"></div>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('paiementId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
        <div class="float-left left-10px">
			<fieldset class="sbm-page1">
<?php if ($this->hidden_responsableId) : ?>
				<?= $this->formHidden($this->form->get('responsableId')); ?>
<?php else : ?>
                <div id="wrapper-responsableId"
					class="row-inner edit">
					<?= $this->formRow($this->form->get('responsableId')); ?></div>
<?php endif; ?>

                <div id="wrapper-code-caisse"
					class="row-inner edit">
					<?= $this->formRow($this->form->get('codeCaisse')); ?></div>
				<div id="wrapper-montant" class="row-inner edit">
					<?= $this->formRow($this->form->get('montant')); ?></div>
				<div id="wrapper-code-mode-de-paiement" class="row-inner edit">
					<?= $this->formRow($this->form->get('codeModeDePaiement')); ?></div>
				<div id="wrapper-exercice" class="row-inner edit">
					<?= $this->formRow($this->form->get('exercice')); ?></div>
				<div id="wrapper-annee-scolaire" class="row-inner edit">
					<?= $this->formRow($this->form->get('anneeScolaire')); ?></div>
				<div id="wrapper-date-paiement" class="row-inner edit">
					<?= $this->formRowDateTime($this->form->get('datePaiement')); ?></div>
				<div id="wrapper-date-valeur" class="row-inner edit">
					<?= $this->formRowDate($this->form->get('dateValeur')); ?></div>
				<div id="wrapper-date-depot" class="row-inner edit">
					<?= $this->formRowDateTime($this->form->get('dateDepot')); ?></div>
				<div id="wrapper-titulaire" class="row-inner edit">
					<?= $this->formRow($this->form->get('titulaire')); ?></div>
				<div id="wrapper-banque" class="row-inner edit">
					<?= $this->formRow($this->form->get('banque')); ?></div>
				<div id="wrapper-reference" class="row-inner edit">
					<?= $this->formRow($this->form->get('reference')); ?></div>
				<div id="wrapper-justificatif" class="row-inner edit">
					<?= $this->formRow($this->form->get('justificatif')); ?></div>
				<div id="wrapper-buttons" class="row-inner edit">
    				<?= $this->formSubmit($this->form->get('submit'));?>
    				<?= $this->formSubmit($this->form->get('cancel')); ?></div>
			</fieldset>
		</div>
		<div class="float-left left-10px">
			<fieldset class="sbm-page1">
				<h3>Liste des enfants préinscrits de ce responsable</h3>
				<table>
					<tbody id="tbody-preinscrits">
						<tr>
							<th>Nom</th>
							<th>Prénom</th>
							<th></th>
						</tr>
					</tbody>
				</table>
				<p class="sbm-description">Cochez les enfants concernés par ce
					paiement.</p>
			</fieldset>
		</div>
<?= $this->form()->closeTag(); ?>
    </div><?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div>
<?php // fiche-wrapper ?>
