<?php
/**
 * Ecran de confirmation de la suppression d'un paiement
 *
 * La suppression d'un paiement doit être archivée. Le motif de la suppression sera saisi.
 * 
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-suppr.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
use SbmBase\Model\DateLib;

$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Suppression d'un paiement</h1>
<div id="suppr-wrapper">
	<p>
		<i>Vous avez demandé la suppression du paiement suivant :</i>
	</p>
	<div class="header-wrapper">
		<ul>
			<li>Responsable : <b><?php echo $this->escapeHtml($this->responsable); ?></b></li>
			<li>Montant : <b><?php echo $fmt->formatCurrency($this->data->montant, 'EUR'); ?></b></li>
			<li>Caisse : <b><?php echo $this->escapeHtml($this->libelles->getLibelle('caisse', $this->data->codeCaisse)); ?></b></li>
			<li>Exercice budgétaire : <b><?php echo $this->data->exercice; ?></b></li>
			<li>Année scolaire : <b><?php echo $this->data->anneeScolaire; ?></b></li>
			<li>Date du paiement : <b><?php echo DateLib::formatDateTimeFromMysql($this->data->datePaiement); ?></b></li>
			<li>Date de valeur : <b><?php echo DateLib::formatDateFromMysql($this->data->dateValeur); ?></b></li>
			<li>Date de dépôt : <b><?php echo DateLib::formatDateTimeFromMysql($this->data->dateDepot); ?></b></li>
			<li>Mode de paiement : <b><?php echo $this->escapeHtml($this->libelles->getLibelle('modeDePaiement', $this->data->codeModeDePaiement)); ?></b></li>
			<?php if ($this->data->codeModeDePaiement == $this->libelles->getCode('modeDePaiement', 'chèque')) :?>
			<li>Banque : <b><?php echo $this->escapeHtml($this->data->banque); ?></b></li>
			<li>Titulaire du compte : <b><?php echo $this->escapeHtml($this->data->titulaire); ?></b></li>
			<li>Référence du chèque : <b><?php echo $this->escapeHtml($this->data->reference); ?></b></li>
			<?php endif; ?>
		</ul>
	</div>
	<p>
		<i>Pour confirmer, donnez la raison puis cliquez sur le bouton de
			confirmation.</i>
	</p>
<?php
echo $this->form()->openTag($form);
echo $this->formHidden($this->form->get('paiementId'));
echo '<div id="paiement-suppr-note" class="row-inner edit" style="vertical-align: top;">' .
     $this->formRow($this->form->get('note')) . '</div>';
echo '<div id="paiement-suppr-buttons" class="row-inner edit">' .
     $this->formSubmit($this->form->get('submit')) .
     $this->formSubmit($this->form->get('cancel')) . '</div>';
echo $this->form()->closeTag();
?>
</div>