<?php
/**
 * Ecran de modification d'un paiement
 *
 * Pour le moment, on peut tout modifier. Par la suite, on limitera la modification d'un responsable aux gestionnaires seulement.
 *
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-edit.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance', [
    'action' => 'paiement-edit'
]);
$hiddens = [
    'op' => $this->h2 ? '' : 'retour'
];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un paiement</h1>
<?php if ($this->hidden_responsableId):?>
<h2>Paiement concernant <?= $this->responsable; ?></h2>
<?php endif;?>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('paiementId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
<?php if ($this->hidden_responsableId) : ?>
		<?= $this->formHidden($this->form->get('responsableId')); ?>
<?php else : ?>
    		<div id="wrapper-responsableId" class="row-inner edit">
    			<?= $this->formRow($this->form->get('responsableId')); ?></div>
<?php endif; ?>
    		<div id="wrapper-code-caisse" class="row-inner edit">
    			<?= $this->formRow($this->form->get('codeCaisse')); ?></div>
			<div id="wrapper-montant" class="row-inner edit">
				<?= $this->formRow($this->form->get('montant')); ?></div>
			<div id="wrapper-code-mode-de-paiement" class="row-inner edit">
				<?= $this->formRow($this->form->get('codeModeDePaiement')); ?></div>
			<div id="wrapper-exercice" class="row-inner edit">
				<?= $this->formRow($this->form->get('exercice')); ?></div>
			<div id="wrapper-annee-scolaire" class="row-inner edit">
				<?= $this->formRow($this->form->get('anneeScolaire')); ?></div>
			<div id="wrapper-date-paiement" class="row-inner edit">
				<?= $this->formRowDateTime($this->form->get('datePaiement')); ?></div>
			<div id="wrapper-date-valeur" class="row-inner edit">
				<?= $this->formRowDate($this->form->get('dateValeur')); ?></div>
			<div id="wrapper-date-depot" class="row-inner edit">
				<?= $this->formRowDateTime($this->form->get('dateDepot')); ?></div>
			<div id="wrapper-titulaire" class="row-inner edit">
				<?= $this->formRow($this->form->get('titulaire')); ?></div>
			<div id="wrapper-banque" class="row-inner edit">
				<?= $this->formRow($this->form->get('banque')); ?></div>
			<div id="wrapper-reference" class="row-inner edit">
				<?= $this->formRow($this->form->get('reference')); ?></div>
			<div id="wrapper-note" class="row-inner edit">
				<?= $this->formRow($this->form->get('note')); ?></div>
			<div id="wrapper-buttons" class="row-inner edit">
    			<?= $this->formSubmit($this->form->get('submit'));?>
    			<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div><?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div><?php // fiche-wrapper ?>