<?php
/**
 * Ecran de modification d'un paiement
 *
 * Pour le moment, on peut tout modifier. Par la suite, on limitera la modification d'un responsable aux gestionnaires seulement.
 * 
 * @project sbm
 * @package module\SbmGestion\view\sbm-gestion\finance
 * @filesource paiement-edit.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance', array(
    'action' => 'paiement-liste',
    'page' => $this->page
));
$hiddens = array(
    'op' => $this->h2 ? '' : 'retour'
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
?>
<h1>Modification d'un paiement</h1>
<?php if ($this->hidden_responsableId):?>
<h2>Paiement concernant <?php echo $this->responsable; ?></h2>
<?php endif;?>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('paiementId'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
<?php if ($this->hidden_responsableId) : ?>
<?php echo $this->formHidden($this->form->get('responsableId')); ?>
<?php else : ?>
    <div id="paiement-edit-responsableId" class="row-inner edit"><?php echo $this->formRow($this->form->get('responsableId')); ?></div>
<?php endif; ?>

    <div id="paiement-edit-code-caisse" class="row-inner edit"><?php echo $this->formRow($this->form->get('codeCaisse')); ?></div>
			<div id="paiement-edit-montant" class="row-inner edit"><?php echo $this->formRow($this->form->get('montant')); ?></div>
			<div id="paiement-edit-code-mode-de-paiement" class="row-inner edit"><?php echo $this->formRow($this->form->get('codeModeDePaiement')); ?></div>
			<div id="paiement-edit-exercice" class="row-inner edit"><?php echo $this->formRow($this->form->get('exercice')); ?></div>
			<div id="paiement-edit-annee-scolaire" class="row-inner edit"><?php echo $this->formRow($this->form->get('anneeScolaire')); ?></div>
			<div id="paiement-edit-date-paiement" class="row-inner edit"><?php echo $this->formRowDateTime($this->form->get('datePaiement')); ?></div>
			<div id="paiement-edit-date-valeur" class="row-inner edit"><?php echo $this->formRowDate($this->form->get('dateValeur')); ?></div>
			<div id="paiement-edit-date-depot" class="row-inner edit"><?php echo $this->formRowDateTime($this->form->get('dateDepot')); ?></div>
			<div id="paiement-edit-titulaire" class="row-inner edit"><?php echo $this->formRow($this->form->get('titulaire')); ?></div>
			<div id="paiement-edit-banque" class="row-inner edit"><?php echo $this->formRow($this->form->get('banque')); ?></div>
			<div id="paiement-edit-reference" class="row-inner edit"><?php echo $this->formRow($this->form->get('reference')); ?></div>
			<div id="paiement-edit-note" class="row-inner edit"><?php echo $this->formRow($this->form->get('note')); ?></div>
			<div id="paiement-edit-buttons" class="row-inner edit">
    <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div><?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div>
<?php // fiche-wrapper ?>