<?php

/**
 * Liste des tarifs
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2019
 * @version 2019-2.5.0
 */
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectiontarif/tarifId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$tarifs = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/finance');
$url_edit = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-suppr',
        'page' => $this->page
    ]);
$url_group = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-group',
        'id' => $this->page
    ]);
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/finance', [
        'action' => 'tarif-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel arrêt sur un circuit'
    ]
];
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Liste des tarifs</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?= $this->flashMessenger()->render('success');?>
            <?= $this->flashMessenger()->render('warning');?>
            <?= $this->flashMessenger()->render('error');?>
            <?= $this->flashMessenger()->render('info');?>
            <?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="tarifs">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Montant</th>
					<th>Rythme</th>
					<th>Grille</th>
					<th>Mode</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($tarifs as $test => $tarif): ?>
        <?php
            // construction des JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $tarif->tarifId);
            $jsCallback .= sprintf("$modele\n", $tarif->tarifId, $this->page,
                $tarif->tarifId);
            $hiddens = [
                'tarifId' => $tarif->tarifId
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ],
                'eleves' => [
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits avec ce tarif'
                ]
            ];
            ?>
            <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="nom">
						<?= $this->escapeHtml($tarif->nom); ?></td>
					<td class="montant">
						<?= $fmt->formatCurrency($tarif->montant, 'EUR'); ?></td>
					<td class="attributs">
						<?= $this->escapeHtml($tarif->rythme); ?></td>
					<td class="attributs">
						<?= $this->escapeHtml($tarif->grille); ?></td>
					<td class="attributs">
						<?= $this->escapeHtml($tarif->mode); ?></td>
					<td class="centre selection">
						<?= renderCheckbox($this, 'selection', 'chk' . $tarif->tarifId, $tarif->selection)?>
						</td>
					<td class="boutons">
						<?= $this->listeLigneActions($tarif->tarifId, $hiddens, $buttons);?>
					</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        	<?= $this->form()->openTag($this->criteres_form);?>
        	<?= $this->formCollection($this->criteres_form, true);?>
        	<?= $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?= $jsTrigger;?>}
<?= $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();
