<?php
/**
 * Liste des tarifs
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 mai 2014
 * @version 2014-1
 */
$this->paginator->setDefaultItemCountPerPage($this->nb_tarif_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$tarifs = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmgestion/finance', array(
    'action' => 'tarif-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/finance', array(
    'action' => 'tarif-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/finance');
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Liste des tarifs</h1>
<div class="liste-wrapper">
	<div class="zone-actions">
		<a href="<?php echo $retour; ?>" class="bouton"
			title="retour au menu de gestion financière"><i class="fam-door-out"></i>
			Retour</a> <a href="<?php echo $pdf; ?>" class="bouton"
			title="exporter en pdf" target="_blank"><i
			class="fam-application-view-list"></i> Exporter en pdf</a> <a
			href="<?php echo $ajouter; ?>" class="bouton"
			title="créer un nouveau tarif"><i class="fam-add"></i> Ajouter un
			tarif</a>
	</div>
	<table class="liste-inner tarifs">
		<tbody>
        <?php foreach($tarifs as $test => $tarif): ?>
        <?php $fmt?>
         <tr
				class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				<td class="nom"><?php echo $this->escapeHtml($tarif->nom); ?></td>
				<td class="montant"><?php echo $fmt->formatCurrency($tarif->montant, 'EUR'); ?></td>
				<td class="attributs"><?php echo $this->escapeHtml($tarif->rythme); ?></td>
				<td class="attributs"><?php echo $this->escapeHtml($tarif->grille); ?></td>
				<td class="attributs"><?php echo $this->escapeHtml($tarif->mode); ?></td>
				<td class="boutons">
             <?php
            $url_edit = $this->url('sbmgestion/finance', array(
                'action' => 'tarif-edit',
                'page' => $this->page,
                'id' => $tarif->tarifId
            ));
            $url_delete = $this->url('sbmgestion/finance', array(
                'action' => 'tarif-suppr',
                'page' => $this->page,
                'id' => $tarif->tarifId
            ));
            $url_group = $this->url('sbmgestion/finance', array(
                'action' => 'tarif-group',
                'page' => $this->page,
                'id' => $tarif->tarifId
            ));
            ?>
                 <a href="<?php echo $url_edit; ?>" class="bouton"
					title="modifier"><i class="fam-pencil"></i></a> <a
					href="<?php echo $url_delete; ?>" class="bouton" title="supprimer"><i
						class="fam-delete"></i></a> <a href="<?php echo $url_group; ?>"
					class="bouton" title="groupe d'élèves inscrits"><i
						class="fam-group"></i></a>
				</td>
			</tr>         
        <?php endforeach;?>
    </tbody>
	</table>
	<div class="zone-pagination"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
<?php echo $this->form()->openTag($this->criteres_form);?>
<?php echo $this->formCollection($this->criteres_form, true);?>
<?php echo $this->form()->closeTag();?>
</div>
