<?php
/**
 * Page de création d'un tarif
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance',
    [
        'action' => 'tarif-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'un nouveau tarif</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('tarifId'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="tarif-ajout-nom" class="row-inner ajout">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="tarif-ajout-montant" class="row-inner ajout">
				<?= $this->formRow($this->form->get('montant')); ?></div>
			<div id="tarif-ajout-rythme" class="row-inner ajout">
				<?= $this->formRow($this->form->get('rythme')); ?></div>
			<div id="tarif-ajout-grille" class="row-inner ajout">
				<?= $this->formRow($this->form->get('grille')); ?></div>
			<div id="tarif-ajout-mode" class="row-inner ajout">
				<?= $this->formRow($this->form->get('mode')); ?></div>
			<div id="tarif-ajout-buttons" class="row-inner ajout">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>