<?php
/**
 * Page de suppression d'un tarif
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Suppression d'un tarif</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du tarif :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->nom); ?></li>
			<li><?= $fmt->formatCurrency($this->data->montant, 'EUR'); ?></li>
			<li><?= $this->escapeHtml($this->data->rythme); ?></li>
			<li><?= $this->escapeHtml($this->data->grille); ?></li>
			<li><?= $this->escapeHtml($this->data->mode); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>