<?php
/**
 * Page de consultation des inscrits sur un tarif
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 août 2015
 * @version 2015-2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/finance', array(
    'action' => 'tarif-liste',
    'page' => $this->pageRetour
));
$url_rapports = $this->url('sbmgestion/finance', array(
    'action' => 'tarif-group-pdf',
    'page' => $this->page
));
$hiddens = array(
    'tarifId' => $this->tarifId
);
$menuImpression = $this->menuRapports($this->url('sbmgestion/finance', array(
    'action' => 'tarif-group'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => $menuImpression['content']
);
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Groupe des élèves inscrits au tarif</h1>
<div class="liste-wrapper">
	<div class="liste-title">
		<ul>
			<li>Tarif : <?php echo $this->escapeHtml($this->tarif->nom); ?></li>
			<li>Montant : <?php echo $fmt->formatCurrency($this->tarif->montant, 'EUR'); ?></li>
		</ul>
	</div>
	<div class="liste-header">
	    <div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->paginator->getAdapter()->count(); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php
foreach ($data as $row) {
    echo '<tr class="' . $this->cycle(array("even", "odd"))->next() . '">';
    foreach ($row as $item) {
        echo '<td>' . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	</div>
</div>