<?php
/**
 * Page de modification d'un tarif
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/finance', 
    [
        'action' => 'tarif-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un tarif</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('tarifId'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
			<div id="tarif-edit-nom" class="row-inner edit"><?php echo $this->formRow($this->form->get('nom'));?></div>
			<div id="tarif-edit-montant" class="row-inner edit"><?php echo $this->formRow($this->form->get('montant')); ?></div>
			<div id="tarif-edit-rythme" class="row-inner edit"><?php echo $this->formRow($this->form->get('rythme')); ?></div>
			<div id="tarif-edit-grille" class="row-inner edit"><?php echo $this->formRow($this->form->get('grille')); ?></div>
			<div id="tarif-edit-mode" class="row-inner edit"><?php echo $this->formRow($this->form->get('mode')); ?></div>
			<div id="tarif-edit-buttons" class="row-inner edit">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>