<?php
/**
 * Page de modification d'un tarif
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/tarif-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/finance', array('action'=> 'tarif-liste', 'page' => $this->page));
?>
<h1>Modification d'un tarif</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la liste des tarifs"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('tarifId'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div id="tarif-edit-nom" class="row-inner edit">' . $this->formRow($this->form->get('nom')) . '</div>';
echo '<div id="tarif-edit-montant" class="row-inner edit">' . $this->formRow($this->form->get('montant')) . '</div>';
echo '<div id="tarif-edit-rythme" class="row-inner edit">' . $this->formRow($this->form->get('rythme')) . '</div>';
echo '<div id="tarif-edit-grille" class="row-inner edit">' . $this->formRow($this->form->get('grille')) . '</div>';
echo '<div id="tarif-edit-mode" class="row-inner edit">' . $this->formRow($this->form->get('mode')) . '</div>';
echo '<div id="tarif-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</fieldset>';
echo $this->form()->closeTag();
?>
</div>