<?php
/**
 * Page de modification des horaires des arrêts sélectionnés
 *
 * Permet d'avancer ou de retarder le passage aux arrêts sélectionnés d'un
 * certain nombre de minutes et de secondes.
 * 
 * @project sbm
 * @package view/sbm-gestion/transport
 * @filesource circuit-modif-horaires.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 oct. 2016
 * @version 2016-2.2.1
 */
?>
<h1>Modification des horaires des arrêts sélectionnés</h1>
<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-inner">
	<?php
echo $this->form()->openTag($this->form);
?>
    <fieldset class="sbm-page1">
			<div id="circuit-modif-horaires-buttons" class="row-inner">
				<div id="horaire-matin" class="row-inner">
					<fieldset>
						<legend>Horaires aller</legend>
						<table>
							<tr id="circuit-m1" class="row-inner">
								<th>Lun Ma Je Ve</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('m1-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('m1-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('m1-sec')) . ' sec</td>';
    ?>
						</tr>
							<tr id="circuit-m2" class="row-inner">
								<th>Mercredi</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('m2-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('m2-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('m2-sec')) . ' sec</td>';
    ?>
						</tr>
							<tr id="circuit-m3" class="row-inner">
								<th>Samedi</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('m3-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('m3-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('m3-sec')) . ' sec</td>';
    ?>
						</tr>
						</table>
					</fieldset>
				</div>
				<div id="horaire-soir" class="row-inner">
					<fieldset>
						<legend>Horaires retour</legend>
						<table id="circuit-s1" class="row-inner">
							<tr>
								<th>Lun Ma Je Ve</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('s1-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('s1-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('s1-sec')) . ' sec</td>';
    ?>
						</tr>
							<tr id="circuit-s2" class="row-inner">
								<th>Mercredi</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('s2-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('s2-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('s2-sec')) . ' sec</td>';
    ?>
						</tr>
							<tr id="circuit-s3" class="row-inner">
								<th>Samedi</th>
						<?php
    echo '<td>' . $this->FormRadio($this->form->get('s3-op')) . '</td>';
    echo '<td>' . $this->formText($this->form->get('s3-min')) . ' min</td>';
    echo '<td>' . $this->formText($this->form->get('s3-sec')) . ' sec</td>';
    ?>
						</tr>
						</table>
					</fieldset>
				</div>
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
    <?php echo $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">
			Avancer le passage de 1 minute veut dire que le passage à tous les
			arrêts sélectionnés aura lieu 1 minute plus tôt.<br>Retarder le
			passage de 1 minute veut dire que le passage à tous les arrêts
			sélectionnés aura lieu 1 minute plus tard.
		</p>
	</div>
</div>