<?php
/**
 * Page de confirmation pour vider la table des circuits pour le millesime courant
 *
 * Reçoit $form, formulaire de confirmation
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource circuit-vider.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 août 2017
 * @version 2017-2.3.6
 */
?>
<h1>Suppression d'un circuit</h1>
<div id="suppr-wrapper">
	<p>
		Si vous confirmez, la table des circuits pour l'année scolaire <b><?php echo $this->as;?></b>
		sera vidée.
	</p>
	<p>Confirmez-vous ?</p>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>
