<?php
/**
 * Page de consultation des inscrits sur un point d'arrêt d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$retour = $this->url('sbmgestion/transport', array(
    'action' => 'circuit-liste',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'circuit-group-pdf',
    'page' => $this->page
));
$hiddens = array(
    'circuitId' => $this->circuitId,
    //'serviceId' => $this->serviceId,
    //'stationId' => $this->stationId,
    //'station' => $this->circuit->station . ' - ' . $this->circuit->communeStation
);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    )
);
?>
<h1>Groupe des élèves inscrits sur un point d'arrêt d'un circuit</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li>Circuit : <?php echo $this->escapeHtml($this->circuit->serviceId); ?></li>
			<li>Arrêt : <?php echo $this->escapeHtml($this->circuit->station . ' - ' . $this->circuit->communeStation); ?></li>
			<li>Type d'arrêt : <?php echo $this->escapeHtml($this->circuit->typeArret); ?></li>
			<li>Commentaire aller : <?php echo $this->escapeHtml($this->circuit->commentaire1); ?></li>
			<li>Commentaire retour : <?php echo $this->escapeHtml($this->circuit->commentaire2); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
				</tr>
			<?php
foreach ($this->data as $row) {
    echo '<tr class="' . $this->cycle(array("even", "odd"))->next() . '">';
    foreach ($row as $item) {
        echo '<td>' . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
</div>