<?php
/**
 * Page de création d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath('/js/jquery.min.js'));
$this->headScript()->appendFile($this->basePath('/js/gestion-circuit.js'));
$this->inlineScript()->captureStart();
?>
js_actions.init();
<?php 
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', array('action'=> 'circuit-liste', 'page' => $this->page));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
?>
<h1>Création d'un nouveau point d'arrêt sur un circuit</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('circuitId'));
echo $this->formHidden($this->form->get('millesime'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
        <div id="circuit-ajout-serviceId" class="row-inner"><?php echo $this->formRow($this->form->get('serviceId')); ?></div>
        <div id="circuit-ajout-stationId" class="row-inner"><?php echo $this->formRow($this->form->get('stationId')); ?></div>
        <div id="circuit-ajout-passage" class="row-inner"><?php echo $this->formRow($this->form->get('passage')); ?></div>
        <div id="circuit-ajout-typeArret" class="row-inner"><?php echo $this->formRow($this->form->get('typeArret')); ?></div>
        <div id="circuit-ajout-distance" class="row-inner"><?php echo $this->formRow($this->form->get('distance')); ?></div>
        <div id="circuit-ajout-montee" class="row-inner"><?php echo $this->formRow($this->form->get('montee')); ?></div>
        <div id="circuit-ajout-descente" class="row-inner"><?php echo $this->formRow($this->form->get('descente')); ?></div>
        <div id="circuit-ajout-semaine" class="row-inner semaine"><?php echo $this->formRow($this->form->get('semaine')); ?></div>
        <div class="clearfix">
            <div id="horaire-matin" class="row-inner float-left cols-2">
                <fieldset><legend>Horaires aller</legend>
                <div id="circuit-m1" class="row-inner"><?php echo $this->formRow($this->form->get('m1')); ?></div>
                <div id="circuit-m2" class="row-inner"><?php echo $this->formRow($this->form->get('m2')); ?></div>
                <div id="circuit-m3" class="row-inner"><?php echo $this->formRow($this->form->get('m3')); ?></div>
                </fieldset>
            </div>
            <div id="horaires-soir" class="row-inner float-left cols-2">
                <fieldset><legend>Horaires retour</legend>
                <div id="circuit-s1" class="row-inner"><?php echo $this->formRow($this->form->get('s1')); ?></div>
                <div id="circuit-s2" class="row-inner"><?php echo $this->formRow($this->form->get('s2')); ?></div>
                <div id="circuit-s3" class="row-inner"><?php echo $this->formRow($this->form->get('s3')); ?></div>
                </fieldset>
            </div>
        </div>
        <div class="clearfix">
            <div id="commentaire-aller" class="row-inner float-left cols-2">
                <div id="circuit-ajout-commentaire" class="row-inner"><?php echo $this->formRow($this->form->get('commentaire1')); ?></div>
            </div>
            <div id="copy" class="float-left left-10px"><br/>
                <input id="comment-copy" type="button" class="fam-comments-add" title="Copier le commentaire aller comme commentaire retour">
            </div>
            <div id="commentaire-retour" class="row-inner ajout float-left cols-2 left-10px">
                <div id="circuit-ajout-commentaire" class="row-inner"><?php echo $this->formRow($this->form->get('commentaire2')); ?></div>
            </div>
        </div>
        <div id="circuit-ajout-buttons" class="row-inner">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
    </fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div> <?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div>