<?php
/**
 * Page de suppression d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/circuit-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 jan. 2016
 * @version 2016-1.7.0
 */
?>
<h1>Suppression d'un circuit</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du circuit :</p>
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapeHtml($this->data->serviceId); ?></li>
			<li><?php echo $this->escapeHtml($this->data->station . ' - ' . $this->data->communeStation); ?></li>
			<li>Passage n° <?php echo $this->data->passage; ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>