<?php
/**
 * Liste des circuits
 *
 * Cette vue reçoit un objet effectifCircuits qui présente la méthode transportes($circuitId)
 * donnant les effectifs des élèves transportés pour chaque identifiant $circuitId.
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 sept. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->themeJS('gestion-transport', 'circuit-liste.js');
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$circuits = $this->paginator->getCurrentItems();

if ($this->service->moment == 1) {
    $depassement_autorise = $this->service->nbPlaces + 7;
} else {
    $depassement_autorise = $this->service->nbPlaces + 15;
}
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-pdf',
        'page' => $this->page
    ]);
$url_deselection = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-selection',
        'page' => $this->page
    ]);
$url_modifhoraires = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-modif-horaires',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-suppr',
        'page' => $this->page
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-group',
        'id' => $this->page
    ]);
$url_localiser = $this->url('sbmgestion/transport',
    [
        'action' => 'station-localisation',
        'page' => $this->page
    ]);
$action_ici = 'circuit-liste';
$url_ici = $this->url('sbmgestion/transport',
    [
        'action' => $action_ici,
        'page' => $this->page
    ]);
$route_ici = $this->url('sbmgestion/transport', [
    'action' => $action_ici
]);
if ($this->layout()->hassbmservicesms) {
    $url_sms = $this->url('sbmservicesms',
        [
            'action' => 'envoi-groupe',
            'page' => $this->page
        ]);
}
$hiddens_bas = $hiddens = [
    'ligneId' => $this->service->ligneId,
    'sens' => $this->service->sens,
    'moment' => $this->service->moment,
    'ordre' => $this->service->ordre
];
$menuImpression = $this->menuRapports($route_ici, $url_rapports, 'fam-printer', null,
    $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'cancel' => [
        'class' => 'fam-book',
        'formaction' => $url_ici,
        'title' => 'Retour aux services de la ligne ' . $this->ligneId
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel arrêt sur ce circuit'
    ]
];
if ($this->categorieId < 250) {
    unset($actions['ajouter']);
}
?>
<h1>Liste des points d'arrêt du circuit <?=$this->service->designation();?> (<?=$this->service->nbPlaces;?> places)</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="circuits">
			<tbody>
				<tr>
					<th>Commune</th>
					<th>Arrêt</th>
					<th>Emplacement</th>
					<?php if ($this->categorieId >= 250):?>
					<th title="N° de passage sur ce circuit">Pas.</th>
					<th title="Montée">Mont.</th>
					<th title="Decente">Desc.</th>
					<th title="Correspondance">Cor.</th>
					<th title="Visible">Vis.</th>
					<th title="Ouverte">Ouv.</th>
					<?php endif;?>
					<th class="horaire">Horaire</th>
					<th class="jours" title="Jours de passage">Jours</th>
					<th class="nbinscrits" title="Montée"><i class="fam-arrow-up"></i></th>
					<th class="nbinscrits" title="Descente"><i class="fam-arrow-down"></i></th>
					<th class="nbinscrits">Effectif</th>
					<?php if ($this->categorieId >= 250) :?>
					<th class="selection">Sélect.</th>
					<th></th>
					<?php endif;?>
				</tr>
        <?php foreach ($circuits as $circuit) :?>
        	<?php
            $nbInscrits = $this->effectifCircuits->transportes($circuit->circuitId);
            if ($this->categorieId >= 250) {
                $hiddens = [
                    'circuitId' => $circuit->circuitId,
                    'stationId' => $circuit->stationId,
                    'origine' => $url_ici,
                    'action' => $action_ici
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'localiser' => [
                        'class' => 'fam-map-magnify',
                        'formaction' => $url_localiser,
                        'title' => 'position sur la carte'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves du circuit %s à l\'arrêt %s',
                            $circuit->designationService(), $circuit->station)
                    ]
                ];
                if ($this->layout()->hassbmservicesms) {
                    $buttons['sms'] = [
                        'class' => 'fam-phone',
                        'formaction' => $url_sms,
                        'title' => 'Envoyer un SMS'
                    ];
                }
            }
            $css = $this->cycle([
                "even",
                "odd"
            ])->next();
            if ($nbInscrits['effectif_reel'] > $this->service->nbPlaces) {
                if ($nbInscrits['effectif_reel'] > $depassement_autorise) {
                    $css .= ' exces';
                } else {
                    $css .= ' warning gras';
                }
            }
            $horaires = [
                (new \DateTime($circuit->horaireA))->format('H:i'),
                (new \DateTime($circuit->horaireD))->format('H:i')
            ];
            $horaires = array_unique($horaires);
            $horaire_title = ' title="Heure de passage"';
            if (count($horaires) > 1) {
                $horaire_title = " title=\"Heure d'arrivée\nHeure de départ\"";
            }
            $oSemaine = new \SbmCommun\Model\Strategy\Semaine();
            $jours = $oSemaine->renderSemaine($oSemaine->extract($circuit->semaine));
            ?>
            	<tr class="petit <?=$css;?>">
					<td class="commune">
						<?=$this->escapeHtml($circuit->lacommuneStation);?></td>
					<td class="station">
						<?=$this->escapeHtml($circuit->station);?></td>
					<td class="emplacement">
						<?=$this->escapeHtml($circuit->emplacement);?></td>
					<?php if ($this->categorieId >= 250):?>
					<td class="centre passage">
						<?=$circuit->passage;?></td>
					<td class="centre montee">
						<?=$circuit->montee ? 'X' : '';?></td>
					<td class="centre descente">
						<?=$circuit->descente ? 'X' : '';?></td>
					<td class="centre correspondance">
						<?=$circuit->correspondance ? 'X' : '';?></td>
					<td class="centre visible">
						<?=$circuit->visible ? 'X' : '';?></td>
					<td class="centre ouvert">
						<?=$circuit->ouvert ? 'X' : '';?></td>
					<?php endif;?>
					<td class="horaire" <?=$horaire_title;?>>
						<?=implode('<br>', $horaires);?></td>
					<td class="jours">
						<?=$jours;?></td>
					<td class="nbinscrits">
						<?=$nbInscrits['montee'];?></td>
					<td class="nbinscrits">
						<?=$nbInscrits['descente'];?></td>
					<td class="nbinscrits">
						<?=$nbInscrits['effectif_reel'];?></td>
					<?php if ($this->categorieId >= 250):?>
					<td class="centre selection">
						<?=$this->renderCheckbox('selection', 'chk', $circuit->circuitId, $circuit->selection)?>
						</td>
					<td class="boutons">
            			<?=$this->listeLigneActions($circuit->circuitId, $hiddens, $buttons);?></td>
            		<?php endif;?>
				</tr>
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<?php
$actions_selection = [
    'modifhoraires' => [
        'class' => 'fam-clock-edit',
        'formaction' => $url_modifhoraires,
        'title' => 'Modifier les horaires'
    ],
    'deselection' => [
        'class' => 'fam-basket-delete',
        'formaction' => $url_deselection,
        'title' => 'Tout décocher'
    ]
];
?>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<div class="sbm-description float-left">Pour décaler des horaires,
				sélectionner les arrêts concernés.</div>
			<div class="selection">
				Pour les fiches sélectionnées :
				<div class="menu float-right">
					<?=$this->listeZoneActions($hiddens_bas, $actions_selection,['name'=>'zoneselection', 'id'=> 'selection']);?>
				</div>
			</div>
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?>
		</div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
	    </div>
	</div>
</div>