<?php
/**
 * Page de suppression d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/circuit-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 juil. 2020
 * @version 2020-2.6.0
 */
?>
<h1>Suppression d'un circuit</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du circuit :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->designationService()); ?></li>
			<li><?= $this->escapeHtml($this->data->station . ' - ' . $this->data->communeStation); ?></li>
			<li>Passage n° <?= $this->data->passage; ?></li>
			<li>Jours de fonctionnement : <?= $this->data->jours;?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>