<?php
/**
 * Liste des services d'une ligne donnant accès aux points d'arrêt du circuit
 *
 * Chaque service propose un bouton permettant d'ouvrir la liste des points d'arrêt du circuit
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource circuit-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 juil. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$services = $this->paginator->getCurrentItems();
$url_ouvrir = $this->url('sbmgestion/transport', [
    'action' => 'circuit-liste'
]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-service-pdf',
        'page' => $this->page
    ]);
$url_deplacer = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'deplacement',
        'page' => $this->page
    ]);
$route_ici = $this->url('sbmgestion/transport', [
    'action' => 'circuit-service'
]);
$url_ici = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-service',
        'page' => $this->page
    ]);
$hiddens = [];
$menuImpression = $this->menuRapports($route_ici, $url_rapports, 'fam-printer', null,
    $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'cancel' => [
        'class' => 'fam-book',
        'formaction' => $url_ici,
        'title' => 'Refermer ce service'
    ],
    'rapports' => $menuImpression['content']
];
?>
<h1>Circuits de l'année scolaire <?=$this->as;?></h1>
<h2>Liste des services de la ligne <?=$this->ligneId;?></h2>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr>
					<th>Service</th>
					<th>Transporteur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th></th>
				</tr>
				<?php foreach ($services as $service) :?>
				<?php
        $serviceId = sprintf('%d|%s|%d|%d|%d', $service->millesime, $service->ligneId,
            $service->sens, $service->moment, $service->ordre);
        if ($this->effectifServices) {
            $nbInscrits = $this->effectifServices->transportes($service->ligneId,
                $service->sens, $service->moment, $service->ordre);
        } else {
            $nbInscrits = 0;
        }
        $css = $this->cycle([
            "even",
            "odd"
        ])->next();
        if ($service->nbPlaces < $nbInscrits) {
            $css .= ' exces';
        }
        $designationService = $service->designation();
        $hiddens = [
            'ligneId' => $service->ligneId,
            'sens' => $service->sens,
            'moment' => $service->moment,
            'ordre' => $service->ordre,
            'origine' => $url_ici
        ];
        $buttons = [
            'ouvrir' => [
                'class' => 'fam-book-open',
                'formaction' => $url_ouvrir,
                'title' => 'Détails du circuit ' . $designationService
            ],
            'deplacer' => [
                'class' => 'fam-group-gear',
                'formaction' => $url_deplacer,
                'title' => 'Déplacer un groupe d\'élèves à sélectionner'
            ]
        ];
        ?>
				<tr class="petit <?=$css;?>">
					<td class="designationService">
						<?=$this->escapeHtml($designationService);?></td>
					<td class="transporteur">
						<?=$this->escapeHtml($service->transporteur);?></td>
					<td class="nbplaces">
						<?=$this->escapeHtml($service->nbPlaces);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="boutons">
            			<?=$this->listeLigneActions($serviceId, $hiddens, $buttons);?></td>
				</tr>
            	<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
        </div>
	</div>
</div>