<?php
/**
 * Page de création d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/transport', array('action'=> 'circuit-liste', 'page' => $this->page));
?>
<h1>Création d'un nouveau point d'arrêt sur un circuit</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la liste des circuits"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('circuitId'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div id="circuit-edit-service" class="row-inner edit">' . $this->formRow($this->form->get('serviceId')) . '</div>';
echo '<div id="circuit-edit-station" class="row-inner edit">' . $this->formRow($this->form->get('stationId')) . '</div>';
echo '<div id="circuit-edit-aller" class="row-inner edit">' . $this->formRow($this->form->get('aller')) . '</div>';
echo '<div id="circuit-edit-retour" class="row-inner edit">' . $this->formRow($this->form->get('retour')) . '</div>';
echo '<div id="circuit-edit-distance" class="row-inner edit">' . $this->formRow($this->form->get('distance')) . '</div>';
echo '<div id="circuit-edit-jOuverture" class="row-inner edit">' . $this->formRow($this->form->get('jOuverture')) . '</div>';
echo '<div id="circuit-edit-horaire1" class="row-inner edit">' . $this->formRow($this->form->get('horaire1')) . '</div>';
echo '<div id="circuit-edit-horaire2" class="row-inner edit">' . $this->formRow($this->form->get('horaire2')) . '</div>';
echo '<div id="circuit-edit-horaire3" class="row-inner edit">' . $this->formRow($this->form->get('horaire3')) . '</div>';
echo '<div id="circuit-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</fieldset>';
echo $this->form()->closeTag();
?>
</div>