<?php
/**
 * Page de consultation des inscrits sur un point d'arrêt d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 sept. 2018
 * @version 2018-2.4.5
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => $this->origine ?  : 'circuit-liste',
        'page' => $this->pageRetour
    ]);
$url_rapports = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-group-pdf',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport', 
    [
        'action' => $this->origine ? $this->origine . '-group' : 'circuit-group',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_edit = $this->url('sbmgestion/eleve', 
    [
        'action' => 'eleve-edit',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_mail = $this->url('sbmgestion/eleve', 
    [
        'action' => 'responsable-mail',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$hiddens = [
    'circuitId' => $this->circuitId
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'circuit-group'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content']
];
?>
<h1>Groupe des élèves inscrits sur un point d'arrêt d'un circuit</h1>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<ul class="float-left">
			<li>Circuit : <?php echo $this->escapeHtml($this->circuit->serviceId); ?></li>
			<li>Arrêt : <?php echo $this->escapeHtml($this->circuit->station . ' - ' . $this->circuit->communeStation); ?></li>
			<li>Type d'arrêt : <?php echo $this->escapeHtml($this->circuit->typeArret); ?></li>
			<li>Commentaire aller : <?php echo $this->escapeHtml($this->circuit->commentaire1); ?></li>
			<li>Commentaire retour : <?php echo $this->escapeHtml($this->circuit->commentaire2); ?></li>
		</ul>
		<div class="flashMessenger float-right">
		<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
		</div>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->data->count(); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php foreach ($this->data as $row):?>
			<?php
    $hiddens = [
        'eleveId' => $row['eleveId'],
        'email' => $row['email'],
        'responsable' => $row['responsable'],
        'group' => $url_group
    ];
    $buttons = [
        'modifier' => [
            'class' => 'fam-pencil',
            'formaction' => $url_edit,
            'title' => 'Modifier'
        ]
    ];
    if (! empty($row['email'])) {
        $buttons['ecrire'] = [
            'class' => 'fam-email',
            'formaction' => $url_mail,
            'title' => 'Envoyer un email'
        ];
    }
    $this->pictogrammes('init')->addPreinscrit(
        $row['paiement'] == 0 && $row['fa'] == 0 & $row['gratuit'] == 0);
    ?>
			    <tr class="<?php echo $this->cycle(["even", "odd"])->next();?>">
					<td><?php echo $this->pictogrammes();?></td>
					<td><?php echo $this->escapeHtml($row['nom']);?></td>
					<td><?php echo $this->escapeHtml($row['prenom']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL1']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL2']);?></td>
					<td><?php echo $this->escapeHtml($row['codePostal']);?></td>
					<td><?php echo $this->escapeHtml($row['commune']);?></td>
					<td><?php echo $this->escapeHtml($row['etablissement']);?></td>
					<td class="centre"><?php echo $this->escapeHtml($row['classe']);?></td>
					<td><?php echo $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?php echo $this->data->count(); ?> élèves.</em>
		</p>
	</div>
</div>