<?php
/**
 * Page de modification d'un circuit
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath('/js/jquery.min.js'));
$this->headScript()->captureStart();
?>
function montreMer(visible) {
    if (visible) {
        $("#circuit-edit-m2").show();
        $("#circuit-edit-s2").show();
    } else {
        $("#circuit-edit-m2").hide();
        $("#circuit-edit-s2").hide();
    }
}
function montreSam(visible) {
    if (visible) {
        $("#circuit-edit-m3").show();
        $("#circuit-edit-s3").show();
    } else {
        $("#circuit-edit-m3").hide();
        $("#circuit-edit-s3").hide();
    }
}
$(document).ready(function($) {
$("#semaine-mer").click(function(){
    montreMer($(this).is(":checked"));
});
$("#semaine-sam").click(function(){
    montreSam($(this).is(":checked"));
});
});
<?php 
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
montreMer($("#semaine-mer").is(":checked"));
montreSam($("#semaine-sam").is(":checked"));
<?php 
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', array('action'=> 'circuit-liste', 'page' => $this->page));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
?>
<h1>Modification d'un point d'arrêt sur un circuit</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('circuitId'));
echo $this->formHidden($this->form->get('millesime'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
        <div id="circuit-edit-serviceId" class="row-inner"><?php echo $this->formRow($this->form->get('serviceId')); ?></div>
        <div id="circuit-edit-stationId" class="row-inner"><?php echo $this->formRow($this->form->get('stationId')); ?></div>
        <div id="circuit-ajout-passage" class="row-inner"><?php echo $this->formRow($this->form->get('passage')); ?></div>
        <div id="circuit-edit-typeArret" class="row-inner"><?php echo $this->formRow($this->form->get('typeArret')); ?></div>
        <div id="circuit-edit-distance" class="row-inner"><?php echo $this->formRow($this->form->get('distance')); ?></div>
        <div id="circuit-edit-montee" class="row-inner"><?php echo $this->formRow($this->form->get('montee')); ?></div>
        <div id="circuit-edit-descente" class="row-inner"><?php echo $this->formRow($this->form->get('descente')); ?></div>
        <div id="circuit-edit-semaine" class="row-inner semaine"><?php echo $this->formRow($this->form->get('semaine')); ?></div>
        <div class="clearfix">
            <div id="horaire-matin" class="row-inner float-left cols-2">
                <fieldset><legend>Horaires aller</legend>
                <div id="circuit-edit-m1" class="row-inner"><?php echo $this->formRow($this->form->get('m1')); ?></div>
                <div id="circuit-edit-m2" class="row-inner"><?php echo $this->formRow($this->form->get('m2')); ?></div>
                <div id="circuit-edit-m3" class="row-inner"><?php echo $this->formRow($this->form->get('m3')); ?></div>
                </fieldset>
            </div>
            <div id="horaires-soir" class="row-inner edit float-left cols-2">
                <fieldset><legend>Horaires retour</legend>
                <div id="circuit-edit-s1" class="row-inner"><?php echo $this->formRow($this->form->get('s1')); ?></div>
                <div id="circuit-edit-s2" class="row-inner"><?php echo $this->formRow($this->form->get('s2')); ?></div>
                <div id="circuit-edit-s3" class="row-inner"><?php echo $this->formRow($this->form->get('s3')); ?></div>
                </fieldset>
            </div>
        </div>
        <div class="clearfix">
            <div id="commentaire-aller" class="row-inner float-left cols-2">
                <div id="circuit-edit-commentaire1" class="row-inner"><?php echo $this->formRow($this->form->get('commentaire1')); ?></div>
            </div>
            <div id="copy" class="float-left left-10px"><br/>
                <input id="comment-copy" type="button" class="fam-comments-add" title="Copier le commentaire aller comme commentaire retour">
            </div>
            <div id="commentaire-retour" class="row-inner ajout float-left cols-2 left-10px">
                <div id="circuit-edit-commentaire2" class="row-inner"><?php echo $this->formRow($this->form->get('commentaire2')); ?></div>
            </div>
        </div>
        <div id="circuit-edit-buttons" class="row-inner"><?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
    </fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div> <?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div>
<?php $this->inlineScript()->captureStart(); ?>
/**
 * Copie le commentaire1 dans le commentaire2
 */
$(function() {
	$("#comment-copy").click(
			function() {
				$("#circuit-commentaire2").append(
						$("#circuit-commentaire1").val());
			});
});
<?php $this->inlineScript()->captureEnd(); ?>