<?php
/**
 * Page de modification des horaires des arrêts sélectionnés
 *
 * Permet d'avancer ou de retarder le passage aux arrêts sélectionnés d'un
 * certain nombre de minutes et de secondes.
 *
 * Cette vue doit recevoir les paramètres $labelHoraires1, $labelHoraires2 et
 * $labelHoraires3 qui seront les entêtes des colonnes des tableaux Horaires aller
 * et Horaire retour.
 *
 * @project sbm
 * @package view/sbm-gestion/transport
 * @filesource circuit-modif-horaires.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 avr. 2020
 * @version 2020-2.6.0
 */
?>
<h1>Modification des horaires des arrêts sélectionnés</h1>
<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('ligneId'));?>
		<?= $this->formHidden($this->form->get('sens'));?>
		<?= $this->formHidden($this->form->get('moment'));?>
		<?= $this->formHidden($this->form->get('ordre'));?>
    	<fieldset class="sbm-page1">
			<div id="circuit-modif-horaires-buttons" class="row-inner">
				<div id="wrapper-horaire-arrivee" class="row-inner">
					<fieldset>
						<legend>Horaires arrivée en station</legend>
						<table>
							<tr id="circuit-horaireA" class="row-inner">
								<th><?= $this->labelHorairesArrivee;?></th>
								<td><?= $this->FormRadio($this->form->get('horaireA-op'));?></td>
								<td><?= $this->formText($this->form->get('horaireA-min'));?> min</td>
								<td><?= $this->formText($this->form->get('horaireA-sec'));?> sec</td>
							</tr>
						</table>
					</fieldset>
				</div>
				<div id="wrapper-horaire-depart" class="row-inner">
					<fieldset>
						<legend>Horaires départ en station</legend>
						<table id="circuit-horaireD" class="row-inner">
							<tr>
								<th><? $this->labelHorairesDepart;?></th>
								<td>
									<?= $this->FormRadio($this->form->get('horaireD-op'));?>
								</td>
								<td>
									<?= $this->formText($this->form->get('horaireD-min'));?> min
								</td>
								<td>
									<?= $this->formText($this->form->get('horaireD-sec'));?> sec
								</td>
							</tr>
						</table>
					</fieldset>
				</div>
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
    	<?= $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">
			Avancer le passage de 1 minute veut dire que le passage à tous les
			arrêts sélectionnés aura lieu 1 minute plus tôt : sur l'horaire cela
			revient à soustraire 1 minute.<br>Retarder le passage de 1 minute
			veut dire que le passage à tous les arrêts sélectionnés aura lieu 1
			minute plus tard : sur l'horaire cela revient à ajouter 1 minute.
		</p>
	</div>
</div>