<?php
/**
 * Liste des circuits
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/circuit-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 sept. 2018
 * @version 2018-2.4.5
 */
use SbmBase\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/gestion-circuit/liste.js');
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectioncircuit/circuitId:%d',
				success : function(data) {
                    js_selection.actions();
				},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$circuits = $this->paginator->getCurrentItems();

$url_dupliquer = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-dupliquer'
    ]);
$url_vider = $this->url('sbmgestion/transport', [
    'action' => 'circuit-vider'
]);
$url_ajouter = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-pdf',
        'page' => $this->page
    ]);
$url_deselection = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-selection',
        'page' => $this->page
    ]);
$url_modifhoraires = $this->url('sbmgestion/transport', 
    [
        'action' => 'circuit-modif-horaires',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'circuit-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'dupliquer' => [
        'class' => $this->circuitsVides ? 'fam-plugin-add' : 'fam-plugin-delete',
        'formaction' => $this->circuitsVides ? $url_dupliquer : $url_vider,
        'title' => ($this->circuitsVides ? 'Générer' : 'Vider') .
             ' les circuits pour l\'année scolaire ' . $this->as
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel arrêt sur un circuit'
    ]
];
if (! $this->admin) {
    unset($actions['dupliquer']);
}
?>
<h1>Liste des circuits</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="circuits">
			<tbody>
				<tr>
					<th class="serviceid">Code</th>
					<th>Service</th>
					<th>Arrêt</th>
					<th>Type</th>
					<th>Mont.</th>
					<th>Desc.</th>
					<th class="horaire">Matin</th>
					<th class="horaire">Soir</th>
					<th class="horaire">Mercredi</th>
					<th class="nbinscrits">Effectif</th>
					<th class="selection">Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($circuits as $test => $circuit): ?>
        <?php
            $nbInscrits = StdLib::getParamR(
                [
                    $circuit->circuitId,
                    'total'
                ], $this->t_nb_inscrits, 0);
            // construction des JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $circuit->circuitId);
            $jsCallback .= sprintf("$modele\n", $circuit->circuitId, $circuit->circuitId);
            ?>
            <tr
					class="<?php echo $this->cycle(["even", "odd"])->next();?>">
					<td class="serviceid"><?php echo $this->escapeHtml($circuit->serviceId); ?></td>
					<td class="service"><?php echo $this->escapeHtml($circuit->service); ?></td>
					<td class="station"><?php echo $this->escapeHtml($circuit->station); ?></td>
					<td class="type-arret"><?php echo $this->escapeHtml($circuit->typeArret); ?></td>
					<td class="centre montee"><?php echo $circuit->montee ? 'X' : ''; ?></td>
					<td class="centre descente"><?php echo $circuit->descente ? 'X' : ''; ?></td>
					<td class="horaire"><?php echo $circuit->m1; ?></td>
					<td class="horaire"><?php echo $circuit->s1; ?></td>
					<td class="horaire"><?php echo $circuit->s2; ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $circuit->circuitId, $circuit->selection)?></td>
					<td class="boutons">
             <?php
            $url_edit = $this->url('sbmgestion/transport', 
                [
                    'action' => 'circuit-edit',
                    'page' => $this->page
                ]);
            $url_delete = $this->url('sbmgestion/transport', 
                [
                    'action' => 'circuit-suppr',
                    'page' => $this->page
                ]);
            $url_group = $this->url('sbmgestion/transport', 
                [
                    'action' => 'circuit-group',
                    'id' => $this->page
                ]);
            $hiddens = [
                'circuitId' => $circuit->circuitId
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ],
                'eleves' => [
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => sprintf('élèves du circuit %s à l\'arrêt %s', 
                        $circuit->serviceId, $circuit->station)
                ]
            ];
            echo $this->listeLigneActions($circuit->circuitId, $hiddens, $buttons);
            ?>
				</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<?php
$actions_selection = [
    'modifhoraires' => [
        'class' => 'fam-clock-edit',
        'formaction' => $url_modifhoraires,
        'title' => 'Modifier les horaires'
    ],
    'deselection' => [
        'class' => 'fam-basket-delete',
        'formaction' => $url_deselection,
        'title' => 'Tout décocher'
    ]
];
?>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<div class="selection">
				Pour les fiches sélectionnées :
				<div class="menu float-right">
					<?php echo $this->listeZoneActions([], $actions_selection);?>
				</div>
			</div>
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?>
		</div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
	    </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();