<?php
/**
 * Page de modification d'une classe
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/classe-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => 'classe-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'une classe</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('classeId'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
        <fieldset class="sbm-page1">
			<div id="classe-edit-nom" class="row-inner edit">
			<?= $this->formRow($this->form->get('nom'));?></div>
			<div id="classe-edit-aliasCG" class="row-inner edit">
			<?= $this->formRow($this->form->get('aliasCG'));?></div>
			<div id="classe-edit-niveau" class="row-inner edit">
			<?= $this->formRow($this->form->get('niveau'));?></div>
			<div id="classe-edit-rang" class="row-inner edit">
			<?= $this->formRow($this->form->get('rang'));?></div>
			<div id="classe-ajout-suivantId" class="row-inner ajout">
			<?= $this->formRow($this->form->get('suivantId'));?></div>
			<div id="classe-edit-buttons" class="row-inner edit">
            <?= $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel'));?>
            </div>
		</fieldset>
    <?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>