<?php
/**
 * Liste des classes
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/classe-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 janv. 2016
 * @version 2016-1.7.1
 */
use SbmCommun\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$classes = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'classe-ajout',
    'page' => $this->page
));
$url_rapports = $this->url('sbmgestion/transport', array(
    'action' => 'classe-pdf',
    'page' => $this->page
));
$url_retour = $this->url('sbmgestion/transport');
$hiddens = array();
$menuImpression = $this->menuRapports($this->url('sbmgestion/transport', array(
    'action' => 'classe-liste'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ),
    'rapports' => $menuImpression['content'],
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle classe'
    )
);
?>
<h1>Liste des classes</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="classes">
			<tbody>
				<tr>
					<th>Nom</th>
					<th class="invisible">Alias</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th title="pour préparer une simulation">Classe suivante</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($classes as $test => $classe): ?>
        <?php
            
$nbInscrits = StdLib::getParamR(array($classe->classeId, 'transportes'), $this->t_nb_inscrits, 0) . ' / ';
$nbInscrits.= StdLib::getParamR(array($classe->classeId, 'demandes'), $this->t_nb_inscrits, 0);
            // selection
            $modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectionclasse/classeId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;
            
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $classe->classeId);
            $jsCallback .= sprintf("$modele\n", $classe->classeId, $classe->classeId);
            ?>
            <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="nom"><?php echo $this->escapeHtml($classe->nom); ?></td>
					<td class="aliascg invisible"><?php echo $this->escapeHtml($classe->aliasCG); ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre"><?php echo $this->escapeHtml($classe->suivant); ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $classe->classeId, $classe->selection)?></td>
					<td class="boutons">
            <?php
            $url_edit = $this->url('sbmgestion/transport', array(
                'action' => 'classe-edit',
                'page' => $this->page
            ));
            $url_delete = $this->url('sbmgestion/transport', array(
                'action' => 'classe-suppr',
                'page' => $this->page
            ));
            $url_group = $this->url('sbmgestion/transport', array(
                'action' => 'classe-group',
                'id' => $this->page
            ));
            $hiddens = array(
                'classeId' => $classe->classeId
            );
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits en ' . $classe->nom
                )
            );
            echo $this->listeLigneActions($classe->classeId, $hiddens, $buttons);
            ?>
				</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
        <?php echo $this->form()->openTag($this->criteres_form);?>
        <?php echo $this->formCollection($this->criteres_form, true);?>
        <?php echo $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();