<?php
/**
 * Liste des classes
 *
 * Cette vue reçoit une variable $t_nb_inscrits qui est un tableau associatif 
 * structuré comme indiqué dans l'exemple ci-dessous :
 * [
 *     code_classe => [
 *         'demandes' => effectif des demandes
 *         'transportes' => effectif des élèves transportés
 *     ],
 *     ...
 * ]
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/classe-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2019
 * @version 2019-2.5.0
 */
use SbmBase\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectionclasse/classeId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$classes = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'classe-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'classe-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'classe-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle classe'
    ]
];
?>
<h1>Liste des classes</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="classes">
			<tbody>
				<tr>
					<th>Nom</th>
					<th class="invisible">Alias</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th title="pour préparer une simulation">Classe suivante</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($classes as $classe): ?>
        	<?php
            $nbInscrits = StdLib::getParamR([
                $classe->classeId,
                'transportes'
            ], $this->t_nb_inscrits, 0) . ' / ';
            $nbInscrits .= StdLib::getParamR([
                $classe->classeId,
                'demandes'
            ], $this->t_nb_inscrits, 0);
            // construction des JS pour selection
            $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $classe->classeId);
            $jsCallback .= sprintf("$modele\n", $classe->classeId, $classe->classeId);
            $url_edit = $this->url('sbmgestion/transport',
                [
                    'action' => 'classe-edit',
                    'page' => $this->page
                ]);
            $url_delete = $this->url('sbmgestion/transport',
                [
                    'action' => 'classe-suppr',
                    'page' => $this->page
                ]);
            $url_group = $this->url('sbmgestion/transport',
                [
                    'action' => 'classe-group',
                    'id' => $this->page
                ]);
            $hiddens = [
                'classeId' => $classe->classeId
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ],
                'eleves' => [
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits en ' . $classe->nom
                ]
            ];
            ?>
            	<tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="nom">
						<?= $this->escapeHtml($classe->nom); ?></td>
					<td class="aliascg invisible">
						<?= $this->escapeHtml($classe->aliasCG); ?></td>
					<td class="nbinscrits">
						<?= $nbInscrits; ?></td>
					<td class="centre">
						<?= $this->escapeHtml($classe->suivant); ?></td>
					<td class="centre selection">
						<?= renderCheckbox($this, 'selection', 'chk' . $classe->classeId, $classe->selection)?>
						</td>
					<td class="boutons">
						<?= $this->listeLigneActions($classe->classeId, $hiddens, $buttons);?>
						</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
        <?= $this->form()->openTag($this->criteres_form);?>
        <?= $this->formCollection($this->criteres_form, true);?>
        <?= $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?= $jsTrigger;?>}
<?= $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();