<?php
/**
 * Page de suppression d'un classe
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/classe-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
?>
<h1>Suppression d'une classe</h1>
<div class="groupe-wrapper">
	<p>Vous avez demandé la suppression de la classe :</p>
	<div class="header-wrapper">
		<ul>
			<li><?php echo '<span class="label">Code INSEE :</span>' . $this->escapeHtml($this->data->communeId); ?></li>
			<li><?php echo '<span class="label">Commune :</span>' . $this->escapeHtml($this->data->nom); ?></li>
			<li><?php echo '<span class="label">Code postal :</span>' . $this->escapeHtml($this->data->codePostal); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>