<?php

/**
 * Liste des communes
 *
 * Cette vue reçoit un objet effectifCommunes qui présente les méthodes demandes($communeId)
 * et transportes($communeId) donnant les effectifs des élèves ayant fait une demande et des
 * élèves transportés pour chaque identifiant $communeId.
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/commune-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 10 mars 2019
 * @version 2019-2.5.0
 */
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectioncommune/communeId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$communes = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'commune-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'commune-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'commune-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle commune'
    ]
];
?>
<h1>Liste des communes</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?=$this->flashMessenger()->render('success');?>
			<?=$this->flashMessenger()->render('warning');?>
			<?=$this->flashMessenger()->render('error');?>
			<?=$this->flashMessenger()->render('info');?>
			<?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="communes">
			<tbody>
				<tr>
					<th>Département</th>
					<th>Canton</th>
					<th>Code INSEE</th>
					<th>Nom</th>
					<th>Code postal</th>
					<th>Membre</th>
					<th>Desservie</th>
					<th>Visible</th>
					<th>Inscription<br>en ligne
					</th>
					<th>Paiement<br>en ligne
					</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php

            foreach ($communes as $commune) :
                ?>
            <?php
                $nbInscrits = $this->effectifCommunes->transportes($commune->communeId) .
                    ' / ' . $this->effectifCommunes->demandes($commune->communeId);
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%s').trigger('change');\n",
                    $commune->communeId);
                $jsCallback .= sprintf("$modele\n", $commune->communeId,
                    $commune->communeId);
                $url_edit = $this->url('sbmgestion/transport',
                    [
                        'action' => 'commune-edit',
                        'page' => $this->page
                    ]);
                $url_delete = $this->url('sbmgestion/transport',
                    [
                        'action' => 'commune-suppr',
                        'page' => $this->page
                    ]);
                $url_group = $this->url('sbmgestion/transport',
                    [
                        'action' => 'commune-group',
                        'id' => $this->page
                    ]);
                $hiddens = [
                    'communeId' => $commune->communeId
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves de ' . $commune->nom
                    ]
                ];
                ?>
            	<tr class="<?=$this->cycle(["even","odd"])->next();?>">
					<td class="departement">
						<?=$this->escapeHtml($commune->departement);?></td>
					<td class="canton">
						<?=$this->escapeHtml($commune->canton);?></td>
					<td class="communeid">
						<?=$this->escapeHtml($commune->communeId);?></td>
					<td class="nom">
						<?=$this->escapeHtml($commune->nom);?></td>
					<td class="codepostal">
						<?=$this->escapeHtml($commune->codePostal);?></td>
					<td class="centre membre">
						<?=$commune->membre ? 'X' : '';?></td>
					<td class="centre desservie">
						<?=$commune->desservie ? 'X' : '';?></td>
					<td class="centre visible">
						<?=$commune->visible ? 'X' : '';?></td>
					<td class="centre visible">
						<?=$commune->inscriptionenligne ? 'X' : '';?></td>
					<td class="centre visible">
						<?=$commune->paiementenligne ? 'X' : '';?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="centre selection">
						<?=renderCheckbox($this, 'selection', 'chk' . $commune->communeId, $commune->selection)?>
						</td>
					<td class="boutons">
						<?=$this->listeLigneActions($commune->communeId, $hiddens, $buttons);?>
						</td>
				</tr>
        <?php
            endforeach
            ;
            ?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
	    </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?=$jsTrigger;?>}
<?=$jsCallback;?>
});
<?php
$this->headScript()->captureEnd();