<?php
/**
 * Page de modification d'une classe
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/classe-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'commune-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'une commune</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('communeId'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="commune-edit-communeId" class="row-inner edit">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="commune-edit-nom" class="row-inner edit">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="commune-edit-nom-min" class="row-inner edit">
				<?= $this->formRow($this->form->get('nom_min')); ?></div>
			<div id="commune-edit-alias" class="row-inner edit">
				<?= $this->formRow($this->form->get('alias')); ?></div>
			<div id="commune-edit-alias-min" class="row-inner edit">
				<?= $this->formRow($this->form->get('alias_min')); ?></div>
			<div id="commune-edit-aliasCG" class="row-inner edit">
				<?= $this->formRow($this->form->get('aliasCG')); ?></div>
			<div id="commune-edit-codepostal" class="row-inner edit">
				<?= $this->formRow($this->form->get('codePostal')); ?></div>
			<div id="commune-edit-departement" class="row-inner edit">
				<?= $this->formRow($this->form->get('departement')); ?></div>
			<div id="commune-edit-canton" class="row-inner edit">
				<?= $this->formRow($this->form->get('canton')); ?></div>
			<div id="commune-edit-population" class="row-inner edit">
				<?= $this->formRow($this->form->get('population')); ?></div>
			<div id="commune-edit-membre" class="row-inner edit">
				<?= $this->formRow($this->form->get('membre')); ?></div>
			<div id="commune-edit-desservie" class="row-inner edit">
				<?= $this->formRow($this->form->get('desservie')); ?></div>
			<div id="commune-edit-visible" class="row-inner edit">
				<?= $this->formRow($this->form->get('visible')); ?></div>
			<div id="commune-edit-inscriptionenligne" class="row-inner edit">
				<?= $this->formRow($this->form->get('inscriptionenligne')); ?></div>
			<div id="commune-edit-paiementenligne" class="row-inner edit">
				<?= $this->formRow($this->form->get('paiementenligne')); ?></div>
			<div id="commune-edit-buttons" class="row-inner edit">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>