<?php
/**
 * Page de suppression d'un classe
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/classe-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Suppression d'une classe</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de la classe :</p>
	<div class="header-wrapper">
		<ul>
			<li><span class="label">Code INSEE :</span>
				<?= $this->escapeHtml($this->data->communeId);?></li>
			<li><span class="label">Commune :</span>
				<?= $this->escapeHtml($this->data->nom);?></li>
			<li><span class="label">Code postal :</span>
				<?= $this->escapeHtml($this->data->codePostal);?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>