<?php
/**
 * Liste des communes
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/commune-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 mai 2014
 * @version 2014-1
 */
use SbmCommun\Model\StdLib;
 
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$communes = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'commune-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'commune-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/transport');
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-printer',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouvelle commune'
    )
);
?>
<h1>Liste des communes</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
	    <div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	    <div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
	</div>
	<div id="liste-inner">
	<table class="communes">
		<tbody>
			<tr>
				<th>Département</th>
				<th>Canton</th>
				<th>Code INSEE</th>
				<th>Nom</th>
				<th>Code postal</th>
				<th>Membre</th>
				<th>Desservie</th>
				<th>Visible</th>
				<th>Inscrits</th>
				<th>Sélect.</th>
				<th></th>
			</tr>
            <?php foreach($communes as $test => $commune): ?>
            <?php 
            $nbInscrits = StdLib::getParamR(array($commune->communeId, 'total'), $this->t_nb_inscrits, 0); 
            // selection
            $modele = <<<EOT
$("#chk%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectioncommune/communeId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;
            
            $jsTrigger .= sprintf("$('#chk%s').trigger('change');\n", $commune->communeId);
            $jsCallback .= sprintf("$modele\n", $commune->communeId, $commune->communeId);
            ?>
            <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
				<td class="departement"><?php echo $this->escapeHtml($commune->departement); ?></td>
				<td class="canton"><?php echo $this->escapeHtml($commune->canton); ?></td>
				<td class="communeid"><?php echo $this->escapeHtml($commune->communeId); ?></td>
				<td class="nom"><?php echo $this->escapeHtml($commune->nom); ?></td>
				<td class="codepostal"><?php echo $this->escapeHtml($commune->codePostal); ?></td>
				<td class="centre membre"><?php echo $commune->membre ? 'X' : ''; ?></td>
				<td class="centre desservie"><?php echo $commune->desservie ? 'X' : ''; ?></td>
				<td class="centre visible"><?php echo $commune->visible ? 'X' : ''; ?></td>
				<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
				<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $commune->communeId, $commune->selection)?></td>
				<td class="boutons">
            <?php
            $url_edit = $this->url('sbmgestion/transport', array(
                'action' => 'commune-edit',
                'page' => $this->page,
            ));
            $url_delete = $this->url('sbmgestion/transport', array(
                'action' => 'commune-suppr',
                'page' => $this->page,
            ));
            $url_group = $this->url('sbmgestion/transport', array(
                'action' => 'commune-group',
                'page' => $this->page,
            ));
            $hiddens = array('communeId' => $commune->communeId);
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves de ' . $commune->nom
                )
            );
            echo $this->listeLigneActions($commune->communeId, $hiddens, $buttons);
            ?>
				</td>
			</tr>         
        <?php endforeach;?>
        </tbody>
	</table>
	</div>
	<div id="liste-footer">
	    <div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	    <div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
	    </div>
    </div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();