<?php
/**
 * Page de consultation des inscrits d'un commune
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/commune-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 août 2015
 * @version 2015-2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/transport', array(
    'action' => 'commune-liste',
    'page' => $this->pageRetour
));
$url_rapports = $this->url('sbmgestion/transport', array(
    'action' => 'commune-group-pdf',
    'page' => $this->page
));
$url_origine = $this->url('sbmgestion/transport', array(
    'action' => 'commune-group',
    'page' => $this->page
));
$url_edit = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-edit',
    'page' => $this->page
));
$hiddens = array(
    'communeId' => $this->communeId
);
$menuImpression = $this->menuRapports($this->url('sbmgestion/transport', array(
    'action' => 'commune-group'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => $menuImpression['content']
);

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Groupe des élèves transportés résidant dans une commune</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li>commune : <?php echo $this->escapeHtml($this->commune->nom); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->paginator->getAdapter()->count(); ?> prises en charge.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
					<th></th>
				</tr>
			<?php
foreach ($data as $row) :
    $pictogrammes = array();
    $inscrit = $row['paiement'] == 1;
    $inscrit |= $row['fa'] == 1;
    $inscrit |= $row['gratuit'] > 0;
    //$inscrit |= ($row['demandeR1'] == 2 && $row['accordR1'] == 0 && $row['subventionR1'] == 1);
    //$inscrit |= ($row['demandeR2'] == 2 && $row['accordR2'] == 0 && $row['subventionR2'] == 1);
    if (! $inscrit) {
        $pictogrammes[] = '<i class="fam-tag-orange" title="Préinscrit"></i>';
    }
    ?>
                <tr
					class="<?php echo $this->cycle(array("even","odd"))->next();?>">
					<td><?php echo implode(' ', $pictogrammes);?></td>
					<td><?php echo $row['nom'];?></td>
					<td><?php echo $row['prenom'];?></td>
					<td><?php echo $row['adresseL1'];?></td>
					<td><?php echo $row['adresseL2'];?></td>
					<td><?php echo $row['codePostal'];?></td>
					<td><?php echo $row['commune'];?></td>
					<td><?php echo $row['etablissement'];?></td>
					<td class="centre"><?php echo $row['classe'];?></td>
					<?php 
					$buttons = array( 'modifier' => array(
					'class' => 'fam-pencil', 'formaction' => $url_edit, 'title' =>
					'Modifier' ) ); $hiddens = array( 'origine' => $url_origine, 'info'
					=> $row['nom'] . ' ' . $row['prenom'], //'responsableId' =>
					$this->responsableId, 'eleveId' => $row['eleveId'] );?>
					<td><?php echo $this->listeLigneActions($row['eleveId'], $hiddens,$buttons);?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
		
		
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		</p>
	</div>
</div>
