<?php
/**
 * Liste des communes
 * 
 * Cette vue reçoit une variable $t_nb_inscrits qui est un tableau associatif 
 * structuré comme indiqué dans l'exemple ci-dessous :
 * [
 *     code_commune => [
 *         'demandes' => [
 *             'r1' => effectif des demandeR1,
 *             'r2' => effectif des demandeR2
 *         ],
 *         'transportes' => [
 *             'r1' => effectif des élèves transportés en demandeR1,
 *             'r2' => effectif des élèves transportés en demandeR2
 *         ],
 *         'total' => [
 *             'demandes' => effectif total des demandes en r1 ou en r2,
 *             'transportes' => effectif total des élèves transportés en demandeR1 ou en demande R2
 *         ]
 *     ],
 *     ...
 * ]
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/commune-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.4.7
 */
use SbmBase\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectioncommune/communeId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$communes = $this->paginator->getCurrentItems();
$url_ajouter = $this->url('sbmgestion/transport', 
    [
        'action' => 'commune-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport', 
    [
        'action' => 'commune-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'commune-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle commune'
    ]
];
// die(var_dump($this->t_nb_inscrits));
?>
<h1>Liste des communes</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="communes">
			<tbody>
				<tr>
					<th>Département</th>
					<th>Canton</th>
					<th>Code INSEE</th>
					<th>Nom</th>
					<th>Code postal</th>
					<th>Membre</th>
					<th>Desservie</th>
					<th>Visible</th>
					<th>Inscription<br>en ligne</th>
					<th>Paiement<br>en ligne</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($communes as $test => $commune): ?>
            <?php
                $demandes = StdLib::getParamR(
                    [
                        $commune->communeId,
                        'total',
                        'demandes'
                    ], $this->t_nb_inscrits, 0);
                $transportes = StdLib::getParamR(
                    [
                        $commune->communeId,
                        'total',
                        'transportes'
                    ], $this->t_nb_inscrits, 0);
                $nbInscrits = "$transportes / $demandes";
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%s').trigger('change');\n", 
                    $commune->communeId);
                $jsCallback .= sprintf("$modele\n", $commune->communeId, 
                    $commune->communeId);
                ?>
            <tr
					class="<?php echo $this->cycle(["even", "odd"])->next();?>">
					<td class="departement"><?php echo $this->escapeHtml($commune->departement); ?></td>
					<td class="canton"><?php echo $this->escapeHtml($commune->canton); ?></td>
					<td class="communeid"><?php echo $this->escapeHtml($commune->communeId); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($commune->nom); ?></td>
					<td class="codepostal"><?php echo $this->escapeHtml($commune->codePostal); ?></td>
					<td class="centre membre"><?php echo $commune->membre ? 'X' : ''; ?></td>
					<td class="centre desservie"><?php echo $commune->desservie ? 'X' : ''; ?></td>
					<td class="centre visible"><?php echo $commune->visible ? 'X' : ''; ?></td>
					<td class="centre visible"><?php echo $commune->inscriptionenligne ? 'X' : ''; ?></td>
					<td class="centre visible"><?php echo $commune->paiementenligne ? 'X' : ''; ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $commune->communeId, $commune->selection)?></td>
					<td class="boutons">
            <?php
                $url_edit = $this->url('sbmgestion/transport', 
                    [
                        'action' => 'commune-edit',
                        'page' => $this->page
                    ]);
                $url_delete = $this->url('sbmgestion/transport', 
                    [
                        'action' => 'commune-suppr',
                        'page' => $this->page
                    ]);
                $url_group = $this->url('sbmgestion/transport', 
                    [
                        'action' => 'commune-group',
                        'id' => $this->page
                    ]);
                $hiddens = [
                    'communeId' => $commune->communeId
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves de ' . $commune->nom
                    ]
                ];
                echo $this->listeLigneActions($commune->communeId, $hiddens, $buttons);
                ?>
				</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
	    </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();