<?php
/**
 * Liste des etablissements
 *
 * Cette vue reçoit un objet effectifEtablissements qui présente les méthodes
 * demandes($etablissementId) et transportes($etablissementId) donnant les effectifs des élèves
 * ayant fait une demande et des élèves transportés pour chaque identifiant $etablissementId.
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 avr. 2020
 * @version 2020-2.6.0
 */
use SbmCartographie\Model\Point;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèles de jsCallback pour selection, visible et desservie
$modele = <<<EOT
$("#chk%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectionetablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
$("#vis%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'visibleetablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
$("#des%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'desservietablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$etablissements = $this->paginator->getCurrentItems();

$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-pdf',
        'page' => $this->page
    ]);
$url_carte = $this->url('sbmcarte', [
    'action' => 'etablissements',
    'filtre' => 0
]);
$url_edit = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-suppr',
        'page' => $this->page
    ]);
$url_relation_services = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service',
        'id' => $this->page
    ]);
$url_relation_stations = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-station',
        'id' => $this->page
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-group',
        'id' => $this->page
    ]);
$url_localiser = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-localisation',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
if ($this->layout()->hassbmservicesms) {
    $url_sms = $this->url('sbmservicesms', [
        'action' => 'envoi-groupe',
        'page' => $this->page
    ]);
}
$hiddens = [
    'back' => $this->url('sbmgestion/transport',
        [
            'action' => 'etablissement-liste',
            'page' => $this->page
        ])
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'etablissement-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'carte' => [
        'class' => 'fam-map-magnify',
        'formaction' => $url_carte,
        'title' => 'Carte des établissements'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel établissement scolaire'
    ]
];
?>
<h1>Liste des établissements</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?=$this->flashMessenger()->render('success');?>
			<?=$this->flashMessenger()->render('warning');?>
			<?=$this->flashMessenger()->render('error');?>
			<?=$this->flashMessenger()->render('info');?>
			<?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="etablissements">
			<tbody>
				<tr class="petit">
					<th></th>
					<th>Code</th>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Email</th>
					<th title="Nombre d'élèves transportés / Nombre de demandes">Effectifs</th>
					<th>Desservis</th>
					<th>Visible</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php

        foreach ($etablissements as $etablissement) :
            ?>
        	<?php
            $pt = new Point($etablissement->x, $etablissement->y);
            $ptOk = $this->projection->isValid($pt, 'etablissement');
            $nbInscrits = $this->effectifEtablissements->transportes(
                $etablissement->etablissementId) . ' / ' .
                $this->effectifEtablissements->demandes($etablissement->etablissementId);
            // construction des JS pour selection, visible et desservie
            $jsTrigger .= sprintf("$('#chk%s').trigger('change');\n",
                $etablissement->etablissementId);
            $jsTrigger .= sprintf("$('#vis%s').trigger('change');\n",
                $etablissement->etablissementId);
            $jsTrigger .= sprintf("$('#des%s').trigger('change');\n",
                $etablissement->etablissementId);
            $jsCallback .= str_replace('%s', $etablissement->etablissementId, "$modele\n");
            $hiddens = [
                'etablissementId' => $etablissement->etablissementId
            ];
            $buttons = [
                'modifier' => [
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ],
                'localiser' => [
                    'class' => $ptOk ? 'fam-map-magnify' : 'fam-map-add',
                    'formaction' => $url_localiser,
                    'title' => $ptOk ? 'position sur la carte' : 'position manquante'
                ],
                'supprimer' => [
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ],
                'services' => [
                    'class' => 'fam-table-relationship',
                    'formaction' => $url_relation_services,
                    'title' => 'circuits desservant cet établissement'
                ],
                'stations' => [
                    'class' => 'fam-arrow-in',
                    'formaction' => $url_relation_stations,
                    'title' => 'stations desservant cet établissement'
                ],
                'eleves' => [
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits dans cet établissement scolaire'
                ]
            ];
            if ($this->layout()->hassbmservicesms) {
                $buttons['sms'] = [
                    'class' => 'fam-phone',
                    'formaction' => $url_sms,
                    'title' => 'Envoyer un SMS'
                ];
            }
            ?>
            	<tr
					class="petit <?=$this->cycle(["even","odd"])->next();?>">
					<td>
					<?php

            if (! $ptOk) :
                ?>
					   <i class="fam-error"></i>
					<?php endif;

            ?>
					</td>
					<td class="etablissementid">
						<?=$this->escapeHtml($etablissement->etablissementId);?></td>
					<td class="nom">
						<?=$this->escapeHtml($etablissement->nom);?></td>
					<td class="commune">
						<?=$this->escapeHtml($etablissement->lacommune);?></td>
					<td class="codepostal">
						<?=$this->escapeHtml($etablissement->codePostal);?></td>
					<td class="telephone">
						<?=$this->telephone($etablissement->telephone);?></td>
					<td class="email">
						<?=$this->escapeHtml($etablissement->email);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="centre desservi">
						<?=$this->renderCheckbox('desservie', 'des', $etablissement->etablissementId,$etablissement->desservie)?></td>
					<td class="centre visible">
						<?=$this->renderCheckbox('visible', 'vis', $etablissement->etablissementId,$etablissement->visible)?></td>
					<td class="centre selection">
						<?=$this->renderCheckbox('selection', 'chk', $etablissement->etablissementId,$etablissement->selection)?></td>
					<td class="boutons">
						<?=$this->listeLigneActions($etablissement->etablissementId, $hiddens, $buttons);?>
						</td>
				</tr>
        <?php
        endforeach
        ;
        ?>
        	</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?>
			</div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?=$jsTrigger;?>}
<?=$jsCallback;?>
});
<?php
$this->headScript()->captureEnd();