<?php
/**
 * Liste des services pour un établissement donné
 *
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 mars 2015
 * @version 2015-1
 */
use SbmCommun\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-service-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-service-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-service',
    'page' => $this->page
));
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';

$hiddens = array(
    'serviceId' => null,
    'etablissementId' => $this->etablissement->etablissementId,
    'origine' => 'etablissement-service'
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouveau service'
    )
);
?>
<h1>Liste des services
<?php echo substr($this->etablissement->nom, 0, 5) == 'ECOLE' ? ' de l\'' : ' du '?>
<?php echo $this->etablissement->nom . ' - ' . $this->etablissement->commune; ?>

</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr>
					<th>Code</th>
					<th>Nom</th>
					<th>Alias</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th></th>
				</tr>
            <?php foreach($this->data as $test => $service): ?>
            <?php $fmt?>
            <?php $nbInscrits = StdLib::getParamR(array($service->serviceId, 'total'), $this->t_nb_inscrits, 0); ?>
            <?php $exces = $service->serv_nbPlaces < $nbInscrits; ?>
                <tr
					class="<?php echo $this->cycle(array(
                    "even",
                    "odd"
                ))->next();
                if ($exces)
                    echo ' exces';
                ?>">
					<td class="serviceid"><?php echo $this->escapeHtml($service->serviceId); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($service->serv_nom); ?></td>
					<td class="aliascg"><?php echo $this->escapeHtml($service->serv_aliasCG); ?></td>
					<td class="transporteur"><?php echo $this->escapeHtml($service->serv_transporteur); ?></td>
					<td class="operateur"><?php echo $this->escapeHtml($service->serv_operateur); ?></td>
					<td class="nbplaces"><?php echo $this->escapeHtml($service->serv_nbPlaces); ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="boutons">
            <?php
                $url_delete = $this->url('sbmgestion/transport', array(
                    'action' => 'etablissement-service-suppr',
                    'page' => $this->page
                ));
                $url_group = $this->url('sbmgestion/transport', array(
                    'action' => 'etablissement-service-group',
                    'page' => $this->page
                ));
                $hiddens = array(
                    'etablissementId' => $etablissement->etablissementId,
                    'serviceId' => $service->serviceId,
                    'origine' => 'etablissement-service'
                );
                $buttons = array(
                    'supprimer' => array(
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ),
                    'eleves' => array(
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de %s inscrits sur le service %s', $this->etablissement->nom, $service->serviceId)
                    )
                );
                echo $this->listeLigneActions($etablissement->etablissementId . '|' . $service->serviceId, $hiddens, $buttons);
                ?>
			        </td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>