<?php
/**
 * Page de suppression d'une relation etablissement - service
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

if (empty($this->etablissementId)) {
    $h1 = sprintf(
        "Suppression d'un établissement desservi par le circuit %s (%s)\nTransporteur : %s",
        $this->serviceId, $this->service->nom, $this->service->transporteur);
    $msg = <<<EOT
Vous avez demandé la suppression de l'établissement %s - %s dans la liste des établissements
desservis par le circuit %s.
EOT;
    $msg = sprintf($msg, $this->etablissement->nom, $this->etablissement->commune,
        $this->serviceId);
} else {
    $h1 = sprintf("Suppression d'un service desservant l'établissement\n%s %s - %s",
        $this->etablissementId, $this->etablissement->nom, $this->etablissement->commune);
    $msg = <<<EOT
Vous avez demandé la suppression du service <br><b>%s</b> <br>dans la liste des circuits desservant
l'établissement <b>%s - %s</b>.
EOT;
    $msg = sprintf($msg, $this->service->designation(), $this->etablissement->nom,
        $this->etablissement->commune);
}
?>
<h1><?= $h1; ?></h1>
<div id="suppr-wrapper">
	<p><?= $msg; ?></p>
	<div class="header-wrapper"></div>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($form);?>
    <?= $this->formCollection($form);?>
    <?= $this->form()->closeTag();?>
</div>