<?php
/**
 * Liste des services pour un établissement donné
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 mars 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-ajout',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-pdf',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service',
        'page' => $this->pageRetour
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-suppr',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-group',
        'pr' => $this->page,
        'id' => $this->pageRetour
    ]);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$hiddens = [
    'ligneId' => null,
    'etablissementId' => $this->etablissement->etablissementId,
    'origine' => 'etablissement-service'
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'etablissement-service'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau service'
    ]
];

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Liste des services
<?=substr($this->etablissement->nom, 0, 5) == 'ECOLE' ? ' de l\'' : ' du '?>
<?=$this->etablissement->nom . ' - ' . $this->etablissement->commune;?>

</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner etablissements-services">
			<tbody>
				<tr>
					<th>Code</th>
					<th>Ligne</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th>Descente</th>
					<th>Horaire</th>
					<th></th>
				</tr>
            <?php
            foreach ($data as $entity) :
                ?>
            	<?php
                $entity->setFlags(ArrayObject::ARRAY_AS_PROPS);
                if ($this->effectifEtablissementsServices) {
                    $nbInscrits = $this->effectifEtablissementsServices->transportes(
                        $entity->ligneId, $entity->sens, $entity->moment, $entity->ordre);
                } else {
                    $nbInscrits = 0;
                }
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($entity->serv_nbPlaces < $nbInscrits) {
                    $css .= ' exces';
                }
                $codeService = sprintf('%s-%d%d%d', $entity->ligneId, $entity->sens,
                    $entity->moment, $entity->ordre);
                ?>
                <tr class="petit <?=$css;?>">
					<td class="serviceid">
						<?=$this->escapeHtml($codeService);?></td>
					<td class="ligne">
						<?=$this->escapeHtml($entity->ligne_extremite1) . ' - ' .$this->escapeHtml($entity->ligne_extremite2);?></td>
					<td class="transporteur">
						<?=$this->escapeHtml($entity->serv_transporteur);?></td>
					<td class="operateur">
						<?=$this->escapeHtml($entity->ligne_operateur);?></td>
					<td class="nbplaces">
						<?=$this->escapeHtml($entity->serv_nbPlaces);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="station">
						<?=$this->escapeHtml($entity->sta_nom);?></td>
					<td class="horaire centre">
						<?=DateLib::formatHoraire($entity->cir_horaireA);?></td>
					<td class="boutons">
            <?php
                $hiddens = [
                    'etablissementId' => $this->etablissement->etablissementId,
                    'ligneId' => $entity->ligneId,
                    'sens' => $entity->sens,
                    'moment' => $entity->moment,
                    'ordre' => $entity->ordre,
                    'origine' => 'etablissement-service'
                ];
                $buttons = [
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de %s inscrits sur le service %s',
                            $this->etablissement->nom, $codeService)
                    ]
                ];
                // etablissementId|millesime|ligneId|sens|moment|ordre
                $id = sprintf('%s|%d|%s|%d|%d|%d', $this->etablissement->etablissementId,
                    $entity->millesime, $entity->ligneId, $entity->sens, $entity->moment,
                    $entity->ordre);
                echo $this->listeLigneActions($id, $hiddens, $buttons);
                ?>
			        </td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
	</div>
</div>