<?php
/**
 * Liste des services pour un établissement donné
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-ajout',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-pdf',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service',
        'page' => $this->pageRetour
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-suppr',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-group',
        'pr' => $this->page,
        'id' => $this->pageRetour
    ]);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$hiddens = [
    'serviceId' => null,
    'etablissementId' => $this->etablissement->etablissementId,
    'origine' => 'etablissement-service'
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'etablissement-service'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau service'
    ]
];

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Liste des services
<?=substr($this->etablissement->nom, 0, 5) == 'ECOLE' ? ' de l\'' : ' du '?>
<?=$this->etablissement->nom . ' - ' . $this->etablissement->commune;?>

</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner etablissements-services">
			<tbody>
				<tr>
					<th>Code</th>
					<th>Nom</th>
					<th>Alias</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th>Descente</th>
					<th>Matin</th>
					<th>Midi</th>
					<th>Soir</th>
					<th></th>
				</tr>
            <?php

            foreach ($data as $entity) :
                ?>
            	<?php
                $nbInscrits = $this->effectifEtablissementsServices->transportes(
                    $entity->serviceId);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($entity->serv_nbPlaces < $nbInscrits) {
                    $css .= ' exces';
                }
                ?>
                <tr class="<?=$css;?>">
					<td class="serviceid">
						<?=$this->escapeHtml($entity->serviceId);?></td>
					<td class="nom">
						<?=$this->escapeHtml($entity->serv_nom);?></td>
					<td class="aliascg">
						<?=$this->escapeHtml($entity->serv_aliasCG);?></td>
					<td class="transporteur">
						<?=$this->escapeHtml($entity->serv_transporteur);?></td>
					<td class="operateur">
						<?=$this->escapeHtml($entity->serv_operateur);?></td>
					<td class="nbplaces">
						<?=$this->escapeHtml($entity->serv_nbPlaces);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="station">
						<?=$this->escapeHtml($entity->sta_nom);?></td>
					<td class="matin">
						<?=$entity->cir_m1;?></td>
					<td class="midi">
						<?=$entity->cir_s2;?></td>
					<td class="soir">
						<?=$entity->cir_s1;?></td>
					<td class="boutons">
            <?php
                $hiddens = [
                    'etablissementId' => $this->etablissement->etablissementId,
                    'serviceId' => $entity->serviceId,
                    'origine' => 'etablissement-service'
                ];
                $buttons = [
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de %s inscrits sur le service %s',
                            $this->etablissement->nom, $entity->serviceId)
                    ]
                ];
                echo $this->listeLigneActions(
                    $this->etablissement->etablissementId . '|' . $entity->serviceId,
                    $hiddens, $buttons);
                ?>
			        </td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
	</div>
</div>