<?php
/**
 * Page de suppression d'un etablissement
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/etablissement-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
?>
<h1>Suppression d'un établissement</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de l'établissement :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->nom); ?></li>
			<li><?= $this->escapeHtml($this->data->commune); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($form);?>
    <?= $this->formCollection($form);?>
    <?= $this->form()->closeTag();?>
</div>