<?php
/**
 * Page de création d'un lien entre un établissement et un service
 * (le service desservant l'établissement)
 * 
 * Voici les variables définies dans cette vue:
 * $origine         : prend l'une des valeurs 'etablissement-service' ou 'service-etablissement'
 * $etablissementId : null ou identifiant d'un établissement
 * $serviceId       : null ou identifiant d'un service
 *                    (l'un parmi $etablissementId, $serviceId est null, l'autre est donné)
 * $etablissement   : null si $etablissementId est null, sinon fiche de l'établissement pour affichage dans titre
 * $service         : null si $serviceId est null, sinon fiche du service pour affichage dans le titre
 * $form            : le formulaire de saisi
 * $page            : la page de la liste initiale dans etablissement-liste ou dans service-liste
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service-ajout.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()
    ->appendFile($this->basePath() . '/js/jquery.min.js')
    ->captureStart();
?>
$(document).ready(function($) {
  // adapte le select aux stations de ce circuit
  $("#serviceIdElement").change(function() {
    var valeur = $(this).val();
    if (valeur != '') {
        $.ajax({
				url : '/sbmajaxtransport/getcircuitstations/serviceId:' + valeur,
				dataType: 'json',
				success : function(dataJson) {
					$('#stationId').empty();
					if (dataJson.success==1) {
					    $.each(dataJson.data, function(k, d) {
	                        $('#stationIdElement').append('<option value="' + d + '">' + k + '</option>');
	                    });
	                }
				},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
	}
  });
});
<?php
$this->headScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', array(
    'action' => $this->origine,
    'page' => $this->page
));
$hiddens = array(
    'etablissementId' => $this->etablissementId,
    'serviceId' => $this->serviceId,
    'origine' => $this->origine
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
if ($this->origine == 'service-etablissement') {
    $h1 = sprintf("Ajout d'un établissement desservi par le circuit %s (%s)\nTransporteur : %s", $this->serviceId, $this->service->nom, $this->service->transporteur);
    $description1 = "l'établissement";
} else {
    $h1 = sprintf("Ajout d'un service desservant l'établissement\n%s %s - %s", $this->etablissementId, $this->etablissement->nom, $this->etablissement->commune);
    $description1 = 'le service';
}
?>
<h1><?php echo nl2br($h1); ?></h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
?>
    <fieldset class="sbm-page1">
<?php
echo $this->formHidden($this->form->get('origine'));
echo $this->formHidden($this->form->get('csrf'));
if ($this->origine == 'service-etablissement') {
    echo $this->formHidden($this->form->get('serviceId'));
    echo '<div id="etablissement-service-ajout-etablissementId" class="row-inner ajout">' . $this->formRow($this->form->get('etablissementId')) . '</div>';
} else {
    echo $this->formHidden($this->form->get('etablissementId'));
    echo '<div id="etablissement-service-ajout-serviceId" class="row-inner ajout">' . $this->formRow($this->form->get('serviceId')) . '</div>';
}
?>
    <div id="etablissement-service-ajout-stationId"
				class="row-inner ajout">
        <?php echo $this->formRow($this->form->get('stationId'));?>
        <p class="sbm-description">Commencez par choisir <?php echo $description1;?><br>Si
					la station n'est pas dans la liste, allez d'abord la rajouter dans
					le circuit que vous avez choisi.
				</p>
			</div>
			<div id="classe-ajout-buttons" class="row-inner ajout">
    <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?>
    </div>
		</fieldset>
<?php

echo $this->form()->closeTag();
?>
    </div>
	<div id="fiche-footer"></div>
</div>