<?php
/**
 * Page de consultation des inscrits d'un etablissement
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/etablissement-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 mars 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$retour = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-liste',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-group-pdf',
    'page' => $this->page
));
$hiddens = array(
    'etablissementId' => $this->etablissementId
);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    )
);
?>
<h1>Groupe des élèves inscrits dans un établissement</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li><?php echo $this->escapeHtml($this->etablissement->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->etablissement->commune); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php
foreach ($this->data as $row) {
    echo '<tr class="' . $this->cycle(array("even", "odd"))->next() . '">';
    foreach ($row as $item) {
        echo '<td>' . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
</div>