<?php
/**
 * Page de création d'un lien entre un établissement et un service
 * (le service desservant l'établissement)
 *
 * Voici les variables définies dans cette vue:
 * $origine         : prend l'une des valeurs 'etablissement-service' ou 'service-etablissement'
 * $etablissementId : null ou identifiant d'un établissement
 * $serviceId       : null ou identifiant d'un service
 *                    (l'un parmi $etablissementId, $serviceId est null, l'autre est donné)
 * $etablissement   : null si $etablissementId est null, sinon fiche de l'établissement pour affichage dans titre
 * $service         : null si $serviceId est null, sinon fiche du service pour affichage dans le titre
 * $form            : le formulaire de saisi
 * $page            : la page de la liste initiale dans etablissement-liste ou dans service-liste
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-service-ajout.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mars 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->headScript()->appendFile(
    $this->basePath('/js/gestion-transport/etablissement-service-ajout.js'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => $this->origine,
        'page' => $this->page
    ]);
$hiddens = [
    'etablissementId' => $this->etablissementId,
    'serviceId' => $this->serviceId,
    'origine' => $this->origine
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
if ($this->origine == 'service-etablissement') {
    $h1 = sprintf(
        "Ajout d'un établissement desservi par le circuit %s (%s)\nTransporteur : %s",
        $this->serviceId, $this->service->nom, $this->service->transporteur);
    $description1 = "l'établissement";
} else {
    $h1 = sprintf("Ajout d'un service desservant l'établissement\n%s %s - %s",
        $this->etablissementId, $this->etablissement->nom, $this->etablissement->commune);
    $description1 = 'le service';
}
?>
<h1><?= nl2br($h1); ?></h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
    	<fieldset class="sbm-page1">

        <?= $this->formHidden($this->form->get('origine'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
        <?php if ($this->origine == 'service-etablissement') :?>
            <?= $this->formHidden($this->form->get('serviceId'));?>
            <div id="wrapper-etablissementId"
				class="row-inner ajout">
            	<?= $this->formRow($this->form->get('etablissementId'));?>
            </div>
        <?php else :?>
            <?= $this->formHidden($this->form->get('etablissementId'));?>
            <div id="wrapper-serviceId"
				class="row-inner ajout">' .
            	<?= $this->formRow($this->form->get('serviceId'));?>
            </div>
        <?php endif;?>
    		<div id="wrapper-stationId"
				class="row-inner ajout">
        		<?= $this->formRow($this->form->get('stationId'));?>
        		<p class="sbm-description">Commencez par choisir <?= $description1;?><br>Si
					la station n'est pas dans la liste, allez d'abord la rajouter dans
					le circuit que vous avez choisi.
				</p>
			</div>
			<div id="wrapper-buttons" class="row-inner ajout">
    			<?= $this->formSubmit($this->form->get('submit'));?>
    			<?= $this->formSubmit($this->form->get('cancel'));?>
    		</div>
		</fieldset>
    	<?= $this->form()->closeTag();?>
    </div>
	<div id="fiche-footer"></div>
</div>