<?php
/**
 * Page de modification d'un etablissement
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/etablissement-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/transport', array('action'=> 'etablissement-liste', 'page' => $this->page));
?>
<h1>Modification d'un établissement</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la liste des etablissements"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('etablissementId'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div class="float-left cols-2">';
echo '<div id="etablissement-edit-etablissementId" class="row-inner edit">' . $this->formRow($this->form->get('codeEtablissement')) . '</div>';
echo '<div id="etablissement-edit-nom" class="row-inner edit">' . $this->formRow($this->form->get('nom')) . '</div>';
echo '<div id="etablissement-edit-alias" class="row-inner edit">' . $this->formRow($this->form->get('alias')) . '</div>';
echo '<div id="etablissement-edit-aliasCG" class="row-inner edit">' . $this->formRow($this->form->get('aliasCG')) . '</div>';
echo '<div id="etablissement-edit-adresse1" class="row-inner edit">' . $this->formRow($this->form->get('adresse1')) . '</div>';
echo '<div id="etablissement-edit-adresse2" class="row-inner edit">' . $this->formRow($this->form->get('adresse2')) . '</div>';
echo '<div id="etablissement-edit-codePostal" class="row-inner edit">' . $this->formRow($this->form->get('codePostal')) . '</div>';
echo '<div id="etablissement-edit-communeId" class="row-inner edit">' . $this->formRow($this->form->get('communeId')) . '</div>';
echo '<div id="etablissement-edit-telephone" class="row-inner edit">' . $this->formRow($this->form->get('telephone')) . '</div>';
echo '<div id="etablissement-edit-fax" class="row-inner edit">' . $this->formRow($this->form->get('fax')) . '</div>';
echo '<div id="etablissement-edit-email" class="row-inner edit">' . $this->formRow($this->form->get('email')) . '</div>';
echo '<div id="etablissement-edit-directeur" class="row-inner edit">' . $this->formRow($this->form->get('directeur')) . '</div>';
echo '</div><div class="float-left cols-2">';
echo '<div id="etablissement-edit-niveau" class="row-inner edit">' . $this->formRow($this->form->get('niveau')) . '</div>';
echo '<div id="etablissement-edit-statut" class="row-inner edit multicheckbox">' . $this->formRow($this->form->get('statut')) . '</div>';
echo '<div id="etablissement-edit-jOuverture" class="row-inner edit multicheckbox">' . $this->formRow($this->form->get('jOuverture')) . '</div>';
echo '<div class="float-left cols-2">';
echo '<div id="etablissement-edit-hMatin" class="row-inner edit">' . $this->formRow($this->form->get('hMatin')) . '</div>';
echo '<div id="etablissement-edit-hMidi" class="row-inner edit">' . $this->formRow($this->form->get('hMidi')) . '</div>';
echo '</div><div class="float-left cols-2">';
echo '<div id="etablissement-edit-hAMidi" class="row-inner edit">' . $this->formRow($this->form->get('hAMidi')) . '</div>';
echo '<div id="etablissement-edit-hSoir" class="row-inner edit">' . $this->formRow($this->form->get('hSoir')) . '</div>';
echo '</div>';
echo '<div id="etablissement-edit-regrPeda" class="row-inner edit">' . $this->formRow($this->form->get('regrPeda')) . '</div>';
echo '<div id="etablissement-edit-rattacheA" class="row-inner edit">' . $this->formRow($this->form->get('rattacheA')) . '</div>';
echo '<div id="etablissement-edit-longitude" class="row-inner edit">' . $this->formRow($this->form->get('longitude')) . '</div>';
echo '<div id="etablissement-edit-latitude" class="row-inner edit">' . $this->formRow($this->form->get('latitude')) . '</div>';
echo '<div id="etablissement-edit-visible" class="row-inner edit">' . $this->formRow($this->form->get('visible')) . '</div>';
echo '<div id="etablissement-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</div></fieldset>';
echo $this->form()->closeTag();
//var_dump($this->form->get('rattacheA')->debugGetValidator());
?>
</div>