<?php
/**
 * Page de suppression d'un etablissement
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/etablissement-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
?>
<h1>Suppression d'un établissement</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de l'établissement :</p>
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapeHtml($this->data->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->data->commune); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>