<?php
/**
 * Page de localisation d'un établissement scolaire
 *
 * La page présente une carte. Il suffit de cliquer sur la carte pour localiser l'établissement
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource etablissement-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 fév. 2019
 * @version 2019-2.5.0
 */
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->appendFile('/js/maps/localisation.js');
// préparation du script
$i = 0;
$aMarkers = [];
foreach ($this->ptEtablissements as $pt) {
    $e = $pt->getAttribute('etablissement');
    if ($e->desservie) {
        $color = "#00ff00";
        // $nature = "ouverte";
    } else {
        $color = "#ff0000";
        // $nature = "fermée";
    }
    $d = [
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        implode(' ', [
            $e->codePostal,
            $e->commune
        ])
    ];
    $aMarkers[] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'color' => $color,
        'text' => 'S',
        'title' => $e->nom,
        'info' => implode('<br>', $d)
    ];
}
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?= $this->config['centre']['lng'];?>;
const INI_ZOOM = <?= $this->config['zoom'];?>;
initialiser('établissement scolaire', "<?= $this->description;?>", <?= json_encode($aMarkers);?>);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position d'un établissement scolaire sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="float-left">
			<ul style="margin-top: 0;">
			<?php foreach ($this->etablissement as $ligne) :?>
				<li><?= $ligne;?></li>
			<?php endforeach;?>
			</ul>
		</div>
		<div class="float-right left-10px" style="max-width: 700px;">
			Cliquez sur la carte à l'emplacement de l'établissement scolaire puis
			cliquez sur le bouton <b>'Enregistrer la localisation'</b>. Utilisez
			le zoom pour plus de précision.<br>
			<?= $this->form($this->form); ?>
		</div>

	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
