<?php
/**
 * Page de modification d'un etablissement
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/etablissement-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mai 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$this->headScript()->appendFile($this->basePath('/js/'));
$this->themeJS('commun','checkallbox.js');
$this->inlineScript()->captureStart();
?>
multicheckbox_actions.init("etablissement-edit-jOuverture");
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un établissement</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('etablissementId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
		<fieldset class="sbm-page1 clearfix">
			<div class="float-left cols-1">
				<div id="wrapper-etablissementId" class="row-inner edit">
					<?= $this->formRow($this->form->get('codeEtablissement')); ?></div>
				<div id="wrapper-nom" class="row-inner edit">
					<?= $this->formRow($this->form->get('nom')); ?></div>
				<div id="wrapper-alias" class="row-inner edit">
					<?= $this->formRow($this->form->get('alias')); ?></div>
				<div id="wrapper-adresse1" class="row-inner edit">
					<?= $this->formRow($this->form->get('adresse1')); ?></div>
				<div id="wrapper-adresse2" class="row-inner edit">
					<?= $this->formRow($this->form->get('adresse2')); ?></div>
				<div id="wrapper-codePostal" class="row-inner edit">
					<?= $this->formRow($this->form->get('codePostal')); ?></div>
				<div id="wrapper-communeId" class="row-inner edit">
					<?= $this->formRow($this->form->get('communeId')); ?></div>
				<div id="wrapper-telephone" class="row-inner edit">
					<?= $this->formRow($this->form->get('telephone')); ?></div>
				<div id="wrapper-fax" class="row-inner edit">
					<?= $this->formRow($this->form->get('fax')); ?></div>
				<div id="wrapper-email" class="row-inner edit">
					<?= $this->formRow($this->form->get('email')); ?></div>
				<div id="wrapper-directeur" class="row-inner edit">
					<?= $this->formRow($this->form->get('directeur')); ?></div>
				<div id="wrapper-regrPeda" class="row-inner edit">
					<?= $this->formRow($this->form->get('regrPeda')); ?></div>
				<div id="wrapper-rattacheA" class="row-inner edit">
					<?= $this->formRow($this->form->get('rattacheA')); ?></div>
				<div id="wrapper-x" class="row-inner edit">
					<?= $this->formRow($this->form->get('x')); ?></div>
				<div id="wrapper-y" class="row-inner edit">
					<?= $this->formRow($this->form->get('y')); ?></div>
				<div id="wrapper-desservie" class="row-inner edit">
					<?= $this->formRow($this->form->get('desservie')); ?></div>
				<div id="wrapper-visible" class="row-inner edit">
					<?= $this->formRow($this->form->get('visible')); ?></div>
			</div>
			<div class="float-left cols-2">
				<div id="wrapper-niveau" class="row-inner edit">
					<?= $this->formRow($this->form->get('niveau')); ?></div>
				<div id="wrapper-statut"
					class="row-inner edit multicheckbox">
					<?= $this->formRow($this->form->get('statut')); ?></div>
				<div id="wrapper-jOuverture"
					class="row-inner edit multicheckbox">
					<?= $this->formRow($this->form->get('jOuverture')); ?></div>
				<div class="clearfix">
					<div id="horaires-matin" class="row-inner edit float-left cols-3">
						<fieldset class="">
							<legend>Horaires du matin</legend>
							<div id="wrapper-hMatin" class="row-inner edit">
								<?= $this->formRow($this->form->get('hMatin')); ?></div>
							<div id="wrapper-hMidi" class="row-inner edit">
								<?= $this->formRow($this->form->get('hMidi')); ?></div>
						</fieldset>
					</div>
					<div id="horaires-soir" class="row-inner edit float-left cols-3">
						<fieldset class="">
							<legend>Horaires de l'après-midi</legend>
							<div id="wrapper-hAMidi" class="row-inner edit">
								<?= $this->formRow($this->form->get('hAMidi')); ?></div>
							<div id="wrapper-hSoir" class="row-inner edit">
								<?= $this->formRow($this->form->get('hSoir')); ?></div>
						</fieldset>
					</div>
				</div>
				<div class="clearfix">
					<div id="ouverture-garderie"
						class="row-inner edit float-left cols-3">
						<fieldset class="rows-2">
							<legend>Ouverture de la garderie</legend>
							<div id="wrapper-hGarderieOMatin"
								class="row-inner edit float-left">
								<?= $this->formRow($this->form->get('hGarderieOMatin')); ?></div>
						</fieldset>
					</div>
					<div id="fermeture-garderie"
						class="row-inner edit float-left cols-3">
						<fieldset>
							<legend>Fermeture de la garderie</legend>
							<div id="wrapper-hGarderieFSoir"
								class="row-inner edit float-left">
								<?= $this->formRow($this->form->get('hGarderieFSoir')); ?></div>
							<div id="wrapper-hGarderieFMidi"
								class="row-inner edit float-left">
								<?= $this->formRow($this->form->get('hGarderieFMidi')); ?></div>
						</fieldset>
					</div>
					<div id="wrapper-buttons" class="row-inner edit">
    					<?= $this->formSubmit($this->form->get('submit'));?>
    					<?= $this->formSubmit($this->form->get('cancel'));?>
    					</div>
				</div>
			</div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div><?php // fiche-inner ?>
	<div id="fiche-footer"></div>
</div><?php //fiche-wrapper ?>