<?php
/**
 * Liste des etablissements
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource etablissement-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 mai 2014
 * @version 2014-1
 */
use SbmCommun\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$etablissements = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-ajout',
    'page' => $this->page
));
$url_pdf = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-pdf',
    'page' => $this->page
));
$url_carte = $this->url('sbmcarte', array(
    'action' => 'etablissements'
));
$url_edit = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-edit',
    'page' => $this->page
));
$url_delete = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-suppr',
    'page' => $this->page
));
$url_relation = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-service',
    'page' => $this->page
));
$url_group = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-group',
    'page' => $this->page
));
$url_localiser = $this->url('sbmgestion/transport', array(
    'action' => 'etablissement-localisation',
    'page' => $this->page
));
$url_retour = $this->url('sbmgestion/transport');
$hiddens = array(
    'back' => $this->url('sbmgestion/transport', array(
        'action' => 'etablissement-liste',
        'page' => $this->page
    ))
);
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-report',
        'formaction' => $url_pdf,
        'title' => 'Rapports à imprimer'
    ),
    'carte' => array(
        'class' => 'fam-map-magnify',
        'formaction' => $url_carte,
        'title' => 'Carte des établissements'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouvel établissement scolaire'
    )
);
?>
<h1>Liste des établissements</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="etablissements">
			<tbody>
				<tr>
					<th>Code</th>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Email</th>
					<th>Inscrits</th>
					<th>Desservis</th>
					<th>Visible</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
        <?php foreach($etablissements as $test => $etablissement): ?>
        <?php
            $nbInscrits = StdLib::getParam($etablissement->etablissementId, $this->t_nb_inscrits, 0);
            // selection
            $modele = <<<EOT
$("#chk%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectionetablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
$("#vis%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'visibleetablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
$("#des%s").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'desservietablissement/etablissementId:%s',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });        
EOT;
            
            $jsTrigger .= sprintf("$('#chk%s').trigger('change');\n", $etablissement->etablissementId);
            $jsTrigger .= sprintf("$('#vis%s').trigger('change');\n", $etablissement->etablissementId);
            $jsTrigger .= sprintf("$('#des%s').trigger('change');\n", $etablissement->etablissementId);
            $jsCallback .= str_replace('%s', $etablissement->etablissementId, "$modele\n"); // , $etablissement->etablissementId, $etablissement->etablissementId, $etablissement->etablissementId, $etablissement->etablissementId, $etablissement->etablissementId);
            ?>
            <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="etablissementid"><?php echo $this->escapeHtml($etablissement->etablissementId); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($etablissement->nom); ?></td>
					<td class="commune"><?php echo $this->escapeHtml($etablissement->commune); ?></td>
					<td class="codepostal"><?php echo $this->escapeHtml($etablissement->codePostal); ?></td>
					<td class="telephone"><?php echo $this->escapeHtml($etablissement->telephone); ?></td>
					<td class="email"><?php echo $this->escapeHtml($etablissement->email); ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre desservi"><?php echo renderCheckbox($this, 'desservie', 'des' . $etablissement->etablissementId, $etablissement->desservie)?></td>
					<td class="centre visible"><?php echo renderCheckbox($this, 'visible', 'vis' . $etablissement->etablissementId, $etablissement->visible)?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $etablissement->etablissementId, $etablissement->selection)?></td>
					<td class="boutons">
            <?php
            $hiddens = array(
                'etablissementId' => $etablissement->etablissementId
            );
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'localiser' => array(
                    'class' => 'fam-map-magnify',
                    'formaction' => $url_localiser,
                    'title' => 'position sur la carte'
            ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'services' => array(
                    'class' => 'fam-table-relationship',
                    'formaction' => $url_relation,
                    'title' => 'circuits desservant cet établissement'
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves inscrits dans cet établissement scolaire'
                )
            );
            echo $this->listeLigneActions($etablissement->etablissementId, $hiddens, $buttons);
            ?>
				</td>
				</tr>         
        <?php endforeach;?>
        </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>	
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();