<?php
/**
 * Page de localisation d'un établissement scolaire
 *
 * La page présente une carte. Il suffit de cliquer sur la carte pour localiser l'établissement
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource etablissement-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 mars 2020
 * @version 2020-2.6.0
 */
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'localisation.js');
$this->themeJS('commun', 'StyledMarker.js');
// préparation du script
$i = 0;
$aMarkers = [];
foreach ($this->ptEtablissements as $pt) {
    $e = $pt->getAttribute('etablissement');
    $niveau = array_sum($e->niveau);
    $accord_desservi = "";
    if ($niveau < 4) {
        // $color = "#ffff00";
        $lettre = "E";
        $nature = "École";
        $accord_desservi = "e";
    } elseif ($niveau == 4) {
        // $color = "#fc6700";
        $lettre = "C";
        $nature = "Collège";
    } else {
        // $color = "#e5c3d0";
        $lettre = "L";
        $nature = "Lycée";
    }
    if ($e->desservie) {
        $color = "#00ff00";
        $nature .= " desservi" . $accord_desservi;
    } else {
        $color = "#ff0000";
        $nature .= " non desservi" . $accord_desservi;
    }
    $d = [
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        implode(" - ", array_filter([
            $e->adresse1,
            $e->adresse2
        ])),
        implode(' ', [
            $e->codePostal,
            $e->lacommune
        ]),
        'Tél. ' . $this->telephone($e->telephone)
    ];
    $tmp = $e->email;
    if ($e->email) {
        $d[] = 'Email : ' . $e->email;
    }
    $d[] = $nature;
    $aMarkers[] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'color' => $color,
        'text' => $lettre,
        'title' => $e->nom,
        'info' => implode('<br>', $d)
    ];
}
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?= $this->config['centre']['lng'];?>;
const INI_ZOOM = <?= $this->config['zoom'];?>;
initialiser("<?=$this->scheme;?>",'établissement scolaire',"<?= $this->description;?>",<?= json_encode($aMarkers);?>);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position d'un établissement scolaire sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="float-left">
			<ul style="margin-top: 0;">
			<?php foreach ($this->etablissement as $ligne) :?>
				<li><?= $ligne;?></li>
			<?php endforeach;?>
			</ul>
		</div>
		<div class="float-right left-10px" style="max-width: 700px;">
			<?= $this->form($this->form); ?>
			<p class="sbm-description">Cliquez sur la carte à l'emplacement de l'établissement scolaire puis
			cliquez sur le bouton <b>'Enregistrer la localisation'</b>.<br>Utilisez
			le zoom pour plus de précision.</p>
		</div>

	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
