<?php
/**
 * Vue de l'action index du controller TransportController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/transport/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 31 déc. 2019
 * @version 2019-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_transport_circuits = $this->url('sbmgestion/transport',
    [
        'action' => 'circuit-liste',
        'page' => $this->page
    ]);
$url_transport_classes = $this->url('sbmgestion/transport',
    [
        'action' => 'classe-liste',
        'page' => $this->page
    ]);
$url_transport_communes = $this->url('sbmgestion/transport',
    [
        'action' => 'commune-liste',
        'page' => $this->page
    ]);
$url_transport_etablissements = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-liste',
        'page' => $this->page
    ]);
$url_transport_lots = $this->url('sbmgestion/transport',
    [
        'action' => 'lot-liste',
        'page' => $this->page
    ]);
$url_transport_services = $this->url('sbmgestion/transport',
    [
        'action' => 'service-liste',
        'page' => $this->page
    ]);
$url_transport_stations = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$url_transport_transporteurs = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-liste',
        'page' => $this->page
    ]);
$url_gestion = $this->url('sbmgestion');
$url_users = $this->url('sbmadmin', [
    'action' => 'user-liste'
]);
$url_secteurs_scolaires_liste = $this->url('sbmadmin',
    [
        'action' => 'secteur-scolaire-liste'
    ]);
$url_simulation_etablissement_liste = $this->url('sbmadmin',
    [
        'action' => 'simulation-etablissement-liste'
    ]);
$url_rpi_liste = $this->url('sbmadmin', [
    'action' => 'rpi-liste'
]);
$url_transport_zonage = $this->url('sbmgestion/transport', [
    'action' => 'zonage-liste'
]);
$action = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_gestion,
        'title' => 'Retour'
    ]
];
?>
<h1>Gestion du réseau de transport</h1>
<div id="menugeneral-wrapper">
	<div id="menugeneral-header" class="clearfix">
		<div class="menu float-left">
		<?=$this->listeZoneActions([], $action);?>
        </div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
        </div>
	</div>
	<div id="menugeneral-inner">
		<ul>
			<li><a href="<?=$url_transport_circuits;?>"><i class="fam-bullet-go"></i>Circuits</a></li>
			<li><a href="<?=$url_transport_classes;?>"><i class="fam-bullet-go"></i>Classes</a></li>
			<li><a href="<?=$url_transport_communes;?>"><i class="fam-bullet-go"></i>Communes</a></li>
			<li><a href="<?=$url_transport_etablissements;?>"><i
					class="fam-bullet-go"></i>Etablissements</a></li>
			<li><a href="<?= $url_simulation_etablissement_liste; ?>"><i
					class="fam-bullet-go"></i>Règles de correspondance pour le passage
					dans un établissement de niveau supérieur</a></li>
			<li><a href="<?=$url_transport_lots;?>"><i class="fam-bullet-go"></i>Lots
					de marché</a></li>
			<li><a href="<?= $url_rpi_liste; ?>"><i class="fam-bullet-go"></i>RPI</a></li>
			<li><a href="<?= $url_secteurs_scolaires_liste; ?>"><i
					class="fam-bullet-go"></i>Secteurs scolaires des
					collèges publics</a></li>
			<li><a href="<?=$url_transport_services;?>"><i class="fam-bullet-go"></i>Services</a></li>
			<li><a href="<?=$url_transport_stations;?>"><i class="fam-bullet-go"></i>Stations</a></li>
			<li><a href="<?=$url_transport_transporteurs;?>"><i
					class="fam-bullet-go"></i>Transporteurs</a></li>
			<li><a href="<?= $url_users; ?>"><i class="fam-bullet-go"></i>Comptes
					des utilisateurs</a></li>
		</ul>
	</div>
</div>