<?php
/**
 * Vue de l'action index du controller TransportController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/transport/index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 avr. 2014
 * @version 2014-1
 */

$url_transport_circuits = $this->url('sbmgestion/transport', array('action' => 'circuit-liste', 'page' => $this->page));
$url_transport_classes = $this->url('sbmgestion/transport', array('action' => 'classe-liste', 'page' => $this->page));
$url_transport_communes = $this->url('sbmgestion/transport', array('action' => 'commune-liste', 'page' => $this->page));
$url_transport_etablissements = $this->url('sbmgestion/transport', array('action' => 'etablissement-liste', 'page' => $this->page));
$url_transport_services = $this->url('sbmgestion/transport', array('action' => 'service-liste', 'page' => $this->page));
$url_transport_stations = $this->url('sbmgestion/transport', array('action' => 'station-liste', 'page' => $this->page));
$url_transport_transporteurs = $this->url('sbmgestion/transport', array('action' => 'transporteur-liste', 'page' => $this->page));
$url_gestion = $this->url('sbmgestion');
?>
<h1>Gestion du réseau de transport</h1>
<ul>
<li><a href="<?php echo $url_transport_circuits; ?>">Circuits</a></li>
<li><a href="<?php echo $url_transport_classes; ?>">Classes</a></li>
<li><a href="<?php echo $url_transport_communes; ?>">Communes</a></li>
<li><a href="<?php echo $url_transport_etablissements; ?>">Etablissements</a></li>
<li><a href="<?php echo $url_transport_services; ?>">Services</a></li>
<li><a href="<?php echo $url_transport_stations; ?>">Stations</a></li>
<li><a href="<?php echo $url_transport_transporteurs; ?>">Transporteurs</a></li>
<li><a href="<?php echo $url_gestion; ?>">Retour au menu général</a></li>
</ul>