<?php
/**
 * Page de modification d'un lot de marché
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource lot-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 29 avr. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/transport', 'lot-fiche.css');
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'lot-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un nouveau lot de marché</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?=$this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?=$this->form()->openTag($this->form);?>
        <?=$this->formHidden($this->form->get('lotId'));?>
        <?=$this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="wrapper-marche" class="marche">
			<?=$this->formRow($this->form->get('marche'));?></div>
			<div id="wrapper-lot" class="lot">
			<?=$this->formRow($this->form->get('lot'));?></div>
			<div id="wrapper-libelle" class="libelle">
			<?=$this->formRow($this->form->get('libelle'));?></div>
			<div id="wrapper-complement" class="complement">
			<?=$this->formRow($this->form->get('complement'));?></div>
			<div id="wrapper-transporteurId" class="transporteurId">
			<?=$this->formRow($this->form->get('transporteurId'));?></div>
			<div id="wrapper-dateDebut" class="dateDebut">
			<?=$this->formRow($this->form->get('dateDebut'));?></div>
			<div id="wrapper-dateFin" class="dateFin">
			<?=$this->formRow($this->form->get('dateFin'));?></div>
			<div id="wrapper-actif" class="actif">
			<?=$this->formRow($this->form->get('actif'));?></div>
			<div id="wrapper-commentaire" class="commentaire">
			<?=$this->formRow($this->form->get('commentaire'));?></div>
			<div id="wrapper-buttons" class="boutons">
        		<?=$this->formSubmit($this->form->get('submit'));?>
                <?=$this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?=$this->form()->closeTag();?>
    </div>
	<div id="fiche-footer"></div>
</div>
