<?php
/**
 * Page de modification d'un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 janv. 2019
 * @version 2019-2.4.6
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => 'service-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un service</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
    <?php
    echo $this->form()->openTag($this->form);
    echo $this->formHidden($this->form->get('serviceId'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>
        <fieldset class="sbm-page1">
            <div id="service-edit-serviceId" class="row-inner edit">
                <?= $this->formRow($this->form->get('codeService')); ?></div>
            <div id="service-edit-nom" class="row-inner edit">
                <?= $this->formRow($this->form->get('nom')); ?></div>
            <div id="service-edit-aliasCG" class="row-inner edit">
                <?= $this->formRow($this->form->get('aliasCG')); ?></div>
            <div id="service-edit-transporteurId" class="row-inner edit">
                <?= $this->formRow($this->form->get('transporteurId')); ?></div>
            <div id="service-edit-operateur" class="row-inner edit">
                <?= $this->formRow($this->form->get('operateur')); ?></div>
            <div id="service-edit-nbPlaces" class="row-inner edit">
                <?= $this->formRow($this->form->get('nbPlaces')); ?></div>
            <div id="service-edit-kmAVide" class="row-inner edit">
                <?= $this->formRow($this->form->get('kmAVide')); ?></div>
            <div id="service-edit-kmEnCharge" class="row-inner edit">
                <?= $this->formRow($this->form->get('kmEnCharge')); ?></div>
            <div id="sercice-edit-natureCarte" class="row-inner edit">
                <?= $this->formRow($this->form->get('natureCarte')); ?></div>
            <div id="service-edit-surEtatCG" class="row-inner edit">
                <?= $this->formRow($this->form->get('surEtatCG')); ?></div>
            <div id="service-edit-buttons" class="row-inner edit">
                <?= $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?>
            </div>
		</fieldset>
<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>