<?php
/**
 * Page de modification d'un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/transport', 'service-fiche.css');
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'service-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un service</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="edit">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('millesime'));?>
		<?= $this->formHidden($this->form->get('ligneId'));?>
		<?= $this->formHidden($this->form->get('sens'));?>
		<?= $this->formHidden($this->form->get('moment'));?>
		<?= $this->formHidden($this->form->get('ordre'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div class="clearfix">
				<div id="wrapper-ligneId" class="row-inner p25 float-left">
				<?= $this->formRow($this->form->get('newligneId')); ?></div>
				<div id="wrapper-sens" class="row-inner p20 float-left">
				<?= $this->formRow($this->form->get('newsens')); ?></div>
				<div id="wrapper-moment" class="row-inner p30 float-left">
				<?= $this->formRow($this->form->get('newmoment')); ?></div>
				<div id="wrapper-ordre" class="row-inner float-left">
				<?= $this->formRow($this->form->get('newordre')); ?></div>

			</div>
			<div id="wrapper-alias" class="row-inner">
				<?= $this->formRow($this->form->get('alias')); ?></div>
			<div id="wrapper-transporteurId" class="row-inner">
				<?= $this->formRow($this->form->get('transporteurId')); ?></div>

			<div class="clearfix">
				<div id="wrapper-rang" class="row-inner p25 float-left">
					<?= $this->formRow($this->form->get('rang')); ?></div>
				<div id="wrapper-nbPlaces" class="row-inner p20 float-left">
					<?= $this->formRow($this->form->get('nbPlaces')); ?></div>
				<div id="wrapper-semaine" class="row-inner horaire">
					<?= $this->formRow($this->form->get('semaine')); ?></div>
			</div>
			<div class="clearfix">
				<div id="wrapper-actif" class="row-inner p25 float-left">
				<?= $this->formRow($this->form->get('actif')); ?></div>
				<div id="wrapper-visible"
					class="row-inner demi float-left">
				<?= $this->formRow($this->form->get('visible')); ?></div>
			</div>
			<div id="wrapper-commentaire" class="row-inner">
				<?= $this->formRow($this->form->get('commentaire')); ?></div>
			<div id="wrapper-buttons" class="row-inner">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>