<?php
/**
 * Page de suppression d'un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/service-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 juil. 2020
 * @version 2020-2.6.0
 */
?>
<h1>Suppression d'un service</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression du service :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->designationService($this->data)); ?>
				(<?=$this->data->jours;?>)</li>
			<?php if ($this->data->alias):?>
			<li><?= $this->escapeHtml($this->data->alias); ?></li>
			<?php endif;?>
			<li><?= $this->escapeHtml($this->data->transporteur); ?></li>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>