<?php
/**
 * Page de consultation des inscrits sur un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 30 mars 2020
 * @version 2020-2.4.14
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => $this->origine,
        'page' => $this->pageRetour
    ]);
$btn_retour = [
    'class' => 'fam-door-out',
    'formaction' => $url_retour,
    'title' => 'Retour'
];
$url_edit = $this->url('sbmgestion/eleve', 
    [
        'action' => 'eleve-edit',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_mail = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-mail'
]);
$url_mark_selection = $this->url('sbmgestion/transport', 
    [
        'action' => 'service-group-selection',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_add_photo = $this->url('sbmgestion/eleve', 
    [
        'action' => 'envoiphoto',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
if ($this->origine == 'service-liste') {
    $url_group = $this->url('sbmgestion/transport', 
        [
            'action' => 'service-group',
            'page' => $this->page,
            'pr' => $this->pageRetour
        ]);
    $url_rapports = $this->url('sbmgestion/transport', 
        [
            'action' => 'service-group-pdf',
            'page' => $this->page,
            'pr' => $this->pageRetour
        ]);
    $hiddens = [
        'serviceId' => $this->serviceId
    ];
    $menuImpression = $this->menuRapports(
        $this->url('sbmgestion/transport', 
            [
                'action' => 'service-group'
            ]), $url_rapports, 'fam-printer', null, $hiddens);
    $hiddens = $menuImpression['hiddens'];
    $btn_retour['onclick'] = $js_retour;
} elseif ($this->origine == 'transporteur-service') {
    $url_group = $this->url('sbmgestion/transport', 
        [
            'action' => 'service-group',
            'page' => $this->page,
            'id' => $this->pageRetour
        ]);
    $url_rapports = $this->url('sbmgestion/transport', 
        [
            'action' => 'service-group-pdf',
            'page' => $this->page,
            'pr' => $this->pageRetour
        ]);
    $hiddens = [
        'serviceId' => $this->serviceId,
        'transporteurId' => $this->service->transporteurId
    ];
    $menuImpression = $this->menuRapports(
        $this->url('sbmgestion/transport', 
            [
                'action' => 'service-group'
            ]), $url_rapports, 'fam-printer', null, $hiddens);
    $hiddens = $menuImpression['hiddens'];
}

$actions = [
    'retour' => $btn_retour,
    'rapports' => $menuImpression['content'],
    'marquer' => [
        'class' => 'fam-basket-add',
        'formaction' => $url_mark_selection,
        'title' => 'Sélectionner toutes les fiches de cette liste'
    ]
];

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
$oEtablissement = $this->etablissement;
$oService = $this->service;
?>
<h1><?php echo $this->h1;?></h1>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<ul class="float-left">
		<?php if (!empty($oEtablissement)) : ?>
		    <li><?php echo $this->escapeHtml($this->etablissement->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->etablissement->commune); ?></li>
		<?php endif;?>
		<?php if (!empty($oService)) :?>
			<li><?php echo $this->escapeHtml($this->service->serviceId); ?></li>
			<li><?php echo $this->escapeHtml($this->service->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->service->transporteur); ?></li>
		<?php endif;?>
		</ul>
		<div class="flashMessenger float-right">
		<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
		</div>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->paginator->getTotalItemCount(); ?> prises en charge.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
					<th>Circuits</th>
					<th>Stations</th>
					<th></th>
				</tr>
			<?php
foreach ($data as $row) :
    $this->pictogrammes('init')
        ->addPreinscrit($row['paiement'] == 0 && $row['fa'] == 0 && $row['gratuit'] == 0)
        ->addSansPhoto($row['sansphoto']);
    $hiddens = [
        'eleveId' => $row['eleveId'],
        'info' => $row['nom'] . ' ' . $row['prenom'],
        'email' => $row['email'],
        'responsable' => $row['responsable'],
        'group' => $url_group
    ];
    $buttons = [
        'modifier' => [
            'class' => 'fam-pencil',
            'formaction' => $url_edit,
            'title' => 'Modifier'
        ]
    ];
    if ($row['sansphoto']) {
        $buttons['photo'] = [
            'class' => 'fam-camera-add',
            'formaction' => $url_add_photo,
            'title' => 'Envoyer une photo'
        ];
    }
    if (! empty($row['email'])) {
        $buttons['ecrire'] = [
            'class' => 'fam-email',
            'formaction' => $url_mail,
            'title' => 'Envoyer un email'
        ];
    }
    ?>
                <tr
					class="<?php echo $this->cycle(["even","odd"])->next();?>">
					<td><?php echo $this->pictogrammes();?></td>
					<td><?php echo $this->escapeHtml($row['nom']);?></td>
					<td><?php echo $this->escapeHtml($row['prenom']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL1']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL2']);?></td>
					<td><?php echo $this->escapeHtml($row['codePostal']);?></td>
					<td><?php echo $this->escapeHtml($row['commune']);?></td>
					<td><?php echo $this->escapeHtml($row['etablissement']);?></td>
					<td class="centre"><?php echo $this->escapeHtml($row['classe']);?></td>
					<td><?php echo implode('<br>', [$row['service1Id'], $row['service2Id']]);?></td>
					<td><?php echo implode('<br>', [$row['station1'], $row['station2']]);?></td>
					<td><?php echo $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
</div>