<?php
/**
 * Page de consultation des inscrits sur un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 18 mars 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/transport', array(
    'action' => $this->origine,
    'page' => $this->pageRetour
));
$url_pdf = $this->url('sbmgestion/transport', array(
    'action' => 'service-group-pdf',
    'page' => $this->page
));
if ($this->origine == 'service-liste') {
    $hiddens = array();
} else {
    $hiddens = array(
        'etablissementId' => $this->etablissementId,
        'serviceId' => $this->serviceId
    );
}
// ne pas utiliser de guillement dans la chaine $js
// $js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    )
    // 'onclick' => $js_retour
    ,
    'rapports' => array(
        'class' => 'fam-printer',
        'formaction' => $url_pdf,
        'title' => 'Rapports à imprimer'
    )
);

$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
$oEtablissement = $this->etablissement;
$oService = $this->service;
?>
<h1><?php echo $this->h1;?></h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
		<?php if (!empty($oEtablissement)) : ?>
		    <li><?php echo $this->escapeHtml($this->etablissement->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->etablissement->commune); ?></li>
		<?php endif;?>
		<?php if (!empty($oService)) :?>
			<li><?php echo $this->escapeHtml($this->service->serviceId); ?></li>
			<li><?php echo $this->escapeHtml($this->service->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->service->transporteur); ?></li>
		<?php endif;?>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->paginator->getAdapter()->count(); ?> prises en charge.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php
foreach ($data as $row) {
    echo '<tr class="' . $this->cycle(array(
        "even",
        "odd"
    ))->next() . '">';
    foreach ($row as $item) {
        echo '<td>' . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	</div>
</div>