<?php
/**
 * Liste des établissements pour un service donné
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource service-etablissement.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 mars 2020
 * @version 2020-2.6.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-ajout', // voir si on peut faire une seule //
                                                    // action
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'service-etablissement-pdf',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'service-etablissement',
        'page' => $this->pageRetour
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-suppr',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'etablissement-service-group',
        'pr' => $this->page,
        'id' => $this->pageRetour
    ]);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$codeId = sprintf('%d|%s|%d|%d|%d', $this->service->millesime, $this->service->ligneId,
    $this->service->sens, $this->service->moment, $this->service->ordre);
//$codeService = sprintf('%s-%d%d%d', $this->service->ligneId, $this->service->sens,
//    $this->service->moment, $this->service->ordre);
$codeService = $service->designation();
$hiddens = [
    'ligneId' => $this->service->ligneId,
    'sens' => $this->service->sens,
    'moment' => $this->service->moment,
    'ordre' => $this->service->ordre,
    'etablissementId' => null,
    'origine' => 'service-etablissement'
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'service-etablissement'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvel établissement'
    ]
];

?>
<h1>Liste des établissements desservis par
<?=$codeService . '<br>' . $this->service->extremite1 . ' - ' . $this->service->extremite2;?>

</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="liste-inner etablissements-services">
			<tbody>
				<tr>
					<th>Code</th>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Email</th>
					<th>Inscrits</th>
					<th>Station</th>
					<th>Horaire</th>
				</tr>
            <?php

            foreach ($this->data as $etablissement) :
                ?>
            	<?php
                $etablissement->setFlags(ArrayObject::ARRAY_AS_PROPS);
                if ($effectifServicesEtablissements) {
                    $nbInscrits = $this->effectifServicesEtablissements->transportes(
                        $etablissement->etablissementId);
                } else {
                    $nbInscrits = 0;
                }
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($etablissement->serv_nbPlaces < $nbInscrits) {
                    $css .= ' exces';
                }
                $hiddens['etablissementId'] = $etablissement->etablissementId;
                $buttons = [
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves du service %s inscrits dans %s',
                            $codeService, $etablissement->etab_nom)
                    ]
                ];
                $id = $etablissement->etablissementId . '|' . $codeId;

                ?>
                <tr class="petit <?php $css;?>">
					<td class="etablissementid">
						<?=$this->escapeHtml($etablissement->etablissementId);?></td>
					<td class="nom">
						<?=$this->escapeHtml($etablissement->etab_nom);?></td>
					<td class="commune">
						<?=$this->escapeHtml($etablissement->etab_commune);?></td>
					<td class="codepostal">
						<?=$this->escapeHtml($etablissement->etab_codePostal);?></td>
					<td class="telephone">
						<?=$this->telephone($etablissement->etab_telephone);?></td>
					<td class="email">
						<?=$this->escapeHtml($etablissement->etab_email);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="station">
						<?=$this->escapeHtml($etablissement->sta_nom);?></td>
					<td class="horaire centre">
						<?=DateLib::formatHoraire($etablissement->cir_horaireA);?></td>
					<td class="boutons">
            			<?=$this->listeLigneActions($id, $hiddens, $buttons);?>
			        </td>
				</tr>
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>
