<?php
/**
 * Page de consultation des inscrits sur un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/transport', array(
    'action' => 'service-liste',
    'page' => $this->page
));
?>
<h1>Groupe des élèves inscrits sur un service</h1>
<div class="groupe-wrapper">
	<div class="header-wrapper">
		<ul>
			<li><?php echo $this->escapeHtml($this->data->serviceId); ?></li>
			<li><?php echo $this->escapeHtml($this->data->nom); ?></li>
			<li><?php echo $this->escapeHtml($this->data->transporteur); ?></li>
		</ul>
	</div>
	<div class="liste-wrapper">
		<div class="zone-actions">
			<a href="<?php echo $retour; ?>" class="bouton"
				title="retour à la liste des services"><i class="fam-door-out"></i>
				Retour</a>
		</div>
		<table class="liste-inner">
			<tbody>
			</tbody>
		</table>

		<p>
			<em>A faire</em>
		</p>
	</div>
</div>