<?php
/**
 * Page de modification d'un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 29 avr. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/transport', 'service-fiche.css');
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'service-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un service</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner" class="edit">
		<?= $this->form()->openTag($this->form);?>
		<?= $this->formHidden($this->form->get('serviceId'));?>
		<?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div class="clearfix">
				<div id="wrapper-serviceId" class="row-inner tiers float-left">
				<?= $this->formRow($this->form->get('codeService')); ?></div>
				<div id="wrapper-alias" class="row-inner tiers float-left">
				<?= $this->formRow($this->form->get('alias')); ?></div>
				<div id="wrapper-aliasTr" class="row-inner tiers-droite float-left">
				<?= $this->formRow($this->form->get('aliasTr')); ?></div>
			</div>
			<div id="wrapper-lotId" class="row-inner">
				<?= $this->formRow($this->form->get('lotId')); ?></div>
			<div id="wrapper-nom" class="row-inner">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="wrapper-aliasCG" class="row-inner">
				<?= $this->formRow($this->form->get('aliasCG')); ?></div>
			<div id="wrapper-transporteurId" class="row-inner">
				<?= $this->formRow($this->form->get('transporteurId')); ?></div>
			<div id="wrapper-operateur" class="row-inner">
				<?= $this->formRow($this->form->get('operateur')); ?></div>
			<div class="clearfix">
				<div id="wrapper-nbPlaces" class="row-inner tiers float-left">
				<?= $this->formRow($this->form->get('nbPlaces')); ?></div>
				<div id="wrapper-kmAVide" class="row-inner tiers float-left">
				<?= $this->formRow($this->form->get('kmAVide')); ?></div>
				<div id="wrapper-kmEnCharge"
					class="row-inner tiers-droite float-left">
				<?= $this->formRow($this->form->get('kmEnCharge')); ?></div>
			</div>
			<div class="clearfix">
				<div id="wrapper-horaire1"
					class="row-inner horaire tiers float-left">
				<?= $this->formRow($this->form->get('horaire1')); ?></div>
				<div id="wrapper-horaire2"
					class="row-inner horaire tiers float-left">
				<?= $this->formRow($this->form->get('horaire2')); ?></div>
				<div id="wrapper-horaire3"
					class="row-inner horaire tiers-droite float-left">
				<?= $this->formRow($this->form->get('horaire3')); ?></div>
			</div>
			<div id="wrapper-natureCarte" class="row-inner tiers">
                <?= $this->formRow($this->form->get('natureCarte')); ?></div>
			<div id="wrapper-surEtatCG" class="row-inner">
				<?= $this->formRow($this->form->get('surEtatCG')); ?></div>
			<div id="wrapper-buttons" class="row-inner">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>