<?php
/**
 * Page de création d'un service
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/service-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'service-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'un nouveau service</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="service-ajout-serviceId" class="row-inner ajout">
			<?= $this->formRow($this->form->get('serviceId')); ?></div>
			<div id="service-ajout-nom" class="row-inner ajout">
			<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="service-ajout-aliasCG" class="row-inner ajout">
			<?= $this->formRow($this->form->get('aliasCG')); ?></div>
			<div id="service-ajout-transporteurId" class="row-inner ajout">
			<?= $this->formRow($this->form->get('transporteurId')); ?></div>
			<div id="service-ajout-operateur" class="row-inner ajout">
			<?= $this->formRow($this->form->get('operateur')); ?></div>
			<div id="service-ajout-nbPlaces" class="row-inner ajout">
			<?= $this->formRow($this->form->get('nbPlaces')); ?></div>
			<div id="service-ajout-kmAVide" class="row-inner ajout">
			<?= $this->formRow($this->form->get('kmAVide')); ?></div>
			<div id="service-ajout-kmEnCharge" class="row-inner ajout">
			<?= $this->formRow($this->form->get('kmEnCharge')); ?></div>
			<div id="service-ajout-surEtatCG" class="row-inner ajout">
			<?= $this->formRow($this->form->get('surEtatCG')); ?></div>
			<div id="service-ajout-buttons" class="row-inner ajout">
        		<?= $this->formSubmit($this->form->get('submit'));?>
                <?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>