<?php
/**
 * Page de création d'une station
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'une nouvelle station</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('stationId'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
			<div id="station-ajout-communeId" class="row-inner ajout"><?php echo $this->formRow($this->form->get('communeId')); ?></div>
			<div id="station-ajout-nom" class="row-inner ajout"><?php echo $this->formRow($this->form->get('nom')); ?></div>
			<div id="station-ajout-aliasCG" class="row-inner ajout"><?php echo $this->formRow($this->form->get('aliasCG')); ?></div>
			<div id="station-ajout-codeCG" class="row-inner ajout"><?php echo $this->formRow($this->form->get('codeCG')); ?></div>
			<div id="station-ajout-longitude" class="row-inner ajout"><?php echo $this->formRow($this->form->get('x')); ?></div>
			<div id="station-ajout-latitude" class="row-inner ajout"><?php echo $this->formRow($this->form->get('y')); ?></div>
			<div id="station-ajout-visible" class="row-inner ajout"><?php echo $this->formRow($this->form->get('visible')); ?></div>
			<div id="station-ajout-ouverte" class="row-inner ajout"><?php echo $this->formRow($this->form->get('ouverte')); ?></div>
			<div id="station-ajout-buttons" class="row-inner ajout">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>