<?php
/**
 * Liste des stations
 *
 * Cette vue reçoit une variable $t_nb_inscrits qui est un tableau associatif 
 * structuré comme indiqué dans l'exemple ci-dessous :
 * [
 *     code_station => [
 *         'r1' => effectif des élèves transportés en demandeR1,
 *         'r2' => effectif des élèves transportés en demandeR2,
 *         'total' => effectif des élèves transportés (r1 ou r2)
 *     ],
 *     ...
 * ]
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 fév. 2019
 * @version 2019-2.4.7
 */
use SbmBase\Model\StdLib;
use SbmCartographie\Model\Point;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectionstation/stationId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$stations = $this->paginator->getCurrentItems();
$url_origine = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$url_ajouter = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-ajout',
        'page' => $this->page
    ]);
$url_carte = $this->url('sbmcarte', [
    'action' => 'stations'
]);
$url_rapports = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-pdf',
        'page' => $this->page
    ]);
$url_nondesservies = $this->url('sbmgestion/transport', 
    [
        'action' => 'stations-non-desservies',
        'page' => $this->page
    ]);
$url_localiser = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-localisation',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-suppr',
        'page' => $this->page
    ]);
$url_relation = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-service',
        'id' => $this->page
    ]);
$url_group = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-group',
        'page' => $this->page
    ]);
$url_suppr_doublon = $this->url('sbmgestion/transport', 
    [
        'action' => 'station-doublon',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$hiddens = [
    'back' => $url_origine
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'station-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'nondesservies' => [
        'class' => 'fam-link-break',
        'formaction' => $url_nondesservies,
        'title' => 'Non desservies'
    ],
    'doublons' => [
        'class' => 'fam-text-replace',
        'formaction' => $url_suppr_doublon,
        'title' => 'Supprimer un doublon'
    ],
    'carte' => [
        'class' => 'fam-map-magnify',
        'formaction' => $url_carte,
        'title' => 'Carte des points d\'arrêt'
    ],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouvelle station'
    ]
];
?>
<h1>Liste des stations</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="stations">
			<tbody>
				<tr>
					<th></th>
					<th>Commune</th>
					<th>Nom</th>
					<th>Visible</th>
					<th>Ouverte</th>
					<th>Inscrits</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($stations as $test => $station): ?>
            <?php
                $pt = new Point($station->x, $station->y);
                $ptOk = $this->projection->isValid($pt, 'station'); // stations et etablissements ont la même config
                $nbInscrits = StdLib::getParamR(
                    [
                        $station->stationId,
                        'total'
                    ], $this->t_nb_inscrits, 0);
                $exces = ! $station->ouverte && ($nbInscrits > 0);
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", 
                    $station->stationId);
                $jsCallback .= sprintf("$modele\n", $station->stationId, 
                    $station->stationId);
                ?>
                <tr
					class="<?php echo $this->cycle(["even", "odd"])->next(); if ($exces) echo ' exces';?>">
					<td>
					<?php if (!$ptOk) : ?>
					   <i class="fam-error"></i>
					<?php endif;?>
					</td>
					<td class="commune"><?php echo $this->escapeHtml($station->commune); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($station->nom); ?></td>
					<td class="visible"><?php echo $station->visible ? 'Oui' : 'Non'; ?></td>
					<td class="ouverte"><?php echo $station->ouverte ? 'Oui' : 'Non'; ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $station->stationId, $station->selection)?></td>
					<td class="boutons">
            <?php
                $hiddens = [
                    'stationId' => $station->stationId,
                    'origine' => $url_origine
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'localiser' => [
                        'class' => $ptOk ? 'fam-map-magnify' : 'fam-map-add',
                        'formaction' => $url_localiser,
                        'title' => $ptOk ? 'position sur la carte' : 'position manquante'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'services' => [
                        'class' => 'fam-table-relationship',
                        'formaction' => $url_relation,
                        'title' => sprintf('circuits desservant la station %s - %s', 
                            $station->nom, $station->commune)
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de la station %s - %s', $station->nom, 
                            $station->commune)
                    ]
                ];
                echo $this->listeLigneActions($station->stationId, $hiddens, $buttons);
                ?>
			        </td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
         <?php echo $this->form()->openTag($this->criteres_form);?>
         <?php echo $this->formCollection($this->criteres_form, true);?>
         <?php echo $this->form()->closeTag();?>
         </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();