<?php
/**
 * Liste des services pour une station donnée
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource transporteur-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 juil. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'station-service-pdf',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'station-service-group',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$hiddens = [
    'stationId' => $this->stationId
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'station-service'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content']
];
?>
<h1>Liste des services desservant une station</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li>Commune : <?=$this->escapeHtml($this->station->commune);?></li>
			<li>Arrêt : <?=$this->escapeHtml($this->station->nom);?></li>
		</ul>
	</div>
	<div id="liste-header" class="clearfix">
		<div class="menu clearfix"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?=$this->data->count();?> services.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr class="petit">
					<th>Service</th>
					<th>Jours</th>
					<th>Description</th>
					<th>Transporteur</th>
					<th>Opérateur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th></th>
				</tr>
            <?php

            foreach ($this->data as $service) :
                ?>
            <?php
                $serviceId = sprintf('%d|%s|%d|%d|%d', $service->millesime,
                    $service->ligneId, $service->sens, $service->moment, $service->ordre);
                $designation = $service->designationService();
                $nbInscrits = $this->effectifStationsServices->transportes(
                    $service->ligneId, $service->sens, $service->moment, $service->ordre);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($service->serviceNbPlaces < $nbInscrits) {
                    $css .= ' exces';
                }
                $hiddens = [
                    'stationId' => $this->stationId,
                    'ligneId' => $service->ligneId,
                    'sens' => $service->sens,
                    'moment' => $service->moment,
                    'ordre' => $service->ordre,
                    'origine' => 'station-service'
                ];
                $buttons = [
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves du service %s montant à %s',
                            $designation, $this->station->nom)
                    ]
                ];
                $id = $this->stationId . '|' . $serviceId?>
                <tr class="petit <?=$css;?>">
					<td class="designation">
						<?=$this->escapeHtml($designation);?></td>
					<td class="semaine">
						<?=$service->jours;?></td>
					<td class="description">
					    <?= $service->ligneExtremite1 . ' - ' .$service->ligneExtremite2;?></td>
					<td class="transporteur">
						<?=$this->escapeHtml($service->transporteur);?></td>
					<td class="operateur">
						<?=$this->escapeHtml($service->operateur);?></td>
					<td class="nbplaces">
						<?=$service->serviceNbPlaces;?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="boutons">
						<?=$this->listeLigneActions($id, $hiddens, $buttons);?>
					</td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?=$this->data->count();?> services.</em>
		</p>
	</div>
</div>
