<?php
/**
 * Page de modification d'une station
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 avr. 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'une station</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('stationId'));?>
        <?= $this->formHidden($this->form->get('origine'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="wrapper-communeId" class="row-inner edit">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="wrapper-nom" class="row-inner edit">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="wrapper-aliasCG" class="row-inner edit">
				<?= $this->formRow($this->form->get('aliasCG')); ?></div>
			<div id="wrapper-codeCG" class="row-inner edit">
				<?= $this->formRow($this->form->get('codeCG')); ?></div>
			<div id="wrapper-longitude" class="row-inner edit">
				<?= $this->formRow($this->form->get('x')); ?></div>
			<div id="wrapper-latitude" class="row-inner edit">
				<?= $this->formRow($this->form->get('y')); ?></div>
			<div id="wrapper-visible" class="row-inner edit">
				<?= $this->formRow($this->form->get('visible')); ?></div>
			<div id="wrapper-ouverte" class="row-inner edit">
				<?= $this->formRow($this->form->get('ouverte')); ?></div>
			<div id="wrapper-equipement" class="row-inner edit">
				<?= $this->formRow($this->form->get('equipement')); ?></div>
			<div id="wrapper-buttons" class="row-inner edit">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>