<?php
/**
 * Liste des stations non desservies
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/stations-non-desservies.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 27 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_origine = $this->url('sbmgestion/transport',
    [
        'action' => 'stations-non-desservies',
        'page' => $this->page,
        'id'=>$this->id
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'stations-non-desservies-pdf'
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->id
    ]);
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'stations-non-desservies'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content']
];
$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$stations = $this->paginator->getCurrentItems();
?>
<h1>Liste des stations non desservies</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?=$this->flashMessenger()->render('success');?>
			<?=$this->flashMessenger()->render('warning');?>
			<?=$this->flashMessenger()->render('error');?>
			<?=$this->flashMessenger()->render('info');?>
			<?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="stations">
			<tbody>
				<tr>
					<th>Commune</th>
					<th>Nom</th>
					<th>Visible</th>
					<th>Ouverte</th>
					<th>Inscrits</th>
				</tr>
            <?php

            foreach ($stations as $station) :
                ?>
            	<?php
                $nbInscrits = $this->effectifStations->transportes($station['stationId']);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($nbInscrits > 0) {
                    $css .= ' exces';
                }
                $url_edit = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-edit',
                        'page' => $this->page,
                        'id' => $this->id
                    ]);
                $url_delete = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-suppr',
                        'page' => $this->page,
                        'id' => $this->id
                    ]);
                $url_group = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-group',
                        'page' => $this->page,
                        'id' => $this->id
                    ]);
                $hiddens = [
                    'stationId' => $station['stationId'],
                    'origine' => $url_origine
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de la station %s - %s', $station['nom'],
                            $station['commune'])
                    ]
                ];
                ?>
                <tr class="<?=$css;?>">
					<td class="commune">
						<?=$this->escapeHtml($station['lacommune']);?></td>
					<td class="nom">
						<?=$this->escapeHtml($station['nom']);?></td>
					<td class="visible">
						<?=$station['visible'] ? 'Oui' : 'Non';?></td>
					<td class="ouverte">
						<?=$station['ouverte'] ? 'Oui' : 'Non';?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="boutons">
                		<?=$this->listeLigneActions($station['stationId'], $hiddens, $buttons);?>
			        </td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
	</div>
</div>