<?php
/**
 * Suppression d'un doublon
 *
 * Permet de remplacer une station par une autre dans toute la base de données, pour
 * toutes les années enregistrées
 * 
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-doublon.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Suppression d'une station en double</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('page'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="station-edit-visible" class="row-inner edit">
        		<?= $this->formRow($this->form->get('stationASupprId')); ?></div>
			<div id="station-edit-ouverte" class="row-inner edit">
        		<?= $this->formRow($this->form->get('stationAGarderId')); ?></div>
			<div id="station-edit-buttons" class="row-inner edit">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
    	<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>
