<?php
/**
 * Page de localisation d'une station
 *
 * La page présente une carte. Il suffit de cliquer sur la carte pour localiser la station
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport
 * @filesource station-localisation.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 mars 2020
 * @version 2020-2.6.0
 */
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'localisation.js');
$this->themeJS('commun', 'StyledMarker.js');
// préparation du script
$aMarkers = [];
foreach ($this->ptStations as $pt) {
    $e = $pt->getAttribute('station');
    if ($e->ouverte) {
        $color = "#00ff00";
        $nature = "ouverte";
    } else {
        $color = "#ff0000";
        $nature = "fermée";
    }
    $d = [
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        $this->escapeHtml($e->alias),
        implode(' ', [
            $e->codePostal,
            $e->commune
        ])
    ];
    $d[] = 'Station ' . $nature;
    $aMarkers[] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'color' => $color,
        'text' => 'S',
        'title' => $e->nom,
        'info' => implode('<br>', array_filter($d))
    ];
}
// lancement du script (sera affiché dans le layout à la fin de la page)
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat'];?>;
const CENTRE_LNG = <?= $this->config['centre']['lng'];?>;
const INI_ZOOM = <?= $this->config['zoom'];?>;
initialiser("<?=$this->scheme;?>","point d'arrêt","<?= $this->description;?>",<?= json_encode($aMarkers);?>);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Position d'une station sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="float-left">
			<ul style="margin-top: 0;">
			<?php foreach ($this->station as $ligne) :?>
				<li><?= $ligne;?></li>
			<?php endforeach;?>
			</ul>
		</div>
		<div class="float-right left-10px" style="max-width: 700px;">
			<?= $this->form($this->form); ?>
			<p class="sbm-description">
				Cliquez sur la carte à l'emplacement de la station puis cliquez sur
				le bouton <b>'Enregistrer la localisation'</b>.<br>Utilisez le zoom
				pour plus de précision.
			</p>
		</div>

	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>
