<?php
/**
 * Liste des stations non desservies
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/stations-non-desservies.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 20 mars 2015
 * @version 2015-1
 */
use SbmCommun\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$origine = $this->url('sbmgestion/transport', array(
    'action' => 'stations-non-desservies',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'stations-non-desservies-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/transport', array(
    'action' => 'station-liste',
    'page' => $this->page
));
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-printer',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    )
);
?>
<h1>Liste des stations non desservies</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
</div>
	</div>
	<div id="liste-inner">
		<table class="stations">
			<tbody>
				<tr>
					<th>Commune</th>
					<th>Nom</th>
					<th>Visible</th>
					<th>Ouverte</th>
					<th>Inscrits</th>
				</tr>
            <?php foreach($this->data as $test => $station): ?>
            <?php $nbInscrits = StdLib::getParamR(array($station['stationId'], 'total'), $this->t_nb_inscrits, 0); ?>
            <?php $exces = $nbInscrits > 0; ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next(); if ($exces) echo ' exces';?>">
					<td class="commune"><?php echo $this->escapeHtml($station['commune']); ?></td>
					<td class="nom"><?php echo $this->escapeHtml($station['nom']); ?></td>
					<td class="visible"><?php echo $station['visible'] ? 'Oui' : 'Non'; ?></td>
					<td class="ouverte"><?php echo $station['ouverte'] ? 'Oui' : 'Non'; ?></td>
					<td class="nbinscrits"><?php echo $nbInscrits; ?></td>
					<td class="boutons">
            <?php
                $url_edit = $this->url('sbmgestion/transport', array(
                    'action' => 'station-edit',
                    'page' => $this->page
                ));
                $url_delete = $this->url('sbmgestion/transport', array(
                    'action' => 'station-suppr',
                    'page' => $this->page
                ));
                $url_group = $this->url('sbmgestion/transport', array(
                    'action' => 'station-group',
                    'page' => $this->page
                ));
                $hiddens = array(
                    'stationId' => $station['stationId'],
                    'origine' => $origine
                );
                $buttons = array(
                    'modifier' => array(
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ),
                    'supprimer' => array(
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ),
                    'eleves' => array(
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de la station %s - %s', $station['nom'], $station['commune'])
                    )
                );
                echo $this->listeLigneActions($station['stationId'], $hiddens, $buttons);
                ?>
			        </td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>