<?php
/**
 * Page de création d'un lien entre deux stations jumelées
 * (c'est à dire qui peuvent facilement établir une correspondance à pied)
 *
 * Voici les variables définies dans cette vue:
 * $origine         : prend la valeur 'station-station'
 * $station         : fiche de la station 1 pour affichage dans titre
 * $form            : le formulaire de saisi
 * $page            : la page de la liste initiale dans station-liste
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource station-station-ajout.php
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 mai 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
// $this->themeJS('gestion-transport', 'station-station-ajout.js');
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => $this->origine,
        'page' => $this->page
    ]);
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
$hiddens = [
    'stationId' => $this->station->stationId,
    'origine' => $this->origine
];
$h1 = sprintf("Ajout d'une station jumelle de la station\n%s - %s",
    $this->station->nom, $this->station->commune);
$description1 = 'la station';
?>
<h1><?= nl2br($h1); ?></h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix"><?= $this->listeZoneActions($hiddens, $actions);?></div>
	</div>
	<div id="fiche-inner">
		<?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('origine'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
        <?= $this->formHidden($this->form->get('station1Id'));?>
    	<fieldset class="sbm-page1">
			<div id="wrapper-stationId" class="row-inner ajout">
            	<?= $this->formRow($this->form->get('station2Id'));?>
            </div>
			<div id="wrapper-temps" class="row-inner ajout">
        		<?= $this->formRow($this->form->get('temps'));?>
			</div>
			<div id="wrapper-buttons" class="row-inner ajout">
    			<?= $this->formSubmit($this->form->get('submit'));?>
    			<?= $this->formSubmit($this->form->get('cancel'));?>
    		</div>
		</fieldset>
    	<?= $this->form()->closeTag();?>
    </div>
	<div id="fiche-footer"></div>
</div>