<?php
/**
 * Liste des stations non desservies
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/stations-non-desservies.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 fév. 2019
 * @version 2019-2.5.0
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_origine = $this->url('sbmgestion/transport',
    [
        'action' => 'stations-non-desservies',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'stations-non-desservies-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'stations-non-desservies'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content']
];
?>
<h1>Liste des stations non desservies</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="stations">
			<tbody>
				<tr>
					<th>Commune</th>
					<th>Nom</th>
					<th>Visible</th>
					<th>Ouverte</th>
					<th>Inscrits</th>
				</tr>
            <?php foreach($this->data as $station): ?>
            	<?php
                $nbInscrits = StdLib::getParamR([
                    $station['stationId'],
                    'total'
                ], $this->t_nb_inscrits, 0);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($nbInscrits > 0) {
                    $css .= ' exces';
                }
                $url_edit = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-edit',
                        'page' => $this->page
                    ]);
                $url_delete = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-suppr',
                        'page' => $this->page
                    ]);
                $url_group = $this->url('sbmgestion/transport',
                    [
                        'action' => 'station-group',
                        'page' => $this->page
                    ]);
                $hiddens = [
                    'stationId' => $station['stationId'],
                    'origine' => $url_origine
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => sprintf('élèves de la station %s - %s', $station['nom'],
                            $station['commune'])
                    ]
                ];
                ?>
                <tr class="<?= $css;?>">
					<td class="commune">
						<?= $this->escapeHtml($station['commune']); ?></td>
					<td class="nom">
						<?= $this->escapeHtml($station['nom']); ?></td>
					<td class="visible">
						<?= $station['visible'] ? 'Oui' : 'Non'; ?></td>
					<td class="ouverte">
						<?= $station['ouverte'] ? 'Oui' : 'Non'; ?></td>
					<td class="nbinscrits">
						<?= $nbInscrits; ?></td>
					<td class="boutons">
                		<?= $this->listeLigneActions($station['stationId'], $hiddens, $buttons);?>
			        </td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
</div>