<?php
/**
 * Page de suppression d'une station
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/finance/station-suppr.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2020
 * @version 2020-2.6.0
 */
?>
<h1>Suppression d'une station</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de la station :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->escapeHtml($this->data->commune); ?></li>
			<li><?= $this->escapeHtml($this->data->nom); ?></li>
			<?php if ($this->data->alias):?>
			<li><?= $this->escapeHtml($this->data->alias); ?></li>
			<?php endif;?>
		</ul>
	</div>
	<p>Confirmez-vous ?</p>
    <?= $this->form()->openTag($form);?>
    <?= $this->formCollection($form);?>
    <?= $this->form()->closeTag();?>
</div>