<?php
/**
 * Page de consultation des inscrits sur une station
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 août 2015
 * @version 2015-2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_rapports = $this->url('sbmgestion/transport', array(
    'action' => 'station-group-pdf',
    'page' => $this->page
));
$hiddens = array(
    'stationId' => $this->stationId
);
$menuImpression = $this->menuRapports($this->url('sbmgestion/transport', array(
    'action' => 'station-group'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'javascript:window.document.getElementById(\'op\').value=\'retour\';';
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $this->origine,
        'title' => 'Retour',
        'onclick' => $js_retour
    ),
    'rapports' => $menuImpression['content']
);
?>
<h1>Groupe des élèves inscrits sur une station</h1>
<div id="liste-wrapper">
	<div id="liste-title">
		<ul>
			<li>Commune : <?php echo $this->escapeHtml($this->station->commune); ?></li>
			<li>Arrêt : <?php echo $this->escapeHtml($this->station->nom); ?></li>
		</ul>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php
foreach ($this->data as $row) {
    echo '<tr class="' . $this->cycle(array(
        "even",
        "odd"
    ))->next() . '">';
    foreach ($row as $key => $item) {
        $css = $key == 'classe' ? ' class="centre"' : '';
        echo "<td$css>" . $item . '</td>';
    }
    echo '</tr>';
}
?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<p>
			<em>Il y a <?php echo count($this->data); ?> élèves.</em>
		</p>
	</div>
</div>