<?php
/**
 * Page de création d'une station
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/station-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'station-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Création d'une nouvelle station</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('stationId'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="wrapper-communeId" class="row-inner ajout">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="wrapper-nom" class="row-inner ajout">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="wrapper-alias" class="row-inner ajout">
				<?= $this->formRow($this->form->get('alias')); ?></div>
			<div id="wrapper-code" class="row-inner ajout">
				<?= $this->formRow($this->form->get('code')); ?></div>
			<div id="wrapper-longitude" class="row-inner ajout">
				<?= $this->formRow($this->form->get('x')); ?></div>
			<div id="wrapper-latitude" class="row-inner ajout">
				<?= $this->formRow($this->form->get('y')); ?></div>
			<div id="wrapper-visible" class="row-inner ajout">
				<?= $this->formRow($this->form->get('visible')); ?></div>
			<div id="wrapper-ouverte" class="row-inner ajout">
				<?= $this->formRow($this->form->get('ouverte')); ?></div>
			<div id="wrapper-equipement" class="row-inner ajout">
				<?= $this->formRow($this->form->get('equipement')); ?></div>
			<div id="wrapper-id_tra" class="row-inner ajout">
				<?= $this->formRow($this->form->get('id_tra')); ?></div>
			<div id="wrapper-buttons" class="row-inner ajout">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>