<?php
/**
 * Liste des transporteurs
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 23 août 2015
 * @version 2015-2
 */
use SbmCommun\Model\StdLib;

function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
$jsCallback = '';
$jsTrigger = '';

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$transporteurs = $this->paginator->getCurrentItems();

$url_ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-ajout',
    'page' => $this->page
));
$url_rapports = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-pdf',
    'page' => $this->page
));
$url_retour = $this->url('sbmgestion/transport');
$url_edit = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-edit',
    'page' => $this->page
));
$url_delete = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-suppr',
    'page' => $this->page
));
$url_relation = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-service',
    'id' => $this->page
));
$url_group = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-group',
    'id' => $this->page
));
$hiddens = array();
$menuImpression = $this->menuRapports($this->url('sbmgestion/transport', array(
    'action' => 'transporteur-liste'
)), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ),
    'rapports' => $menuImpression['content'],
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau transporteur'
    )
);
?>
<h1>Liste des transporteurs</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
	<div id="liste-inner">
		<table class="transporteurs">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Fax</th>
					<th>Email</th>
					<th>Inscrits</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($transporteurs as $test => $transporteur): ?>
            <?php
                // selection
                $modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectiontransporteur/transporteurId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;
                
                $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n", $transporteur->transporteurId);
                $jsCallback .= sprintf("$modele\n", $transporteur->transporteurId, $transporteur->transporteurId);
                ?>
                <tr
					class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="nom"><?php echo $this->escapeHtml($transporteur->nom); ?></td>
					<td class="commune"><?php echo $this->escapeHtml($transporteur->commune); ?></td>
					<td class="codepostal"><?php echo $this->escapeHtml($transporteur->codePostal); ?></td>
					<td class="telephone"><?php echo $this->escapeHtml($transporteur->telephone); ?></td>
					<td class="fax"><?php echo $this->escapeHtml($transporteur->fax); ?></td>
					<td class="email"><?php echo $this->escapeHtml($transporteur->email); ?></td>
					<td class="nbinscrits"><?php echo StdLib::getParamR(array($transporteur->transporteurId, 'total'), $this->t_nb_inscrits, 0); ?></td>
					<td class="centre selection"><?php echo renderCheckbox($this, 'selection', 'chk' . $transporteur->transporteurId, $transporteur->selection)?></td>
					<td class="boutons">
            <?php
                $hiddens = array(
                    'transporteurId' => $transporteur->transporteurId
                );
                $buttons = array(
                    'modifier' => array(
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ),
                    'supprimer' => array(
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ),
                    'services' => array(
                        'class' => 'fam-table-relationship',
                        'formaction' => $url_relation,
                        'title' => 'circuits attribués à ' . $transporteur->nom
                    ),
                    'eleves' => array(
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves pris en chage par ' . $transporteur->nom
                    )
                );
                echo $this->listeLigneActions($transporteur->transporteurId, $hiddens, $buttons);
                ?>
					</td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
		<div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?php echo $jsTrigger;?>}
<?php echo $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();