<?php
/**
 * Page de création d'un transporteur
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mai 2014
 * @version 2014-1
 */
$retour = $this->url('sbmgestion/transport', array('action'=> 'transporteur-liste', 'page' => $this->page));
?>
<h1>Création d'un nouveau transporteur</h1>
<div class="fiche-wrapper">
  <div class="zone-actions">
    <a href="<?php echo $retour; ?>" class="bouton" title="retour à la liste des transporteurs"><i class="fam-door-out"></i> Retour</a>
  </div>
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('transporteurId'));
echo $this->formHidden($this->form->get('csrf'));
echo '<fieldset class="edit">';
echo '<div id="transporteur-edit-nom" class="row-inner edit">' . $this->formRow($this->form->get('nom')) . '</div>';
echo '<div id="transporteur-edit-adresse1" class="row-inner edit">' . $this->formRow($this->form->get('adresse1')) . '</div>';
echo '<div id="transporteur-edit-adresse2" class="row-inner edit">' . $this->formRow($this->form->get('adresse2')) . '</div>';
echo '<div id="transporteur-edit-codePostal" class="row-inner edit">' . $this->formRow($this->form->get('codePostal')) . '</div>';
echo '<div id="transporteur-edit-comuneId" class="row-inner edit">' . $this->formRow($this->form->get('communeId')) . '</div>';
echo '<div id="transporteur-edit-telephone" class="row-inner edit">' . $this->formRow($this->form->get('telephone')) . '</div>';
echo '<div id="transporteur-edit-fax" class="row-inner edit">' . $this->formRow($this->form->get('fax')) . '</div>';
echo '<div id="transporteur-edit-email" class="row-inner edit">' . $this->formRow($this->form->get('email')) . '</div>';
echo '<div id="transporteur-edit-siret" class="row-inner edit">' . $this->formRow($this->form->get('siret')) . '</div>';
echo '<div id="transporteur-edit-naf" class="row-inner edit">' . $this->formRow($this->form->get('naf')) . '</div>';
echo '<div id="transporteur-edit-rib_titulaire" class="row-inner edit">' . $this->formRow($this->form->get('rib_titulaire')) . '</div>';
echo '<div id="transporteur-edit-rib_domiciliation" class="row-inner edit">' . $this->formRow($this->form->get('rib_domiciliation')) . '</div>';
echo '<div id="transporteur-edit-rib_bic" class="row-inner edit">' . $this->formRow($this->form->get('rib_bic')) . '</div>';
echo '<div id="transporteur-edit-rib_iban" class="row-inner edit">' . $this->formRow($this->form->get('rib_iban')) . '</div>';
echo '<div id="transporteur-edit-buttons" class="row-inner edit">' . $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')) .'</div>';
echo '</fieldset>';
echo $this->form()->closeTag();
?>
</div>