<?php
/**
 * Liste des services pour un transporteur donné
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/transport/
 * @filesource transporteur-service.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-service-pdf',
        'page' => $this->page,
        'pr' => $this->pageRetour
    ]);
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-liste',
        'page' => $this->pageRetour
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'service-group',
        'pr' => $this->page,
        'id' => $this->pageRetour
    ]);
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';

$hiddens = [
    'transporteurId' => $this->transporteurId
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'transporteur-service'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content']
];

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Liste des services d'un transporteur</h1>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<ul class="float-left">
			<li><?php

echo $this->escapeHtml($this->transporteur->nom);
?></li>
		</ul>
		<div class="flashMessenger float-right">
		    <?=$this->flashMessenger()->render('success');?>
		    <?=$this->flashMessenger()->render('warning');?>
		    <?=$this->flashMessenger()->render('error');?>
		    <?=$this->flashMessenger()->render('info');?>
		    <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-header" class="clearfix">
		<div class="menu clearfix"><?=$this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?=$this->paginator->getTotalItemCount();?> services.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="liste-inner services">
			<tbody>
				<tr>
					<th>Service</th>
					<th>Alias</th>
					<th>Opérateur</th>
					<th>Capacité</th>
					<th>Inscrits</th>
					<th></th>
				</tr>
            <?php

            foreach ($data as $service) :
                ?>
            	<?php
                $serviceId = sprintf('%d|%s|%d|%d|%d', $service->millesime,
                    $service->ligneId, $service->sens, $service->moment, $service->ordre);
            	$designation = $service->designation();
                $nbInscrits = $this->effectifTransporteursServices->transportes(
                    $service->ligneId, $service->sens, $service->moment, $service->ordre);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                if ($service->nbPlaces < $nbInscrits) {
                    $css .= ' exces';
                }
                $hiddens = [
                    'transporteurId' => $this->transporteurId,
                    'ligneId' => $service->ligneId,
                    'sens' => $service->sens,
                    'moment' => $service->moment,
                    'ordre' => $service->ordre,
                    'origine' => 'transporteur-service'
                ];
                $buttons = [
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves inscrits sur ce service'
                    ]
                ];
                ?>
                <tr class="<?=$css;?>">
					<td class="designation">
						<?=$this->escapeHtml($designation);?></td>
					<td class="aliascg">
						<?=$this->escapeHtml($service->alias);?></td>
					<td class="operateur">
						<?=$this->escapeHtml($service->operateur);?></td>
					<td class="nbplaces">
						<?=$this->escapeHtml($service->nbPlaces);?></td>
					<td class="nbinscrits">
						<?=$nbInscrits;?></td>
					<td class="boutons">
					<?=$this->listeLigneActions($this->serviceId, $hiddens, $buttons);?>
					</td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
	</div>
</div>
