<?php
/**
 * Page de consultation des élèves transportés par un transporteur
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-group.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 jan. 2019
 * @version 2019-2.4.6
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/transport', 
    [
        'action' => 'transporteur-liste',
        'page' => $this->pageRetour
    ]);
$url_rapports = $this->url('sbmgestion/transport', 
    [
        'action' => 'transporteur-group-pdf',
        'page' => $this->page
    ]);
$url_group = $this->url('sbmgestion/transport', 
    [
        'action' => 'transporteur-group',
        'page' => $this->page
    ]);
$url_edit = $this->url('sbmgestion/eleve', 
    [
        'action' => 'eleve-edit',
        'page' => $this->page
    ]);
$url_mail = $this->url('sbmgestion/eleve', [
    'action' => 'responsable-mail'
]);
$url_mark_selection = $this->url('sbmgestion/transport', 
    [
        'action' => 'transporteur-group-selection',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$url_add_photo = $this->url('sbmgestion/eleve', 
    [
        'action' => 'envoiphoto',
        'page' => $this->page,
        'id' => $this->pageRetour
    ]);
$hiddens = [
    'transporteurId' => $this->transporteurId
];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'transporteur-group'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
// ne pas utiliser de guillement dans la chaine $js
$js_retour = 'window.document.getElementById(\'op\').value=\'retour\';';
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => $js_retour
    ],
    'rapports' => $menuImpression['content'],
    'marquer' => [
        'class' => 'fam-basket-add',
        'formaction' => $url_mark_selection,
        'title' => 'Sélectionner toutes les fiches de cette liste'
    ]
];

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
?>
<h1>Groupe des élèves pris en charge par un transporteur</h1>
<div id="liste-wrapper">
	<div id="liste-title" class="clearfix">
		<ul class="float-left">
			<li><?php echo $this->escapeHtml($this->transporteur->nom); ?></li>
		</ul>
		<div class="flashMessenger float-right">
		<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
		</div>
	</div>
	<div id="liste-header">
		<div class="menu clearfix"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<p>
			<em>Il y a <?php echo $this->paginator->getTotalItemCount(); ?> prises en charge.</em>
		</p>
	</div>
	<div id="liste-inner">
		<table class="eleves">
			<tbody>
				<tr>
					<th></th>
					<th>Service</th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Adresse</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Commune</th>
					<th>Etablissement</th>
					<th>Classe</th>
				</tr>
			<?php foreach ($data as $row):?>
			<?php
    $hiddens = [
        'eleveId' => $row['eleveId'],
        'info' => $row['nom'] . ' ' . $row['prenom'],
        'email' => $row['email'],
        'responsable' => $row['responsable'],
        'group' => $url_group
    ];
    $buttons = [
        'modifier' => [
            'class' => 'fam-pencil',
            'formaction' => $url_edit,
            'title' => 'Modifier'
        ]
    ];
    if ($row['sansphoto']) {
        $buttons['photo'] = [
            'class' => 'fam-camera-add',
            'formaction' => $url_add_photo,
            'title' => 'Envoyer une photo'
        ];
    }
    if (! empty($row['email'])) {
        $buttons['ecrire'] = [
            'class' => 'fam-email',
            'formaction' => $url_mail,
            'title' => 'Envoyer un email'
        ];
    }
    $this->pictogrammes('init')
        ->addPreinscrit($row['paiement'] == 0 && $row['fa'] == 0 & $row['gratuit'] == 0)
        ->addSansPhoto($row['sansphoto']);
    ?>
			    <tr class="<?php echo $this->cycle(["even", "odd"])->next();?>">
					<td><?php echo $this->pictogrammes();?></td>
					<td><?php echo $row['serviceId'];?></td>
					<td><?php echo $this->escapeHtml($row['nom']);?></td>
					<td><?php echo $this->escapeHtml($row['prenom']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL1']);?></td>
					<td><?php echo $this->escapeHtml($row['adresseL2']);?></td>
					<td><?php echo $this->escapeHtml($row['codePostal']);?></td>
					<td><?php echo $this->escapeHtml($row['commune']);?></td>
					<td><?php echo $this->escapeHtml($row['etablissement']);?></td>
					<td class="centre"><?php echo $this->escapeHtml($row['classe']);?></td>
					<td><?php echo $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);?></td>
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
</div>