<?php
/**
 * Page de création d'un transporteur
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-ajout.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 11 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport', array('action'=> 'transporteur-liste', 'page' => $this->page));
$hiddens =[];
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    )
);
?>
<h1>Création d'un nouveau transporteur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
<?php 
echo $this->form()->openTag($this->form);
echo $this->formHidden($this->form->get('transporteurId'));
echo $this->formHidden($this->form->get('csrf'));
?>
    <fieldset class="sbm-page1">
        <div id="transporteur-ajout-nom" class="row-inner ajout"><?php echo $this->formRow($this->form->get('nom')); ?></div>
        <div id="transporteur-ajout-adresse1" class="row-inner ajout"><?php echo $this->formRow($this->form->get('adresse1')); ?></div>
        <div id="transporteur-ajout-adresse2" class="row-inner ajout"><?php echo $this->formRow($this->form->get('adresse2')); ?></div>
        <div id="transporteur-ajout-codePostal" class="row-inner ajout"><?php echo $this->formRow($this->form->get('codePostal')); ?></div>
        <div id="transporteur-ajout-comuneId" class="row-inner ajout"><?php echo $this->formRow($this->form->get('communeId')); ?></div>
        <div id="transporteur-ajout-telephone" class="row-inner ajout"><?php echo $this->formRow($this->form->get('telephone')); ?></div>
        <div id="transporteur-ajout-fax" class="row-inner ajout"><?php echo $this->formRow($this->form->get('fax')); ?></div>
        <div id="transporteur-ajout-email" class="row-inner ajout"><?php echo $this->formRow($this->form->get('email')); ?></div>
        <div id="transporteur-ajout-siret" class="row-inner ajout"><?php echo $this->formRow($this->form->get('siret')); ?></div>
        <div id="transporteur-ajout-naf" class="row-inner ajout"><?php echo $this->formRow($this->form->get('naf')); ?></div>
        <div id="transporteur-ajout-tvaIntraCommunautaire" class="row-inner ajout"><?php echo $this->formRow($this->form->get('tvaIntraCommunautaire')); ?></div>
        <div id="transporteur-ajout-rib_titulaire" class="row-inner ajout"><?php echo $this->formRow($this->form->get('rib_titulaire')); ?></div>
        <div id="transporteur-ajout-rib_domiciliation" class="row-inner ajout"><?php echo $this->formRow($this->form->get('rib_domiciliation')); ?></div>
        <div id="transporteur-ajout-rib_bic" class="row-inner ajout"><?php echo $this->formRow($this->form->get('rib_bic')); ?></div>
        <div id="transporteur-ajout-rib_iban" class="row-inner ajout"><?php echo $this->formRow($this->form->get('rib_iban')); ?></div>
        <div id="transporteur-ajout-buttons" class="row-inner ajout">
        <?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
    </fieldset>
<?php echo $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>