<?php
/**
 * Page de modification d'un transporteur
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 2 oct. 2018
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-liste',
        'page' => $this->page
    ]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'un transporteur</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	</div>
	<div id="fiche-inner">
        <?= $this->form()->openTag($this->form);?>
        <?= $this->formHidden($this->form->get('transporteurId'));?>
        <?= $this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div id="transporteur-edit-nom" class="row-inner edit">
				<?= $this->formRow($this->form->get('nom')); ?></div>
			<div id="transporteur-edit-adresse1" class="row-inner edit">
				<?= $this->formRow($this->form->get('adresse1')); ?></div>
			<div id="transporteur-edit-adresse2" class="row-inner edit">
				<?= $this->formRow($this->form->get('adresse2')); ?></div>
			<div id="transporteur-edit-codePostal" class="row-inner edit">
				<?= $this->formRow($this->form->get('codePostal')); ?></div>
			<div id="transporteur-edit-comuneId" class="row-inner edit">
				<?= $this->formRow($this->form->get('communeId')); ?></div>
			<div id="transporteur-edit-telephone" class="row-inner edit">
				<?= $this->formRow($this->form->get('telephone')); ?></div>
			<div id="transporteur-edit-fax" class="row-inner edit">
				<?= $this->formRow($this->form->get('fax')); ?></div>
			<div id="transporteur-edit-email" class="row-inner edit">
				<?= $this->formRow($this->form->get('email')); ?></div>
			<div id="transporteur-edit-siret" class="row-inner edit">
				<?= $this->formRow($this->form->get('siret')); ?></div>
			<div id="transporteur-edit-naf" class="row-inner edit">
				<?= $this->formRow($this->form->get('naf')); ?></div>
			<div id="transporteur-edit-tvaIntraCommunautaire"
				class="row-inner edit">
				<?= $this->formRow($this->form->get('tvaIntraCommunautaire')); ?></div>
			<div id="transporteur-edit-rib_titulaire" class="row-inner edit">
				<?= $this->formRow($this->form->get('rib_titulaire')); ?></div>
			<div id="transporteur-edit-rib_domiciliation" class="row-inner edit">
				<?= $this->formRow($this->form->get('rib_domiciliation')); ?></div>
			<div id="transporteur-edit-rib_bic" class="row-inner edit">
				<?= $this->formRow($this->form->get('rib_bic')); ?></div>
			<div id="transporteur-edit-rib_iban" class="row-inner edit">
				<?= $this->formRow($this->form->get('rib_iban')); ?></div>
			<div id="transporteur-edit-buttons" class="row-inner edit">
        		<?= $this->formSubmit($this->form->get('submit'));?>
        		<?= $this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
    </div>
	<div id="fiche-footer"></div>
</div>