<?php

/**
 * Liste des transporteurs
 *
 * Cette vue reçoit un objet effectifTransporteurs qui présente la méthode
 * transportes($transporteurId) donnant les effectifs des élèves transportés
 * pour chaque identifiant $transporteurId.
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 juin 2019
 * @version 2019-2.5.0
 */
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxtransport/'+action+'selectiontransporteur/transporteurId:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$transporteurs = $this->paginator->getCurrentItems();

$url_ajouter = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-ajout',
        'page' => $this->page
    ]);
$url_rapports = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-pdf',
        'page' => $this->page
    ]);
$url_retour = $this->url('sbmgestion/transport');
$url_edit = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-edit',
        'page' => $this->page
    ]);
$url_delete = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-suppr',
        'page' => $this->page
    ]);
$url_relation = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-service',
        'id' => $this->page
    ]);
$url_group = $this->url('sbmgestion/transport',
    [
        'action' => 'transporteur-group',
        'id' => $this->page
    ]);
if ($this->layout()->hassbmservicesms) {
    $url_sms = $this->url('sbmservicesms', [
        'action' => 'envoi-groupe',
        'page' => $this->page
    ]);
}
$hiddens = [];
$menuImpression = $this->menuRapports(
    $this->url('sbmgestion/transport', [
        'action' => 'transporteur-liste'
    ]), $url_rapports, 'fam-printer', null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'ajouter' => [
        'class' => 'fam-add',
        'formaction' => $url_ajouter,
        'title' => 'Nouveau transporteur'
    ]
];
?>
<h1>Liste des transporteurs</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
			<?=$this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?=$this->flashMessenger()->render('success');?>
            <?=$this->flashMessenger()->render('warning');?>
            <?=$this->flashMessenger()->render('error');?>
            <?=$this->flashMessenger()->render('info');?>
            <?=$this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="transporteurs">
			<tbody>
				<tr>
					<th>Nom</th>
					<th>Commune</th>
					<th>Code postal</th>
					<th>Téléphone</th>
					<th>Fax</th>
					<th>Email</th>
					<th>Inscrits</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php

            foreach ($transporteurs as $transporteur) :
                ?>
            <?php
                $nbInscrits = $this->effectifTransporteurs->transportes(
                    $transporteur->transporteurId);
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n",
                    $transporteur->transporteurId);
                $jsCallback .= sprintf("$modele\n", $transporteur->transporteurId,
                    $transporteur->transporteurId);
                $css = $this->cycle([
                    "even",
                    "odd"
                ])->next();
                $hiddens = [
                    'transporteurId' => $transporteur->transporteurId
                ];
                $buttons = [
                    'modifier' => [
                        'class' => 'fam-pencil',
                        'formaction' => $url_edit,
                        'title' => 'modifier'
                    ],
                    'supprimer' => [
                        'class' => 'fam-delete',
                        'formaction' => $url_delete,
                        'title' => 'supprimer'
                    ],
                    'services' => [
                        'class' => 'fam-table-relationship',
                        'formaction' => $url_relation,
                        'title' => 'circuits attribués à ' . $transporteur->nom
                    ],
                    'eleves' => [
                        'class' => 'fam-group',
                        'formaction' => $url_group,
                        'title' => 'élèves pris en chage par ' . $transporteur->nom
                    ]
                ];
                if ($this->layout()->hassbmservicesms) {
                    $buttons['sms'] = [
                        'class' => 'fam-phone',
                        'formaction' => $url_sms,
                        'title' => 'Envoyer un SMS'
                    ];
                }
                ?>
                <tr class="petit <?=$css;?>">
					<td class="nom">
						<?=$this->escapeHtml($transporteur->nom);?></td>
					<td class="commune">
						<?=$this->escapeHtml($transporteur->commune);?></td>
					<td class="codepostal">
						<?=$this->escapeHtml($transporteur->codePostal);?></td>
					<td class="telephone">
						<?=$this->telephone($transporteur->telephone);?></td>
					<td class="fax">
						<?=$this->telephone($transporteur->fax);?></td>
					<td class="email">
						<?=$this->escapeHtml($transporteur->email);?></td>
					<td class="nbinscrits align-right">
						<?=$nbInscrits;?></td>
					<td class="centre selection">
						<?=renderCheckbox($this, 'selection', 'chk' . $transporteur->transporteurId,$transporteur->selection)?>
					</td>
					<td class="boutons">
						<?=$this->listeLigneActions($transporteur->transporteurId, $hiddens, $buttons);?>
					</td>
				</tr>
            <?php
            endforeach
            ;
            ?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []);?></div>
		<div class="criteres-wrapper">
	    	<?=$this->form()->openTag($this->criteres_form);?>
	    	<?=$this->formCollection($this->criteres_form, true);?>
	    	<?=$this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
<?=$jsTrigger;?>}
<?=$jsCallback;?>
});
<?php
$this->headScript()->captureEnd();