<?php
/**
 * Liste des transporteurs
 *
 *
 * @project sbm
 * @package SbmGestion
 * @filesource view/sbm-gestion/transport/transporteur-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 mai 2014
 * @version 2014-1
 */
use SbmCommun\Model\StdLib;
 
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->paginator->setDefaultItemCountPerPage($this->nb_pagination);
$this->paginator->setCurrentPageNumber($this->page);
$transporteurs = $this->paginator->getCurrentItems();
$ajouter = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-ajout',
    'page' => $this->page
));
$pdf = $this->url('sbmgestion/transport', array(
    'action' => 'transporteur-pdf',
    'page' => $this->page
));
$retour = $this->url('sbmgestion/transport');
$hiddens = array();
$actions = array(
    'retour' => array(
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ),
    'rapports' => array(
        'class' => 'fam-application-view-list',
        'formaction' => $pdf,
        'title' => 'Rapports à imprimer'
    ),
    'ajouter' => array(
        'class' => 'fam-add',
        'formaction' => $ajouter,
        'title' => 'Nouveau transporteur'
    )
);
?>
<h1>Liste des transporteurs</h1>
<div class="liste-wrapper">
	<div id="liste-header" class="clearfix">
	    <div class="float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
	    <div class="flashMessenger float-right"><?php 
		    echo $this->flashMessenger()->render('success');
		    echo $this->flashMessenger()->render('warning');
		    echo $this->flashMessenger()->render('error');
		    echo $this->flashMessenger()->render('info');
		    echo $this->flashMessenger()->render('default');
		    ?></div>
	</div>
	<div id="liste-inner">
		<table class="transporteurs">
			<tbody>
			    <tr><th>Nom</th><th>Commune</th><th>Code postal</th><th>Téléphone</th><th>Fax</th><th>Email</th><th>Inscrits</th><th></th></tr>
            <?php foreach($transporteurs as $test => $transporteur): ?>
            <?php $fmt?>
                <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
					<td class="nom"><?php echo $this->escapeHtml($transporteur->nom); ?></td>
					<td class="commune"><?php echo $this->escapeHtml($transporteur->commune); ?></td>
					<td class="codepostal"><?php echo $this->escapeHtml($transporteur->codePostal); ?></td>
					<td class="telephone"><?php echo $this->escapeHtml($transporteur->telephone); ?></td>
					<td class="fax"><?php echo $this->escapeHtml($transporteur->fax); ?></td>
					<td class="email"><?php echo $this->escapeHtml($transporteur->email); ?></td>
					<td class="nbinscrits"><?php echo StdLib::getParamR(array($transporteur->transporteurId, 'total'), $this->t_nb_inscrits, 0); ?></td>
					<td class="boutons">
            <?php
            $url_edit = $this->url('sbmgestion/transport', array(
                'action' => 'transporteur-edit',
                'page' => $this->page,
            ));
            $url_delete = $this->url('sbmgestion/transport', array(
                'action' => 'transporteur-suppr',
                'page' => $this->page,
            ));
            $url_relation = $this->url('sbmgestion/transport', array(
                'action' => 'transporteur-service',
                'page' => $this->page
            ));
            $url_group = $this->url('sbmgestion/transport', array(
                'action' => 'transporteur-group',
                'page' => $this->page,
            ));
            $hiddens = array(
                'transporteurId' => $transporteur->transporteurId
            );
            $buttons = array(
                'modifier' => array(
                    'class' => 'fam-pencil',
                    'formaction' => $url_edit,
                    'title' => 'modifier'
                ),
                'supprimer' => array(
                    'class' => 'fam-delete',
                    'formaction' => $url_delete,
                    'title' => 'supprimer'
                ),
                'services' => array(
                    'class' => 'fam-table-relationship',
                    'formaction' => $url_relation,
                    'title' => 'circuits attribués à ' . $transporteur->nom
                ),
                'eleves' => array(
                    'class' => 'fam-group',
                    'formaction' => $url_group,
                    'title' => 'élèves pris en chage par ' . $transporteur->nom
                )
            );
            echo $this->listeLigneActions($transporteur->transporteurId, $hiddens, $buttons);
            ?>
					</td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
	    <div class="pagination-wrapper clearfix"><?php echo $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', array()); ?></div>
	    <div class="criteres-wrapper">
	    <?php echo $this->form()->openTag($this->criteres_form);?>
	    <?php echo $this->formCollection($this->criteres_form, true);?>
	    <?php echo $this->form()->closeTag();?>
        </div>	
    </div>
</div>