<?php
/**
 * Carte des établissements scolaires
 *
 * Affichage des établissements décrits dans $this->ptEtablissements qui est un tableau de Point
 * Chaque Point est donné dans le système géographique RGF93 (ou WGS84) en degrés décimaux.
 * Des cases à cocher permettent de sélectionner l'affichage.
 *
 * @project sbm
 * @package SbmCarographie/view/sbm-cartographie/carte
 * @filesource etablissements.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 9 nov. 2020
 * @version 2020-2.6.1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headStyle()->captureStart();
?>
#carte-inner {
    width: 90%;
    height: 500px;
    margin-left: auto;
    margin-right: auto;
    margin-top: 20px;
    margin-bottom: 20px;
}
#choix {
	margin-right: 5em;
}
<?php
$this->headStyle()->captureEnd();
// préparation du script
$i = 0;
$aMarkers = [];
foreach ($this->ptEtablissements as $pt) {
    $e = $pt->getAttribute('etablissement');
    $niveau = is_array($e->niveau) ? array_sum($e->niveau) : $e->niveau;
    $accord_desservi = "";
    if ($niveau < 4) {
        $color = "pink";
        $icon = "pink-pushpin.png";
        $lettre = "E";
        $nature = "École";
        $accord_desservi = "e";
        $index = "ecole";
    } elseif ($niveau == 4) {
        $color = "yellow";
        $icon = "ylw-pushpin.png";
        $lettre = "C";
        $nature = "Collège";
        $index = "college";
    } else {
        $color = "blue";
        $icon = "ltblu-pushpin.png";
        $lettre = "L";
        $nature = "Lycée";
        $index = "lycee";
    }
    if ($e->desservie) {
        $nature .= " desservi" . $accord_desservi;
    } else {
        $color = "black";
        $icon = "flag.png";
        $nature .= " non desservi" . $accord_desservi;
        $index = "nonDesservi";
    }
    $d = [
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        trim(implode(" - ", [
            $e->adresse1,
            $e->adresse2
        ]), " -"),
        implode(' ', [
            $e->codePostal,
            $e->lacommune
        ]),
        'Tél. ' . $this->telephone($e->telephone)
    ];
    $tmp = $e->email;
    if (! empty($tmp)) {
        $d[] = 'Email : ' . $e->email;
    }
    $d[] = $nature;
    $aMarkers[$index][] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'icon' => $icon,
        'text' => $lettre,
        'title' => $e->nom . "\n" . $e->lacommune,
        'info' => implode('<br>', $d)
    ];
}
$carte_init_parametres = sprintf('"%s","%s","%s",%f,%f,%d,%s', 'etablissementcheckbox',
    'carte-inner', $this->scheme, $this->config['centre']['lat'],
    $this->config['centre']['lng'], $this->config['zoom'], json_encode($aMarkers));

// mise en place des JS de googleMaps
$this->headScript()->prependFile($this->url_api);
$this->JQuery();
$this->ThemeJs('commun', 'carte.js');
$this->headScript()->captureStart();
?>
carte.init(<?=$carte_init_parametres;?>);
<?php
$this->headScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
$hiddens = [];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'title' => 'Retour'
    ]
];
?>
<h1>Ecoles et établissements scolaires</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="menu float-left">
		<?= $this->listeZoneActions($hiddens, $actions);?>
		</div>
		<div id="choix" class="float-right">
			Cochez ou décochez pour choisir les établissements affichés : <input
				name="etablissementcheckbox" type="checkbox" checked value="ecole">Écoles
			<input name="etablissementcheckbox" type="checkbox" checked
				value="college">Collèges <input name="etablissementcheckbox"
				type="checkbox" checked value="lycee">Lycées
			<?php if (! $this->filtre):?>
			<input name="etablissementcheckbox" type="checkbox"
				value="nonDesservi">Non desservis
			<?php endif;?>
		</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>