<?php
/**
 * Carte des établissements scolaires
 *
 * Affichage des établissements décrits dans $this->ptEtablissements qui est un tableau de Point
 * Chaque Point est donné dans le système géographique RGF93 (ou WGS84) en degrés décimaux.
 * 
 * Le style des markers peut être changé : remplacer BUBBLE par MARKER ligne 39
 * 
 * @project sbm
 * @package SbmCarographie/view/sbm-cartographie/carte
 * @filesource etablissements.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 9 août 2016
 * @version 2016-2.1.10
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// mise en place des JS de googleMaps
$this->headScript()->appendFile('https://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->appendFile('/js/maps/carte.js');
$this->headScript()->captureStart();
?>
const CENTRE_LAT = <?php echo $this->config['centre']['lat']; ?>;
const CENTRE_LNG = <?php echo $this->config['centre']['lng']; ?>;
const INI_ZOOM = <?php echo $this->config['zoom']; ?>;
<?php
$this->headScript()->captureEnd();
// lancement du script 
$i = 0;
$tMarkers = "[\n";
foreach ($this->ptEtablissements as $pt) {
    $e = $pt->getAttribute('etablissement');
    $niveau = array_sum($e->niveau);
    if ($niveau <4) {
        //$color = "#ffff00";
        $lettre = "E";
        $nature = "Ecole";
    } elseif ($niveau == 4) {
        //$color = "#fc6700";
        $lettre = "C";
        $nature = "Collège";
    } else {
        //$color = "#e5c3d0";
        $lettre = "L";
        $nature = "Lycée";
    }
    if ($e->desservie) {
        $color = "#00ff00";
        $nature .= " desservie";
    } else {
        $color = "#ff0000";
        $nature .= " non desservie";
    }
    $d = array(
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        trim(implode(" - ", array(
            $e->adresse1,
            $e->adresse2
        )), " -"),
        implode(' ', array(
            $e->codePostal,
            $e->commune
        )),
        'Tél. ' . $e->telephone,
    );
    $tmp = $e->email;
    if (!empty($tmp)) {
        $d[] = 'Email : ' . $e->email;
    }
    $d[] = $nature;
    
    $tMarkers .= '{"lat":' . $pt->getLatitude() .',"lng":' . $pt->getLongitude() . ',"color":"' . $color . '","text":"' . $lettre. '","title":"' . $e->nom .'","info":"' . implode('<br>', $d) ."\"},\n";

}
$tMarkers .= ']';
$this->inlineScript()->captureStart();
?>
tMarkers = <?php echo $tMarkers;?>;
initialiser();
<?php 
$this->inlineScript()->captureEnd(); 
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Ecoles et établissements scolaires</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="menu float-left"><?php
echo $this->listeZoneActions(array(), array(
    'cancel' => array(
        'class' => 'fam-door-out',
        'title' => 'Retour'
    )
));
?></div>
        <div class="float-right right-10px"><span style="background-color:#ff0000; font-weight:bold;">En rouge</span> les écoles et les établissements non desservis.
        <span style="background-color:#00ff00; font-weight:bold;">En vert</span> les écoles et les établissements desservis.</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>