<?php
/**
 * Carte des établissements scolaires
 *
 * Affichage des établissements décrits dans $this->ptEtablissements qui est un tableau de Point
 * Chaque Point est donné dans le système géographique RGF93 (ou WGS84) en degrés décimaux.
 *
 * Le style des markers peut être changé : remplacer BUBBLE par MARKER ligne 39
 *
 * @project sbm
 * @package SbmCarographie/view/sbm-cartographie/carte
 * @filesource etablissements.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 25 mars 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'carte.js');
$this->themeJS('commun', 'StyledMarker.js');
// préparation du script
$i = 0;
$aMarkers = [];
foreach ($this->ptEtablissements as $pt) {
    $e = $pt->getAttribute('etablissement');
    $niveau = array_sum($e->niveau);
    $accord_desservi = "";
    if ($niveau < 4) {
        // $color = "#ffff00";
        $lettre = "E";
        $nature = "École";
        $accord_desservi = "e";
    } elseif ($niveau == 4) {
        // $color = "#fc6700";
        $lettre = "C";
        $nature = "Collège";
    } else {
        // $color = "#e5c3d0";
        $lettre = "L";
        $nature = "Lycée";
    }
    if ($e->desservie) {
        $color = "#00ff00";
        $nature .= " desservi" . $accord_desservi;
    } else {
        $color = "#ff0000";
        $nature .= " non desservi" . $accord_desservi;
    }
    $d = [
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        trim(implode(" - ", [
            $e->adresse1,
            $e->adresse2
        ]), " -"),
        implode(' ', [
            $e->codePostal,
            $e->lacommune
        ]),
        'Tél. ' . $this->telephone($e->telephone)
    ];
    $tmp = $e->email;
    if (! empty($tmp)) {
        $d[] = 'Email : ' . $e->email;
    }
    $d[] = $nature;
    $aMarkers[] = [
        'lat' => $pt->getLatitude(),
        'lng' => $pt->getLongitude(),
        'color' => $color,
        'text' => $lettre,
        'title' => $e->nom,
        'info' => implode('<br>', $d)
    ];
}
// lancement du script
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= $this->config['centre']['lat']; ?>;
const CENTRE_LNG = <?= $this->config['centre']['lng']; ?>;
const INI_ZOOM = <?= $this->config['zoom']; ?>;
initialiser("<?=$this->scheme;?>",<?= json_encode($aMarkers);?>);
<?php
$this->inlineScript()->captureEnd();
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
$hiddens = [];
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'title' => 'Retour'
    ]
];
?>
<h1>Ecoles et établissements scolaires</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="menu float-left">
		<?= $this->listeZoneActions($hiddens, $actions);?>
		</div>
		<div class="float-right right-10px sbm-description">Zoomez puis cliquez sur une marque
			pour obtenir des renseignements.</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>