<?php
/**
 * Carte des stations
 *
 * Affichage des stations décrites dans $this->ptStations qui est un tableau de Point
 * Chaque Point est donné dans le système géographique RGF93 (ou WGS84) en degrés décimaux.
 * 
 * Le style des markers peut être changé : remplacer BUBBLE par MARKER ligne 39
 * 
 * @project sbm
 * @package SbmCarographie/view/sbm-cartographie/carte
 * @filesource stations.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 1 nov. 2016
 * @version 2016-2.2.2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// mise en place des JS de googleMaps
$this->headScript()->appendFile($this->url_api);
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->appendFile('/js/maps/carte.js');
// préparation du script
$i = 0;
$tMarkers = "[\n";
foreach ($this->ptStations as $pt) {
    $e = $pt->getAttribute('station');
    if ($e->ouverte) {
        $color = "#00ff00";
        $nature = "ouverte";
    } else {
        $color = "#ff0000";
        $nature = "fermée";
    }
    $d = array(
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        implode(' ', array(
            $e->codePostal,
            $e->commune
        ))
    );
    
    $tMarkers .= '{"lat":' . $pt->getLatitude() . ',"lng":' . $pt->getLongitude() . ',"color":"' . $color . '","text":"S","title":"' . $e->nom . '","info":"' . implode('<br>', $d) . "\"},\n";
}
$tMarkers .= ']';
// lancement du script
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?php echo $this->config['centre']['lat']; ?>;
const CENTRE_LNG = <?php echo $this->config['centre']['lng']; ?>;
const INI_ZOOM = <?php echo $this->config['zoom']; ?>;
initialiser(<?php echo $tMarkers;?>);
<?php 
$this->inlineScript()->captureEnd(); 
/* ========== FIN DE LA MISE EN PLACE DES JAVASCRIPTS ====== */
?>
<h1>Points d'arrêt</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="menu float-left"><?php
echo $this->listeZoneActions(array(), array(
    'cancel' => array(
        'class' => 'fam-door-out',
        'title' => 'Retour'
    )
));
?></div>
		<div class="float-right right-10px">
			<span style="background-color: #ff0000; font-weight: bold;">En rouge</span>
			les points d'arrêt fermés. <span style="background-color: #00ff00; font-weight: bold;">En vert</span>
			les points d'arrêt ouverts.
		</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>