<?php
/**
 * Carte des stations
 *
 * Affichage des stations décrites dans $this->ptStations qui est un tableau de Point
 * Chaque Point est donné dans le système géographique RGF93 (ou WGS84) en degrés décimaux.
 * 
 * Le style des markers peut être changé : remplacer BUBBLE par MARKER ligne 39
 * 
 * @project sbm
 * @package SbmCarographie/view/sbm-cartographie/carte
 * @filesource stations.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 13 juin 2015
 * @version 2015-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// mise en place des JS de googleMaps
$this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->appendFile('/js/StyledMarker.js');
$this->headScript()->captureStart();
?>
var tMarkers = new Array();
function initialiser() {
    // initialisation des paramètres de la carte
    var options = {
        'center': new google.maps.LatLng(<?php echo $this->config['centre']['lat'];?>, <?php echo $this->config['centre']['lng'];?>),
        'zoom': <?php echo $this->config['zoom'];?>,
        //'mapTypeId': google.maps.MapTypeId.ROADMAP
        mapTypeId: "OSM",
        mapTypeControl: true,
        mapTypeControlOptions: {
            mapTypeIds: [
                "OSM",
                //google.maps.MapTypeId.ROADMAP, 
                //google.maps.MapTypeId.SATELLITE, 
                google.maps.MapTypeId.HYBRID, 
                google.maps.MapTypeId.TERRAIN
            ],
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        streetViewControl: true
    };
    var oCarte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // define OSM map type pointing at the OpenStreetMap tile server
    oCarte.mapTypes.set("OSM", new google.maps.ImageMapType({
        getTileUrl: function(coord, zoom) {
            return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
        },
        tileSize: new google.maps.Size(256,256),
        name: "OpenStreetMap",
        maxZoom: 18,
        opacity: 1,
        alt: "Carte OpenStreetMap"
    }));
    // info bulle
    var oInfo = new google.maps.InfoWindow();
    // placement des markers
    for (var i = 0; i < tMarkers.length; i++) {
        var optionsMarker = {
            'styleIcon': new StyledIcon(StyledIconTypes.BUBBLE,{color:tMarkers[i].color,text:tMarkers[i].text}),
            'map': oCarte,
            'position': new google.maps.LatLng( tMarkers[i].lat, tMarkers[i].lng),
            'numero': i,
            'title': tMarkers[i].title
        }
        var oMarker = new StyledMarker(optionsMarker);        
        // listeners
        google.maps.event.addListener(oMarker, 'click', function(data) {
            oInfo.setContent(tMarkers[this.numero].info);
            oInfo.open(this.getMap(), this);
        });
    }
}

<?php
$this->headScript()->captureEnd();
// lancement du script
$i = 0;
$tMarkers = "[\n";
foreach ($this->ptStations as $pt) {
    $e = $pt->getAttribute('station');
    if ($e->ouverte) {
        $color = "#00ff00";
        $nature = "ouverte";
    } else {
        $color = "#ff0000";
        $nature = "fermée";
    }
    $d = array(
        '<b>' . $this->escapeHtml($e->nom) . '</b>',
        implode(' ', array(
            $e->codePostal,
            $e->commune
        ))
    );
    
    $tMarkers .= '{"lat":' . $pt->getLatitude() . ',"lng":' . $pt->getLongitude() . ',"color":"' . $color . '","text":"S","title":"' . $e->nom . '","info":"' . implode('<br>', $d) . "\"},\n";
}
$tMarkers .= ']';
$this->inlineScript()->captureStart();
?>
tMarkers = <?php echo $tMarkers;?>;
initialiser();
<?php $this->inlineScript()->captureEnd(); ?>
<h1>Points d'arrêt</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
		<div class="float-left left-10px"><?php
echo $this->listeZoneActions(array(), array(
    'cancel' => array(
        'class' => 'fam-door-out',
        'title' => 'Retour'
    )
));
?></div>
		<div class="float-right right-10px">
			<span style="background-color: #ff0000; font-weight: bold;">En rouge</span>
			les points d'arrêt fermés. <span
				style="background-color: #00ff00; font-weight: bold;">En vert</span>
			les points d'arrêt ouverts.
		</div>
	</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div>