<?php
/**
 * Page d'affectation des élèves inscrits
 *
 * Présente la liste des élèves inscrits sans affectation et un bouton individuel
 * pour les affecter à un circuit
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource affecter-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 04 juin 2019
 * @version 2019-2.5.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();
$url_retour = $this->url('sbmgestion/gestioneleve');
$url_affecter = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'affecter',
        'page' => $this->page
    ]);
$buttons = [
    'affecter' => [
        'class' => 'fam-car-add',
        'formaction' => $url_affecter,
        'title' => 'affecter'
    ]
];
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Liste des élèves <?= $this->title;?> sans affectation</h1>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
			<?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
<?php if ($this->paginator->getCurrentItemCount()): ?>
	<div id="liste-inner">
		<table class="data">
			<tbody>
				<tr>
					<th></th>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Régime</th>
					<th>Adresse</th>
					<th>Commune</th>
					<th>Etablissement scolaire</th>
					<th>Commune</th>
					<th>Distance</th>
				</tr>
<?php foreach ($data as $row): ?>
<?php
        $distance = $row['estR1'] ? $row['distanceR1'] : $row['distanceR2'];
        if ($row['district'] || $row['derogation']) {
            if ($distance == 0 || $distance == 99) {
                $tr_css = 'warning';
            } elseif ($distance < 1) {
                $tr_css = 'alert';
            } else {
                $tr_css = '';
            }
        } else {
            $tr_css = 'error';
        }
        $this->pictogrammes('init')
            ->addPreinscrit(! $this->inscrit)
            ->addSansPhoto(! $row['hasphoto'])
            ->addDistanceZero($row['demandeR1'], $row['distanceR1'], $row['demandeR2'],
            $row['distanceR2']);
        $hiddens = [
            'eleveId' => $row['eleveId'],
            'millesime' => $row['millesime'],
            'trajet' => $row['estR1'] ? 1 : 2,
            'jours' => 31,
            'sens' => 3,
            'correspondance' => 1,
            'responsableId' => $row['responsableId'],
            'op' => 1
        ];
        $cle = implode('|',
            [
                $row['millesime'],
                $row['eleveId'],
                $row['estR1'] ? 1 : 2,
                $row['responsableId']
            ]);
        $adresse = implode('<br/>',
            array_filter(
                [
                    $this->escapeHtml($row['adresseL1']),
                    $this->escapeHtml($row['adresseL2'])
                ]));
        ?>
            	<tr
					class="petit <?= $tr_css . ' ' . $this->cycle(['even', 'odd'])->next(); ?>">
					<td><?= $this->pictogrammes(); ?></td>
					<td><?= $this->escapeHtml($row['nom']); ?></td>
					<td><?= $this->escapeHtml($row['prenom']); ?></td>
					<td><?= $row['regimeId'] ? 'Interne' : 'DP';?></td>
					<td><?= $adresse?></td>
					<td><?= $this->escapeHtml($row['commune']); ?></td>
					<td><?= $this->escapeHtml($row['etablissement']); ?></td>
					<td><?= $this->escapeHtml($row['communeEtablissement']); ?></td>
					<td><?= $distance; ?></td>
					<td><?= $this->listeLigneActions($cle, $hiddens, $buttons); ?></td>
				</tr>
<?php endforeach;?>
		</tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?=$this->paginationControl($this->paginator,'Sliding','sbm/pagination',[]);?></div>
		<div class="clearfix">
			<div class="criteres-wrapper float-left">
				<div class="clearfix">
	                <?= $this->form()->openTag($this->criteres_form);?>
	                <fieldset>
						<div style="display: inline-block">
						<?= $this->formRow($this->criteres_form->get('choix'));?>
						</div>
						<div style="display: inline-block" class="left-10px">
							<?= $this->formRow($this->criteres_form->get('submit'));?></div>
					</fieldset>
	                <?= $this->form()->closeTag();?>
	            </div>
			</div>
			<p class="sbm-description float-right">
				<span class="alert">En rouge</span> les demandes qui ne semblent pas
				être éligibles, à moins d'une dérogation.<br> <span class="warning">En
					bleu</span> les demandes d'élèves où la distance n'a pas été
				renseignée.<br> En noir les demandes d'élèves ayant droit.
			</p>
		</div>
	</div>
<?php else: ?>
    <div id="liste-inner">
		<i>Il n'y a pas d'élève inscrit non affecté.</i>
	</div>
	<div id="liste-footer"></div>
<?php endif; ?>
</div>