<?php
/**
 * Page d'affectation d'un élève inscrit
 *
 * Présente le formulaire d'affectation d'un élève inscrit
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource affecter.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 avr. 2015
 * @version 2015-1
 */
// calcul des variables
$url_retour = $this->url('sbmgestion/gestioneleve', array(
    'action' => 'affecter-liste',
    'page' => $this->page
));
$descriptionElv = implode('<br>', array(
    $this->eleve['nom'] . ' ' . $this->eleve['prenom'],
    empty($this->eleve['adresseL2']) ? $this->eleve['adresseL1'] : $this->eleve['adresseL1'] . '<br>' . $this->eleve['adresseL2'],
    $this->eleve['codePostal'] . ' ' . $this->eleve['commune']
));
$descriptionEta = addslashes(implode('<br>', array(
    $this->eleve['etablissement'],
    $this->eleve['communeEtablissement']
)));
$latCentre = ($this->ptElv->getLatitude() + $this->ptEta->getLatitude()) / 2;
$lngCentre = ($this->ptElv->getLongitude() + $this->ptEta->getLongitude()) / 2;
// page html
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->headScript()->appendFile($this->basePath('/js/jquery.min.js'));
$this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->captureStart()?>
function adaptedecision()
{
    var district = document.getElementById("decision_district");
    if (district) {
    var derogation = document.getElementById("decision_derogation");
    derogation.style.display = district.checked ? 'none' : '';
    document.getElementById("decision_motifDerogation").style.display = derogation.checked ? '' : 'none';
    var accord = document.getElementById("decision_accordR");
    document.getElementById("decision_motifRefusR").style.display = accord.checked ? 'none' : '';
    var subvention = document.getElementById("decision_subventionR");
    subvention.checked = false;
    subvention.style.display = accord.checked ? 'none' : '';
    }
}

function initialiser() {
    var latlng = new google.maps.LatLng(<?php echo $latCentre;?>, <?php echo $lngCentre;?>);
    // initialisation des paramètres de la carte
    var options = {
        center: latlng,
        zoom: 12,
        //mapTypeId: google.maps.MapTypeId.ROADMAP
        mapTypeId: "OSM",
        mapTypeControl: true,
        mapTypeControlOptions: {
            mapTypeIds: [
                "OSM",
                //google.maps.MapTypeId.ROADMAP, 
                //google.maps.MapTypeId.SATELLITE, 
                google.maps.MapTypeId.HYBRID, 
                google.maps.MapTypeId.TERRAIN
            ],
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        streetViewControl: true
    };
    var carte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // define OSM map type pointing at the OpenStreetMap tile server
    carte.mapTypes.set("OSM", new google.maps.ImageMapType({
        getTileUrl: function(coord, zoom) {
            return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
        },
        tileSize: new google.maps.Size(256,256),
        name: "OpenStreetMap",
        maxZoom: 18,
        opacity: 1,
        alt: "Carte OpenStreetMap"
    }));
    // initialisation du marker du domicile
    var optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(<?php echo $this->ptElv->getLatitude(); ?>, <?php echo $this->ptElv->getLongitude(); ?>),
        title: 'domicile de l\'élève'
    }
    var markerElv = new google.maps.Marker(optionsMarqueur);
    var infoElv = new google.maps.InfoWindow({
        content  : "<?php echo $descriptionElv;?>",
        position : latlng
    });
    google.maps.event.addListener(markerElv, 'click', function() {
        infoElv.open(carte,markerElv);
    });
    optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(<?php echo $this->ptEta->getLatitude(); ?>, <?php echo $this->ptEta->getLongitude(); ?>),
        title: 'établissement scolaire'
    }
    var markerEta = new google.maps.Marker(optionsMarqueur);
    var infoEta = new google.maps.InfoWindow({
        content  : "<?php echo $descriptionEta;?>",
        position : latlng
    });
    google.maps.event.addListener(markerEta, 'click', function() {
        infoEta.open(carte,markerEta);
    });
}
$(document).ready(function($) {
$("#affectation-service1Id").on('change',function() {
	    var valeur = $(this).val();
	    $.ajax({
	            url : '/sbmajaxeleve/getstationsforselect/serviceId:'+valeur,
	            dataType: 'json',
	            success : function(dataJson){
	                $("#affectation-station1Id").empty();
	                $("#affectation-station2Id").empty();
	                if (dataJson.success) {
	                    $.each(dataJson.data, function(k, d) {
	                        $('#affectation-station1Id').append('<option value="' + k + '">' + d + '</option>');
	                        $('#affectation-station2Id').append('<option value="' + k + '">' + d + '</option>');
	                    });
	                }
	            },
	            error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
	    });
	});
});
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
initialiser();
adaptedecision();
<?php $this->inlineScript()->captureEnd(); ?>
<div id="page-titre" class="clearfix">
	<div class="float-left">
		<h1>Affectation d'un élève inscrit</h1>
	</div>
	<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
</div>
<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-inner">
		<div class="clearfix">
			<div class="float-left" style="width: 45%;">
				<ul>
					<li><?php echo $this->eleve['nom'] . ' ' . $this->eleve['prenom']; ?></li>
					<li><?php
    if (empty($this->eleve['adresseL2'])) {
        echo $this->eleve['adresseL1'];
    } else {
        echo $this->eleve['adresseL1'] . ' - ' . $this->eleve['adresseL2'];
    }
    ?></li>
					<li><?php echo $this->eleve['codePostal'] . ' ' . $this->eleve['commune']; ?></li>
					<li><?php echo $this->eleve['etablissement'] . ' ' . $this->eleve['communeEtablissement']; ?></li>
				</ul>
				<div class="inner-form-auto">
			<?php
if ($this->op == 1) {
    echo $this->form($this->decision);
} else {
    // affichage des informations en texte;
    echo '<p>Transport accepté</p>
          <p class="sbm-description">Précisez le circuit, le point de montée et, en cas de correspondance, le point de descente et le circuit suivant.';
}
?>
	<?php
if ($this->op > 1) {
    echo $this->form($this->decision);
}
?>			</div>
			</div>
			<div id="carte-wrapper" class="float-right"
				style="margin-right: 10px; width: 50%;">
				<div id="carte-inner" style="height: 300px;"></div>
			</div>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>

