<?php
/**
 * Page d'affectation d'un élève inscrit
 *
 * Présente le formulaire d'affectation d'un élève inscrit
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource affecter.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 04 juin 2019
 * @version 2019-2.5.0
 */
// test sur le formulaire decision

// calcul des variables
$descriptionElv = implode('<br>',
    array_filter(
        [
            $this->eleve['nom'] . ' ' . $this->eleve['prenom'],
            $this->eleve['adresseL1'],
            $this->eleve['adresseL2'],
            $this->eleve['codePostal'] . ' ' . $this->eleve['commune']
        ]));
$descriptionEta = addslashes(
    implode('<br>',
        [
            $this->eleve['etablissement'],
            $this->eleve['communeEtablissement']
        ]));
// page html
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/eleve-gestion', 'affecter.css');
$this->jQuery();
$this->headScript()->appendFile($this->url_api);
$this->themeJS('commun', 'carte.js');
$this->themeJS('commun', 'StyledMarker.js');
$this->themeJS('gestion-eleve', 'affecter.js');
// construction du tableau de marqueurs pour la carte
$tMarkers = "[\n";
$color = '#fc6700';
$lettre = 'D';
$title = "domicile de l'élève";
$info = $descriptionElv;
$tMarkers .= '{"lat":' . $this->ptElv->getLatitude() . ',"lng":' .
    $this->ptElv->getLongitude() . ',"color":"' . $color . '","text":"' . $lettre .
    '","title":"' . $title . '","info":"' . $info . "\"},\n";
$color = '#e5c3d0';
$lettre = 'E';
$title = "établissement scolaire";
$info = $descriptionEta;
$tMarkers .= '{"lat":' . $this->ptEta->getLatitude() . ',"lng":' .
    $this->ptEta->getLongitude() . ',"color":"' . $color . '","text":"' . $lettre .
    '","title":"' . $title . '","info":"' . $info . "\"},\n";
$tMarkers .= ']';
// lancement des scripts d'initialisation
$this->inlineScript()->captureStart();
?>
const CENTRE_LAT = <?= ($this->ptElv->getLatitude() + $this->ptEta->getLatitude()) / 2; ?>;
const CENTRE_LNG = <?= ($this->ptElv->getLongitude() + $this->ptEta->getLongitude()) / 2; ?>;
const INI_ZOOM = <?= $this->config['zoom']; ?>;
initialiser("<?=$this->scheme;?>",<?= $tMarkers;?>);
js_affecter.adaptedecision();
<?php
$this->inlineScript()->captureEnd();
// ============= fin des javaScripts ===================
$adresse = implode(' - ',
    array_filter([
        $this->eleve['adresseL1'],
        $this->eleve['adresseL2']
    ]));
?>
<div id="page-titre" class="clearfix">
	<div class="float-left">
		<h1>Affectation d'un élève inscrit</h1>
	</div>
	<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
	</div>
</div>
<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-inner">
		<div class="clearfix">
			<div class="float-left" style="width: 45%;">
				<ul>
					<li><?= $this->eleve['nom'] . ' ' . $this->eleve['prenom']; ?></li>
					<li><?= $adresse;?></li>
					<li>
						<?= $this->eleve['codePostal'];?>
					    <?= $this->eleve['commune'];?></li>
					<li>
						<?= $this->eleve['etablissement'];?>
						<?= $this->eleve['communeEtablissement'];?></li>
				</ul>
				<div class="inner-form">
<?php if ($this->op == 1):?>
    <?= $this->form()->openTag($this->decision);?>
    <?php foreach ($this->decision->getElements() as $element):?>
        <?php if ($element->getAttribute('type') == 'hidden'):?>
            <?= $this->formHidden($element);?>
        <?php elseif ($element->getAttribute('type') != 'submit'):?>
            <div id="row-<?= $element->getAttribute('id');?>"
						class="row-inner">
            <?= $this->formRow($element);?>
            </div>
        <?php endif;?>
    <?php endforeach;?>
    <div class="bloc-bouton">
    	<?= $this->formSubmit($this->decision->get('cancel'));?>
    	<?= $this->formSubmit($this->decision->get('submit'));?>
    </div>
    <?= $this->form()->closeTag(); ?>
<?php else:?>
    <h3>Transport accepté</h3>
<?php endif;?>
<?php if ($this->op > 1) : ?>
    <?= $this->form($this->decision);?>
    <p class="sbm-description">Précisez le circuit, le point de montée
						et, en cas de correspondance, le point de descente et le circuit
						suivant.'</p>
<?php endif;?>
    			</div>
			</div>
			<div id="carte-wrapper" class="float-right"
				style="margin-right: 10px; width: 50%;">
				<div id="carte-inner" style="height: 300px;"></div>
			</div>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>