<?php
/**
 * Ecran de choix de la sélection de cartes de transport
 *
 * On peut demander l'impression de :
 * - cartes non encore tirées des élèves affectés sur des circuits
 * - cartes tirées à une date donnée
 * - cartes des élèves sélectionnés
 * 
 * On peut également définir des critères de sélection sur les circuits, les transporteurs, les établissements, les communes de résidence
 * On peut préciser l'ordre de cartes à tirer 
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource cartes.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 août 2016
 * @version 2016-2.1.10
 */
use SbmCommun\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-liste',
    'page' => $this->page
]);
$hiddens = [
    // afin de retrouver les critères en session
    'op' => 'retour' 
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour, 
        'title' => 'Retour'
    ]
];
$this->headScript()
    ->appendFile($this->basePath('/js/jquery.min.js'))
    ->captureStart();
?>
js_carte = (function(){
  $(document).ready(function($) {
    $("#selection").click(function() {
      js_carte.montreDate();
    });
  });
  return {
    "montreDate": function() {
      if ($("#selectionradio1").is(':checked')) {
        $("#quelle-date").show();
      } else {
        $("#quelle-date").hide();
      }
    }
  }
})();    
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
js_carte.montreDate();
<?php $this->inlineScript()->captureEnd();?>
<div id="fiche-wrapper">
	<h1>Edition des cartes</h1>
	<div id="fiche-header">
		<div class="menu clearfix">
        <?php echo $this->listeZoneActions($hiddens, $actions);?>
        </div>
	<?php if ($this->lastDateCarte >= $this->dateDebut) : ?>
	<p>La dernière préparation a été faite le <?php echo DateLib::formatDateTimeFromMysql($this->lastDateCarte);?>.</p>
	<?php endif;?>
	</div>
	<div id="fiche-inner">	    
		<?php echo $this->form()->openTag($this->form1); ?>
	    <fieldset class="sbm-page1">
			<p>Si vous souhaitez préparer une nouvelle édition, cliquez sur le
				bouton ci-dessous.</p>
			<div class="row-inner"><?php echo $this->formSubmit($this->form1->get('nouvelle')); ?></div>
			<p>
				Par la suite, cochez <i>Dernière édition</i>, sélectionnez vos
				critères (élèves inscrits ou élèves préinscrits) ainsi que le
				document que vous voulez obtenir et cliquez sur le bouton <i>Lancer
					l'édition</i>.
			</p>
		</fieldset>
	    <?php echo $this->form()->closeTag(); ?>
	    <p></p>
	    <?php echo $this->form()->openTag($this->form2); ?>
		<fieldset class="sbm-page1">
			<div id="selection" class="row-inner"><?php echo $this->formRow($this->form2->get('selection'));?></div>
			<div id="quelle-date" class="row-inner"><?php echo $this->formRow($this->form2->get('dateReprise'));?></div>
			<div id="critere" class="row-inner"><?php echo $this->formRow($this->form2->get('critere'));?></div>
			<div id="document" class="row-inner"><?php echo $this->formRow($this->form2->get('document'));?></div>
			<div class="row-inner"><?php echo $this->formSubmit($this->form2->get('submit')); ?></div>
		</fieldset>
		<?php echo $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">Vous pouvez créer une nouvelle édition de
			cartes, reprendre une édition déjà réalisée à une date donnée ou
			demander l'édition des cartes pour les fiches sélectionnées.</p>
	</div>
</div>