<?php
/**
 * Ecran de choix de la sélection de cartes de transport
 *
 * On peut demander l'impression de :
 * - cartes non encore tirées des élèves affectés sur des circuits
 * - cartes tirées à une date donnée
 * - cartes des élèves sélectionnés
 * 
 * On peut également définir des critères de sélection sur les circuits, les transporteurs, les établissements, les communes de résidence
 * On peut préciser l'ordre de cartes à tirer 
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource cartes.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 16 fév. 2019
 * @version 2019-2.5.0
 */
use SbmBase\Model\DateLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$url_retour = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-liste',
        'page' => $this->page
    ]);
$hiddens = [
    // afin de retrouver les critères en session
    'op' => 'retour'
];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
$this->jQuery();
$this->headScript()->appendFile($this->basePath('/js/gestion-eleve/cartes-photos.js'));
$this->inlineScript()->captureStart();
?>
js_date.montreDate();
<?php $this->inlineScript()->captureEnd();?>
<div id="fiche-wrapper">
	<h1>Edition des <?= strtolower($this->natureCartes);?></h1>
	<div id="fiche-header">
		<div class="menu clearfix">
        <?= $this->listeZoneActions($hiddens, $actions);?>
        </div>
	<?php if ($this->lastDateCarte >= $this->dateDebut) : ?>
	<p>La dernière préparation a été faite le <?= DateLib::formatDateTimeFromMysql($this->lastDateCarte);?>.</p>
	<?php endif;?>
	</div>
	<div id="fiche-inner">	    
		<?= $this->form()->openTag($this->form1); ?>
	    <fieldset class="sbm-page1">
			<p>
				Si vous souhaitez préparer une nouvelle édition, cliquez sur le
				bouton ci-dessous.<br>Attention ! Seuls les élèves qui sont affectés 
				sur un circuit nécessitant des <?= strtolower($this->natureCartes);?> 
				seront pris en compte.</p>
			<div class="row-inner"><?= $this->formSubmit($this->form1->get('nouvelle')); ?></div>
			<p>
				Par la suite pour utiliser cette nouvelle édition, cochez <i>Dernière
					préparation</i>, sélectionnez vos critères (élèves inscrits ou
				élèves préinscrits) ainsi que le document que vous voulez obtenir et
				cliquez sur le bouton <i>Lancer l'édition</i>.
			</p>
		</fieldset>
	    <?= $this->form()->closeTag(); ?>
	    <p></p>
	    <?= $this->form()->openTag($this->form2); ?>
		<fieldset class="sbm-page1">
			<div id="selection" class="row-inner">
				<?= $this->formRow($this->form2->get('selection'));?></div>
			<div id="quelle-date" class="row-inner">
				<?= $this->formRow($this->form2->get('dateReprise'));?></div>
			<div id="critere" class="row-inner">
				<?= $this->formRow($this->form2->get('critere'));?></div>
			<div id="document" class="row-inner">
				<?= $this->formRow($this->form2->get('document'));?></div>
			<div class="row-inner">
				<?= $this->formSubmit($this->form2->get('submit')); ?></div>
		</fieldset>
		<?= $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">Vous pouvez créer une nouvelle édition de
			cartes, reprendre une édition déjà réalisée à une date donnée ou
			demander l'édition des cartes pour les fiches sélectionnées.</p>
	</div>
</div>