<?php
/**
 * Page de confirmation et configuration d'un duplicata
 *
 * On confirme le souhait d'avoir un duplicata et on indique la position sur la planche d'étiquette.
 * Le pdf est créé et le champ duplicata de la table scolarites est incrémenté.
 * Il est possible de faire un duplicata à titre gratuit. Dans ce cas, pas d'incrémentation dans la table.
 * 
 * @project sbm
 * @package SbmGestion/view/eleve-gestion
 * @filesource duplicata-carte.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 fév. 2019
 * @version 2019-2.4.7
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$hiddens = [
    'eleveId' => $this->eleveId,
    'origine' => $this->origine
];
$url_ici = $this->url('sbmgestion/gestioneleve', 
    [
        'action' => 'duplicata-carte'
    ]);
$actions = [
    'cancel' => [
        'class' => 'fam-door-out',
        'formaction' => $url_ici, // traitement de cancel pour un redirect proprement
        'title' => 'Retour'
    ]
];
?>
<div id="fiche-wrapper">
	<h1>Duplicata d'une carte de transport</h1>
	<div id="fiche-header">
		<div class="menu clearfix">
	    <?= $this->listeZoneActions($hiddens, $actions);?>
	    </div>
	</div>
	<div id="fiche-inner">
	    <?= $this->form()->openTag($this->form); ?>
	    <?= $this->formHidden($this->form->get('eleveId'));?>
	    <?= $this->formHidden($this->form->get('origine'));?>
		<fieldset class="sbm-page1">
			<div class="row-inner planche">
	    <?php if ($this->form->hasPlanche()) :?>
			Indiquez la position de l'étiquette dans la planche d'étiquettes
	    <?php endif;?>
            <?= $this->form->renderPlanche();?>
            </div>
			<div class="row-inner"><?= $this->formRow($this->form->get('gratuit'));?></div>
		</fieldset>
		<div class="row-inner">
		    <?= $this->formSubmit($this->form->get('submit'));?>
		    <?= $this->formSubmit($this->form->get('cancel')); ?></div>
		<?= $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer">
		<p class="sbm-description">
			Vous pouvez exceptionnellement éditer un duplicata à titre gratuit en
			cochant la case <em>gratuité</em>. Sinon, le coût d'un duplicata sera
			ajouté à la somme due par la famille.
		</p>
	</div>
</div>