<?php
/**
 * Liste des élèves en garde alternée dont le responsable N°2 n'a pas de distance calculée.
 *
 * Cela vient souvent du fait que le responsable n°1 a saisi l'identité du responsable n°2
 * mais qu'il n'est pas localisé sur la carte.
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource ga-localisation-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 mai 2020
 * @version 2020-2.6.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();

$url_retour = $this->url('sbmgestion/gestioneleve');
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Demande de transport en garde alternée</h1>
<h2>Localisation du second domicile</h2>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left">
			<?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
            <?= $this->flashMessenger()->render('success');?>
            <?= $this->flashMessenger()->render('warning');?>
            <?= $this->flashMessenger()->render('error');?>
            <?= $this->flashMessenger()->render('info');?>
            <?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
<?php if ($data->count()) :?>
    <div id="liste-inner">
		<table class="data">
			<tbody>
				<tr>
					<th>Elève</th>
					<th>Etablissement scolaire</th>
					<th colspan="2">Adresse 1</th>
					<th>D1</th>
					<th colspan="2">Adresse 2</th>
					<th>D2</th>
					<th></th>
				</tr>
<?php foreach ($data as $row): ?>
<?php
        $hiddens = [
            'eleveId' => $row['eleveId'],
            'responsableId' => $row['responsable2Id'],
            'xr1' => $row['xr1'],
            'yr1' => $row['yr1'],
            'descriptionr1' => implode('<br>',
                [
                    $row['responsable1'],
                    $row['adresseR1L1'],
                    $row['adresseR1L2'],
                    $row['communeR1']
                ]),
            'xeta' => $row['xeta'],
            'yeta' => $row['yeta'],
            'descriptioneta' => implode('<br>',
                [
                    $row['etablissement'],
                    $row['lacommuneEtablissement']
                ])
        ];
        /*
         * $url_distByAddr = $this->url('sbmgestion/gestioneleve', [ 'action' =>
         * 'ga-localisation-byaddr', 'page' => $this->page ]);
         */
        $url_distByMap = $this->url('sbmgestion/gestioneleve',
            [
                'action' => 'ga-localisation-bymap',
                'page' => $this->page
            ]);
        ;
        $buttons = [
            /*
             * 'addresse' => [ 'class' => 'fam-book-addresses', 'formaction' =>
             * $url_distByAddr, 'title' => 'localisation par l\'adresse' ],
             */
            'carte' => [
                'class' => 'fam-map-magnify',
                'formaction' => $url_distByMap,
                'title' => 'position sur la carte'
            ]
        ];
        $adresseR1 = implode('<br>',
            array_filter(
                [
                    $this->escapeHtml($row['adresseR1L1']),
                    $this->escapeHtml($row['adresseR1L2'])
                ]));
        $adresseR2 = implode('<br>',
            array_filter(
                [
                    $this->escapeHtml($row['adresseR2L1']),
                    $this->escapeHtml($row['adresseR2L2'])
                ]));
        ?>
                <tr
					class="<?= $this->cycle(['even', 'odd'])->next(); ?>">
					<td><?= $this->escapeHtml($row['nom'] . ' ' . $row['prenom']);?></td>
					<td>
						<?= $this->escapeHtml($row['etablissement']);?> -
						<?= $this->escapeHtml($row['lacommuneEtablissement']);?></td>
					<td><?= $adresseR1;?></td>
					<td><?= $this->escapeHtml($row['communeR1']);?></td>
					<td><?= $row['distanceR1'];?></td>
					<td><?= $adresseR2;?></td>
					<td><?= $this->escapeHtml($row['communeR2']);?></td>
					<td><?= $row['distanceR2'];?></td>
					<td><?= $this->listeLigneActions($row['numero'], $hiddens, $buttons);?></td>
				</tr>
<?php endforeach;?>
		   </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
<?php else :?>
    <div id="liste-inner">
		<i>Il n'y a pas de demande non localisée.</i>
	</div>
	<div id="liste-footer"></div>
<?php endif;?>
</div>