<?php
/**
 * Page de localisation du domicile du 2e responsable en cas de garde alternée (inscriptions en ligne)
 *
 * Présente une carte et les boutons enregistrer ou abandonner
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource ga-localisation-bymap.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 27 avr. 2015
 * @version 2015-1
 */
// mise en place des JS de googleMaps
$this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=false');
$this->headScript()->captureStart();?>
var marker;
function initialiser() {
    var latlng = new google.maps.LatLng(<?php echo $this->config['centre']['lat'];?>, <?php echo $this->config['centre']['lng'];?>);
    // initialisation des paramètres de la carte
    var options = {
        center: latlng,
        zoom: <?php echo $this->config['zoom'];?>,
        //mapTypeId: google.maps.MapTypeId.ROADMAP
        mapTypeId: "OSM",
        mapTypeControl: true,
        mapTypeControlOptions: {
            mapTypeIds: [
                "OSM",
                //google.maps.MapTypeId.ROADMAP, 
                //google.maps.MapTypeId.SATELLITE, 
                google.maps.MapTypeId.HYBRID, 
                google.maps.MapTypeId.TERRAIN
            ],
            style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        streetViewControl: true
    };
    var carte = new google.maps.Map(document.getElementById('carte-inner'), options);
    // define OSM map type pointing at the OpenStreetMap tile server
    carte.mapTypes.set("OSM", new google.maps.ImageMapType({
        getTileUrl: function(coord, zoom) {
            return "http://tile.openstreetmap.org/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
        },
        tileSize: new google.maps.Size(256,256),
        name: "OpenStreetMap",
        maxZoom: 18,
        opacity: 1,
        alt: "Carte OpenStreetMap"
    }));
    // initialisation du marker
    var optionsMarqueur = {
        map: carte,
        position: new google.maps.LatLng(document.getElementById('lat').value, document.getElementById('lng').value),
        title: 'domicile de l\'élève'
    }
    marker = new google.maps.Marker(optionsMarqueur);
    
    var contentMarker = "<?php echo $this->description;?>";
 
    var infoWindow = new google.maps.InfoWindow({
        content  : contentMarker,
        position : latlng
    });
    google.maps.event.addListener(marker, 'click', function() {
        infoWindow.open(carte,marker);
    });
    
    google.maps.event.addListener(carte, 'click', function(event) {
        var latlng = event.latLng;
    	document.getElementById('lat').value = latlng.lat();
    	document.getElementById('lng').value = latlng.lng();
    	if (marker) {
    	   marker.setPosition(latlng);
    	} else {
    	   var optionsMarker = {
    	       map: carte,
    	       position: new google.maps.LatLng(latlng.lat(), latlng.lng()),
    	       title: 'mon domicile'
    	   }
    	   marker = Marker(optionsMarker);
        }
    });
}

<?php 
$this->headScript()->captureEnd();
// lancement du script (sera affiché dans le layout à la fin de la page
$this->inlineScript()->captureStart(); ?>
initialiser();
<?php $this->inlineScript()->captureEnd(); ?>
<h1>Position d'un domicile sur la carte</h1>
<div id="carte-wrapper">
	<div id="carte-header" class="clearfix">
	    <div class="float-left"><ul style="margin-top:0;"><?php foreach ($this->responsable as $ligne) echo '<li>' . $ligne . '</li>'; ?></ul></div>
		<div class="float-right left-10px" style="max-width: 700px;">
			Cliquez sur la carte à l'emplacement du domicile puis cliquez
			sur le bouton <b>'Enregistrer la localisation'</b>. Utilisez le zoom pour plus de précision.<br>
			<?php echo $this->form($this->form); ?>
		</div>

</div>
	<div id="carte-inner"
		style="width: 90%; height: 500px; margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;"></div>
</div> 