<?php
/**
 * Liste des élèves en garde alternée dont le responsable N°2 n'a pas de distance calculée.
 * 
 * Cela vient souvent du fait que le responsable n°1 a saisi l'identité du responsable n°2 
 * mais qu'il n'est pas localisé sur la carte.
 * 
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource ga-localisation-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 4 fév. 2019
 * @version 2019-2.4.7
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$data = $this->paginator->getCurrentItems();

$url_retour = $this->url('sbmgestion/gestioneleve');
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Demande de transport en garde alternée</h1>
<h2>Localisation du second domicile</h2>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
<?php if ($data->count()) :?>
    <div id="liste-inner">
		<table class="data">
			<tbody>
				<tr>
					<th>Elève</th>
					<th>Etablissement scolaire</th>
					<th colspan="2">Adresse 1</th>
					<th>D1</th>
					<th colspan="2">Adresse 2</th>
					<th>D2</th>
					<th></th>
				</tr>
<?php foreach ($data as $row): ?>
<?php

        $hiddens = [
            'eleveId' => $row['eleveId'],
            'responsableId' => $row['responsable2Id'],
            'xr1' => $row['xr1'],
            'yr1' => $row['yr1'],
            'descriptionr1' => implode('<br>', 
                [
                    $row['responsable1'],
                    $row['adresseR1L1'],
                    $row['adresseR1L2'],
                    $row['communeR1']
                ]),
            'xeta' => $row['xeta'],
            'yeta' => $row['yeta'],
            'descriptioneta' => implode('<br>', 
                [
                    $row['etablissement'],
                    $row['communeEtablissement']
                ])
        ];
        /*
         * $url_distByAddr = $this->url('sbmgestion/gestioneleve', [
         * 'action' => 'ga-localisation-byaddr',
         * 'page' => $this->page
         * ]);
         */
        $url_distByMap = $this->url('sbmgestion/gestioneleve', 
            [
                'action' => 'ga-localisation-bymap',
                'page' => $this->page
            ]);
        ;
        $buttons = [
            /*
             * 'addresse' => [
             * 'class' => 'fam-book-addresses',
             * 'formaction' => $url_distByAddr,
             * 'title' => 'localisation par l\'adresse'
             * ],
             */
            'carte' => [
                'class' => 'fam-map-magnify',
                'formaction' => $url_distByMap,
                'title' => 'position sur la carte'
            ]
        ];
        ?>
                <tr
					class="<?php echo $this->cycle(['even', 'odd'])->next(); ?>">
					<td><?php echo $this->escapeHtml($row['nom'] . ' ' . $row['prenom']);?></td>
					<td><?php echo $this->escapeHtml($row['etablissement'] . ' - ' . $row['communeEtablissement']);?></td>
					<td><?php echo implode('<br>', [$this->escapeHtml($row['adresseR1L1']), $this->escapeHtml($row['adresseR1L2'])]);?></td>
					<td><?php echo $this->escapeHtml($row['communeR1']);?></td>
					<td><?php echo $row['distanceR1'];?></td>
					<td><?php echo implode('<br>', [$this->escapeHtml($row['adresseR2L1']), $this->escapeHtml($row['adresseR2L2'])]);?></td>
					<td><?php echo $this->escapeHtml($row['communeR2']);?></td>
					<td><?php echo $row['distanceR2'];?></td>
					<td><?php echo $this->listeLigneActions($row['numero'], $hiddens, $buttons);?></td>
				</tr>
<?php endforeach;?>
		   </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix">
			<?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
	</div>
<?php else :?>
    <div id="liste-inner">
		<i>Il n'y a pas de demande non localisée.</i>
	</div>
	<div id="liste-footer"></div>
<?php endif;?>
</div>