<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 * 
 * @project project_name
 * @package package_name
 * @filesource ga-localisation-liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_retour = $this->url('sbmgestion/gestioneleve');
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Demande de transport en garde alternée</h1>
<h2>Localisation du second domicile</h2>
<div id="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?php echo $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right"><?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?></div>
	</div>
<?php if (count($data)) :?>
    <div id="liste-inner">
		<table class="data">
			<tbody>
				<tr>
					<th>Elève</th>
					<th>Etablissement scolaire</th>
					<th colspan="2">Adresse 1</th>
					<th>D1</th>
					<th colspan="2">Adresse 2</th>
					<th>D2</th>
					<th></th>
				</tr>
<?php foreach ($this->data as $row): ?>
<?php

        $hiddens = [
            'eleveId' => $row['eleveId'],
            'responsableId' => $row['responsable2Id'],
            'x1' => $row['x1'],
            'y1' => $row['y1'],
            'description' => implode('<br>', 
                [
                    $row['responsable1'],
                    $row['adresseR1L1'],
                    $row['adresseR1L2'],
                    $row['communeR1']
                ])
        ];
        /*
         * $url_distByAddr = $this->url('sbmgestion/gestioneleve', [
         * 'action' => 'ga-localisation-byaddr',
         * 'page' => $this->page
         * ]);
         */
        $url_distByMap = $this->url('sbmgestion/gestioneleve', 
            [
                'action' => 'ga-localisation-bymap',
                'page' => $this->page
            ]);
        ;
        $buttons = [
            /*
             * 'addresse' => [
             * 'class' => 'fam-book-addresses',
             * 'formaction' => $url_distByAddr,
             * 'title' => 'localisation par l\'adresse'
             * ],
             */
            'carte' => [
                'class' => 'fam-map-magnify',
                'formaction' => $url_distByMap,
                'title' => 'position sur la carte'
            ]
        ];
        ?>
                <tr
					class="<?php echo $this->cycle(['even', 'odd'])->next(); ?>">
					<td><?php echo $this->escapeHtml($row['nom'] . ' ' . $row['prenom']);?></td>
					<td><?php echo $this->escapeHtml($row['etablissement'] . ' - ' . $row['communeEtablissement']);?></td>
					<td><?php echo implode('<br>', [$this->escapeHtml($row['adresseR1L1']), $this->escapeHtml($row['adresseR1L2'])]);?></td>
					<td><?php echo $this->escapeHtml($row['communeR1']);?></td>
					<td><?php echo $row['distanceR1'];?></td>
					<td><?php echo implode('<br>', [$this->escapeHtml($row['adresseR2L1']), $this->escapeHtml($row['adresseR2L2'])]);?></td>
					<td><?php echo $this->escapeHtml($row['communeR2']);?></td>
					<td><?php echo $row['distanceR2'];?></td>
					<td><?php echo $this->listeLigneActions($row['numero'], $hiddens, $buttons);?></td>
				</tr>
<?php endforeach;?>
		   </tbody>
		</table>
	</div>
	<div id="liste-footer"></div>
<?php else :?>
    <div id="liste-inner">
		<i>Il n'y a pas de demande non localisée.</i>
	</div>
	<div id="liste-footer"></div>
<?php endif;?>
</div>
<p>
	<i>Il faut rajouter un paginateur</i>
</p>