<?php
/**
 * Page d'accueil de l'espace de gestion des élèves
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 avr. 2018
 * @version 2018-2.4.0
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_non_affectes = $this->url('sbmgestion/gestioneleve', [
    'action' => 'affecter-liste'
]);
$url_ga_localisation = $this->url('sbmgestion/gestioneleve',
    [
        'action' => 'ga-localisation-liste'
    ]);
$retour = $this->url('sbmgestion/eleve', [
    'action' => 'eleve-liste'
]);
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ]
];
?>
<h1>Gestion des élèves</h1>
<div id="menugeneral-wrapper">
	<div id="menugeneral-header" class="clearfix">
		<div class="menu float-left">
<?=$this->listeZoneActions(['op' => 'retour'], $actions);?>
        </div>
		<div class="flashMessenger float-right">
			<?= $this->flashMessenger()->render('success');?>
			<?= $this->flashMessenger()->render('warning');?>
			<?= $this->flashMessenger()->render('error');?>
			<?= $this->flashMessenger()->render('info');?>
			<?= $this->flashMessenger()->render('default');?>
        </div>
	</div>
	<div id="menugeneral-inner">
		<ul>
			<li><a href="<?= $url_non_affectes; ?>"><i class="fam-bullet-go"></i>Traitement
					des élèves non affectés</a></li>
			<li><a href="<?= $url_ga_localisation;?>"><i class="fam-bullet-go"></i>Localisation
					de la seconde adresse des élèves en garde alternée</a></li>
		</ul>
	</div>
</div>