<?php
/**
 * Page de modification de l'inscription d'un invité
 *
 * Cette vue reçoit les variables suivantes :
 * - form
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource invite-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 10 juin 2021
 * @version 2021-2.6.2
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/eleve-gestion', 'invite.css');
$this->jQuery([
    'jquery-ui'
]);
$this->themeJs('gestion-eleve', 'invite.js');
$this->inlineScript()->captureStart();
?>

$(function() {
	$("#tabs").tabs({active: <?=$this->form->getEtat() == -1 ? 1 : $this->form->getEtat() - 1;?>});
    js_invite.init(<?=$this->inviteId;?>);
	js_invite.montreOnglet(<?=$this->form->getEtat();?>);
});
<?php
$this->inlineScript()->captureEnd();
$js = 'window.document.getElementById(\'op\').value=%s;';
$this->inlineScript()->captureStart();
?>
<?php
$this->inlineScript()->captureEnd();
$url_retour = $this->url('sbmgestion/gestioneleve', [
    'action' => 'invite'
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'une demande de PASS PROVISOIRE</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
			<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
	</div>
	<div id="fiche-inner">
	    <?=$this->form()->openTag($this->form);?>
        <?=$this->formHidden($this->form->get('inviteId'));?>
        <?=$this->formHidden($this->form->get('millesime'));?>
        <?=$this->formHidden($this->form->get('csrf'));?>

        <?php
        switch ($this->form->getEtat()) {
            case 1:
                $hiddens = [
                    'nom' => null,
                    'prenom' => null,
                    'sexe' => null,
                    'nationalite' => null,
                    'responsableId' => null,
                    'organismeId' => null
                ];
                break;
            case 2:
                $hiddens = [
                    'chez' => '',
                    'adresseL1' => '',
                    'adresseL2' => '',
                    'adresseL3' => '',
                    'codePostal' => '',
                    'communeId' => '',
                    'etablissementId' => '',
                    'stationId' => - 1,
                    'responsableId' => - 1,
                    'organismeId' => - 1,
                    'servicesMatin' => '',
                    'servicesMidi' => '',
                    'servicesSoir' => '',
                    'servicesMerSoir' => ''
                ];
                break;
            case 3:
                $hiddens = [
                    'chez' => null,
                    'adresseL1' => null,
                    'adresseL2' => null,
                    'adresseL3' => null,
                    'codePostal' => null,
                    'communeId' => null,
                    'etablissementId' => null,
                    'stationId' => null,
                    'eleveId' => null,
                    'organismeId' => null
                ];
                break;
            case 4:
                $hiddens = [
                    'chez' => null,
                    'adresseL1' => null,
                    'adresseL2' => null,
                    'adresseL3' => null,
                    'codePostal' => null,
                    'communeId' => null,
                    'etablissementId' => null,
                    'stationId' => null,
                    'eleveId' => null,
                    'responsableId' => null
                ];
                break;
            case 5:
                $hiddens = [
                    'eleveId' => null,
                    'responsableId' => null,
                    'organismeId' => null
                ];
                break;
            default:
                break;
        }
        ?>
		<fieldset class="sbm-page1 label-180">
			<p>Choisissez l'onglet correspondant à la situation du bénéficiaire.</p>
			<div id="tabs">
				<ul>
					<li><a href="#onglet1">Élève déjà inscrit ayant<br>besoin d'un
							déplacement<br>sur d'autres itinéraires
					</a></li>
					<li><a href="#onglet2">Bénéficiaire rattaché à un élève<br>déjà
							inscrit et affecté sur les<br>mêmes itinéraires que l'élève
					</a></li>
					<li><a href="#onglet3">Bénéficiaire hébergé chez un<br>responsable
							déjà inscrit mais<br>avec des itinéraires spécifiques
					</a></li>
					<li class="centre"><a href="#onglet4">Bénéficiaire dépendant<br>d'un<br>organisme
							d'accueil
					</a></li>
					<li><a href="#onglet5">&nbsp;<br>Autres cas<br>&nbsp;
					</a></li>
				</ul>
				<div id="onglet1"></div>
				<div id="onglet2"></div>
				<div id="onglet3"></div>
				<div id="onglet4"></div>
				<div id="onglet5"></div>
				</ul>
			</div>
			<div id="wrapper-motifDemande" class="row-inner edit">
			    <?=$this->formRow($this->form->get('motifDemande'));?></div>
			<div class="validite clearfix">
				<div id="wrapper-dateDebut" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('dateDebut'));?></div>
				<div id="wrapper-dateFin" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('dateFin'));?></div>
			</div>
			<div id="wrapper-demande" class="clearfix">
				<div id="inner-demande" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('demande'));?></div>
				<div id="inner-motifRefus" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('motifRefus'));?></div>
			</div>
			<div id="wrapper-commentaire" class="row-inner edit">
			    <?=$this->formRow($this->form->get('commentaire'));?></div>
			<div id="wrapper-buttons" class="row-inner edit boutons">
        		<?=$this->formSubmit($this->form->get('submit'));?>
                <?=$this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?=$this->form()->closeTag();?>
	</div>
	<div id="fiche-footer"></div>
</div>