<?php
/**
 * Page de modification de l'inscription d'un invité
 *
 * Cette vue reçoit les variables suivantes :
 * - form
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/eleve-gestion
 * @filesource invite-edit.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 avr. 2021
 * @version 2021-2.6.1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->themeCss('sbm-gestion/eleve-gestion', 'invite.css');
$this->jQuery();
$this->themeJs('gestion-eleve', 'invite.js');
$js = 'window.document.getElementById(\'op\').value=%s;';
$url_retour = $this->url('sbmgestion/gestioneleve', [
    'action' => 'invite'
]);
$hiddens = [];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $url_retour,
        'title' => 'Retour',
        'onclick' => sprintf($js, "'retour'")
    ]
];
?>
<h1>Modification d'une demande de PASS PROVISOIRE</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<div class="menu clearfix">
			<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		</div>
	</div>
	<div id="fiche-inner">
	<?=$this->form()->openTag($this->form);?>
        <?=$this->formHidden($this->form->get('inviteId'));?>
        <?=$this->formHidden($this->form->get('millesime'));?>
        <?=$this->formHidden($this->form->get('eleveId'));?>
        <?=$this->formHidden($this->form->get('gratuit'));?>
        <?=$this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1 label-180">
			<div id="wrapper-nom" class="row-inner edit">
			    <?=$this->formRow($this->form->get('nom'));?></div>
			<div id="wrapper-prenom" class="row-inner edit">
			    <?=$this->formRow($this->form->get('prenom'));?></div>
			<div id="wrapper-sexe" class="clearfix">
				<div id="inner-sexe" class="row-inner ajout float-left">
			    <?=$this->formRow($this->form->get('sexe'));?></div>
			</div>
			<div id="wrapper-nationalite" class="row-inner edit">
			    <?=$this->formRow($this->form->get('nationalite'));?></div>
			<div id="wrapper-identifiantSejour" class="row-inner edit">
			    <?=$this->formRow($this->form->get('identifiantSejour'));?></div>
			<div id="wrapper-dateDebut" class="row-inner edit">
			    <?=$this->formRow($this->form->get('dateDebut'));?></div>
			<div id="wrapper-dateFin" class="row-inner edit">
			    <?=$this->formRow($this->form->get('dateFin'));?></div>
			<div id="wrapper-demande" class="clearfix">
				<div id="inner-demande" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('demande'));?></div>
				<div id="inner-motifRefus" class="row-inner edit float-left">
			    <?=$this->formRow($this->form->get('motifRefus'));?></div>
			</div>
			<div id="wrapper-commentaire" class="row-inner edit">
			    <?=$this->formRow($this->form->get('commentaire'));?></div>
			<div id="wrapper-buttons" class="row-inner edit boutons">
        		<?=$this->formSubmit($this->form->get('submit'));?>
                <?=$this->formSubmit($this->form->get('cancel'));?></div>
		</fieldset>
		<?=$this->form()->closeTag();?>
	</div>
	<div id="fiche-footer"></div>
</div>