<?php
/**
 * Liste des paiements pour la table `systempay`
 *
 * @project sbm
 * @package SbmPaiement/Plugin/SystemPay/view
 * @filesource liste.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 fév. 2019
 * @version 2019-2.5.0
 */
use Zend\View\Model\ViewModel;

/**
 *
 * @param string $date
 */
function formatDate($date)
{
    return \DateTime::createFromFormat('YmdHis', $date)->format('d/m/Y H:i:s');
}

/**
 *
 * @param ViewModel $view
 * @param string $name
 * @param string $id
 * @param boolean $value
 *            0 ou 1
 */
function renderCheckbox($view, $name, $id, $value)
{
    $element = new \Zend\Form\Element\Checkbox($name);
    $element->setUseHiddenElement(false)
        ->setAttribute('id', $id)
        ->setValue($value);
    return $view->formCheckbox($element);
}
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));
$this->jQuery();
$jsCallback = '';
$jsTrigger = '';
// modèle de jsCallback pour selection
$modele = <<<EOT
$("#chk%d").change(function() {
    var action = ($(this).is(':checked'))?'check':'uncheck';
    $.ajax({
				url : '/sbmajaxfinance/'+action+'selectionnotification/id:%d',
				success : function(data) {},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
  });
EOT;

$this->paginator->setDefaultItemCountPerPage($this->count_per_page);
$this->paginator->setCurrentPageNumber($this->page);
$datas = $this->paginator->getCurrentItems();
$url_rapports = $this->url('sbmpaiement', [
    'action' => 'pdf',
    'page' => $this->page
]);
$url_rapprochement = $this->url('sbmpaiement',
    [
        'action' => 'rapprochement',
        'page' => $this->page
    ]);
$url_voir = $this->url('sbmpaiement', [
    'action' => 'voir',
    'page' => $this->page
]);
$config = include __DIR__ . '/../config/systempay.config.php';
$url_marchand = $config['url_marchand'];
$retour = $this->url('sbmgestion/finance');
$hiddens = [
    'origine' => 'liste'
];
$menuImpression = $this->menuRapports('/paiement/liste', $url_rapports, 'fam-printer',
    null, $hiddens);
$hiddens = $menuImpression['hiddens'];
$actions = [
    'retour' => [
        'class' => 'fam-door-out',
        'formaction' => $retour,
        'title' => 'Retour'
    ],
    'rapports' => $menuImpression['content'],
    'systempay' => [
        'class' => 'fam-house-link',
        'formaction' => $url_marchand,
        'title' => 'Systempay Back Office',
        'formtarget' => '_blank'
    ],
    'rapprochement' => [
        'class' => 'fam-plugin-error',
        'formaction' => $url_rapprochement,
        'title' => 'Rapprochement avec les encaissements de Systempay Back Office'
    ]
];
$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<h1>Liste des notifications de paiement</h1>
<div class="liste-wrapper">
	<div id="liste-header" class="clearfix">
		<div class="menu float-left"><?= $this->listeZoneActions($hiddens, $actions);?></div>
		<div class="flashMessenger float-right">
		<?= $this->flashMessenger()->render('success');?>
		<?= $this->flashMessenger()->render('warning');?>
		<?= $this->flashMessenger()->render('error');?>
		<?= $this->flashMessenger()->render('info');?>
		<?= $this->flashMessenger()->render('default');?>
		</div>
	</div>
	<div id="liste-inner">
		<table class="notifications">
			<tbody>
				<tr>
					<th>Prénom Nom</th>
					<th>Email</th>
					<th>Date</th>
					<th>Id</th>
					<th>Statut</th>
					<th>Autorisation</th>
					<th>Montant</th>
					<th>Sélect.</th>
					<th></th>
				</tr>
            <?php foreach($datas as $notification): ?>
            <?php
                $montant = $fmt->formatCurrency($notification->vads_amount / 100, 'EUR');
                $date_trans = formatDate($notification->vads_trans_date);
                $title_voir = <<<EOT
Mode : $notification->vads_ctx_mode
Type d'opération : $notification->vads_operation_type
Date de la transaction : $date_trans
Référence de la transaction : $notification->vads_trans_id
Statut de la transaction : $notification->vads_trans_status
Résultat de la transaction : $notification->vads_result
Complément du résultat : $notification->vads_extra_result
Réponse de la banque : $notification->vads_auth_result
Autorisation n° : $notification->vads_auth_number
Email : $notification->vads_cust_email
Référence du responsable : $notification->vads_cust_id
Nom du responsable : $notification->vads_cust_name
Référence de la commande : $notification->vads_order_id
Référence des élèves concernés : $notification->ref_eleveIds
Certificat de paiement : $notification->vads_payment_certificate
Configuration du paiement : $notification->vads_payment_config
Erreur retournée : $notification->vads_payment_error
Numéro de l'échéance : $notification->vads_sequence_number
Délai de remise : $notification->vads_capture_delay
Montant : $montant
Monnaie : $notification->vads_currency
Carte enrôlée 3DSecure : $notification->vads_threeds_enrolled
Statut 3DSecure : $notification->vads_threeds_status
Carte bancaire : $notification->vads_card_brand
Pays origine de la carte bancaire : $notification->vads_card_country
Numéro de la carte : $notification->vads_card_number
Date d'expiration de la carte : $notification->vads_expiry_month/$notification->vads_expiry_year
Code de la banque : $notification->vads_expiry_year
Code du produit de paiement : $notification->vads_bank_product
EOT;
                $hiddens = [
                    'notificationId' => $notification->systempayId
                ];
                $buttons = [
                    'voir' => [
                        'class' => 'fam-zoom',
                        'formaction' => $url_voir,
                        'title' => $title_voir
                    ]
                ];
                // construction des JS pour selection
                $jsTrigger .= sprintf("$('#chk%d').trigger('change');\n",
                    $notification->systempayId);
                $jsCallback .= sprintf("$modele\n", $notification->systempayId,
                    $notification->systempayId);
                ?>
                <tr class="<?= $this->cycle(["even", "odd"])->next();?>">
					<td class="vads_cust_name">
						<?= $this->escapeHtml($notification->vads_cust_name); ?></td>
					<td class="vads_cust_email">
						<?= $this->escapeHtml($notification->vads_cust_email); ?></td>
					<td class="vads_trans_date">
						<?= $date_trans; ?></td>
					<td class="vads_trans_id">
						<?= $this->escapeHtml($notification->vads_trans_id); ?></td>
					<td class="vads_trans_status">
						<?= $this->escapeHtml($notification->vads_trans_status); ?></td>
					<td class="vads_auth_number">
						<?= $this->escapeHtml($notification->vads_auth_number); ?></td>
					<td class="vads_amount">
						<?= $montant; ?></td>
					<td class="centre selection">
						<?= renderCheckbox($this, 'selection', 'chk' . $notification->systempayId, $notification->selection)?></td>
					<td class="boutons">
            			<?= $this->listeLigneActions($notification->systempayId, $hiddens, $buttons);?></td>
				</tr>         
            <?php endforeach;?>
            </tbody>
		</table>
	</div>
	<div id="liste-footer">
		<div class="pagination-wrapper clearfix"><?= $this->paginationControl($this->paginator, 'Sliding', 'sbm/pagination', []); ?></div>
		<div class="criteres-wrapper">
	    <?= $this->form()->openTag($this->criteres_form);?>
	    <?= $this->formCollection($this->criteres_form, true);?>
	    <?= $this->form()->closeTag();?>
        </div>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
$(function() {
function triggerChange() {
	<?= $jsTrigger;?>}
	<?= $jsCallback;?>
});
<?php
$this->headScript()->captureEnd();