<?php
// Generated by Zend Framework 2
return array(
    'SbmPortail\Module'                                    => __DIR__ . '/Module.php',
    'SbmPortail\Controller\IndexController'                => __DIR__ . '/src/SbmPortail/Controller/IndexController.php',
    'SbmPortail\Controller\Service\IndexControllerFactory' => __DIR__ . '/src/SbmPortail/Controller/Service/IndexControllerFactory.php',
    'SbmPortail\Form\CriteresForm'                         => __DIR__ . '/src/SbmPortail/Form/CriteresForm.php',
    'SbmPortail\Model\Db\ObjectData\Criteres'              => __DIR__ . '/src/SbmPortail/Model/Db/ObjectData/Criteres.php',
);