<?php
/**
 * Page d'accueil du portail pour les établissements
 *
 * Les variables définies dans cette vue sont :
 * - data : tableau associatif décrit ci-dessous
 * - etablissements : nom d'un (ou des) établissement(s)
 *
 * Description du tableau data
 * - etablissementId => tableau des statistiques pour cet établissement
 *
 * Contenu d'un tableau de statistiques :
 * - 'etablissement' => $lacommune_etablissement,
 * - 'elevesDpEnregistres',
 * - 'elevesIntEnregistres',
 * - 'elevesEnregistres',
 * - 'elevesInscrits',
 * - 'elevesInscritsRayes',
 * - 'elevesGardeAlternee',
 * - 'elevesMoins1km',
 * - 'elevesDe1A3km',
 * - 'eleves3kmEtPlus'
 *
 * @project sbm
 * @package SbmPortain/view/sbm-portail/etablissement
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 14 nov. 2020
 * @version 2020-2.6.1
 */
use SbmBase\Model\StdLib;

$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

$url_eleves = $this->url('sbmportail/etablissement', [
    'action' => 'eleves'
]);
$url_circuits = $this->url('sbmportail/etablissement', [
    'action' => 'lignes'
]);
$url_carte_stations = $this->url('sbmportail/etablissement',
    [
        'action' => 'carte-stations'
    ]);
$url_carte_etablissements = $this->url('sbmportail/etablissement',
    [
        'action' => 'carte-etablissements'
    ]);
?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
		<?=$this->flashMessenger()->render('success');?>
		<?=$this->flashMessenger()->render('warning');?>
		<?=$this->flashMessenger()->render('error');?>
		<?=$this->flashMessenger()->render('info');?>
		<?=$this->flashMessenger()->render('default');?>
    </div>
	<h1>Portail des établissements : <?=$this->etablissements;?></h1>
	<div class="float-left">
		<h2>Quelques chiffres</h2>
		<?php foreach($this->data as $etablissement):?>
		<?php
    $elevesEnregistres = StdLib::getParam('elevesEnregistres', $etablissement, 0) ?: 0;
    $nbInternes = StdLib::getParam('elevesIntEnregistres', $etablissement, 0);
    $elevesMoins1km = StdLib::getParam('elevesMoins1km', $etablissement, 0) ?: 0;
    $elevesDe1A3km = StdLib::getParam('elevesDe1A3km', $etablissement, 0) ?: 0;
    $eleves3kmEtPlus = StdLib::getParam('eleves3kmEtPlus', $etablissement, 0) ?: 0;
    $nbDistanceInconnue = $elevesEnregistres - $elevesMoins1km - $elevesDe1A3km -
        $eleves3kmEtPlus;
    ?>
		<?php if (count($this->data) > 1 && array_key_exists('etablissement', $etablissement)):?>
		<h3><?=$etablissement['etablissement']?></h3>
		<?php endif;?><div class="bleu float-left" style="max-width: 300px;">
			<table>
				<tbody>
					<tr>
						<td>Nombre d'élèves enregistrés</td>
						<td class="effectif"><?=$elevesEnregistres;?></td>
					</tr>
					<tr>
						<td class="align-right">
					dont <?=StdLib::getParam('elevesDpEnregistres', $etablissement, 0);?> DP</td>
						<td></td>
					</tr>
					<tr>
						<td class="align-right">
					et <?=$nbInternes;?> interne<?=$nbInternes > 1 ? 's' : '';?></td>
						<td></td>
					</tr>
					<tr>
						<td>Nombre d'abonnements délivrés</td>
						<td class="effectif"><?=StdLib::getParam('elevesInscrits',$etablissement, 0);?></td>
					</tr>
					<tr class="separateur">
						<td class="align-right">
						dont <?= StdLib::getParam('elevesInscritsRayes',$etablissement, 0);?>
						abonnements rayés</td>
						<td></td>
					</tr>
					<tr>
						<td>Nombre d'élèves à moins de 1 km</td>
						<td class="effectif"><?=$elevesMoins1km;?></td>
					</tr>
					<tr>
						<td>Nombre d'élèves de 1 à 3 km</td>
						<td class="effectif"><?=$elevesDe1A3km;?></td>
					</tr>
					<tr class="separateur">
						<td>Nombre d'élèves à 3 km et plus</td>
						<td class="effectif"><?=$eleves3kmEtPlus;?></td>
					</tr>
					<tr class="separateur">
						<td>Nombre d'élèves non géolocalisés</td>
						<td class="effectif"><?= $nbDistanceInconnue;?></td>
					</tr>
					<tr>
						<td>Nombre d'élèves en garde alternée</td>
						<td class="effectif"><?=StdLib::getParam('elevesGardeAlternee',$etablissement, 0);?></td>
					</tr>
				</tbody>
			</table>
		<?php endforeach;?>
		<p class="sbm-description">L'écart entre le nombre d'élèves
				enregistrés et le nombre d'abonnements délivrés s'explique par
				l'impossibilité de répondre à la demande ou le non paiement de
				l'abonnement.</p>
		</div>
	</div>
	<div id="menugeneral" class="float-right" style="min-width: 306px;">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?=$url_eleves;?>"><i class="fam-bullet-go"></i>Liste
						des élèves</a></li>
				<li><a href="<?=$url_circuits;?>"><i class="fam-bullet-go"></i>Circuits
						et horaires</a></li>
				<li><a href="<?=$url_carte_stations;?>"><i class="fam-bullet-go"></i>Points
						d'arrêts desservant l'établissement</a></li>
				<li><a href="<?=$url_carte_etablissements;?>"><i
						class="fam-bullet-go"></i>Établissements scolaires</a></li>
			</ul>
		</div>
	</div>
</div>