<?php
/**
 * Affichage des horaires d'un circuit pour un élève qui y est affecté
 *
 * (Modèle fourni par l'organisateur)
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/index
 * @filesource horaires.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 29 avr. 2019
 * @version 2019-2.5.0
 */
$this->themeCss('sbm-parent/index', 'horaires.css');
$url_retour = $this->url('sbmparent');
$url_horaires = $this->url('sbmdocument', [
    'action' => 'horaires'
]);
$h3contentG = [];
$h3contentD = [];
$aller = [];
$retour = [];
$data = [];
foreach ($this->circuits as $obj) {
    $data[$obj->circuitId] = $obj;
}
$data = array_values($data);
$nbCircuits = count($data);
for ($i = 0; $i < $nbCircuits; $i ++) {
    if ($i < $nbCircuits) { // sans doublons
        $h3contentG[$data[$i]->serviceId] = 'Circuit n° ' . $data[$i]->serviceId .
            ' - car ' . $data[$i]->transporteur;
        $h3contentD[$data[$i]->transporteurId] = 'Tél. ' . $data[$i]->transporteur . ' : ' .
            $this->telephone($data[$i]->telephoneTransporteur);
    }
    $aller[$i] = [
        $data[$i]->m1,
        $data[$i]->station,
        $data[$i]->typeArret,
        empty($this->t_nb_inscrits[$i]) ? '' : $this->t_nb_inscrits[$i],
        empty($this->t_nb_inscrits[$i]) ? '' : '(voir tableau ci-dessous)',
        $data[$i]->commentaire1
    ];
}
for ($j = 0, $i = $nbCircuits - 1; $i >= 0; $i --, $j ++) {
    $retour[$j] = [
        $data[$i]->s2 . '<br>' . $data[$i]->s1,
        $data[$i]->station,
        $data[$i]->typeArret,
        empty($this->t_nb_inscrits[$i]) ? '' : $this->t_nb_inscrits[$i],
        empty($this->eleves[$i]) ? '' : implode('<br>', $this->eleves[$i]),
        $data[$i]->commentaire2
    ];
}
?>
<div id="fiche-wrapper" class="parent horaires">
	<h1>Transport de <?=$this->enfant;?></h1>
	<div id="fiche-header">
		<div class="clearfix">
			<div class="float-left">
				<h3>Horaires théoriques donnés à titre indicatif</h3>
			</div>
			<div class="float-right">
				<p class="sbm-description">Les horaires peuvent être légèrement
					revus dès la 1ère semaine de la rentrée.</p>
				<p class="important">Merci d'être présent 5 minutes avant le passage
					du car.</p>
			</div>
		</div>
		<div class="clearfix">
			<h3 class="float-left"><?=implode('<br>', $h3contentG);?></h3>
			<h3 class="float-right"><?=implode('<br>', $h3contentD);?></h3>
		</div>
	</div>
	<div id=fiche-inner>
		<fieldset class="sbm-page1">
			<legend>Matin</legend>
			<table>
				<tbody>
					<tr>
						<th>Horaire</th>
						<th>Nom de l'arrêt</th>
						<th>Emplacement</th>
						<th>Nbre<br>élèves
						</th>
						<th>Nom des élèves</th>
						<th>Remarques</th>
					</tr>
	                <?php for ($i = 0; $i < count($data); $i ++) :?>
	                <?php
                    $css = $this->cycle([
                        'odd',
                        'even'
                    ])->next();
                    ?>
	                <tr class="<?=$css;?>">
						<td><?=implode('</td><td>', $aller[$i]);?></td>
					</tr>
	                <?php endfor;?>
				</tbody>
			</table>
		</fieldset>
		<p></p>
		<fieldset class="sbm-page1">
			<legend>Mercredi midi &amp; soir</legend>
			<table>
				<tbody>
					<tr>
						<th>Horaire</th>
						<th>Nom de l'arrêt</th>
						<th>Emplacement</th>
						<th>Nbre<br>élèves
						</th>
						<th>Nom des élèves</th>
						<th>Remarques</th>
					</tr>
	                <?php for ($i = 0; $i < count($data); $i ++) :?>
	                <?php
                    $css = $this->cycle([
                        'odd',
                        'even'
                    ])->next();
                    ?>
	                <tr class="<?=$css;?>">
						<td><?=implode('</td><td>', $retour[$i]);?></td>
					</tr>
	                <?php endfor;?>
				</tbody>
			</table>
		</fieldset>
		<div class="left-95px top-6px">
			<form method="post" action="<?=$url_retour;?>">
				<input type="submit" class="default" name="horaires"
					value="Imprimer" formaction="<?=$url_horaires;?>"
					formtarget="_blank"> <input type="submit" class="default"
					name="cancel" value="Retour">
			</form>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>