<?php
/**
 * Affichage des horaires d'un circuit pour un élève qui y est affecté
 *
 * (Modèle fourni par l'organisateur)
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/index
 * @filesource horaires.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 26 avr. 2021
 * @version 2021-2.6.1
 */
$this->themeCss('sbm-parent/index', 'horaires.css');
$url_retour = $this->url('sbmparent');
$url_horaires = $this->url('sbmdocument', [
    'action' => 'horaires'
]);
$nomenclatureMoments = [
    1 => 'Aller Matin',
    3 => 'Retour Soir',
    2 => 'Retour Midi',
    4 => 'Aller Après-midi',
    5 => 'Aller Dimanche soir'
];
$h3contentG = [];
$h3contentD = [];
$data = [];
foreach ($this->lignes as $ligne) {
    $h3contentG[$ligne['moment']][] = sprintf('%s : Ligne %s',
        $nomenclatureMoments[$ligne['moment']], $ligne['ligneId']);
    $h3contentD[$ligne['moment']][] = sprintf('%s - %s', $ligne['ligneExtremite1'],
        $ligne['ligneExtremite2']);
}
foreach ($this->circuits as $circuit) {
    $array = $circuit->getArrayCopy();
    unset($array['moment']);
    $data[$circuit['moment']][] = $array;
}
?>
<div id="fiche-wrapper" class="parent horaires">
	<h1>Transport de <?=$this->enfant;?></h1>
	<div id="fiche-header">
		<div class="clearfix">
			<div class="float-left">
				<h3>Horaires théoriques donnés à titre indicatif</h3>
			</div>
			<div class="float-right">
				<p class="sbm-description">Les horaires peuvent être légèrement
					revus dès la 1ère semaine de la rentrée.</p>
				<p class="important">Merci d'être présent 5 minutes avant l'horaire
					indiqué.</p>
			</div>
		</div>
	</div>
	<div id=fiche-inner>
<?php foreach ($nomenclatureMoments as $moment => $legend):?>
    <?php if (array_key_exists($moment, $data) && count($data[$moment])):?>
		<fieldset class="sbm-page1">
			<legend><?=$legend;?></legend>
			<div class="clearfix">
				<h3 class="float-left"><?=implode('<br>', $h3contentG[$moment]);?></h3>
				<h3 class="float-right"><?=implode('<br>', $h3contentD[$moment]);?></h3>
			</div>
			<table>
				<tbody>
					<tr>
						<th>Point de montée</th>
						<th>Commune</th>
						<th>Horaire</th>
						<th>Point de descente</th>
						<th>Commune</th>
						<th>Horaire</th>
					</tr>
	                <?php foreach($data[$moment] as $circuit) :?>
	                <?php
            $css = $this->cycle([
                'odd',
                'even'
            ])->next();
            ?>
	                <tr class="<?=$css;?>">
						<td><?=implode('</td><td>', $circuit);?></td>
					</tr>
	                <?php endforeach;?>
				</tbody>
			</table>
		</fieldset>
	<?php endif;?>
<?php endforeach;?>
		<div class="left-95px top-6px">
			<form method="post" action="<?=$url_retour;?>">
				<input type="submit" class="default" name="horaires"
					value="Télécharger" formaction="<?=$url_horaires;?>"
					formtarget="_blank"> <input type="submit" class="default"
					name="cancel" value="Retour">
			</form>
		</div>
	</div>
	<div id="fiche-footer"></div>
</div>