<?php
/**
 * Page d'inscription d'un élève pour les parents.
 *
 * L'élève est créé et sa scolarité est mise à jour. Il restera à saisir l'identité et l'adresse du second parent en cas de garde alternée.
 *
 * Attention !!!
 * Vérifier en cas de mise en forme que le js n'a pas changé lignes 28 et 67
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/index
 * @filesource inscription-eleve.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 05 jan. 2020
 * @version 2020-2.6.0
 */
$this->themeCss('sbm-parent/index', 'edit.css');
$this->jQuery('jquery-ui');
$this->themeJS('sbm-parent','edit-eleve.js');
$texteDemandeR2 = <<<EOT
Si cette deuxième adresse est dans le ressort territorial, une deuxième carte
de transport sera attribuée. Sinon, vous devez faire une demande auprès du
service régional des transports de l’Aveyron à l’adresse :
EOT;
$texteDemandeR2 = preg_replace('/\s/', ' ', $texteDemandeR2) . ' ' . $this->url_ts_region;
$this->headScript()->captureStart();
?>
texteDemandeR2 = "<?=$texteDemandeR2;?>";
<?php
$this->headScript()->captureEnd();
// préparation du signalement d'erreur sur le sexe
$elementErrorsHelper = new \Zend\Form\View\Helper\FormElementErrors();
$elementError = $elementErrorsHelper->render($this->form->get('sexe'));
if (!empty($elementError)) {
    $this->form->get('sexe')->setAttribute('class', 'input-error');
}
//----- suite -----------
$identiteResponsable = sprintf('%s %s %s', $this->responsable->titre,
    $this->responsable->nom, $this->responsable->prenom);
?>
<h1>Inscription d'un enfant</h1>
<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-content">
		<?=$this->form()->openTag($this->form);?>
		<?=$this->formHidden($this->form->get('eleveId'));?>
		<?=$this->formHidden($this->form->get('responsable1Id'));?>
		<?=$this->formHidden($this->form->get('csrf'));?>
    	<fieldset class="sbm-page1">
			<div class="table2cols">
				<div class="zone col1">
					<div id="enfant-nom" class="row-inner">
				        <?=$this->formRow($this->form->get('nom'));?></div>
					<div id="enfant-prenom" class="row-inner">
					   <?=$this->formRow($this->form->get('prenom'));?></div>
					<div class="table2cols">
						<div id="enfant-dateN" class="row-inner zone col11">
					   		<?=$this->formRowDate($this->form->get('dateN'));?></div>
						<div id="enfant-sexe" class="row-inner zone col12">
					    	<?=$this->formSelect($this->form->get('sexe'));?>
					    	<?=$elementError;?></div>
					</div>
					<div id="z3cg-r1" class="bloc-wrapper">
						<fieldset>
							<div>
								<div class="label-enfant">Responsable</div>
                    				<?=$identiteResponsable;?></div>
							<div>
								<div class="label-enfant">Adresse</div>
                    				<?=$this->responsable->adresseL1;?></div>
							<div>
								<div class="label-enfant">Adresse</div>
                    				<?=$this->responsable->adresseL2;?></div>
							<div>
								<div class="label-enfant">Adresse</div>
                    				<?=$this->responsable->adresseL3;?></div>
							<div>
								<div class="label-enfant">Commune</div>
                    				<?=$this->responsable->codePostal;?>
                    				<?=$this->responsable->commune;?>
                    		</div>
						</fieldset>
					</div>
					<div id="enfant_ap"></div>
					<div id="wrapper-radio-col1" class="table2cols">
						<div id="wrapper-joursTransportR1"
							class="row-inner bloc-wrapper zone col13">
                		<?=$this->formRow($this->form->get('joursTransportR1'));?></div>
						<div id="wrapper-fa" class="bloc-wrapper zone">
						<?=$this->formRow($this->form->get('fa'));?></div>
					</div>
				</div>
				<div class="zone col2">
					<div id="enfant-etablissementId" class="row-inner">
					   <?=$this->formRow($this->form->get('etablissementId'));?></div>
					<div class="table2cols">
						<div class="zone col21">
							<div id="enfant-classeId" class="row-inner">
					   		<?=$this->formRow($this->form->get('classeId'));?></div>
							<div id="wrapper-radio-col2" class="table2cols">
								<div id="wrapper-regimeId"
									class="row-inner bloc-wrapper zone fit-content">
					   			<?=$this->formRow($this->form->get('regimeId'));?></div>
								<div id="wrapper-ga" class="bloc-wrapper zone fit-content">
								<?=$this->formRow($this->form->get('ga'));?></div>
							</div>
						</div>
					</div>
					<div id="z3cd-r1"></div>
					<div id="enfant_ga"></div>
				</div>
			</div>
			<div id="wrapper-commentaire">
				<?=$this->formRow($this->form->get('commentaire'));?></div>
			<div id="enfant-buttons" class="row-inner">
            	<?=$this->formSubmit($this->form->get('submit'));?>
            	<?=$this->formSubmit($this->form->get('cancel'));?>
            </div>
		</fieldset>
    <?=$this->form()->closeTag();?>
    </div>
	<div id="fiche-footer"></div>
</div>
<div style="display: none;">
	<div id="content_enfant_ga">
    	<?=$this->formHidden($this->formga->get('r2responsable2Id'));?>
	    <?=$this->formHidden($this->formga->get('r2userId'));?>
    	<div id="_titre" class="row-inner">
		    <?=$this->formRow($this->formga->get('r2titre'));?></div>
		<div id="_nom" class="row-inner">
			<?=$this->formRow($this->formga->get('r2nom'));?></div>
		<div id="_prenom" class="row-inner">
			<?=$this->formRow($this->formga->get('r2prenom'));?></div>
		<div id="_adresseL1" class="row-inner">
			<?=$this->formRow($this->formga->get('r2adresseL1'));?></div>
		<div id="_adresseL2" class="row-inner">
			<?=$this->formRow($this->formga->get('r2adresseL2'));?></div>
		<div id="_adresseL3" class="row-inner">
			<?=$this->formRow($this->formga->get('r2adresseL3'));?></div>
		<div id="_codePostal" class="row-inner">
			<?=$this->formRow($this->formga->get('r2codePostal'));?></div>
		<div id="_communeId" class="row-inner">
			<?=$this->formRow($this->formga->get('r2communeId'));?></div>
		<div id="_telephone_bloc" class="clearfix">
			<div id="_telephoneF" class="row-inner float-left"
				style="display: inline-block;">
				<?=$this->formRow($this->formga->get('r2telephoneF'));?></div>
				<?php if ($this->layout()->hassbmservicesms) :?>
				<div id="_smsF" class="row-inner float-left left-20px">
					<?=$this->formLabel($this->formga->get('r2smsF'));?>
					<?=$this->formRadio($this->formga->get('r2smsF'));?></div>
				<?php endif;?>
		</div>
		<div id="_email" class="row-inner">
			<?=$this->formRow($this->formga->get('r2email'));?></div>
		<div id="_demandeR2" class="row-inner bloc-wrapper">
			<?=$this->formRow($this->form->get('demandeR2'));?>
		</div>
	</div>
</div>