<?php
/**
 * Page présentant les enfants connus et à réinscrire d'un parent
 * 
 * En phase 1, la page présente les enfants connus et à réinscrire du parent
 * - phase = 1
 * - aReinscrire est un tableau dont les clés sont 'eleveId', 'nom' et 'prenom'
 * En phase 2, la page présente la fiche prérempli de l'enfant à inscrire.
 * - phase = 2
 * - responsable est un objet 
 * - responsable2 est un tableau
 * - hasGa est un booléen
 * - form est le formulaire d'inscription
 * - formga est le formulaire du responsable2
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/index
 * @filesource reinscription-eleve.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 sept. 2018
 * @version 2018-2.4.5
 */
if ($this->phase == 1) {
    $url_ajoutEleve = $this->url('sbmparent', [
        'action' => 'inscription-eleve'
    ]);
    $url_reinscrire = $this->url('sbmparent', [
        'action' => 'reinscription-eleve'
    ]);
    $url_retour = $this->url('sbmparent');
    $modeleligne = '<tr class="%s"><td>%s</td><td>%s</td><td>%s</td></tr>';
    ?>
<h1>Inscription ou réinscription d'un enfant</h1>
<div id="liste-wrapper">
	<div id="liste-header"></div>
	<div id="liste-inner">
		<fieldset class="sbm-page1">
			<legend>Enfants pouvant être réinscrits</legend>
			<table class="parent eleve">
				<tbody>
					<tr>
						<th>Nom</th>
						<th>Prénom</th>
						<th></th>
					</tr>
					<?php
    foreach ($this->aReinscrire as $row) {
        $hiddens = [
            'eleveId' => $row['eleveId'],
            'phase' => 2
        ];
        $buttons = [
            'reinscrire' => [
                'class' => 'button default left-10px',
                'formaction' => $url_reinscrire,
                'title' => 'réinscrire ' . $row['prenom'],
                'value' => 'Réinscrire'
            ]
        ];
        $btligne = $this->listeLigneActions($row['eleveId'], $hiddens, $buttons);
        echo sprintf($modeleligne, $this->cycle([
            "odd",
            "even"
        ])->next(), $row['nom'], $row['prenom'], $btligne);
    }
    ?>
		        </tbody>
			</table>
		</fieldset>
		<p class="sbm-description">
			Pour réinscrire un enfant présent dans cette liste, cliquez sur le
			bouton <b>Réinscrire</b> puis vérifiez et complétez les informations
			le concernant.
		</p>
	</div>
	<div id="liste-footer">
		<p class="sbm-description">
			Pour inscrire un enfant qui n'est pas dans la liste, cliquez sur le
			bouton <b>Inscrire un autre enfant</b>.
		</p>

		<div class="bouton-inscrire">
			<div class="menu clearfix">
			<?php
    $boutons = [
        [
            'class' => 'button default float-right left-10px',
            'formaction' => $url_ajoutEleve,
            'value' => 'Inscrire un autre enfant',
            'title' => 'Inscrire un enfant qui n\'est pas dans la liste'
        ],
        [
            'class' => 'button default float-right left-10px',
            'formaction' => $url_retour,
            'value' => 'Retour à l\'espace parent'
        ]
    ];
    echo $this->listeZoneActions([], $boutons);
    ?>
			</div>
		</div>
	</div>
</div>
<?php } else {?>
<?php

    $this->headScript()->appendFile($this->basePath() . '/js/jquery.min.js');
    $texteDemandeR2 = <<<EOT
La Communauté de communes vous informe que le transport pour cette 2ème adresse ne sera validé qu’en fonction de la disponibilité des places sur les circuits existants. Vous serez informés prochainement des suites données à votre demande par mail.
EOT;
    
    $this->headScript()->captureStart();
    ?>
function phraseDemandeR2(state) {
    var div=$("#demandeR2-text");
    if (div.length==0) {
        $('#r2enfant_demandeR2 fieldset').append('<div id="demandeR2-text"></div>');
    }
    div=$("#r2enfant_demandeR2 #demandeR2-text");
    if (state) {
        div.append('<?= $texteDemandeR2;?>');
    } else {
        div.empty();
    }
}
//copie / suppression de la div par le bouton radio
$(function() {
  // montre ou cache la partie du formulaire concernant la garde alternee
  $("#btnradioga0").on('click', function() {
    $("#enfant_ga").empty();
  });
  $("#btnradioga1").click(function() {
    $("#enfant_ga").empty();
    if ($(this).is(':checked')) {
      bloc=$("#formga").clone();
      ch = bloc.find('*[id]');
      ch.each(function(i) {
        if(this.id) {
          this.id = 'r2'+this.id;
        }
      });
      bloc.removeAttr("id").appendTo("#enfant_ga");
    }
  });
  // adapte le select de la commune au code postal
  $("#enfant_ga").on('keyup', '#r2codePostal', function() {
    var valeur = $('#r2codePostal').val();
    if (valeur.length==5) {
    $.ajax({
				url : '/sbmajaxparent/getcommunesforselect/codePostal:' + valeur,
				dataType: 'json',
				success : function(dataJson) {
					$('#r2communeId').empty();
					if (dataJson.success==1) {
					    $.each(dataJson.data, function(k, d) {
	                        $('#r2communeId').append('<option value="' + d + '">' + k + '</option>');
	                    });
	                }
				},
				error : function(xhr, ajaxOptions, thrownError) {
					alert(xhr.status + " " + thrownError);
				}
			});
	}
  });
  // ajoute un texte si demandeR2 est oui
  $("#enfant_ga").on('click', 'input[type=radio][name=demandeR2]', function(){
    var state=$(this).val()==1;
    phraseDemandeR2(state);
  });
});
<?php
    $this->headScript()->captureEnd();
    // initialisation s'il y a garde alternée
    $this->inlineScript()->captureStart();
    ?>
$(function() {
  if ($("#btnradioga1").is(':checked')) {
    bloc=$("#formga").clone();
    ch = bloc.find('*[id]');
      ch.each(function(i) {
        if(this.id) {
          this.id = 'r2'+this.id;
        }
      });
    bloc.removeAttr("id").appendTo("#enfant_ga");
  }
  if ($("#r2demandeR2").is(':checked')) {
      phraseDemandeR2(true);
  }
});
<?php
    
    $this->inlineScript()->captureEnd();
    $identiteResponsable = sprintf('%s %s %s', $this->responsable->titre, $this->responsable->nom, $this->responsable->prenom);
    if ($this->hasGa) {
        $r2identite = sprintf('%s %s %s', $this->responsable2['titre'], $this->responsable2['nom'], $this->responsable2['prenom']);
        $r2adresseL1 = $this->responsable2['adresseL1'];
        $r2adresseL2 = $this->responsable2['adresseL2'];
        $r2cp = $this->responsable2['codePostal'];
        $r2commune = $this->responsable2['commune'];
    } else {
        $r2identite = $r2adresseL1 = $r2adresseL2 = $r2cp = $r2commune = '';
    }
    $formatDateN = \SbmBase\Model\DateLib::formatDateFromMysql($this->form->get('dateN')->getValue());
    ?>
<h1>Modification des informations concernant un enfant</h1>

<div id="fiche-wrapper">
	<div id="fiche-header"></div>
	<div id="fiche-inner">
    	<?= $this->form()->openTag($this->form);?>
    	<?= $this->formHidden($this->form->get('eleveId'));?>
    	<?= $this->formHidden($this->form->get('responsable1Id'));?>
    	<?= $this->formHidden($this->form->get('csrf'));?>
    	<?= $this->formHidden($this->form->get('nom'));?>
    	<?= $this->formHidden($this->form->get('prenom'));?>
    	<?= $this->formHidden($this->form->get('dateN'));?>
    	<?= $this->formHidden($this->form->get('derogation'));?>
    	<?= $this->formHidden($this->form->get('motifDerogation'));?>
    	<?= $this->formHidden($this->form->get('phase'));?>
    	<fieldset class="sbm-page1">
	    	<div>
		    	<div class="enfant-label">
		    		<?= $this->form->get('nom')->getLabel(); ?></div>
		    	<?= $this->form->get('nom')->getValue(); ?></div>
			<div>
		    	<div class="enfant-label">
		    		<?= $this->form->get('prenom')->getLabel(); ?></div>
		    	<?= $this->form->get('prenom')->getValue(); ?></div>
	    	<div>
	        	<div class="enfant-label">
	        		<?= $this->form->get('dateN')->getLabel(); ?></div>
	        	<?= $formatDateN; ?></div>
        	<div>
	        	<div class="enfant-label">Responsable</div>
	        	<?= $identiteResponsable; ?></div>
        	<div>
	        	<div class="enfant-label">Adresse</div>
	        	<?= $this->responsable->adresseL1; ?></div>
        	<div>
	        	<div class="enfant-label">Adresse</div>
	        	<?= $this->responsable->adresseL2; ?></div>
        	<div>
	        	<div class="enfant-label">Commune</div>
	        	<?= $this->responsable->codePostal . ' ' . $this->responsable->commune; ?></div>
        	<div id="enfant-edit-etablissementId" class="row-inner edit">
        		<?= $this->formRow($this->form->get('etablissementId')); ?></div>
        	<div id="enfant-edit-classeId" class="row-inner edit">
        		<?= $this->formRow($this->form->get('classeId')); ?></div>
        	<div id="wrapper-radio" class="clearfix">
	        	<div id="enfant-edit-joursTransport" class="row-inner edit float-left">
	        		<?= $this->formRow($this->form->get('joursTransport')); ?></div>
	        	<div id="enfant-edit-ga" class="row-inner edit float-left">
	        		<?= $this->formRow($this->form->get('ga')); ?></div>
	        	<div id="enfant-edit-fa" class="row-inner edit float-left">
	        		<?= $this->formRow($this->form->get('fa')); ?></div>
        	</div>
        	<div id="enfant_ga"></div>
        	<div id="user">
	        	<div id="wrapper-commentaire">
	        		<?= $this->formRow($this->form->get('commentaire'));?></div>
        	</div>
        	<div id="enfant-edit-buttons" class="row-inner edit">    		
            	<?= $this->formSubmit($this->form->get('submit'));?> 
            	<?= $this->formSubmit($this->form->get('cancel'));?></div>
    	</fieldset>
		<?= $this->form()->closeTag(); ?>
	</div>
	<div id="fiche-footer"></div>
</div>
<div style="display: none;">
	<div id="formga">
    	<?= $this->formHidden($this->formga->get('r2responsable2Id')); ?>
    	<?= $this->formHidden($this->formga->get('r2userId')); ?>
<?php if (is_null($this->responsable2) || $this->responsable2['owner']) : ?>
    	<div id="enfant_titre" class="row-inner edit">
    		<?= $this->formRow($this->formga->get('r2titre'));?></div>
		<div id="enfant_nom" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2nom'));?></div>
		<div id="enfant_prenom" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2prenom'));?></div>
		<div id="enfant_adresseL1" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2adresseL1'));?></div>
		<div id="enfant_adresseL2" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2adresseL2'));?></div>
		<div id="enfant_codePostal" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2codePostal'));?></div>
		<div id="enfant_communeId" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2communeId'));?></div>
		<div id="enfant_telephoneF" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2telephoneF'));?></div>
		<div id="enfant_email" class="row-inner edit">
			<?= $this->formRow($this->formga->get('r2email'));?></div>
		<div id="enfant_demandeR2" class="row-inner edit">
			<?= $this->formRow($this->form->get('demandeR2'));?></div>
<?php else : ?>
        <div>
			<div class="enfant-label">Responsable</div><?= $r2identite; ?></div>
		<div>
			<div class="enfant-label">Adresse</div><?= $r2adresseL1; ?></div>
		<div>
			<div class="enfant-label">Adresse</div><?= $r2adresseL2; ?></div>
		<div>
			<div class="enfant-label">Commune</div><?= $r2cp . ' ' . $r2commune; ?></div>
		<div id="enfant_demandeR2" class="row-inner edit">
			<?= $this->formRow($this->form->get('demandeR2')); ?></div>
<?php endif; ?>
    </div>
</div>
<?php }?>