<?php
/**
 * Page de suppression d'une inscription d'un élève
 *
 * Après validation, les affectations et la scolarité seront supprimées. Par contre, la fiche eleve n'est pas supprimée.
 *
 * @project sbm
 * @package SbmParent/view/sbm-parent/index
 * @filesource suppr-eleve.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 avr. 2020
 * @version 2020-2.6.0
 */
?>
<h1>Suppression de l'inscription d'un enfant</h1>
<div id="suppr-wrapper">
	<p>Vous avez demandé la suppression de l'inscription de :</p>
	<div class="header-wrapper">
		<ul>
			<li><?= $this->eleve['nom'] . ' ' . $this->eleve['prenom']; ?></li>
			<li>Scolarisation : <?= $this->eleve['etablissement'] . ' - ' . $this->eleve['communeEtablissement']; ?></li>
	        <?php if ($this->affectations->count() > 0) : ?>
	        <li>Circuits utilisés :
				<ul>
	            <?php foreach ($this->affectations as $affectation) :?>
	               <li><?= $this->printAffectation($affectation); ?></li>
	            <?php endforeach; ?>
	            </ul>
			</li>
	        <?php endif; ?>
        </ul>
	</div>
	<p>Confirmez-vous ?</p>
	<?= $this->form()->openTag($form);?>
	<?= $this->formCollection($form);?>
	<?= $this->form()->closeTag();?>
</div>