<?php
/**
 * Vue de l'action index du controller IndexController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 12 févr. 2014
 * @version 2014-1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// $url_gest_eleve = $this->url('sbmgestion/eleve');
$url_gest_eleves = $this->url('sbmgestion/eleve', array(
    'action' => 'eleve-liste',
    'page' => $this->page
));
$url_gest_responsables = $this->url('sbmgestion/eleve', array(
    'action' => 'responsable-liste',
    'page' => $this->page
));
$url_portail = $this->url('sbmportail');
$url_gest_finance = $this->url('sbmgestion/finance');
$url_gest_transport = $this->url('sbmgestion/transport');
$url_gest_change_as = $this->url('sbmgestion/anneescolaire');
$url_gest_simulation = $this->url('sbmgestion/simul');
$url_gest_parametre = $this->url('sbmgestion/config');
$url_parent = $this->url('sbmparent');

$paiementsAS = $this->paiements['totalASMode'];
$paiementsMode = current($paiementsAS);
$paiementsTotal = $this->paiements['totalGeneral'];

$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
	<?php
echo $this->flashMessenger()->render('success');
echo $this->flashMessenger()->render('warning');
echo $this->flashMessenger()->render('error');
echo $this->flashMessenger()->render('info');
echo $this->flashMessenger()->render('default');
?>
    </div>
	<h1>Gestion du service</h1>
	<div class="float-left">
		<h2>Quelques chiffres</h2>
		<table class="bleu float-left">
			<tbody>
				<tr>
					<td>Nombre d'élèves enregistrés</td>
					<td class="effectif"><?php echo $this->elevesEnregistres ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves inscrits</td>
					<td class="effectif"><?php echo $this->elevesInscrits ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves préinscrits</td>
					<td class="effectif"><?php echo $this->elevesPreinscrits ?:0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves rayés</td>
					<td class="effectif"><?php echo $this->elevesRayes ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves à moins de 1 km</td>
					<td class="effectif"><?php echo $this->elevesMoins1km ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves de 1 à 3 km</td>
					<td class="effectif"><?php echo $this->elevesDe1A3km ?:0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves à 3 km et plus</td>
					<td class="effectif"><?php echo $this->eleves3kmEtPlus ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves en famille d'accueil</td>
					<td class="effectif"><?php echo $this->elevesFamilleAcceuil ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves en garde alternée</td>
					<td class="effectif"><?php echo $this->elevesGardeAlternee ?:0;?></td>
				</tr>
			</tbody>
		</table>
		<div class="float-left">
			<table class="rose ">
				<tbody>
					<tr>
						<td>Nombre de responsables</td>
						<td class="effectif"><?php echo $this->responsablesEnregistres;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant inscrit des enfants</td>
						<td class="effectif"><?php echo $this->responsablesAvecEnfant;?></td>
					</tr>
					<tr class="separateur">
						<td>Nombre de responsables sans enfant inscrit</td>
						<td class="effectif"><?php echo $this->responsablesSansEnfant;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables résidant hors périmètre</td>
						<td class="effectif"><?php echo $this->responsablesHorsZone;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant déménagé</td>
						<td class="effectif"><?php echo $this->responsablesDemenagement;?></td>
					</tr>
				</tbody>
			</table>
			<p></p>
			<table class="jaune">
				<tbody></tbody>
				<tr>
					<td>Paiements en ligne</td>
					<td class="euro"><?php echo $fmt->formatCurrency(isset($paiementsMode['CB']) ? $paiementsMode['CB'] : 0, 'EUR');?></td>
				</tr>
				<tr>
					<td>Paiements par chèque</td>
					<td class="euro"><?php echo $fmt->formatCurrency(isset($paiementsMode['chèque']) ? $paiementsMode['chèque'] : 0, 'EUR');?></td>
				</tr>
				<tr>
					<td>Paiements en espèces</td>
					<td class="euro"><?php echo $fmt->formatCurrency(isset($paiementsMode['espèces']) ? $paiementsMode['espèces'] : 0, 'EUR');?></td>
				</tr>
				<tr class="separateur">
					<td>Paiements par titre individuel</td>
					<td class="euro"><?php echo $fmt->formatCurrency(isset($paiementsMode['Titre individuel']) ? $paiementsMode['Titre individuel'] : 0, 'EUR');?></td>
				</tr>
				<tr>
					<td>Total des encaissements</td>
					<td class="euro"><?php echo $fmt->formatCurrency($paiementsTotal, 'EUR');?></td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div id="menugeneral" class="float-right">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?php echo $url_gest_eleves; ?>"><i
						class="fam-bullet-go"></i>Gestion des élèves</a></li>
				<li><a href="<?php echo $url_gest_responsables; ?>"><i
						class="fam-bullet-go"></i>Gestion des responsables</a></li>
				<li><a href="<?php echo $url_gest_finance; ?>"><i
						class="fam-bullet-go"></i>Gestion financière</a></li>
				<li><a href="<?php echo $url_gest_transport; ?>"><i
						class="fam-bullet-go"></i>Gestion du réseau de transport</a></li>
				<li><a href="<?php echo $url_gest_change_as; ?>"><i
						class="fam-bullet-go"></i>Choix de l'année scolaire</a></li>
				<!-- li><a href="<?php echo $url_gest_simulation; ?>"><i
					class="fam-bullet-go"></i>Simulation d'organisation</a></li>
			<li><a href="<?php echo $url_gest_parametre; ?>"><i
					class="fam-bullet-go"></i>Configuration et paramètres</a></li-->
				<li><a href="<?php echo $url_portail; ?>"><i class="fam-bullet-go"></i>Portail
						de consultation</a></li>
			</ul>
		</div>
	</div>
</div>