<?php
/**
 * Vue de l'action index du controller IndexController du module SbmGestion
 *
 *
 * @project sbm
 * @package SbmGestion/view/sbm-gestion/index
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 3 avr. 2021
 * @version 2021-2.6.1
 */
$this->headLink()->appendStylesheet($this->basePath('/css/fam-icons-custom.css'));

// $url_gest_eleve = $this->url('sbmgestion/eleve');
$url_gest_eleves = $this->url('sbmgestion/eleve',
    [
        'action' => 'eleve-liste',
        'page' => $this->page
    ]);
$url_gest_responsables = $this->url('sbmgestion/eleve',
    [
        'action' => 'responsable-liste',
        'page' => $this->page
    ]);
$url_portail = $this->url('sbmportail');
$url_gest_finance = $this->url('sbmgestion/finance');
$url_gest_transport = $this->url('sbmgestion/transport');
$url_gest_change_as = $this->url('sbmgestion/anneescolaire');
$url_gest_statistiques = $this->url('sbmgestion/statistiques');
$url_gest_mailchimp = $this->url('sbmmailchimp');
$url_gest_servicesms = $this->url('sbmservicesms');
$url_gest_parametre = $this->url('sbmgestion/config');
$url_pass_provisoires = $this->url('sbmgestion/gestioneleve', [
    'action' => 'invite'
]);

$pAS = $this->paiements['totalASMode'];
$pMode = current($pAS);
$pTotal = $this->paiements['totalGeneral'];

$nbDistanceInconnue = ($this->elevesDpEnregistres ?: 0) +
    ($this->elevesIntEnregistres ?: 0) - ($this->elevesMoins1km ?: 0) -
    ($this->elevesDe1A3km ?: 0) - ($this->eleves3kmEtPlus ?: 0);

$fmt = new NumberFormatter('fr_FR', NumberFormatter::CURRENCY);
?>
<div id="tableau-de-bord" class="clearfix">
	<div class="flashMessenger float-right">
        <?= $this->flashMessenger()->render('success');?>
        <?= $this->flashMessenger()->render('warning');?>
        <?= $this->flashMessenger()->render('error');?>
        <?= $this->flashMessenger()->render('info');?>
        <?= $this->flashMessenger()->render('default');?>
    </div>
	<h1>Gestion du service</h1>
	<div class="float-left">
		<h2>Quelques chiffres</h2>
		<table class="bleu float-left">
			<tbody>
				<tr>
					<td>Nombre d'élèves enregistrés</td>
					<td class="effectif">
						<?= ($this->elevesDpEnregistres ?: 0) + ($this->elevesIntEnregistres ?: 0);?></td>
				</tr>
				<tr>
					<td class="align-right">dont <?=$this->elevesDpEnregistres ?: 0;?> DP</td>
				</tr>
				<tr>
					<td class="align-right">et <?=$this->elevesIntEnregistres ?: 0;?> Internes</td>
				</tr>
				<tr>
					<td>Nombre d'abonnements payés</td>
					<td class="effectif"><?= $this->elevesInscrits ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'abonnements payés puis rayés</td>
					<td class="effectif"><?= $this->elevesInscritsRayes ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre de demandes non payées</td>
					<td class="effectif"><?= $this->elevesPreinscrits ?:0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre de demandes non payées puis rayés</td>
					<td class="effectif"><?= $this->elevesPreinscritsRayes ?:0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves à moins de 1 km</td>
					<td class="effectif"><?= $this->elevesMoins1km ?: 0;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves de 1 à 3 km</td>
					<td class="effectif"><?= $this->elevesDe1A3km ?: 0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves à 3 km et plus</td>
					<td class="effectif"><?= $this->eleves3kmEtPlus ?: 0;?></td>
				</tr>
				<tr class="separateur">
					<td>Nombre d'élèves non géolocalisés</td>
					<td class="effectif"><?= $nbDistanceInconnue;?></td>
				</tr>
				<tr>
					<td>Nombre d'élèves en garde alternée</td>
					<td class="effectif"><?= $this->elevesGardeAlternee ?:0;?></td>
				</tr>
			</tbody>
		</table>
		<div class="float-left">
			<table class="rose ">
				<tbody>
					<tr>
						<td>Nombre de responsables</td>
						<td class="effectif"><?= $this->responsablesEnregistres;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant inscrit des enfants</td>
						<td class="effectif"><?= $this->responsablesAvecEnfant;?></td>
					</tr>
					<tr class="separateur">
						<td>Nombre de responsables sans enfant inscrit</td>
						<td class="effectif"><?= $this->responsablesSansEnfant;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables résidant hors périmètre</td>
						<td class="effectif"><?= $this->responsablesHorsZone;?></td>
					</tr>
					<tr>
						<td>Nombre de responsables ayant déménagé</td>
						<td class="effectif"><?= $this->responsablesDemenagement;?></td>
					</tr>
				</tbody>
			</table>
			<p></p>
			<table class="jaune">
				<tbody></tbody>
				<tr>
					<td>Paiements en ligne</td>
					<td class="euro">
						<?= $fmt->formatCurrency(isset($pMode['CB']) ? $pMode['CB'] : 0, 'EUR');?>
						</td>
				</tr>
				<tr>
					<td>Paiements par chèque</td>
					<td class="euro">
						<?= $fmt->formatCurrency(isset($pMode['chèque']) ? $pMode['chèque'] : 0, 'EUR');?>
						</td>
				</tr>
				<tr>
					<td>Paiements en espèces</td>
					<td class="euro">
						<?= $fmt->formatCurrency(isset($pMode['espèces']) ? $pMode['espèces'] : 0, 'EUR');?>
						</td>
				</tr>
				<tr class="separateur">
					<td>Paiements par titre individuel</td>
					<td class="euro">
						<?= $fmt->formatCurrency(isset($pMode['Titre individuel']) ? $pMode['Titre individuel'] : 0, 'EUR');?>
						</td>
				</tr>
				<tr>
					<td>Total des encaissements</td>
					<td class="euro">
						<?= $fmt->formatCurrency($pTotal, 'EUR');?></td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div id="menugeneral" class="float-right">
		<div id="menugeneral-header">
			<h2>Menu</h2>
		</div>
		<div id="menugeneral-inner">
			<ul>
				<li><a href="<?= $url_gest_eleves; ?>"><i class="fam-bullet-go"></i>Gestion
						des élèves</a></li>
				<li><a href="<?=$url_gest_responsables;?>"><i class="fam-bullet-go"></i>Gestion
						des responsables</a></li>
				<li><a href="<?= $url_gest_finance; ?>"><i class="fam-bullet-go"></i>Gestion
						financière</a></li>
				<li><a href="<?= $url_gest_transport; ?>"><i class="fam-bullet-go"></i>Gestion
						du réseau de transport</a></li>
				<li><a href="<?=$url_pass_provisoires;?>"><i class="fam-bullet-go"></i>Gestion
						des demandes de PASS PROVISOIRE</a></li>
				<li><a href="<?= $url_gest_change_as; ?>"><i class="fam-bullet-go"></i>Choix
						de l'année scolaire</a></li>
				<li><a href="<?= $url_gest_statistiques; ?>"><i
						class="fam-bullet-go"></i>Statistiques</a></li>
				<li><a href="<?= $url_gest_servicesms; ?>"><i class="fam-bullet-go"></i>Suivi
						des envois de SMS</a></li>
				<li><a href="<?= $url_gest_mailchimp; ?>"><i class="fam-bullet-go"></i>Gestion
						de la liste de diffusion</a></li>
				<!-- >li><a href="<?= $url_gest_parametre; ?>"><i
					class="fam-bullet-go"></i>Configuration et paramètres</a></li-->
				<li><a href="<?= $url_portail; ?>"><i class="fam-bullet-go"></i>Portail
						de consultation</a></li>
			</ul>
		</div>
	</div>
</div>