<?php
use Zend\View\Helper\HeadScript;
/**
 * Page d'envoi d'un message
 *
 * Les adresses de destination doivent être configurées dans le fichier config/autolaod/sbm.local.php
 * (voir $mail, clé 'destinataires')
 * Pour des raisons de sécurité, le textarea a été supprimé et est créé à la volée en jQuery.
 * Utilisation de tinymce pour améliorer la saisie et la sécurité.
 *
 * @project sbm
 * @package SbmMail/view
 * @filesource index.phtml
 * @encodage UTF-8
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 15 fév. 2019
 * @version 2019-2.4.7
 */
$this->jQuery();
$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
$this->headScript()->captureStart();
?>
tinymce.init({
    selector: "textarea",
    language: "fr_FR",
    menubar : false,
    statusbar: false
 });
<?php
$this->headScript()->captureEnd();
$this->inlineScript()->captureStart();
?>
var bodyWrapper = $("#body-wrapper");
var label = $('<label class="sbm-label required" for="mail-body">Message</label>'); 
var textArea = $('<textarea name="body" id="mail-body"></textarea>');
bodyWrapper.append(label);
bodyWrapper.append(textArea);
<?php
$this->inlineScript()->captureEnd();
?>
<h1>Envoi d'un message au service de transport</h1>
<div id="fiche-wrapper">
	<div id="fiche-header">
		<p>
			Vous êtes <b><?php echo $user['titre'] . ' ' . $user['prenom'] . ' ' . $user['nom'];?></b>
			et votre email est <b><?php echo $user['email'];?></b>.
		</p>
		<p>Si vous n'êtes pas cette personne, nous vous prions de bien vouloir
			vous déconnecter.</p>
	</div>
	<div id="fiche-inner">
    <?php
    echo $this->form()->openTag($this->form);
    echo $this->formHidden($this->form->get('userId'));
    echo $this->formHidden($this->form->get('csrf'));
    ?>
    <fieldset class="sbm-page1">
			<div><?php echo $this->formRow($this->form->get('subject'));?></div>
			<div id="body-wrapper"></div>
			<div><?php echo $this->formSubmit($this->form->get('submit')) . $this->formSubmit($this->form->get('cancel')); ?></div>
		</fieldset>
    <?php echo $this->form()->closeTag();?>
    </div>
	<div id="fiche-footer">
		<p class="sbm-description">Votre message va être adressé au service de
			transport qui y répondra dans les meilleurs délais.</p>
	</div>
</div>
